### ISSUE TITLE
Component Rename — Busy/Progress to Loader

### ISSUE THREAD

**Issue by katieinfor** [infor-design/enterprise#5375] opened 2021-06-29 18:18 UTC
**Is your feature request related to a problem or use case? Please describe.**
Original Component Name
'Busy Indicator' then we changed it to 'Loading Indicator' [[Link, with the wrong info lol](https://design.infor.com/product/components/loading-indicator)] We then renamed it to 'Progress Indicator' for a brief time (now we have two pages live with similar content)

**Describe the solution you'd like**
New Component Name
Loader

Bar Loader
Spin Loader
Remove this [page](https://design.infor.com/product/components/progress-indicator)

We will have to update:

product & component pages on design.infor.com 
component pages on the demo site
references in the code

**Describe alternatives you've considered**
N/A

**Additional context**
Jira Ticket: https://jira.infor.com/browse/UXD-2804

**Comment by tmcconechy** [comment] 2021-06-29 18:23
I think we need to finalize the names as we though of using loading-indicator. We probably need a call for this.

**Comment by tmcconechy** [comment] 2021-07-12 13:31
In 4.54.0 we are adding a new ProgressIndicator but kept the old one as well. SO this is a duplicate of that work

**Closed by tmcconechy** 2021-07-12 13:31 UTC
Labels: [5], status: clarification, type: enhancement :sparkles:
