### ISSUE TITLE
Popupmenu: Issue in opening soho-popupmenu at single click (Time to value)

### ISSUE THREAD

**Issue by bveerabathini** [infor-design/enterprise#5383] opened 2021-07-01 13:40 UTC
**Describe the bug**
Issue in opening soho-popupmenu at single click.  we need to click 2 times on filter button to open popupmenu.
This is a multiselect popup menu.
We have tried with menu-button as well with popupmenu but same behavior seen when used with normal button.

**To Reproduce**
Please find code here in stackblitz with menubutton.
https://stackblitz.com/edit/ids-quick-start-940-vzazly

1. Click on Filter button--> popup opens --> click on any menu item --> popup closes
2. Click on Filter button again , it will not open popupmenu --> again we need to click on button then it opens.
From here onwards mutiselection of menu items works.
3. There is an Apply Filter button in the code in that we are calling this.popupMenuComponent.close(true);
it closes the popup menu but to open popupmenu again we need to click 2 times on the button.

**Expected behavior**
popupmenu should open on single click.

**Version**
IDS Enterprise 4.36.1

**Screenshots**
![image](https://user-images.githubusercontent.com/85981034/124133335-5b383e80-da9f-11eb-8b9b-325ac67c984b.png)

**Platform**
 - Infor LN
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: Version 91.0.4472.124 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment] 2021-07-01 13:42
@bveerabathini where can this be reproduced?

**Comment by bveerabathini** [comment] 2021-07-01 14:14
You can reproduce here in stackblitz,
https://stackblitz.com/edit/ids-quick-start-940-vzazly

**Comment by tmcconechy** [comment] 2023-02-14 19:56
Closing this issue as old. We cannot reproduce in the default examples on the newest version https://main-enterprise.demo.design.infor.com/components/popupmenu/example-selectable-multiple.html

**Closed by tmcconechy** 2023-02-14 19:56 UTC
Labels: type: bug :bug:, [5], team: ln
