### ISSUE TITLE
[Datagrid] Cannot enter space on editable cells

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#629] opened 2018-08-20 09:02 UTC
**Describe the bug**
[Datagrid] Cannot enter space on editable cells

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
2. Click on the Activity column of the first row
3. Type "test" then press spacebar, nothing will happen, space will not be entered
4. This is applicable to all editable cells

**Expected behavior**
Space should be entered when spacebar is pressed

**Screenshots**
No applicable screenshots.

**Platform**
 - All OS and browsers

**Additional context**
No additional context

**Comment by tmcconechy** [comment] 2018-08-20 13:30
This is a duplicate of https://github.com/infor-design/enterprise/issues/624 (i noticed that as well)

**Closed by tmcconechy** 2018-08-20 13:30 UTC
