### ISSUE TITLE
Icons: sorting icons are not consistent

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise#5086] opened 2021-04-15 11:55 UTC
**Describe the bug**
Sorting icons up/down does not have consistent look. The up direction has bold horizontal lines.

1. Go to https://design.infor.com/code/ids-enterprise/latest/icons
2. See error

**Expected behavior**
Icons should have same layout except the direction of the arrow.

**Version**
latest

**Screenshots**
![image](https://user-images.githubusercontent.com/11279863/114865090-14b53b00-9df2-11eb-9b49-34a5ead01955.png)

**Comment by tmcconechy** [comment] 2021-04-15 13:23
Are you sure maybe this isnt some sort of a cross pixel / zoom effect on your end? As im not seeing it.

<img width="84" alt="Screen Shot 2021-04-15 at 9 22 04 AM" src="https://user-images.githubusercontent.com/814283/114876269-28e64180-9dcc-11eb-9401-92e148ae4c6e.png">

What do you think @kevinwhitedesign ?

**Comment by hohnzy** [comment] 2021-04-15 13:29
I see your screenshot almost the same as mine. Ive noticed earlier that there are differences on macs/windows/linux. I am on linux 4k@60Hz.

**Comment by tmcconechy** [comment] 2021-04-15 13:31
Ok when i look at them they look different. Yours looks bold and in mine both look identical.

**Comment by EdwardCoyle** [comment] 2021-04-15 14:15
There is some kind of a difference, depending on the screen you're using it seems:

Macbook Retina Monitor (1080p @ 220dpi) |  Dell Monitor - 2408WFP (1080p @ 72dpi)
:-------------------------:|:-------------------------:
![20210415_093426](https://user-images.githubusercontent.com/3249601/114882799-53d39400-9dd2-11eb-8ca4-2189bc0b7249.jpg) | ![20210415_093455](https://user-images.githubusercontent.com/3249601/114882808-559d5780-9dd2-11eb-9e06-b29602ce216c.jpg)

The screenshot on the right is from an older computer monitor at 72dpi.  The "up" sort icon is noticeably more blurry compared to the Retina monitor (however, the "down" sort looks good).

@kevinwhitedesign not sure what implications this has for the icons but it seems at lower resolutions, the thin line art might end up sitting halfway between pixels instead of directly on them.  Maybe something that needs to be corrected in the sketch file?

**Comment by hohnzy** [comment] 2021-04-16 09:25
When I am looking at other icons quickly I see the same issues with these:
add (and variants - plusminus-folder-closed, sec-menu-expand), caret-down, down-arrow, download, drilldown duplicate (plus inside), export (arrow), info (the i letter looks bold), left-arrow, right-arrow, up-arrow, transfer

My resolution 3840x2160 @ 60 Hz. Not sure about dpi and how to check it.

**Comment by hohnzy** [comment] 2021-07-13 15:08
Any progress on this one?

**Comment by tmcconechy** [comment] 2021-07-13 15:12
No im not 100% sure there is anything we can do about it. However we are changing the generation process to a new tool. So we can check if we still see that when thats done. https://github.com/infor-design/design-system/pull/464

Can also see if design can look at this and figure out if there is anything wrong on the icons. cc @katieinfor if it doesnt fix it

**Comment by tmcconechy** [comment] 2021-07-13 15:19
Should not i cant reproduce this myself. So will need assistance there.

**Comment by hohnzy** [comment] 2021-07-13 15:21
thats the thing, usually UI/design ppl are using good screens with high dpi so they do not notice

**Comment by tmcconechy** [comment] 2021-07-13 15:23
Yeah they will have to try and setup something. Could take some time to figure out @katieinfor can you make a Jira for this for design?

**Comment by katieinfor** [comment] 2021-07-13 18:54
Created ticket in jira: https://jira.infor.com/browse/UXD-2890

**Comment by tmcconechy** [comment] 2021-07-23 14:49
We had design look at it but doesnt seem like anything can be done about it. So closing as we dont have any solution.

**Closed by tmcconechy** 2021-07-23 14:49 UTC
Labels: [5], for: design, type: bug :bug:

**Comment by tmcconechy** [comment] 2021-07-23 14:52
also https://github.com/infor-design/design-system/pull/464 will be merged soon. we changed from sketch to figma. not sure if that will fix anything around this however but worth noting
