### ISSUE TITLE
Editor: Could not paste copied texts from pdf file opened in Acrobat Reader

### ISSUE THREAD

**Issue by jmartirez** [infor-design/enterprise#5889] opened 2021-11-23 04:22 UTC
**Describe the bug**
Could not paste copied texts from pdf file opened in Acrobat Reader. although when the i "paste as plain text" or if the pdf file is opened on Microsoft Edge pasting on the editor works.

**To Reproduce**

1. Copy any text from PDF file opened in Acrobat Reader
2. Go to http://localhost:4000/components/editor/example-index.html
2. Paste on editor

**Expected behavior**
Copied text will be pasted on editor even without using "paste as plain text"

**Version**

- ids-enterprise: v4.52.0

**Screenshots**
![CopyFromPDF](https://user-images.githubusercontent.com/84698297/142974961-5513aa54-bee3-49e4-86fb-2fd01d548f5c.gif)

**Platform**
 - Infor Application/Team Name: Landmark
 - Device: (if applicable) N/A
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 96.0.4664.45 (Official Build) (64-bit)

**Additional context**
https://jira.lawson.com/browse/LMCLIENT-37739

**Comment by tmcconechy** [comment] 2021-11-29 15:41
I wasnt able to reproduce this on a few PDF files i have. I think in general we cant expect to support all the formatter the PDF does but the text should be cleaned up and applied when pasted.

Tried this on mac chrome....

**Comment by tmcconechy** [comment] 2022-01-05 17:41
Tried to reproduce this but could not. So closing as we did not get a reply. If you have anymore info on reproducing just let us know.

**Closed by tmcconechy** 2022-01-05 17:41 UTC
Labels: type: bug :bug:, [3], team: lawson, status: clarification

**Comment by rvilleno** [comment] 2022-06-01 04:33
Hi @tmcconechy the issue only happens when we open the PDF file in acrobat reader, if we open it on say a browser it would work. Should we just re-open this Git ticket or should I open a new one?
![LMCLIENT-37739](https://user-images.githubusercontent.com/10869544/171328222-fb15429c-5241-40e0-8554-6d4403a7ca5c.gif)

**Comment by tmcconechy** [comment] 2022-06-01 13:33
I think the new issue is good but i could not reproduce it. Lets take this on that issue
