### ISSUE TITLE
Datagrid - Loading animation

### ISSUE THREAD

**Issue by brafajloski** [infor-design/enterprise#3608] opened 2020-03-13 00:15 UTC
**Is your feature request related to a problem? Please describe.**
This request is about new loading animations for data grids, but might apply for other UI elements as well. In general it is an enhancement for content loading to display placeholder content until it's fully loaded.

**Describe the solution you'd like**
When the datagrid columns are know, provide support to show a loading animation while the data is fetched:
- Display a mockup grid with the column names filled out
- Display the cells as empty or with blurry content.
- Indicate over the grid that data is being loaded, something similar to current loading icon or smaller.
- Once the data is fetched display it over the existing grid.

Optional: Support the above also when the column names are unknown. 
Show a predefined size placeholder grid as part of the loading animation.

**Describe alternatives you've considered**
The above animation might also work for other UI elements when the element's size, position and colors are know before their content is loaded. 

**Additional context**
Examples: https://medium.com/@backyardcoder/lazy-load-content-beautifully-8caba1983ca2

**Comment by tmcconechy** [comment] 2020-03-13 14:01
We have some newer designs to implement for loading indicator on https://github.com/infor-design/enterprise/issues/3422

We could add a datagrid example. But also how slow is yours? Ideally we dont need that many loading indicators appearing all over the place in the app

**Comment by brafajloski** [comment] 2020-03-13 14:36
It's for Data Lake Compass Query Editor , which is a grid-heavy, data driven product with a lot of data density in grids. 

We intend to introduce virtualized infinite scrolling for result sets. As users page through query results presented in a grid, it would be helpful to have a lazy loading animation within the rows/cells as the data grid is preparing to present the result set.

**Comment by tmcconechy** [comment] 2020-09-03 13:22
Closing this in favor of https://github.com/infor-design/enterprise/issues/4340

**Closed by tmcconechy** 2020-09-03 13:22 UTC
Labels: [3], focus: datagrid, type: enhancement :sparkles:

**Comment by brafajloski** [comment] 2020-09-07 13:10
@tmcconechy #4340 and #3422 doesn't really match the example and what PM had in mind. Anything we can do to reconsider the requirement? Thanks

**Comment by tmcconechy** [comment] 2020-09-09 14:32
https://github.com/infor-design/enterprise/issues/3422 actually does cover this issue. The issue is stalled because they are working on a new animation. We might go in that direction. Would help to make a comment on that issue as the designers are watching that one.
