### ISSUE TITLE
Datagrid - Performance issues

### ISSUE THREAD

**Issue by brafajloski** [infor-design/enterprise#1905] opened 2019-04-04 11:28 UTC
**Describe the bug**
Datagrid is slow on performance when it contains a large data set.

**To Reproduce**
1. Create a data grid with around ~10k cells. e.g. 100 rows x 100 columns, with no pagination.
2. Try to resize rows/columns
3. Try to sort a column
4. Try to filter a column

All of these actions are  slow and make the usage laggy.

**Expected behavior**
Datagrid should handle larger data sets efficiently without any performance impact.
Datagrid component should have a clear recommendation on sizing in regards to performance. i.e. What is the max size of a datagrid before we hit performance issues?

**Version**
- ids-enterprise: [v4.17.0]

**Screenshots**
N/A

**Platform**
 - Device: i5-6300U @ 2.40GHz, 16GB RAM
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Latest

**Additional context**
N/A

**Comment by clepore** [comment] 2019-04-04 15:51
- [ ] In the least, I like the idea that we should document what our datagrid data capacity is before performance starts to degrade.

**Comment by tmcconechy** [comment] 2019-04-08 15:03
The best way for performance is to actually use paging. So i recommend that first of all.
We did do some benchmarks but didnt document anything specific. IE is going to be slow no matter what but Chrome should probably work at about max 10,000 actual cells. So you probably just hitting around the top of the threshold. We'll do something more on #1912 and document it more. But if you think about it your processing a lot of DOM elements in those operations.

Also i think the problem is the 100 columns more than the 100 rows, specifically the filter row as it is expensive to initialize. Perhaps this can be optimized there, this would be my initial guess.

Also this is a lot of cognitive load on the user, can you do things like hide unused columns and use client side paging? And in general rethink the approach that requires showing so much data to the user at once? Maybe implement a search ect.

One Example:
http://latest-enterprise.demo.design.infor.com/components/datagrid/test-large-dataset-performance.html

One related enhancement: https://github.com/infor-design/enterprise/issues/460

**Comment by awbuboltz** [comment] 2019-09-04 19:25
Hey Tim, we're getting hit with performance issues on the grid. Customers moving from the 3.6 controls version of our product to the 4.0 version and it's drastically slower. Our customers render 200 rows, with 8 or less columns.

**Comment by tmcconechy** [comment] 2019-09-04 19:41
The problem is probably also combined with other elements on the page. Do you have an example of a page and numbers and browsers being used? That number doesnt seem like it should be a problem. Perhaps we need to pick this up and see what else we can do?

Is it paging is it filtering row? What is slow exactly? Helping with some sort of a benchmark test we can drop in will help here.

**Comment by tmcconechy** [comment] 2020-02-07 15:45
Closing this in favor of https://github.com/infor-design/enterprise/issues/3026

**Closed by tmcconechy** 2020-02-07 15:45 UTC
Labels: [8], focus: datagrid, status: duplicate, type: enhancement :sparkles:, type: support :sos:

**Comment by tmcconechy** [comment] 2020-02-07 15:47
Might be able to look at how https://www.ag-grid.com/ works.
