### ISSUE TITLE
Tabs: TypeError: Cannot read properties of undefined (reading 'parent')

### ISSUE THREAD

**Issue by adamzhang1932** [infor-design/enterprise#8419] opened 2024-02-06 02:57 UTC
**Describe the bug**
One scenario is that:
We initialize the tabs component and then destroy/updated tabs component immediately.
And then some errors occured:
`TypeError: Cannot read properties of undefined (reading 'parent')
    at Tabs.positionFocusState (tabs.js:3816:33)
    at tabs.js:491:12`

**To Reproduce**

1.There is one mock javascript file to reproduce this issue, it just simplifies the logic in tabs.js file.
[TabsMock.zip](https://github.com/infor-design/enterprise/files/14174027/TabsMock.zip)
2.You can download the attachment file [TabsMock.zip] and unzip it and just run the TabsMock.js file.
3.Then you will see the error:
![image](https://github.com/infor-design/enterprise/assets/151612185/65e4ed7b-41dc-4759-ba61-c592da092944)

The logic to reproduce this issue is that:
Initialize the tabs component and then call the destroy method or updated method immediately.

**Expected behavior**

**Version**
- ids-enterprise: v4.91.0, it can be reproduced in the earlier version.

**Screenshots**
<img width="960" alt="f1" src="https://github.com/infor-design/enterprise/assets/151612185/fb1d54c7-b285-4b6f-aea5-39d368804b8a">
<img width="960" alt="f2" src="https://github.com/infor-design/enterprise/assets/151612185/d06e5f14-8e77-4285-aaa7-ec4705ab3530">

**Platform**
 - Infor Application/Team Name: Infor SunSystems
 - Device: 
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 121.0.6167.140 (Official Build) (64-bit)

**Additional context**
The reason for this issue might be that there is a timer, see it below.
And the timer will be called after 100ms.
And if destroy method OR updated method is called before the timer, the variable focusState will be set 'undefined', and then 
the error will occur.
![image](https://github.com/infor-design/enterprise/assets/151612185/f27ce9d7-be3c-4612-8b1f-64539e1b0796)

**I just wonder that whether it is better to 'clearTimeout' when destroy method OR updated method is called.** 
**_For example:_**
![image](https://github.com/infor-design/enterprise/assets/151612185/36eb7409-15cf-4541-9cf5-f7ac35a3d448)

**Comment by tmcconechy** [comment] 2024-02-06 14:51
@adamzhang1932 if you can do try 4.92.2 i think this may be fixed but did not verify it for you yet, so give it a try. If not we'll add this next sprint

**Comment by adamzhang1932** [comment] 2024-02-07 05:29
@tmcconechy I cannot verify it, because when I upgrade it to 4.92.2, a new error occurred:

![image](https://github.com/infor-design/enterprise/assets/151612185/ab8ced4d-1ae5-4566-9860-2ce0209b91a7)

![image](https://github.com/infor-design/enterprise/assets/151612185/5c6b90a2-b260-46ea-8a85-6c6e6e730a39)

**Comment by adamzhang1932** [comment] 2024-02-07 05:49
@tmcconechy When I upgrade IDS to 4.92.2, a new error occurred.

TypeError: Cannot read properties of undefined (reading 'prop')


![image](https://github.com/infor-design/enterprise/assets/151612185/5710aa53-8f29-4533-a48e-4b503d227586)

![image](https://github.com/infor-design/enterprise/assets/151612185/1dff0360-3536-4e2e-aca0-1d87d83379d9)

**Comment by nbeare-infor** [comment] 2024-02-14 11:25
Hi Team

Good to see that this in in Enterprise (Next) Sprint Grooming 👍. Might a fix for this be coming out in 4.92.3?
Reason I ask is it is blocking us on a number of our Jira tickets and if we upgrade atm to 4.92.2 it breaks one of our apps completely.

**Comment by tmcconechy** [comment] 2024-02-14 16:41
@nbeare-infor @adamzhang1932 

1. I added a guard which may fix this issue. Im going to put it in a 4.92.3 patch so you can test it. See announcements and try.
2. I was unable to reproduce this issue, im not sure how to "run the tabMock.js" file thats a bit unclear. Can you test out my patch when its done later today and then if you still have an issue please update the steps.

We can include it in 4.93.0 if clearer. Or if you want to suggest an exact code change to fix it and I can add that?
Thanks!

**Comment by nbeare-infor** [comment] 2024-02-14 17:05
Excellent! Thanks @tmcconechy . 

I think @adamzhang1932 's tabMock.js was  provided to highlight his original error, not the latest.
We'll give the patch a try when it's available and come back to you.

**Comment by tmcconechy** [comment] 2024-02-14 18:20
@nbeare-infor 

Give This release a try with my "guards" added for possible fix
https://github.com/infor-design/enterprise-ng/releases/tag/17.4.4
 
Announcements:  https://teams.microsoft.com/l/message/19:4cb6cf62e9ff4856b1c3a9428cde3ef6@thread.skype/1707934721627?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1707934721627&teamName=IDS%20Enterprise%20Development&channelName=Announcements&createdTime=1707934721627

**Comment by nbeare-infor** [comment] 2024-02-15 11:22
Thanks Tim. Appreciated. Are you planning to release a  4.92.3 patch also, as we don't take enterprise-ng releases?

**Comment by tmcconechy** [comment] 2024-02-15 13:48
@nbeare-infor yes its available as enterprise release:

https://www.npmjs.com/package/ids-enterprise/v/4.92.3
https://github.com/infor-design/enterprise/releases/tag/4.92.3

(i thought you used angular)

**Comment by nbeare-infor** [comment] 2024-02-15 17:29
Thanks @tmcconechy . That's excellent. I'll give that a try tomorrow.

Theo's (.net) team may use Angular I think. But java team (inc myself, Adam and Rikesh) use ids-enterprise.

**Comment by nbeare-infor** [comment] 2024-02-16 11:51
Hi @tmcconechy 
Just tested with v4.92.3. Unfortunately get same issue:-
![image](https://github.com/infor-design/enterprise/assets/49482971/1b62c41f-6deb-4de2-bffa-3cb97a8b93bc)

![image](https://github.com/infor-design/enterprise/assets/49482971/82d78975-3215-4f74-91a8-f41d780c3c16)

**Comment by tmcconechy** [comment] 2024-02-16 15:35
ok @nbeare-infor can you provide the way to reproduce this as i wasnt sure how to run what you gave me. The part about the timeout is the thing that complicates it for me.

But if you have an idea of what might fix it as an actual change we could also try to fix it that way? Seems like it might just need some sort of a guard on a variable.

Or do you se see anything on these examples https://main-enterprise.demo.design.infor.com/components/tabs/example-index.html  ?

**Comment by nbeare-infor** [comment] 2024-02-16 19:00
Hi @tmcconechy 

Time ran out on me unfortunately. I have asked if @adamzhang1932 in Shanghai might pick this up and run with it.
Otherwise I may be able to carry on on Monday.

Have a great weekend

**Comment by tjamesallen15** [comment] 2024-03-11 06:17
May I know how to test this one?

**Comment by adamzhang1932** [comment] 2024-03-11 08:01
@tjamesallen15  I might give one example to reproduce this issue later, you can pause this issue now.

**Comment by tmcconechy** [comment] 2024-03-11 14:02
Could be the same issue.. Trying to get a fix. @adamzhang1932 can you make sure to provide us the steps. If not maybe @tjamesallen15 you can put a guard on that line

**Comment by adamzhang1932** [comment] 2024-03-12 01:03
@tmcconechy @tjamesallen15 I am not sure whether I can provide the steps. It might take a long time to investigate for it.

**Comment by tmcconechy** [comment] 2024-03-12 13:13
ok @tjamesallen15 can you just add `.?` on the lines as shown in the screen shot error and PR? i.e. `this.focusState?.parent()?.is`... 

That might fix it ...

**Comment by tjamesallen15** [comment] 2024-03-13 13:28
> ok @tjamesallen15 can you just add `.?` on the lines as shown in the screen shot error and PR? i.e. `this.focusState?.parent()?.is`...
> 
> That might fix it ...

will do!

**Closed** 2024-03-14 15:22 UTC
Labels: type: bug :bug:, [2]
