### ISSUE TITLE
Buttons Control: The buttons for "Primary" and "Secondary" need spacing

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#300] opened 2018-06-28 19:39 UTC
**Describe the bug**
The buttons for "Primary" and "Secondary" need spacing

**To Reproduce**
1. Go to url: http://480-beta0-sohoxi.demo.design.infor.com/components/button/test-on-tab.html
2. The buttons for "Primary" and "Secondary" need spacing
3. Please see screen shot attached. 

**Expected behavior**
Spacing is needed

**Screenshots**
![buttons_tabs](https://user-images.githubusercontent.com/39101346/42056685-04d6a7a2-7ae9-11e8-847d-594939bf87d2.png)

**Platform**

 - All Browsers 

**Additional context**
None

**Comment by tmcconechy** [comment] 2018-06-28 19:47
Note to someone fixing this do not add padding / margin to the buttons.
Rather update the example to but the buttons in a grid row/column setup that has padding.

**Comment by theakatz** [comment] 2018-10-15 16:29
duplicate of #691

**Comment by brianjuan** [comment] 2018-10-16 10:35
http://localhost:4000/components/button/test-on-tab.html
http://master-enterprise.demo.design.infor.com/components/button/test-on-tab.html
Passed QA testing across all browsers

**Closed** 2018-10-25 20:15 UTC
Labels: status: duplicate, type: bug
