### ISSUE TITLE
Dropdown: Syntax error on dropdown with ":" in id attribute

### ISSUE THREAD

**Issue by chamilledyan** [infor-design/enterprise#4432] opened 2020-09-29 15:27 UTC
**Describe the bug**
Dropdown element not generated. 
Encountered Uncaught Error: Syntax error on dropdown with ":" in id attribute
Note: we are using a framework that dynamically generates id and unable to control this behavior

**To Reproduce**
Create a dropdown element with ":" in id attribute
Sample
![image](https://user-images.githubusercontent.com/68043861/94578815-b9cf5280-02aa-11eb-9f88-1dc5982f1ea3.png)

**Expected behavior**
Dropdown should be created

**Version**

- ids-enterprise:  4.32.1

**Screenshots**
![image](https://user-images.githubusercontent.com/68043861/94579065-fef38480-02aa-11eb-8d73-c510070c3164.png)
![image](https://user-images.githubusercontent.com/68043861/94579077-01ee7500-02ab-11eb-872c-2b48df02748f.png)
![image](https://user-images.githubusercontent.com/68043861/94579094-04e96580-02ab-11eb-85b3-3d5c124e99ff.png)

**Platform**
 - Infor Application/Team Name: Mobile Supply Chain Mgt
 - Device: Desktop
 - OS Version: Windows 10
 - Browser Name: Microsoft Edge Chrome
 - Browser Version: 85.0.4183.121

**Additional context**

**Comment by tmcconechy** [comment] 2020-09-30 15:59
Pretty much the same issue as https://github.com/infor-design/enterprise/issues/4357 since we have multiple requests. Lets fix this 👍

**Comment by tmcconechy** [comment] 2020-10-22 18:25
I tried this on 4.34 and could no longer reproduce. Perhaps a change fixed this. Test page https://master-enterprise.demo.design.infor.com/components/dropdown/test-wierd-ids (will be there in 30minutes)

Moving to QA to test

**Closed by tmcconechy** 2020-10-22 18:25 UTC
Labels: [3], type: bug :bug:

**Comment by jbrcna** [comment] 2020-10-26 10:36
The issue is now resolved. moving this ticket to done. thank you
