### ISSUE TITLE
Datagrid: Mask for a large number is incorrectly transposing the number

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#5318] opened 2021-06-15 17:32 UTC
Describe the bug
When entering a large integer number into a list cell, the entered value is being incorrectly transformed with the applied mask.  An 18 digit integer number is being transformed from 123456789012345678 into 123456789012345680. 

1. Using the attached 'test-integer-maskoptions.html'
2. Click on a Batch Number cell
3. Enter the value of 123456789012345678 into the cell and tab out
4. Notice that the number has been transposed to 123456789012345678

Expected behavior
Mask is correctly applied to the integer number

Version
- ids-enterprise: v4.51.0-dev

Additional context
This is a critical issue for Landmark since the user is unable to enter say a Batch Number correctly or to filter on an 18 digit Batch Number.

Seems to be related to https://github.com/infor-design/enterprise/issues/5308,

Is an issue for both List and Form.  For the form example could use the following... 
Goto https://master-enterprise.demo.design.infor.com/components/locale/test-format-big-negative.html
Enter the value of 123456789012345678
Click on the Format button

**Comment by claudenbach** [comment] 2021-06-15 17:35
[Git-5318.zip](https://github.com/infor-design/enterprise/files/6657568/Git-5318.zip)

**Comment by tmcconechy** [comment] 2021-06-15 17:40
Is this from before or after fixing #5308 ?

**Comment by claudenbach** [comment] 2021-06-15 17:41
Here is the Landmark example...

![LMCLIENT-35901](https://user-images.githubusercontent.com/39804038/122098862-fad6ab00-cdd6-11eb-8ac2-3d685a62aed1.gif)

**Comment by claudenbach** [comment] 2021-06-15 17:46
Sure, I can retest with NG 9.5.1

**Comment by tmcconechy** [comment] 2021-06-15 17:57
Still see the issue i tested it with the fix too.

FYI max supported number is 18.6 https://github.com/infor-design/enterprise/blob/main/src/utils/number.js#L49
123456789012345678

So this should work. Taking a look

**Comment by Sovia** [comment] 2021-06-15 18:36
We also saw some weirdness, where if the last two digits were 71 it would be changed to 60.

So: 123456789012345671 -> 123456789012345660

**Comment by tmcconechy** [comment] 2021-06-15 19:32
FYI the issue is this number is outside whats supported in JS.

```
parseFloat('123456789012345678')
123456789012345680
```

I think to fix we can make parseNumber use a string.

**Comment by tmcconechy** [comment] 2021-06-15 20:19
Accidentally pushed the fix to main directly so no PR. Steps to test: https://github.com/infor-design/enterprise/commit/5a5c1b28a7327beb056146da90c9d18796101476

- go to http://localhost:4000/components//locale/test-format-big-negative.html
- paste 123456789012345671 and hit format (should not change the numbers except for adding .00
- paste 123456789012345671 and hit format (should not change the numbers except for adding .00

**Closed** 2021-06-15 20:19 UTC
Labels: [2], priority: high, type: bug :bug:

**Comment by tmcconechy** [comment] 2021-06-16 14:01
So two patches done
 	NG 9.4.6 -> This has 4.50.4 which contains just #5308
	NG 9.5.2 -> This has 4.51.4 which contains both #5308 and #5318

**Comment by jbrcna** [comment] 2021-06-18 06:42
this is now working as expected. thank you
v4.53.0-dev
https://main-enterprise.demo.design.infor.com/components//locale/test-format-big-negative.html
![image](https://user-images.githubusercontent.com/56722184/122517293-6a040780-d042-11eb-8447-20729d8e7d98.png)
