### ISSUE TITLE
Datagrid: Date Formatter not working with the textOverflow option

### ISSUE THREAD

**Issue by petr-hlavnicka** [infor-design/enterprise#2853] opened 2019-09-27 12:11 UTC
![1_code](https://user-images.githubusercontent.com/49194823/65768207-9b32fa80-e130-11e9-86e7-6f94497822da.png)
![2_no_ellipsis_by_date](https://user-images.githubusercontent.com/49194823/65768209-9b32fa80-e130-11e9-86d9-b0a20d514824.png)

**Describe the bug**
The parameter _textOverflow: 'ellipsis'_ does not work for _formatter: Soho.Formatters.Date_.

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/test-ellipsis.html
2. Resize the order date column
3. Make sure textOverflow: 'ellipsis is set in the code
4. Should see ellipsis on this type

**Expected behavior**
Ellipsis should work with textOverflow. Also check all types (alert maybe).

**Version**
- ids-enterprise-ng: [e.g. v4.21.0]

**Platform**
 - Chrome/mac or any

**Comment by deep7102** [comment] 2019-10-09 17:28
Hi @petr-hlavnicka cannot reproduce this looks fixed with some other issue. check at your end should work fine, also added PR #2942 to update the example page.

**Closed** 2019-10-11 13:55 UTC
Labels: [2], focus: datagrid, type: bug :bug:

**Comment by brianjuan** [comment] 2019-10-17 11:26
http://master-enterprise.demo.design.infor.com/components/datagrid/test-ellipsis.html
![image](https://user-images.githubusercontent.com/39508864/67004880-e333b480-f113-11e9-8b63-5ed670fec67c.png)
