### ISSUE TITLE
Field Filter: Unable to select in Dropdown field

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5504] opened 2021-08-09 11:41 UTC
**Describe the bug**
Field Filter: Unable to select in Dropdown field

**To Reproduce**

1. Go to https://4540-beta0-enterprise.demo.design.infor.com/components/field-filter/example-index.html & https://4540-beta0-enterprise.demo.design.infor.com/components/field-filter/example-short.html
2. Tab to dropdown and select Inquiry 

**Expected behavior**
Inquiry should be selected

**Version**
IDS 4.54-beta0

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/128700758-1ede4a98-2db3-4e6c-aef4-907157a20ebd.png)

**Platform**
All major browser, OS and devices

**Additional context**
N/A

**Comment by tmcconechy** [comment] 2021-08-09 13:01
Duplicate of https://github.com/infor-design/enterprise/issues/5310

**Closed by tmcconechy** 2021-08-09 13:01 UTC
Labels: [2], status: duplicate
