### ISSUE TITLE
Datagrid: Tooltip for header is not showing in Chrome and IE. 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3853] opened 2020-05-04 04:18 UTC
**Describe the bug**
Datagrid: Tooltip for the header is not showing in Chrome and IE. 

**To Reproduce**
1. Open Chrome or IE browser & Go to https://4280-rc0-enterprise.demo.design.infor.com/components/datagrid/example-tooltips.html?theme=uplift&variant=light
2. Resize the Order Date column until it becomes 'Order D...'
3. Hover to the Header/Title

**Expected behavior**
The tooltip should show as it has ellipsis. 

**Version**
IDS 4.280-rc0

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/80935776-ca18f980-8e00-11ea-886d-9180b2e6ca41.png)

**Platform**
Windows 10 & macOS Mojave - Chrome Browser
Windows  10- IE 11

**Additional context**
n/a

**Comment by tmcconechy** [comment] 2020-05-04 13:54
Hi @janahintal  

Im not seeing this issue. I tried it in windows 10 chrome and IE11 and im getting a tooltip everytime.
<img width="329" alt="Screen Shot 2020-05-04 at 9 51 55 AM" src="https://user-images.githubusercontent.com/814283/80973148-004c7e00-8ded-11ea-97b2-362871f20209.png">

**Comment by tmcconechy** [comment] 2020-06-05 14:01
Was not able to reproduce this issue so closing

**Closed by tmcconechy** 2020-06-05 14:01 UTC
Labels: [3], status: cant reproduce, type: bug :bug:
