### ISSUE TITLE
Bar Chart: Overlapping and cropped axis labels

### ISSUE THREAD

**Issue by ryanChrstn** [infor-design/enterprise#7614] opened 2023-06-19 08:48 UTC
**Describe the bug**
Bar Charts' axis labels were cropped and overlapped with the chart's legend. Specifically with the bottom label, it was cropped.

**To Reproduce**

1. Go to (https://main-enterprise.demo.design.infor.com/components/bar/example-axis-labels.html)

Prerequisite(for the right label)
Edit the name value to at least six digits number.

**Expected behavior**
Axis labels should be visible at any part of the chart.

**Version**

- ids-enterprise: v4.82.1

**Screenshots**
<img width="593" alt="image" src="https://github.com/infor-design/enterprise/assets/14357059/50f16b22-b292-46bb-b3bf-935312d50233">

**Platform**
 - Infor Application/Team Name: Lawson Portal (LSF)
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: Version 114.0.5735.134 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment] 2023-06-19 13:00
Partly duplicate of https://github.com/infor-design/enterprise/issues/7612
Also you may want to try the newest version of the chart https://main.wc.design.infor.com/ids-bar-chart/

**Comment by ryanChrstn** [comment] 2023-06-20 05:51
Thanks for the update on the newest chart version.

Would like to add as well that the right-axis label is not visible.

**Comment by ericangeles** [comment] 2023-09-13 10:49
The axis label issue should also be fixed now.

**Comment by tmcconechy** [comment] 2023-09-13 14:38
Is this really in progress? I dont see a PR? I think we would need to add an example with 6 digits and see how it works

**Closed** 2023-09-28 14:15 UTC
Labels: type: bug :bug:, [3]
