### ISSUE TITLE
Datagrid: Console error hovering over a parent node in the Data Grid's Tree Grid view

### ISSUE THREAD

**Issue by byannalam** [infor-design/enterprise#4478] opened 2020-10-13 02:30 UTC
**Describe the bug**
When you have the Tree Grid view enabled for the Data Grid, hovering over any parent node will not trigger the tooltip (when the content is long enough to do so). It does not affect the innermost child node. For the same parent nodes, it should be noted that a console error is displayed when you hover over them.

**To Reproduce**
1. Create a Data Grid with the Tree Grid enabled. Enable tooltips.
2. Add a dataset with at least 2 levels of items. The values should be long enough to trigger the tooltip.
3. Open your browser's console.
4. Hover over the parent. Note that the tooltip does not appear. Also take note of the error in the console.

**Expected behavior**
I expect to see the tooltip when I hover over any item with a lengthy value.

**Version**
4.30

**Screenshots**
No tooltip
![image](https://user-images.githubusercontent.com/4402939/95807232-5be44580-0d55-11eb-95c5-a9c826754a90.png)
Parent node that is supposed to have a tooltip
![image](https://user-images.githubusercontent.com/4402939/95810838-9b169480-0d5d-11eb-843a-fa062b58cc3d.png)
Child node with a tooltip
![image](https://user-images.githubusercontent.com/4402939/95810877-b386af00-0d5d-11eb-8332-beb005068ebf.png)

**Platform**
 - Infor Application/Team Name: Infor MRM
 - Device: Dell laptop
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 85.0.4183.121 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment] 2020-10-13 13:45
The way this should work is both the parent and children cell should get the tooltip when hovered.

**Comment by deep7102** [comment] 2020-11-09 17:27
Hi @byannalam this issue looks fixed with some other issue, I cannot reproduced it anymore. Please let me know if you still see this at your end.
- Navigate to: https://master-enterprise.demo.design.infor.com/components/datagrid/test-tree-tooltip.html
- Open developer tools
- Resize browser window small, so first column have some hidden text
- Hover over any cell (parent or child node)
- It should show tooltip and see console should not be any error

**Closed** 2020-11-10 20:50 UTC
Labels: [3], focus: datagrid, status: cant reproduce, type: bug :bug:
