### ISSUE TITLE
Dropdown: automation identifiers

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#4741] opened 2021-01-14 15:27 UTC
**Describe the bug**
Not sure if this should be a bug or feature. But we need to be able to set identifiers on dropdowns. Right now it is set on the select, but since the user needs to user the dropdown div the id needs to be set on that one as well.

**To Reproduce**

1. Go to https://master-enterprise.demo.design.infor.com/components/dropdown/example-index.html 
2. Open dev tools
3. Inspect the dropdown element
4. Note that it's the dropdown div that is clicked and not the select. And that the id is no on the dropdown div

**Expected behavior**
The id set on the select or set in attributes to the select should be added  to the dropdown like id="<added-id>-dropdown"

**Version**

- ids-enterprise: 4.36

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/104611327-4993e380-5685-11eb-84f2-f0ef03445fcd.png)

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version:  Windows 10
 - Browser Name: chrome
 - Browser Version: Version 87.0.4280.141 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment] 2021-01-14 15:32
Working on some dropdown changes and have this fixed locally

**Comment by tmcconechy** [comment] 2021-01-19 14:28
Closing this as a duplicate of https://github.com/infor-design/enterprise/issues/4742 - doing the work there

**Closed by tmcconechy** 2021-01-19 14:28 UTC
Labels: [1], team: homepages, team: landmark, type: bug :bug:

**Comment by janahintal** [comment] 2021-01-20 10:46
QA Passed. Verified in https://master-enterprise.demo.design.infor.com/components/dropdown/example-index.html

![image](https://user-images.githubusercontent.com/45757016/105164156-bf99be00-5b4f-11eb-9288-798efa199f6c.png)

**Comment by SofiK** [comment] 2021-02-23 15:20
@tmcconechy  how do i get the id to work when using the ng components? I can't get it working in Homepages and also the id is not showing on the dropdown in this sample: http://localhost:4200/ids-enterprise-ng-demo/dropdown-simple 
Do I have to add it as as attributes[{name: "id",.value:"my-id"}] for it to work in the angular components?

**Comment by tmcconechy** [comment] 2021-02-23 15:43
I didnt add an example to every single NG component since its the same but i did try it on a few like this one:

https://github.com/infor-design/enterprise-ng/blob/master/src/app/colorpicker/colorpicker.demo.ts#L22
https://github.com/infor-design/enterprise-ng/blob/master/src/app/colorpicker/colorpicker.demo.html#L6

I think when it comes to objects i'd not inline the whole thing.....I'd make a variable

**Comment by SofiK** [comment] 2021-02-23 16:41
Thanks Tim! I just wanted to confim that that was the idea.
