### ISSUE TITLE
Datagrid: Ellipsis formatter not working when datagrid is inside the modal

### ISSUE THREAD

**Issue by krnandam** [infor-design/enterprise#5521] opened 2021-08-16 20:02 UTC
**Describe the bug**
The ellipsis option does not appear to work in datagrid when its in a modal.

**To Reproduce**

1. Go to https://stackblitz.com/edit/ids-enterprise-4520-jtwmtp?file=index.js
2. Click on the button
4. See error -> no ellipsis is shown and the widths are not set (the whole grid is acting as auto size)

**Expected behavior**
The Ellipsis formatter or the `textOverflow: 'ellipsis'` should work when in the datagrid. Also should be able to set the column width and resize the coumns.

**Version**
- 4.54.0

**Screenshots**
NA

**Platform**
- Any platform

**Additional context**
Ms Teams

Here is the sample which is not working when using Soho.Formatters.Ellipsis for a column "Activity" in the grid. 
https://stackblitz.com/edit/ids-enterprise-4520-jtwmtp?file=index.js

![image](https://user-images.githubusercontent.com/89043371/129622545-1b9b4f59-1c20-4579-95ba-9f4a879053d1.png)

**Comment by brianpettit** [comment] 2021-08-17 13:36
How do I get MY stackblitz to show a wider modal?
![image](https://user-images.githubusercontent.com/74990136/129735519-36880cba-d7e6-4a61-81d2-8ee7173b3357.png)

**Comment by tmcconechy** [comment] 2021-08-17 13:38
Click "open in new window" but the example has a fixed width for testing in index.html 

```
 <div id="modal-content" style="display: none;width: 200px">
```

The issue is related to the widths it sets on the modals i think. Cant quite figure this one out

**Comment by tmcconechy** [comment] 2021-08-18 17:33
Closing this as i cannot see a fix that doesnt break anything but i figured out that you can set the width to make it work.

Pushed an example to https://main-enterprise.demo.design.infor.com/components/lookup/test-long-text.html
(takes a bit to come up).

The keys are:

1) Set the table width to override that we use stretch/fill-available by default
https://github.com/infor-design/enterprise/blob/main/app/views/components/lookup/test-long-text.html#L13
2) Set width and maxWidth as needed per column https://github.com/infor-design/enterprise/blob/main/app/views/components/lookup/test-long-text.html#L33
3) Also on https://github.com/infor-design/enterprise/blob/main/app/views/components/lookup/test-long-text.html#L33 can use textOverflow: 'ellipsis'
4) and enableTooltips if wanted on the cut off columns https://github.com/infor-design/enterprise/blob/main/app/views/components/lookup/test-long-text.html#L49

**Closed by tmcconechy** 2021-08-18 17:33 UTC
Labels: type: bug :bug:, [3]

**Comment by tmcconechy** [comment] 2021-08-18 18:04
Note that in Angular the workaround is like this

```
::ng-deep #datagridId table {
 width: 100% !important;
}
```

**Comment by CindyMercadoReyes** [comment] 2021-08-23 18:35
This issue is now resolved.
