### ISSUE TITLE
Toolbarsearchfield: On flex-toolbar, adding the property "showGoButton: true" to .toolbarsearchfield({...}) will cause alignment issues

### ISSUE THREAD

**Issue by kaeleding** [infor-design/enterprise#6014] opened 2022-01-12 10:17 UTC
**Describe the bug**
When using flex-toolbar (behavior is fine on non flex-toolbar), adding the property `showGoButton: true` to `.toolbarsearchfield({...})` will cause alignment issues, as shown in the screenshot section.

**To Reproduce**
1. Edit the page example-flex-toolbar-align-with-searchfield.html and add the code 

```
<script>
  $('#toolbar-searchfield-02').toolbarsearchfield({
    categories: [
      {name: 'Animals', id: 'animals', value: 'an', checked: true},
      {name: 'Baby', id: 'baby', value: 'ba', checked: false},
      {name: 'Clothing', id: 'clothing', value: 'cl', checked: true},
      {name: 'Images', id: 'images', value: 'im', checked: true},
      {name: 'People', id: 'people', value: 'pe', checked: false},
      {name: 'Places', id: 'places', value: 'pl', checked: false}
    ],
    categoryMultiselect: true,
    showGoButton: true
  });
</script>
```

2. Go to http://localhost:4000/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html

3. See the search field is too short (text inside will be unreadable and there's extra margin on the left) and the "X" button is misaligned.

**Expected behavior**
On the non flex-toolbar version, the alignment seems to be fine:

<img width="1154" alt="non_flex" src="https://user-images.githubusercontent.com/18295372/149122213-cf47712c-6575-4bc1-bf9b-02bbdd6a17d6.png">

**Version**
- ids-enterprise: 4.60.0-dev

**Screenshots**

<img width="641" alt="misaligned" src="https://user-images.githubusercontent.com/18295372/149121312-66843ee0-fec3-49e9-87a8-88d1bebd83c6.png">

**Platform**
 - Infor Application/Team Name: Infor Lawson
 - Browser Name: Chrome 
 - Browser Version: Version 97.0.4692.71 (Official Build) (64-bit)

**Comment by hsubtain** [comment] 2022-11-25 03:24
Hi @tmcconechy, would like to ask on the possible delivery date for the fix on this issue? Thank you!

**Comment by tmcconechy** [comment] 2022-11-27 14:32
I'll try to get this in the January sprint. (Complete and released early Feb)

**Comment by s-werking** [comment] 2023-01-18 17:51
Hi @tmcconechy, yes we are planning on removing the Go button from our searchfield. I think for this issue, we were looking into migrating from a toolbar to toolbar-flex for our searchfield. Here is the sample that has the toolbar component:
http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html

In the past this has been a discussion (PR #6722), but there are some issues when using the toolbar-flex component. I created a new sample to see the issues in the header by subbing a toolbar-flex component in for the toolbar in the existing sample above and removing the Go Button.
Please use this zipped html file: [example-category-searchfield-home-flex-toolbar.zip](https://github.com/infor-design/enterprise/files/10449023/example-category-searchfield-home-flex-toolbar.zip)

We're hoping to have the visual issues of the toolbar-flex component fixed on this ticket so that migrating to toolbar-flex could be a possibility.

**Comment by tmcconechy** [comment] 2023-01-18 18:18
ok lets take a look @ericangeles but lets scope it to flex toolbar only (dont fix against both old and new toolbar)

**Comment by tmcconechy** [comment] 2023-02-22 18:51
@yohannahbautista i dont think this really fits with the other buttons. Can we make the go button:

- have no   /* background-color: #d7d7d8;
- have the press state

So basically it is like all other buttons. (icon button ect) but has a border so it looks attached to the field.

**Closed** 2023-02-27 05:56 UTC
Labels: type: bug :bug:, [2], team: lawson

**Comment by janahintal** [comment] 2023-02-27 17:19
Hello team, the 'x' button still looks off on classic and new theme. 

Classic: 
![image](https://user-images.githubusercontent.com/45757016/221633774-d903cf0c-e3dc-4ac5-8d07-80e00f00838a.png)

New:
![image](https://user-images.githubusercontent.com/45757016/221633920-9068f7b7-7b02-4008-9b1f-ecfc42b12a6b.png)

**Comment by janahintal** [comment] 2023-03-09 09:46
Hi Team, the 'x' and minimize icon is overlapping in responsive view.
Test Evidence: 
![image](https://user-images.githubusercontent.com/45757016/223983557-173fdfbf-a2bb-4a15-986c-7e60e45d3294.png)
Video: https://www.screencast.com/t/m6u5NfwF

**Comment by tmcconechy** [comment] 2023-03-09 14:27
cc @yohannahbautista ☝🏻

**Comment by janahintal** [comment] 2023-03-13 14:11
Hi @yohannahbautista, the issue still exists in https://main-enterprise.demo.design.infor.com/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html?theme=classic&mode=light&colors=default Kindly play around 644 x 500 to 746 x 500 responsive view. 
Video: https://www.screencast.com/t/cJ34LXH41N

**Comment by yohannahbautista** [comment] 2023-03-14 03:59
Hello, on running in local, the icons are aligned:
<img width="743" alt="image" src="https://user-images.githubusercontent.com/85279127/224889472-afdb090d-5344-47af-a6cd-79969bd90893.png">
<img width="736" alt="image" src="https://user-images.githubusercontent.com/85279127/224889538-8c1e91b4-ea95-4ffc-9144-5dddbc9374ca.png">
<img width="688" alt="image" src="https://user-images.githubusercontent.com/85279127/224889576-ac4429cc-16b2-4bf7-bbab-8b043c75accd.png">
<img width="709" alt="image" src="https://user-images.githubusercontent.com/85279127/224889607-72a6b108-924b-41ff-90e7-3f6f9ca059ec.png">

**Comment by tmcconechy** [comment] 2023-03-14 14:02
Ok will put this in QA to test again

**Comment by janahintal** [comment] 2023-03-14 17:32
QA Passed. The issue is now resolved in https://main-enterprise.demo.design.infor.com/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html?theme=classic&mode=light&colors=default. Thank you! 
![image](https://user-images.githubusercontent.com/45757016/225089548-6d9df362-debf-4f5c-bd5a-9beab97afc35.png)
