### ISSUE TITLE
Dropdown: Typing capital letters in an open noSearch dropdown does not focus a value

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#6069] opened 2022-01-27 14:51 UTC
**Describe the bug**
Typing a capital letter to select a value works when the dropdown is closed, but not when the dropdown is open. This happens on dropdowns with the noSearch option set to true.

**To Reproduce**
1. Go to http://localhost:4000/components/dropdown/example-no-search-lsf.html
2. Click on the top dropdown to open it
3. Type "T"
Expected Result: "T - Thor"  should be focused
Actual Result: The blank option is focused

**Expected behavior**
When a capital letter is typed in an open dropdown with noSearch turned on, the corresponding option should receive focus just as it would when the lowercase letter is typed.

**Version**
- ids-enterprise: v.4.60.0-dev

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows10
 - Browser Name: chrome
 - Browser Version: Version 97.0.4692.99 (Official Build) (64-bit)
Related Lawson JIRA Ticket: [LSF-50656](https://jira.lawson.com/browse/LSF-50656)

**Comment by tmcconechy** [comment] 2022-01-27 14:54
Seems like it just happens the first time...

**Comment by awbuboltz** [comment] 2022-01-27 17:07
Note, this is the second occurrence of this issue: https://github.com/infor-design/enterprise/issues/4757

**Comment by tmcconechy** [comment] 2022-01-27 17:09
OK lets be sure to add a test to (who picks this up...)

**Comment by awbuboltz** [comment] 2022-02-18 16:28
Hey team, this issue is causing a large majority of our tests to fail and makes it difficult to use our product. Any chance of it getting looked at sooner than later?

**Comment by tmcconechy** [comment] 2022-02-18 16:31
Added to the sprint can you look when you can @ericangeles

**Comment by davidcarlsonberg** [comment] 2022-02-18 18:01
Just attempted this and it worked fine. Steps below:
- Visit master-enterprise.demo.design.infor.com/components/dropdown/example-no-search-lsf.html
- Click on top dropdown arrow to open
- Press Shift + T
- Notice T - Thor is highlighted
![windows10chrome-dropdown](https://user-images.githubusercontent.com/7952168/154737340-469fd782-6821-41c2-b6f6-d762d78d4ef8.png)

**Comment by tmcconechy** [comment] 2022-02-18 18:08
@davidcarlsonberg try it on https://main-enterprise.demo.design.infor.com/components/dropdown/example-no-search-lsf.html instead (master is old) or local

**Comment by awbuboltz** [comment] 2022-02-18 18:31
@davidcarlsonberg, are you seeing it now on main-enterprise?

**Comment by davidcarlsonberg** [comment] 2022-02-18 18:39
Yes, I can reproduce it now. It happens only the first time you click Shift + T on Windows10 Chrome.

**Comment by tmcconechy** [comment] 2022-02-25 14:41
Great - do you think you can fix this before the end of the month @davidcarlsonberg ?

**Comment by davidcarlsonberg** [comment] 2022-02-25 18:40
@tmcconechy I'll prioritize this over the weekend and have an update Monday.

**Comment by davidcarlsonberg** [comment] 2022-02-28 14:50
Unfortunately, I'm not unable to reproduce this using Browserstack. Can anyone else reproduce in that environment?

**Comment by tmcconechy** [comment] 2022-02-28 16:22
Im not able to reproduce it either (never have) - but since the search is case insensitive anyways i wonder if this can be fixed by making both ends of the string lowerCase?

Do you have any suggestions for a fix @s-werking since you can see it clearly?

**Comment by s-werking** [comment] 2022-02-28 18:16
It looks like this issue started happening after the noSearch dropdown input was disabled in: https://github.com/infor-design/enterprise/pull/5369

Without this line in dropdown.js, a capital letter is searched correctly, although a disabled search does make sense:
this.searchInput.prop('readonly', this.settings.noSearch);

The issue is that once it hits the line 1766 (self.highlightStartsWith(self.filterTerm);), self.filterTerm is the Shift key symbol and "t" when in branch 4.52.x self.filterTerm is just "t" for the case that "T" is entered in the dropdown search.

**Comment by s-werking** [comment] 2022-02-28 18:39
Okay I may have found a possible fix. Let me know what you think @davidcarlsonberg @tmcconechy .

Line 1629 - Add '&& !self.isControl(key)' to the conditional

**Comment by s-werking** [comment] 2022-02-28 18:39
of dropdown.js

**Comment by tmcconechy** [comment] 2022-02-28 19:22
Can you try to push that - and then we just test out everything else on a PR @davidcarlsonberg and assume it fixes?

**Comment by s-werking** [comment] 2022-02-28 19:39
Just pushed this to main. Should be ready for a pull request for testing, thanks!

**Closed** 2022-03-03 10:28 UTC
Labels: type: patch, type: regression bug  :leftwards_arrow_with_hook:, [2], priority: high, team: lawson

**Comment by jbrcna** [comment] 2022-03-04 06:48
this issue is now resolved. moving this ticket to done. thanks
verified in https://main-enterprise.demo.design.infor.com/components/dropdown/example-no-search-lsf.html
`BS Win 10 chrome 97`
![Large GIF (956x494)](https://user-images.githubusercontent.com/56722184/156713550-b9a0e4d0-ac6d-42da-b283-70cc2ff748a5.gif)
