### ISSUE TITLE
soho-tooltip doesn't work with readonly input type=number which allows decimal value

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise#1964] opened 2019-04-11 07:52 UTC
**Describe the bug**
When using soho-tooltip with readonly input type=number which allows decimal value, the tooltip doesn't show when mouse over the input field.

**To Reproduce**
1. Open example app of enterprise-ng
2. Go to `tooltip.demo.html`
3. Add this code
```
<label for="foo">Foo input label</label>
<input type="number" id="foo" name="foo" step="0.01" [disabled]="true"
       soho-tooltip [title]="'3.14'" value="3.14">
```
4. Mouse over this input field and no tooltip shows

**Expected behavior**
Tooltip should show normally like other input fields. I haven't checked all input field types yet but I think tooltip should work on all input field types.

**Version**
- ids-enterprise-ng: master branch

**Screenshots**
**N.A.**

**Platform**
 - Device **N.A.**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 73.0.3683.103 (Official Build) (64-bit)

**Additional context**
**N.A.**

**Comment by clepore** [comment] 2019-04-16 15:20
@tmcconechy I think the problem being discussed is that the tooltip doesn't work with a readonly input.

**Comment by tmcconechy** [comment] 2019-04-16 15:23
@ahnpnl Seems i may have misread part of this and i now have a fuller understanding. In general whatever input you want to use should be fine. The problem is that the number types use browser styling but thats ok I guess.

The real problem you mentioned is that its disabled and then the tooltip wont show. We had an issue for that https://github.com/infor-design/enterprise/issues/453 which was fixed for buttons. The problem is tricky because disabled elements do not get some events needed for tooltips to work.
There is also a workaround there you could attempt.

To fix this problem on inputs we have this issue: https://github.com/infor-design/enterprise/issues/579 So if that was solved it would work for you after that.

**Comment by ahnpnl** [comment] 2019-04-16 15:25
Yes I think that workaround is possibly working.

**Comment by tmcconechy** [comment] 2019-04-16 15:27
Ok, Lets leave spinbox alone, and say we support any input type you want (as thats not the problem).
So we just have this as Duplicate of #579 , so i will close. Feel free to watch and vote that one up and try that workaround out.

**Comment by clepore** [comment] 2019-04-16 15:28
Duplicate of #453

**Closed by tmcconechy** 2019-04-16 15:27 UTC
Labels: [5], type: enhancement :sparkles:

**Comment by tmcconechy** [comment] 2019-04-16 15:31
Duplicate of #453

Ok, Lets leave spinbox alone, and say we support any input type you want (as thats not the problem).
So we just have this as Duplicate of 579 , so i will close. Feel free to watch and vote that one up and try that workaround out.

**Comment by ahnpnl** [comment] 2019-04-17 06:44
confirmed workaround works. However, the developer has to adjust the wrapper width otherwise tooltip will just be at half width of the wrapper
