### ISSUE TITLE
Popover: header-color  - tool tip title alignment Vibrant/Uplift

### ISSUE THREAD

**Issue by johnbarcena** [infor-design/enterprise#2952] opened 2019-10-10 10:43 UTC
**Describe the bug**
tool tip title alignment using Vibrant/Uplift

**To Reproduce**
1. Go to 'http://4220-beta0-enterprise.demo.design.infor.com/components/popover/example-header-color.html'
2. Switch to Vibrant Theme
3. Verify Pop-Over

**Expected behavior**
![image](https://user-images.githubusercontent.com/52902639/66561868-ea474980-eb8c-11e9-9495-660d947d45e1.png)

**Version**
4.22 Beta

**Screenshots**

![image](https://user-images.githubusercontent.com/52902639/66561433-0ac2d400-eb8c-11e9-9f7f-5bc993b1bfb9.png)

**Platform**
ALL browser 
ALL device

**Additional context**
in mobile, the container is squished
related to #2272
![image](https://user-images.githubusercontent.com/52902639/66561558-46f63480-eb8c-11e9-8008-defc72ec2e7c.png)

**Comment by tmcconechy** [comment] 2019-10-10 13:23
Duplicate of #2954

**Closed by tmcconechy** 2019-10-10 13:23 UTC
