### ISSUE TITLE
DataGrid: Row re-order is broken after trying to reorder rows

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#6938] opened 2022-11-02 10:45 UTC
**Describe the bug**
DataGrid: Row re-order is broken after trying to reorder rows

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-row-reorder.html?theme=classic&mode=light&colors=2578a9
2. Try to move the first row to another

**Expected behavior**
Row should be moved accordingly 

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]
IDS 4.69-DEV

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/199469519-1862a9eb-c41e-4188-8ca6-6838028162d3.png)

**Platform**
Windows 10 Chrome and all major Browsers and OS. 

**Additional context**
N/A

**Comment by tmcconechy** [comment] 2022-11-02 13:27
Looks ok to me @janahintal ?

**Comment by tmcconechy** [comment] 2022-11-22 14:50
Closing older issues we cant reproduce.

**Closed by tmcconechy** 2022-11-22 14:50 UTC
Labels: type: bug :bug:, status: cant reproduce, [2]
