### ISSUE TITLE
Dirty Tracker: Color issue on High Contrast theme

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1465] opened 2019-01-07 10:53 UTC
**Describe the bug**
Dirty Tracker: Color issue on High Contrast theme. Dirty Tracker color is gray instead of yellow.

**To Reproduce**
1. Go to http://localhost:4000/components/trackdirty/example-index.html
2. Change the theme to High Contrast
3. Type "something" on the Text box, tab out
4. See issue: Dirty Tracker color is gray instead of yellow

**Expected behavior**
Dirty Tracker should stay as color yellow on all themes

**Version**
- ids-enterprise: v4.15.0

**Screenshots**
<img width="587" alt="screen shot 2019-01-07 at 6 46 38 pm" src="https://user-images.githubusercontent.com/39508864/50764347-4ce18100-12ad-11e9-9901-f0eaa1fad187.png">

**Platform**
 - All Devices, OS and browsers

**Additional context**
No additional context.

**Comment by tmcconechy** [comment] 2019-01-07 14:19
This changed because the alert color changes so that we could be WCAGAAA compliant with contrast on that theme. So it is correct now.

**Comment by clepore** [comment] 2019-01-07 14:39
Yeah, @kayiuho , any thoughts on what we should do?

**Comment by kayiuho** [comment] 2019-01-07 16:51
This is a tricky one.. one solution I thought of was moving the indicator to the right of the elements (to the left side of the words), similar to how the dirty indicator sits for the color picker UI.

**Comment by tmcconechy** [comment] 2019-01-07 16:54
That could work for checkbox and maybe radio too (its a but funny there). Maybe another idea is to do something on the label (similar to how a required checkbox is) but would have to come up with something new and move them all.

What about the color? Is it correct on high contrast now?

**Comment by kayiuho** [comment] 2019-01-07 17:03
Yea, I thought about having the dirty indicator showing on the labels too because currently for checkboxes and radio buttons, the indicator is "attached" to the first selection which could be a little misleading. I'd need to try a couple things in design (including the label+indicator combo) and see what looks the best. 

For color, yes, #504100 is what we're going for in order to get a 7.0+ contrast ratio.

**Comment by tmcconechy** [comment] 2020-03-09 16:52
Can no longer reproduce this issue. This was fixed on a different issue, the color is now yellow

**Closed by tmcconechy** 2020-03-09 16:52 UTC
Labels: [1], type: bug :bug:
