### ISSUE TITLE
Toolbar contrast is changing in iOS devices 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3053] opened 2019-10-30 08:59 UTC
**Describe the bug**
Toolbar contrast is changing in iOS devices 

**To Reproduce**
1. Open iOS Device
2, Go to http://master-enterprise.demo.design.infor.com/components/toolbar/example-full-toolbar.html?
3. Notice that there is a difference in contrast in the label in the toolbar

**Expected behavior**
Color and contrast should be consistent

**Version**
Beta 4.23

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/67843161-6b638200-fb36-11e9-925d-2a7eec7df916.png)

**Platform**
iOS Mobile Devices
Tested in iPhone XR

**Comment by tmcconechy** [comment] 2019-10-30 13:07
@janahintal im not sure what you are referring to here?
@EdwardCoyle do u see anything wrong?

**Comment by EdwardCoyle** [comment] 2019-10-30 14:50
Is it that the button labeled "Second" is bold in the screenshot for some reason?

**Comment by tmcconechy** [comment] 2019-10-31 13:37
Closing this as too minor to worry about / not able to reproduce easily.

**Closed by tmcconechy** 2019-10-31 13:37 UTC
Labels: [1], priority: minor, status: cant reproduce, type: bug :bug:
