### ISSUE TITLE
Tabs: When Dismissing tabs getting extra events

### ISSUE THREAD

**Issue by nbeare-infor** [infor-design/enterprise#1940] opened 2019-04-10 12:42 UTC
**Bug Description**
There appears to be an issue with the close event on the Tabset control when closing Dismissible tabs. Discovered in version 4.14, but evident also in the latest version (4.17).

**To Reproduce**
1. Goto  https://design.infor.com/code/ids-enterprise/latest/demo/components/tabs/example-dismissible-tabs (I used Chrome in order that DevTools could be used)
2. Open Dev Tools (CTRL-SHIFT-I).
3. To get the console output, paste the following 2 lines into the console window, against the command prompt:-
$('#tabsetC').on('close', function(e, anchor) { console.log("Close -> " + anchor[0].href); });
$('#tabsetC').on('afteractivated', function(e, anchor) { console.log("AfterActivated -> " + anchor[0].href); });
4.  Back on the example-dismissible-tabs page in the browser, close a tab with a simple mouse click (left button) on the x on the tab and observe the 2 AfterActivated events trace in the console window, after the close event. There should only be one.
<img width="505" alt="dismissibleCloseCllick" src="https://user-images.githubusercontent.com/49482971/55878734-e5311f80-5b94-11e9-908a-0cfd099e980f.png">

**Expected Behaviour**
Only the close event and one AfterActivated Event should be triggered. This can be observed if the mouse button (still the left one) is clicked and kept depressed for a while before releasing. I closed Internet Explorer tab this time:-
<img width="485" alt="dismissbleCloseClickAndHold" src="https://user-images.githubusercontent.com/49482971/55879561-d186b880-5b96-11e9-8cfb-b88bbc15eb12.png">

**Version**
4.14, 4.15 and 4.17

**Screenshots**
See above for link to your example-dismissible-tabs page and also for console output I observed for each scenario.

**Platform**
hp Elitebook running Windows 10.
Chrome Browser 
Browser Version 73.0.3683.86

**Comment by tmcconechy** [comment] 2019-04-10 12:55
Can you please edit the issue to follow the bug reporting template https://github.com/infor-design/enterprise/issues/new?template=bug_report.md

I do not understand this issue? It doe'snt appear that there is anything going in the console when i click the tabs to close them. Even if there was, that shouldnt be a problem as its showing the events fire?

So the issue to me is unclear. Perhaps using the template will help us understand the issue.

**Comment by nbeare-infor** [comment] 2019-04-10 13:28
Thanks for coming back so quick! I shall edit the issue to more closely follow the template and also put some instruction on how to get the trace info in the console log. In essence when the tab is closed, it is incorrectly firing an AfterActivated event on the tab that has been closed (in addition to an AfterActivated event on the tab that is being Activated in its place).

**Comment by tmcconechy** [comment] 2019-04-10 13:46
OK, Sounds good. I think the problem was reported here: 
https://github.com/infor-design/enterprise/issues/426

But we couldnt reproduce based on that. I also wonder if https://github.com/infor-design/enterprise/pull/1938 will solve this. The issue is that the tab is actually being focused when you close it for a sec and then the other tab is. So maybe you can workaround it in the events. But its maybe not quite perfect so looking for your issue corrections. Thanks!

**Comment by nbeare-infor** [comment] 2019-04-10 15:48
Hi
Appending the emboldened and italisised code to below, works!

      // to the tablist element so that tabs can be added/removed/hidden/shown without
      // needing to change event bindings.
      this.tablist.on('mousedown.tabs', '> li', function (e) {
        self.handleAddFocusData(e, $(this));

        if ($(e.target).hasClass('close') && $(e.target).parent().hasClass('has-popupmenu')) {
          var menu = $(this).data('popupmenu').menu;
          var hrefs = [];
          $.each(menu[0].children, function (i, li) {
            hrefs.push(li.children[0].href);
          });
          self.closeDismissibleTabs(hrefs);
        } **else if ($(e.target).hasClass('close')) {
          // don't close on a mouse down

          return false;          
        }**

**Comment by tmcconechy** [comment] 2020-12-30 14:35
Descoping this for now due to age... This code spot is no longer present. So perhaps this works now. If not feel free to make a PR based on the current code.

**Closed by tmcconechy** 2020-12-30 14:35 UTC
Labels: [2], type: bug :bug:
