### ISSUE TITLE
Avatar issues after IDS Upgrades impacted all CQA tenants. 

### ISSUE THREAD

**Issue by kuldeepsingh1905** [infor-design/enterprise#8556] opened 2024-03-18 14:09 UTC
observed image-initials IDS class issues on some widgets in our tenants after latest IDS upgrade. The problem involves conversion of round to square around initials along with alignment issues after the IDS upgrade on our tenants. This issue persists across all workspaces and the same problems have been confirmed by other product teams as well. Please refer to the screenshots below reference.

**Version**
IDS version: 4.92.3

<img width="352" alt="image" src="https://github.com/infor-design/enterprise/assets/157625099/d091f537-ce7d-415f-91ea-bb92bb4cf20b">

<img width="345" alt="image" src="https://github.com/infor-design/enterprise/assets/157625099/9e384982-bfd7-480d-9330-6d046978df5c">

<img width="236" alt="image" src="https://github.com/infor-design/enterprise/assets/157625099/37fa5514-7cc9-4b29-91ed-e9c0263a0dfd">

<img width="235" alt="image" src="https://github.com/infor-design/enterprise/assets/157625099/488137fb-0ff4-43c4-9c3b-5d722fe4c38d">

**Platform**
 - impacted all the CQA tenants

**Comment by tmcconechy** [comment] 2024-03-18 15:09
This is a duplicate of https://github.com/infor-design/enterprise/issues/8539 this is already fixed and patched in [4.92.5](https://www.npmjs.com/package/ids-enterprise/v/4.92.5)

This is in Angular fix of [17.4.6](https://www.npmjs.com/package/ids-enterprise-ng/v/17.4.6)

For the fix we reverted the change that made them square instead of round. It looks like you have layout issues that we cannot be sure to fix. What i did was add `min/maxWidth/ min/maxHeight` on the avatar. This should fix it. But if in your css you do something weird to the layout of it you will have to fix that on your end. We dont have a way to reproduce and see whats happening with that. But it might work. So try it and check your css.

**Closed by tmcconechy** 2024-03-18 15:09 UTC
