### ISSUE TITLE
Tabs: Side form is not scrollable in iOS and has different display in iOS than in Android mobile view. 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3201] opened 2019-12-03 05:32 UTC
**Describe the bug**
Tabs: Side form is not scrollable in iOS and has different display in iOS than in Android mobile view. 

**To Reproduce**

1. Open a Mobile Device Both iOS and Android to see difference 
2. Go to http://master-enterprise.demo.design.infor.com/components/tabs/example-composite-form-on-side.html?theme=uplift&variant=light
3. Switch to Landscape 
Notice the difference of the form when displayed in iOS and Android

**Expected behavior**
Side form should be responsive and consistent in Mobile View. 

**Version**
4.24 

**Screenshots**
Android (Working as Expected)
![image](https://user-images.githubusercontent.com/45757016/70022683-00dbb100-15d0-11ea-8932-581daf74e132.png)

iOS Safari (Different form Android display)
![image](https://user-images.githubusercontent.com/45757016/70022717-19e46200-15d0-11ea-9252-19c50c736dd8.png)

iOS Chrome **(Unable to Scroll down to hide  the panel)**
![image](https://user-images.githubusercontent.com/45757016/70022753-3aacb780-15d0-11ea-956f-a8b147dd13a5.png)

**Platform**
All Platforms - Browser (Responsive View)
Mobile Devices iOS 

**Additional context**
N/a

**Comment by tmcconechy** [comment] 2019-12-03 14:15
Duplicate of #2931

**Closed by tmcconechy** 2019-12-03 14:15 UTC
