### ISSUE TITLE
Lookup: Datagrid show search result values selected by default

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise#4208] opened 2020-07-29 12:18 UTC
**Describe the bug**
lookup datagrid show search result values selected default.

**To Reproduce**

1. Go to ids-enterprise-ng-demo/lookup example 
2. Go to  "Products (Async Results) Multi Select" lookup
3. Click on browse button and select "2142201" record
4. Click on apply button
5. Again click on browse button and in popup it will show "2142201" selected
6. Go to Keyword search and search value for "Different Compressor" and press enter
7. In serach result it will show "Different Compressor" by default selected 
8. click on apply button
9. Now that value not get selected in lookup.

When user search any keyword it show results with default selected.

**Expected behavior**
It should not show search result selected default. 

**Version**

- ids-enterprise: [4.30.1, 4.31.0 dev]

**Screenshots**

**Platform**
 - Infor Application/Team Name: [Infor GRC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment] 2020-07-29 13:35
We may want to retest this after 4.31 was applied as a similar sounding issue was fixed.

**Comment by davidJayaraj** [comment] 2020-07-29 14:04
Hi Tim, would it be possible to patch this issue on 4.30 as we have already picked 4.30 for our current development sprint. 4.31 is planed to be GA on 4th Aug which is middle of our development sprint. Many of our customer are already asking a fix for this issue.  (https://github.com/infor-design/enterprise/issues/3601). Any help from you side is much apricated.  

Thank,
David Jayaraj

**Comment by tmcconechy** [comment] 2020-07-29 14:51
Having a quick look to see what if anything we can dof for you. This might be too complicated to patch with other features. So far i can see i cannot reproduce it in EP so this maybe just a problem with the example or NG

**Comment by tmcconechy** [comment] 2020-07-29 15:27
Ok, i was able to track this down. It doesnt require a fix but you will have to verify it works on your older version. I made an example exactly like the NG example mentioned at:

http://localhost:4000/components/lookup/test-paging-server-side-keyword-search.html

Steps For QA:
- open the picker and pick 214220
- reopen the picker a search on "1"
- it should not select that record

I also pushed a fix to master on NG so the example now works. the key to the fix is to use ID's to match the records

```
            [options]="{
              allowSelectAcrossPages: true,
              paging: true,
              columnIds: ['productId'],
              pagesize: 5,
              pagesizes: [3, 5, 10, 15]
            }"
```

I added the `columnIds: ['productId'],` option. We need this to be the keys in your table then it should work because this makes it match up on the id not position in the table.. I think this should work ok on 4.30 but not 100% sure about that.

4.31 will be in beta today.

**Closed** 2020-07-29 15:31 UTC
Labels: [3], type: bug :bug:

**Comment by davidJayaraj** [comment] 2020-07-30 04:56
Thanks Tim for your quick response. we will review based on your updates.

**Comment by jbrcna** [comment] 2020-07-30 08:59
**QA Passed**
v4.31.0-beta1
https://4310-beta1-enterprise.demo.design.infor.com/components/lookup/test-paging-server-side-keyword-search.html
![image](https://user-images.githubusercontent.com/56722184/88900262-be16c980-d281-11ea-823c-845adbb305c3.png)
