### ISSUE TITLE
DataGrid Date column doesn't keep its dateFormat when using in-range filter type

### ISSUE THREAD

**Issue by AsafMeirBarziv** [infor-design/enterprise#4864] opened 2021-02-21 05:47 UTC
I was using the dateFormat: 'yyyyMMdd' and the dates were correctly formatted unless the 'in-range' filter type was selected.

To Reproduce - use any other dateFormat other then the default.

In addition - the format does not return to be correct even switching back to other filer types.

**Comment by tmcconechy** [comment] 2021-02-22 14:27
Hi @AsafMeirBarziv this issue is unclear to me. When you created the issue we have a template you can fill in with the necessary information. https://github.com/infor-design/enterprise/issues/new/choose

In particular I'm not sure exactly what you did to reproduce this (specificaly how you set the locale). And whats happening / not working. Also important (as is all the information in the template) is what version your own. We had problems with formats without separators in the past and it is possible some bugs are fixed.

**Comment by tmcconechy** [comment] 2021-03-09 16:23
Closing this as i was not able to reproduce it due to lack of information

**Comment by AsafMeirBarziv** [comment] 2021-03-09 16:54
Please open and reproduce by using this column

    columns.push({id: 'Start Date', name: 'Start Date', field: 'Start Date', filterType: 'date', filterConditions: ['equals', 'does-not-equal', 'in-range', 'less-than', 'less-equals', 'greater-than', 'greater-equals'], formatter: Soho.Formatters.Date, dateFormat: 'yyyyMMdd'});

All U have to do is selecting the filter type to be 'in-range' and the date format yyyyMMdd will not be active anymore.

please let me know if you still can't reproduce this

**Comment by tmcconechy** [comment] 2021-03-09 17:14
ok, as a workaround please try and use a dateformat with separators like yyyy/MM/dd - im not sure when we will be able to fix this.

**Closed** 2021-09-13 14:20 UTC
Labels: type: bug :bug:, [5], team: m3

**Comment by janahintal** [comment] 2021-09-16 12:30
QA Passed. Working as expected in https://main-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
![image](https://user-images.githubusercontent.com/45757016/133607407-4c6b068d-9b64-4737-a6fd-7f778fe5b476.png)
![image](https://user-images.githubusercontent.com/45757016/133607509-01076dd3-35d4-46f7-bb8d-77fb17510b10.png)
