### ISSUE TITLE
placeholder class doesn't show text any light than normal text in uplift

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#2528] opened 2019-07-25 16:03 UTC
In Soho themes it all looks good

![code block placeholder text](https://user-images.githubusercontent.com/4737815/61889914-f4ca3f00-aecb-11e9-855b-a8dae9c4e6a4.jpg)

In uplift themes there doesn't seem to be any real difference.

![imgpsh_mobile_save](https://user-images.githubusercontent.com/4737815/61889861-d2382600-aecb-11e9-9260-ebe9f1577d08.jpg)

**Comment by tmcconechy** [comment] 2019-07-25 16:32
Duplicate of #2318

**Comment by tmcconechy** [comment] 2019-07-25 16:33
This was noticed and fixed on https://github.com/infor-design/enterprise/issues/2318 on PR https://github.com/infor-design/enterprise/pull/2516

I just merged it so give the latest a try to confirm. You can also test on master once it builds through.

**Comment by brianjuan** [comment] 2019-07-29 11:15
There is no difference in placeholder colors in the current version http://4200-beta1-enterprise.demo.design.infor.com/components/multiselect/example-placeholder.html?theme=uplift&variant=light&colors=0563C2 compared to 4.19 http://4190-enterprise.demo.design.infor.com/components/multiselect/example-placeholder.html?theme=uplift&variant=light&colors=0563C2
Is this expected?

**Comment by tmcconechy** [comment] 2019-07-29 12:43
@EdwardCoyle Can you take a look at this again? He's right the colors are the same still. I thought that i saw this fixed.

**Closed** 2019-07-31 17:24 UTC
Labels: [1], status: duplicate, team: landmark

**Comment by brianjuan** [comment] 2019-08-05 09:46
https://4200-rc0-enterprise.demo.design.infor.com/components/multiselect/example-placeholder.html?theme=uplift&variant=contrast&colors=0563C2
Tested acroll all browsers. Will move to Done now since the color of placeholder is different from color of the selected. I will just retest once https://github.com/infor-design/design-system/issues/393 is closed.
