### ISSUE TITLE
Hierarchy: Submenu is not displayed properly on iOS

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2362] opened 2019-06-11 10:25 UTC
**Describe the bug**
Hierarchy: Submenu is not displayed properly on iOS

**To Reproduce**
1. Open browsers in iOS
2. Go to http://4190-rc0-enterprise.demo.design.infor.com/components/hierarchy/example-context-menu-with-details.html
3. Click ... button in Kaylee Edwards to open the context menu
4. Click the Options item
5. See issue: Submenu is not displayed properly

**Expected behavior**
Submenu should be displayed properly on iOS browsers.

**Version**
- ids-enterprise: v4.12.0 - v4.19.0-rc0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/59264632-1c47ae00-8c76-11e9-8a23-72d2efbb6bc0.png)

**Platform**
 - iOS Safari
 - iOS Chrome

**Additional context**
No additional context.

**Comment by tmcconechy** [comment] 2019-06-11 12:46
Duplicate of https://github.com/infor-design/enterprise/issues/1928

**Closed by tmcconechy** 2019-06-11 12:46 UTC
Labels: status: duplicate
