### ISSUE TITLE
Dropdown: Arrow keys open the dropdown even when handled by a custom onKeyDown handler

### ISSUE THREAD

**Issue by jake-harrington** [infor-design/enterprise#1262] opened 2018-11-21 17:34 UTC
**Describe the bug**
We have hotkeys that are user customizable. Two hotkeys by default are shift + up/down arrow, it switches focus between rows of inputs in a table. Some users even change the hotkey to just up/down arrow with no modifier. In either circumstance the dropdown will open even though we handle the event with the onKeyDown option.
Here's an example where the up/down (also left/right to test the handler) will switch focus to the previous or next dropdowns.
[example-no-search-lsf.zip](https://github.com/infor-design/enterprise/files/2605180/example-no-search-lsf.zip)

**To Reproduce**
1. Go to attached file
2. Focus the first dropdown
3. Use up/down arrow keys
4. Observe the focus changes but the dropdown opens

**Expected behavior**
The dropdown should not open if the custom onKeyDown handler handles the key.

**Platform**
 - 4.11.x

**Additional context**

**Comment by tmcconechy** [comment] 2018-11-21 18:23
This is similar to 
https://github.com/infor-design/enterprise/issues/1239 if not a duplicate issue of that

**Comment by jake-harrington** [comment] 2018-11-27 17:19
@tmcconechy Is this going to be fixed anytime soon? We are otherwise might have to delay our release to wait for this one.

**Comment by clepore** [comment] 2018-11-27 20:44
Hey @jake-harrington , we code freeze the last full week of each month for QA, so we are already into that period for `v4.13.0`. We do have #1239 planned in our December sprint to be completed for the `v4.14.0` release (the end of December).

**Comment by tmcconechy** [comment] 2018-11-28 16:39
Closing this as a dup as we will fix it against https://github.com/infor-design/enterprise/issues/1239 so please watch that one.

**Closed by tmcconechy** 2018-11-28 16:39 UTC
Labels: [2], type: bug

**Comment by clepore** [comment] 2018-11-28 16:43
Duplicate of #1239
