### ISSUE TITLE
Datagrid: calendar icon is now visible in row height medium. However, in normal height, the timepicker field is too close to the grid both in uplift and soho theme.

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2784] opened 2019-09-12 04:11 UTC
**Describe the bug**
Datagrid: calendar icon is now visible in row height medium. However, in normal height, the timepicker field is too close to the grid both in uplift and soho theme.

**To Reproduce**
1. Go to http://4210-beta3-enterprise.demo.design.infor.com/components/datagrid/example-filter.html?theme=uplift&variant=dark&colors=0053B1

Notice that the Timepicker field is  too close to the grid. 

**Expected behavior**
The fields should be aligned.

Beta3 4.21

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/64753626-6e8aba80-d556-11e9-8c83-a6b3dfba35bc.png)

**Platform**
All Browser, OS and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment] 2019-09-13 13:28
Closing this issue as everything seems ok. So either we cannot reproduce or not important enough to fix

**Closed by tmcconechy** 2019-09-13 13:28 UTC
Labels: status: cant reproduce
