### ISSUE TITLE
Busy Indictor Component: Indicator not appearing correctly on Up Lift Dark Contrast

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#3726] opened 2020-04-07 20:43 UTC
**Describe the bug**

**To Reproduce**
1. Go to url: https://4270-rc1-enterprise.demo.design.infor.com/?theme=uplift&variant=dark
2. Scroll down to Busy Indicator and click on the "Submit" button
4. See error in the screen shot the word "Loading" is highlighted when it shouldn't

**Expected behavior**
The word "Loading" should not be high lighted

**Version**

- ids-enterprise: [ v4.27]

**Screenshots**
![bs_win10_Edge_80 0(2)](https://user-images.githubusercontent.com/39101346/78717623-e3f11a80-78ee-11ea-9de9-baf286f47a40.jpg)

**Platform**

 - OS Version: [e.g. Windows 10 8]
 - Browser Name [Edge]

**Additional context**
None

**Comment by tmcconechy** [comment] 2020-04-07 20:45
Looks like you somehow selected the text.

**Comment by tmcconechy** [comment] 2020-04-07 21:29
https://4260-rc0-enterprise.demo.design.infor.com/components/busyindicator/example-index.html?theme=uplift&variant=dark
- then click the submit
- then select “loading” text

I can only reproduce it that way. To me its valid that the text can be selected so will close this for now.

**Closed by tmcconechy** 2020-04-07 21:29 UTC
Labels: [2], priority: minor, type: bug :bug:
