### ISSUE TITLE
Modal: Content doesn't overflow on smaller screen resolution

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#7660] opened 2023-06-30 18:54 UTC
**Describe the bug**
Modal content doesn't overflow. This can be seen when sizing the browser viewport to a smaller resolution.

**To Reproduce**

1. Go to http://localhost:4000/components/modal/test-body-scroll.html
2. Make browser viewport smaller
3. See issue

**Expected behavior**
Modal content should overflow

**Version**

- ids-enterprise: 4.84.2

**Screenshots**
<img width="605" alt="image" src="https://github.com/infor-design/enterprise/assets/1056684/c6ede286-49d0-45b3-99af-198eb72cd0d1">

**Platform**
 - Windows
 - Chrome (latest)

**Additional context**

**Comment by tmcconechy** [comment] 2023-06-30 19:11
This does not seem to be reproducible on main. https://main-enterprise.demo.design.infor.com/components/modal/test-body-scroll.html

I think this was a recent fix. If we find which one we can add it to 4.84.x

**Comment by tmcconechy** [comment] 2023-06-30 20:00
Ok found this. Duplicate of https://github.com/infor-design/enterprise/pull/7620/files
Already fixed in 4.85.0 and will be patched in 4.84.3 with the others

**Closed by tmcconechy** 2023-06-30 20:00 UTC
Labels: type: bug :bug:, type: patch, type: regression bug  :leftwards_arrow_with_hook:, [2], team: landmark

**Comment by jbrcna** [comment] 2023-07-13 02:55
working as expected. moving this ticket to Done.
<img width="394" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/9a2d9705-03d0-4c49-8aef-889434f17905">
