### ISSUE TITLE
Tabs component does not take jquery object

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise#1843] opened 2019-03-25 16:42 UTC
**Describe the bug**
Previous version of sohoxi (4.9.0) it was okay to add a tab content which was of type jquery/angularjs object.
However in version 4.16.1 it isn't possible anymore.

**To Reproduce**
Pass a jquery object as a tab content.
**Expected behavior**
Should render the object into template
**Version**
4.16.1

**Comment by kels0** [comment] 2019-05-06 11:15
This issue is blocking several jira-tickets in App Builder Development.
https://jira.infor.com/browse/MUPS-2215
https://jira.infor.com/browse/MUPS-2107
And one issue regarding locales for date-pickers.

**Comment by tmcconechy** [comment] 2019-05-06 13:09
As a workaround could you pass in a non jQuery object? `$('tabs-id')[0]` do you have an example or code snippet of this?

**Comment by tmcconechy** [comment] 2019-05-09 17:46
Closing as was unable to reproduce. If you have any new info let us know

**Closed by tmcconechy** 2019-05-09 17:46 UTC
Labels: [2], for: up for grabs, priority: high, status: cant reproduce, type: regression bug  :leftwards_arrow_with_hook:
