### ISSUE TITLE
Card: The widget header has right side margin in the Uplift theme

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#2527] opened 2019-07-25 15:58 UTC
Sometimes we put custom links in the widget header and they are but up against the right side of the widget-header

![image](https://user-images.githubusercontent.com/4737815/61889498-21ca2200-aecb-11e9-9df0-53b67c0b59d4.png)

**Comment by tmcconechy** [comment] 2019-07-25 16:29
@pwpatton i think this is a bug due to the override on the css. I can see it on http://localhost:4000/components/cards/example-index.html?theme=uplift so i think we need to do it another way. Can you fill this out with the template though? https://github.com/infor-design/enterprise/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by davidcarlsonberg** [comment] 2019-08-12 12:16
I cannot reproduce this bug. Is there a markup example we could take advantage of to replicate the error?

**Comment by tmcconechy** [comment] 2019-08-22 18:20
Closing until further information can be provided as we could not reproduce.

**Closed by tmcconechy** 2019-08-22 18:20 UTC
Labels: [2], status: cant reproduce, team: landmark, type: bug :bug:
