### ISSUE TITLE
Icons: the 'amend' icon is incorrect when using the vibrant theme 

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#3613] opened 2020-03-13 19:31 UTC
Describe the bug
The amend icon is different when using the vibrant theme vs the subtle theme.  Believe the icon is correct in the subtle theme.

To Reproduce
1. Using the existing test-form-buttons.html example
2. Change the definition of a column, to use the icon 'amend'
3. Click on the more icon to change the theme between Subtle and Vibrant

Expected behavior
Amend icon would be the same regardless of the theme

Version
v4.27.0-dev

**Comment by claudenbach** [comment] 2020-03-13 19:32
![image](https://user-images.githubusercontent.com/39804038/76653765-5d3b5e80-6537-11ea-8b6d-0938aea396db.png)

**Comment by tmcconechy** [comment] 2020-03-13 19:34
Almost all the icons are different in each theme. That was part of the point of it. So i think that assumption is incorrect.

Is it really more the meaning is way different? I.E. one is like a ledger and one is an edit?

**Comment by nbcp** [comment] 2020-03-18 09:40
@tmcconechy I'm a bit confused too. It seems the icons' svg html files are built coming from ids-identity, however in the live demo from design.infor.com I'm seeing the icons correctly: https://design.infor.com/code/ids-enterprise/latest/demo/components/icons/example-index?theme=uplift&variant=light

**Comment by nbcp** [comment] 2020-03-18 10:39
I also have another icon with this issue, 'update-preview' ![image](https://user-images.githubusercontent.com/11013464/76952040-72edc100-6947-11ea-8a97-e7480342f4c6.png) that is showing like a refresh icon in uplift
![image](https://user-images.githubusercontent.com/11013464/76952120-9284e980-6947-11ea-96f6-171f1ed4d15a.png)

**Comment by tmcconechy** [comment] 2020-03-18 13:16
The design.infor.com site shows the uplift style of the icons. And the designers that made these made certain decisions. So i sort of agree that

update-preview -> looks identical to reload
amend -> looks identical to edit and lost its meaning.

@inforandy - Could you add this to the design list to check.

**Comment by nbcp** [comment] 2020-04-14 00:18
Hi @tmcconechy any update on this one?

**Comment by tmcconechy** [comment] 2020-04-14 14:28
@inforandy @lucacolumbu - Do we have any design resources available that can correct these icons? Thanks

**Comment by inforandy** [comment] 2020-04-14 17:17
@tmcconechy thanks tim, will have someone take a look

**Comment by elizabethhartley** [comment] 2020-04-15 14:00
@tmcconechy hey tim, these are the correct vibrant icons we intended to replace the subtle icons. when designing the uplift set we got rid of most object-specific shapes, such as the "amend" icon which was specific to a spreadsheet row, and replaced it with the more general action shape, in this case "edit". the same applies to update preview — instead of a context specific shape as seen in the subtle icons, we reduced down to the basic action, which was "update", or "refresh". if these icons do not serve their intended purpose in these contexts, maybe we can point to other icons within the uplift set.

**Comment by tmcconechy** [comment] 2020-04-15 14:21
I see - does that work @claudenbach @nbcp ? I guess my question would be what is the difference between amending and editing? Sounds like a different word for the same action?

**Comment by tmcconechy** [comment] 2020-04-29 17:58
Keep as Is / Change Rejected:
update-preview -> now less object specific so looks similar to reload
amend -> now less object specific so looks similar to edit

Already Fixed:
locked -> also the locked / unlock icon looks like a hand bag

**Comment by jamie-norman** [comment] 2020-04-29 19:34
If I understand this correctly, this seems arbitrary and incorrect. the Landmark implementation of "amend" is for a helper list. The generic "edit" icon doesn't not have the same meaning. This is a regression in my opinion. The icon change at the IDS level did not adequately consider how other products were using it currently and that decision's downstream impact.

**Comment by tmcconechy** [comment] 2020-04-29 19:51
So as i see it the current problems are with:

amend -
update preview -

Can you explain @jamie-norman what those do? It's probably arbitrary to change them to be the same as edit and reload. But i think maybe we could come up with some that capture the usage in a non object specific way (which was the just of the icn changes in uplift). This is my suggestion...

Can we restart with what those two do?

**Comment by tmcconechy** [comment] 2020-04-30 19:35
@jamie-norman could i get an quick explanation of those. We will make a design jira to try and fix it further to better match the case + the design change.

cc @inforandy

**Comment by jamie-norman** [comment] 2020-04-30 19:44
The "amend" icon was being used for a helper list, which pulls up a select list similar to the way the lookup/select list (search-list icon) works. Not totally sure about "update preview." 
Quick gif: https://recordit.co/hFytWvNGTp

**Comment by nbcp** [comment] 2020-05-03 23:46
Btw as for update-preview, it was meant to be used as "preview", can we also please change that name to just "preview" to avoid confusion to us all? The meaning is completely off with how it looks just like the refresh icon, why do we even need 3 different icon names for the same icon? refresh, refresh-current, update-preview all looks the same (https://design.infor.com/product/identity/icons).

I believe the preview icon should look similar the way it's done before in https://design.infor.com/code/ids-enterprise/4.26.0/demo/components/icons/example-index?theme=uplift&variant=light since it represents the action better.

see https://jira.lawson.com/browse/LMCLIENT-29584 for more context

**Comment by tmcconechy** [comment] 2020-05-04 13:31
Yeah i see we dont have a preview icon. I would think we would. We maybe have to add a preview icon so there is both. Then add a different amend icon (amend is adding to a ledger as you dont edit it you always add).

**Comment by elizabethhartley** [comment] 2020-05-04 13:38
@tmcconechy I've been using the `eye` icon for preview in recent designs.

if amending is adding to a ledger, should the icon be add?

we don't want to get back in the habit of being too prescriptive.

**Comment by jamie-norman** [comment] 2020-05-04 14:21
The specific case I'm referencing is for bringing up a helper list that allows the user to fill in a field with a value from a pre-defined set. So, "amend" isn't really literal. It's adding, but from a list, so I don't know if a simple "add" icon would suffice. I think what I've been asking for is that icons are not replaced or deprecated without understanding their use in other product teams

**Comment by tmcconechy** [comment] 2020-05-04 14:21
I'm pretty sure ledger is a common thing. So maybe an + onto a document or something? Dont think its just an add icon. But i think a new preview document (like preview for printing) whatever we want for that could work. Isnt that usually more like document with a magification glass on it?

**Comment by elizabethhartley** [comment] 2020-05-04 14:59
![add row](https://user-images.githubusercontent.com/47726073/80980180-54a82b80-8df6-11ea-961c-683eba5ec44c.png)
![add report](https://user-images.githubusercontent.com/47726073/80980181-54a82b80-8df6-11ea-9e77-6fc35ae0ab30.png)
![add document](https://user-images.githubusercontent.com/47726073/80980182-5540c200-8df6-11ea-978c-ae4bfeefe25e.png)
 @jamie-norman here are a few icons we have that might suffice — what do you think?

**Comment by aaron-usiskin** [comment] 2020-05-04 15:09
Good morning, thanks for all the input. We should set up some time to talk about this further, understand the ask, and see how we can move forward. @jamie-norman @elizabethhartley, I have some questions, we had an old "Amend' icon, why did we not convert it into the new style. 

I am new so having a meeting to discuss would be great. thanks A

**Comment by jamie-norman** [comment] 2020-05-04 15:32
![image](https://user-images.githubusercontent.com/44705854/80983721-7ef7ea00-8df2-11ea-89d5-42e5bf6ee5e7.png)

**Comment by jamie-norman** [comment] 2020-05-04 15:33
couple of quick ideas for adding to list. 

If you want to set up a call, that's fine with me. Should probably include Phillip Patton as well

**Comment by aaron-usiskin** [comment] 2020-05-04 15:35
@jamie-norman those look nice. I will set up a meeting to get me caught up and move this forward. Can you send me the file you created the icons in?

**Comment by jamie-norman** [comment] 2020-05-04 17:00
[helper-list.zip](https://github.com/infor-design/enterprise/files/4576032/helper-list.zip)

**Comment by aaron-usiskin** [comment] 2020-05-04 17:03
@jamie-norman THANKS

**Comment by aaron-usiskin** [comment] 2020-05-04 17:41
@jamie-norman figma file here √

**Comment by nbcp** [comment] 2020-05-12 06:33
Hi everyone, it's been a while is there any update on this one yet? Do we have a draft preview of the new proposed icons? I guess it's enough for me as long as they don't overlap with the meaning of other existing icons to avoid confusion.

**Comment by tmcconechy** [comment] 2020-05-22 13:05
I found an additional case where the icon has lost meaning. This is in the tree. We used to have a "#icon-tree-node" icon that looked like a base level of a UI tree. Now its just a circle that looks like a radio button that you can select. This is confusing.

Can we change this too?

Compare:
https://master-enterprise.demo.design.infor.com/components/tree/example-select-multiple.html?theme=uplift&variant=light&colors=0066D4

With
https://master-enterprise.demo.design.infor.com/components/tree/example-select-multiple.html

**Comment by elizabethhartley** [comment] 2020-05-27 14:20
![image](https://user-images.githubusercontent.com/47726073/83032269-9e55f180-a003-11ea-9524-1df1a2c5774c.png)

here are four options for amend, let me know what you think @aaron-usiskin

**Comment by elizabethhartley** [comment] 2020-05-27 14:21
<img width="478" alt="Screen Shot 2020-05-18 at 8 37 54 PM" src="https://user-images.githubusercontent.com/47726073/83032410-c9d8dc00-a003-11ea-8803-9cb0d01b463f.png">

here are four options for amend, let me know what you think @aaron-usiskin @jamie-norman

**Comment by elizabethhartley** [comment] 2020-05-27 14:22
<img width="907" alt="Screen Shot 2020-05-27 at 10 18 27 AM" src="https://user-images.githubusercontent.com/47726073/83032481-dfe69c80-a003-11ea-8270-5e0b20463f43.png">

here are four options for amend, let me know what you think @aaron-usiskin @jamie-norman

**Comment by jamie-norman** [comment] 2020-05-27 15:10
@elizabethhartley my preference is option 1, since this is used in the context of a list

**Comment by elizabethhartley** [comment] 2020-05-27 19:03
@jamie-norman great! we're merging this into the `ids-icons-standard.sketch` file in `design system/sketch/theme-uplift` now

**Comment by tmcconechy** [comment] 2020-05-27 19:05
@elizabethhartley are we fixing any other icons mentioned here?

- icon-tree-node (lost meaning)
- update-preview 
- amend (you mentioned)

**Comment by elizabethhartley** [comment] 2020-05-27 19:13
@tmcconechy those are different tickets in our jira board — we'll be dealing with them separately

**Comment by tmcconechy** [comment] 2020-05-28 14:01
I added https://github.com/infor-design/enterprise/issues/3978 to track the two other icon changes getting into EP code.

**Comment by lucacolumbu** [comment] 2020-05-28 14:14
A new Amend icon has been designed, and approved:

https://jira.infor.com/browse/HLPE-363

The icon has been merged into the design system here:
https://github.com/infor-design/design-system/pull/447

**Comment by tmcconechy** [comment] 2020-05-28 14:21
Added a PR for the changed icon (4.30). Closing this as this is done. Note again i made #3978 for the remaining icons.

PR: https://github.com/infor-design/enterprise/pull/3979/files

**Closed by tmcconechy** 2020-05-28 14:21 UTC
Labels: [2], for: design, team: landmark, type: bug :bug:
