### ISSUE TITLE
Datagrid: Reset to Default issue in affects the dropdown

### ISSUE THREAD

**Issue by vsatyamsetty** [infor-design/enterprise#7973] opened 2023-09-21 08:56 UTC
**Describe the bug**
In Datagrid, Apply **frozen columns** and **dropdown filters on columns**.
select the **personalize** columns and select few columns.
selecting the **Reset to Default** misses the data on all the dropdown **filters** on columns missing. All of the dropdown shows empty in the datagrid.

**To Reproduce**
1. Go to Datagrid, dropdown filters and frozen column to be applied on grid.
<img width="368" alt="image" src="https://github.com/infor-design/enterprise-ng/assets/134535184/31be4215-05ca-4453-b4df-b461509cbd56">

3. Click on personalize columns
4. Select few columns on personalize columns. close the personalize columns
5. Select Reset to default missing the data on filters on dropdown.
<img width="333" alt="image" src="https://github.com/infor-design/enterprise-ng/assets/134535184/05a9afad-8f65-4c11-a42e-faa875257e1f">

**Expected behavior**
The data and filters on dropdown should not remove the filters/data.
<img width="333" alt="image" src="https://github.com/infor-design/enterprise-ng/assets/134535184/19cb2589-d985-411b-bd8b-60e3916a65bb">

**Version**
- ids-enterprise-ng: 
- "ids-enterprise": "4.87.0",
    "ids-enterprise-typings": "16.7.0",

**Screenshots**
<img width="333" alt="image" src="https://github.com/infor-design/enterprise-ng/assets/134535184/19cb2589-d985-411b-bd8b-60e3916a65bb">

**Comment by tmcconechy** [comment] 2023-09-21 14:32
Cant reproduce this:

I added reset and personalization to this example but i cant reproduce https://main-enterprise.demo.design.infor.com/components/datagrid/example-filter.html (may take a bit to refelect)

The dropdowns really should have nothing to do with that functionality. So my guess its its something your doing. Can you either reproduce this on our examples, or make a change to the examples to show it? Or make a stackblitz.

**Comment by vsatyamsetty** [comment] 2023-09-22 10:55
In this example Dropdowns information/data are static in javascript. [https://main-enterprise.demo.design.infor.com/components/datagrid/example-filter.html](https://main-enterprise.demo.design.infor.com/components/datagrid/example-filter.html) 

Could you please use dropdown dynamic data with an API call in javascript.

I will provide the stackblitz in next comment/ other way to show the example.

**Comment by tmcconechy** [comment] 2023-09-22 13:56
Yes i think we will need the stackblitz with these details before we can look at this.

**Comment by tmcconechy** [comment] 2024-02-01 15:55
Closing this as unable to reproduce

**Closed by tmcconechy** 2024-02-01 15:55 UTC
Labels: type: bug :bug:, status: cant reproduce, [3]
