### ISSUE TITLE
Datagrid: issues adding a row when have frozen columns

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#6918] opened 2022-10-25 18:03 UTC
**Describe the bug**
Issues when adding a row to the top of the datagrid when also have frozen columns.  Unable to correctly add the values for the new row. Seems to be working correctly when frozen columns are not defined on the datagrid.

**To Reproduce**
1. Using the attached 'test-addrow-with-frozen-columns.html'
2. Click on 'Add Row'
3. Notice unable to enter a value for Product Name on the added row
4. Click on the lookup icon for Product Id on the added row
5. Notice the value for the lookup is being placed in the Order Date cell
6. Unable to correctly add the values for the new row

**Expected behavior**
Correctly add values to the updatable columns of an added row.

**Version**
- ids-enterprise: v4.68.0-dev

**Additional context**
Have a Landmark regression ticket attached to this issue.  Need to confirm when this started, but Landmark is seeing the issue in v4.67.2.

**Comment by claudenbach** [comment] 2022-10-25 18:10
[Git-6918.zip](https://github.com/infor-design/enterprise/files/9862820/Git-6918.zip)

**Comment by claudenbach** [comment] 2022-10-25 18:15
Maybe related to https://github.com/infor-design/enterprise/issues/6746.

**Comment by vonnyw** [comment] 2022-10-25 20:37
@tmcconechy please prioritize and will need a patch for IDS 4.67. Thanks!

**Comment by tmcconechy** [comment] 2022-10-25 20:43
@ericangeles can you guys add this to the sprint for next patch release (Nov 1 or 15th). And see if we can fix for this version?

**Comment by ericangeles** [comment] 2022-10-26 03:39
@tmcconechy sure.

**Comment by tjamesallen15** [comment] 2022-10-27 02:29
Same as https://github.com/infor-design/enterprise/issues/6730. I cant reproduce it anymore. I just made PR together with the test page attached in here.

PR: https://github.com/infor-design/enterprise/pull/6923

**Comment by tmcconechy** [comment] 2022-10-31 13:59
@tjamesallen15 i tested this on 4.67.x branch and still didnt see it. But you are closer to this issue. Did you try on 4.67.x as well?

**Comment by claudenbach** [comment] 2022-10-31 16:10
I've attached a new zip file.  Think the previous zip file didn't have the correct .html file contained in it.  Let me know if this new example doesn't show the issue.

[Git-6918-V2.zip](https://github.com/infor-design/enterprise/files/9902800/Git-6918-V2.zip)

**Comment by tmcconechy** [comment] 2022-10-31 16:43
Yes i can reproduce it with that example. Also it doesnt seem to be related to https://github.com/infor-design/enterprise/issues/6746 as i reverted that.

Can you prioritize this @tjamesallen15 ?

**Closed** 2022-11-03 13:40 UTC
Labels: type: patch, type: regression bug  :leftwards_arrow_with_hook:, [3], priority: high, team: landmark

**Comment by jbrcna** [comment] 2022-11-07 13:10
this is now working as expected.
https://main-enterprise.demo.design.infor.com/components/datagrid/test-addrow-with-frozen-columns
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/56722184/200318077-928e5b91-2277-4796-bba6-f284e2aa23e8.png">
