### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'email')  (onadd note option for my note taking app)

### ISSUE THREAD

**Issue by MariaBashir995** [infor-design/enterprise#6808] opened 2022-09-11 11:45 UTC
**here is my code and error is in line 10**
```
  import { StyleSheet, Text, View ,TouchableOpacity,Image,pressable, FlatList} from 'react-native'
import React,{useState,useEffect, useReducer} from 'react'
import ImgBtn from '../../components/imgBtn'
import { ADD_BTN_ICON,NOTE_ICON } from '../../../resources/drawables';
import AsyncStorage from '@react-native-async-storage/async-storage';
import FirebaseApp from '../../../API/firebase';

const Main = (props) => {

  const {email}=props.route.params
  const[data,getData]=useState([ ])


 useEffect(()=>{
   loadAllKeyFromAsyncStorage()
  },[])

  const loadAllKeyFromAsyncStorage = async()=>{
    let key=await AsyncStorage.getAllKeys()
   getData(key)
  }
  return (
    <View style={styles.container}>
      <View style={styles.profile}>

      </View>
      <FlatList
      data={data}
      numColumns={4}
      renderItem={({item})=>{
       return(
        <TouchableOpacity      
          onPress={()=>props.navigation.navigate('Createnote',{notetitle:item,email})}>
        
          <Image
          style={styles.imgnotes}
          source={NOTE_ICON}
         
          />
          <Text style={styles.titletext}>{item}</Text>
        </TouchableOpacity>
       )
      }}
      
      keyExtractor={(item)=>item}
      
      
      />
    <TouchableOpacity style={{alignItems:'flex-end'}}
    onPress={()=>props.navigation.navigate('Createnote',{notetitle:null,email})}>
    <Image
    style={styles.addbtn}
    source={ADD_BTN_ICON}
    />
    </TouchableOpacity>

      {/* <View>
      <Image style={styles.start}
        source={require('../../../assets/start.png')}/>
      </View> */}
        
       
      </View>
 
  )
}

const styles = StyleSheet.create({
    container:{
        flex:1,
        // alignItems:'center',
        // justifyContent:'center',   
    },
    addbtn:{
      height:40,
      width:40,
      margin:10,
    },
    profile:{
     height:40,
     width:40,
     backgroundColor:'red',
     borderRadius:20,

    },
    start:{
      height:360,
      width:360,
      marginTop:10,
      resizeMode:'contain',
      // justifyContent:'center',
      // alignItems:'center',
      alignSelf:'center'
      
    },
    imgnotes:{
      height:70,
      width:70,
      margin:10
    },
    titletext:{
      margin:1,
      fontWeight:'bold',
      textAlign:'center',
      justifyContent:'center',
      width:70,
      
      
    }
   
})

export default Main
```

**Comment by tmcconechy** [comment] 2022-09-12 13:19
@MariaLogic5 I really dont understand this issue. Is this in the right place as it mentions one note? Please try to clarify what your looking for here and if this is an IDS bug?

1. https://github.com/infor-design/enterprise/issues/new/choose use the bug template and fill in all sections
2. Provide an example so we can see the error https://stackblitz.com/edit/ids-quick-start-1411

**Comment by tmcconechy** [comment] 2022-11-22 14:50
Closing older issues we cant reproduce.

**Closed by tmcconechy** 2022-11-22 14:50 UTC
Labels: type: support :sos:, status: cant reproduce, [1], status: clarification
