### ISSUE TITLE
Datagrid: Editable field value when changed programatically: On enter edit mode, original value of editable field is reflected

### ISSUE THREAD

**Issue by marclouisgenedeguzman** [infor-design/enterprise#4324] opened 2020-09-01 10:42 UTC
**Describe the bug**
Datagrid editable field value when changed programatically:
On enter edit mode, original value of editable field is reflected.
One of our use case is we have context menu enabled for editable fields on datagrid.
A user can select:
 - Cut
 - Copy
 - Paste
 - Copy to All Rows
 - Delete

When we select Delete, the value of editable fields will be removed. But upon click, the original value of the editable field is reflected. This will be the case for those options that updates editable field values 

**To Reproduce**
Steps to reproduce the behavior (application implementation of soho-datagrid):
1. Run MMS001
2. right click on an editable field
3. select delete
4. value of editable field should be cleared

![datagrid_editable_field_implementation](https://user-images.githubusercontent.com/50192038/91840114-bed8bc00-ec82-11ea-89e0-fd8b1b5eb69f.gif)

**Expected behavior**
1. Run MMS001
2. right click on an editable field
3. select delete
4. value of editable field should be cleared (expected behavior is met)
5. **when we click on the editable field, the original value is reflected**

**Version**
- ids-enterprise-ng 7.2.4

**Screenshots**

**Platform**
 - Infor Application/Team Name: User Productivity Team
 - Device: N/A
 - OS Version: Windows 10
 - Browser Name: Google Chrome
 - Browser Version: Version 85.0.4183.83 (Official Build) (64-bit)

**Additional context**
Updating all rows editable field programatically, when we click any editable field, the original value is reflected

![datagrid_editable_field_implementation2](https://user-images.githubusercontent.com/50192038/91840126-c4ce9d00-ec82-11ea-9a46-7243a33cb247.gif)

**Comment by marclouisgenedeguzman** [comment] 2020-09-17 10:08
Hi Tim, 
1. this is from DEVAPP, 
2. I cannot recreate the issue on ids samples, need peer test with soho teams @lucacolumbu 
3. Our team have some styling implementation but the component we are using is soho-datagrid
4. Cannot replicate on the given link, there's some coding to do to update the editable cells programmatically w/o the user clicking/activating the editable cell

**Comment by tmcconechy** [comment] 2020-09-17 13:16
OK, let me know when you have info on how to reproduce and we can take a look. IN the video it doesnt look like soho datagrid is what i was wondering?

**Comment by lucacolumbu** [comment] 2020-09-30 14:03
@marclouisgenedeguzman can you email us access to an environment where we can replicate this?

**Comment by tmcconechy** [comment] 2020-10-14 16:51
@marclouisgenedeguzman one question is why does the grid look so different with editors / inputs in side it? Is it really soho-datagrid? Also wondering if it is this issue https://github.com/infor-design/enterprise/issues/4028 ?

**Comment by marclouisgenedeguzman** [comment] 2020-10-15 03:50
@tmcconechy, yes this is soho-datagrid, we just made some css styles to make the editable cell look like an input field since that is one of the existing behavior from our classic application

**Comment by tmcconechy** [comment] 2020-10-15 13:58
OK, understand now a bit. Maybe we should explore the use case of why you need that? Is it this https://github.com/infor-design/enterprise/issues/3077 if so perhaps we need to come up with some treatment that will prevent the need for workarounds that could break in the future and solve an additional use case for everyone.

Also suspecting this issue is perhaps because of the workaround.

**Comment by marclouisgenedeguzman** [comment] 2020-11-11 11:45
Hi, I was able to recreate the issue on the samples:
I just added the update quantity button and did some modifications so that the input field would show on the row.
Clicking the Update Quantity button will trigger the method that will change the editable values.
One observation is that when an editable cell is blank/null, the value that was set programmatically was retained.

[datagrid-editors.zip](https://github.com/infor-design/enterprise/files/5523771/datagrid-editors.zip)

Below is the recording for your reference:
![editable cell issue](https://user-images.githubusercontent.com/50192038/98807876-4480a100-2456-11eb-9b03-d41c8cab6262.gif)

**Comment by tmcconechy** [comment] 2020-11-11 14:48
Wondering - have you given any thought to not putting the input on the row? If it is causing the issue? 
We have to decide if we should support this feature and previously we have not as it clutters the grid up with a lot of inputs.

**Comment by marclouisgenedeguzman** [comment] 2020-11-12 03:26
the input on the row is one of the features from our classic UI, existing users need this feature, so it should stay that way. 
There are some use cases as well that rows have multiple input fields.

**Comment by tmcconechy** [comment] 2020-12-04 15:40
@marclouisgenedeguzman thanks that example really helped. I was able to see what the problem is. The issue is in the update quantity button you made your only setting the value in the field and in the underlying dataset so there is a mismatch.

I changed the `updateQuantity` function to this to make it work... Calling updateRow with the new data.

```
  updateQuantity() {
    // Get all available row Nodes
    const datagridElement: HTMLElement = this.elemRef.nativeElement;
    const datagridRows = datagridElement.querySelectorAll('.datagrid-row');

    const val = '20';

    datagridRows.forEach((row: HTMLElement | any) => {
      const rowIndex = row.dataset?.index;
      const rowCell = `datagrid-inline-input-${rowIndex}-5`;
      const rowCellInput = row.querySelector(`#${rowCell}`) as HTMLInputElement;
      if (rowCellInput) {
        rowCellInput.value = val;
      }
      (this.sohoDataGridComponent as any).dataset[rowIndex].quantity = val;
      (this.sohoDataGridComponent as any).updateRow(rowIndex, (this.sohoDataGridComponent as any).dataset[rowIndex]);
    });
  }
```

This might work in other ways but you can test that. You might not need to set the value in the input at all, you can just call updateRow. Or you can try to just set the value in the dataset AND the input. Also to make this work on master i had to change the example to make the script "strict" so i attached a zip with the example that i updated to work....

Here is the working example:
[updated-example.zip](https://github.com/infor-design/enterprise/files/5643668/updated-example.zip)

I'm a little concerned about any additional problems with overriding the editing behavior with inputs that stand out? Do you have any flexibility to do it the way the design suggests with it flush in the cell? In addition to maybe causing other bugs or feature bugs if we change something, It's also inconsistent with how other apps look.

Or perhaps we have to make this a real feature? The only issue with that is it will be inconsistent how the applications look / and when to use this and when not to. Let's say if there are additional issues we can consider these options further.

**Closed by tmcconechy** 2020-12-04 15:40 UTC
Labels: [8], team: m3, type: bug :bug:
