### ISSUE TITLE
Datagrid: grid display issues after performing hideColumn()

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#1802] opened 2019-03-15 18:45 UTC
Describe the bug
A datagrid contained within a modal dialog has several display issues when several columns are hidden via hideColumn().

To Reproduce
I don't have a good example that illustrates exactly the issue being experienced in Landmark. If this isn't enough info to duplicate the issue we may need a webex meeting.  

1. Using the attached example-modal-dialog.html
2. Click on the 'Add Context' button to open a datagrid within a modal dialog
3. Several of the columns (Landmark example is 10 columns) are hidden via hideColumn() once data is retrieved (in Landmark's case we retrieve data from server) 
4. Modal window is to larger, a horizontal scrollbar is display, the column header for the last column doesn't span across the grid cell 

Expected behavior
Modal dialog window would be sized correctly, horizontal scrollbar is not displayed, column header span across the entir

**Comment by claudenbach** [comment] 2019-03-15 18:50
[Enterprise-1802.zip](https://github.com/infor-design/enterprise/files/2972484/Enterprise-1802.zip)

**Comment by claudenbach** [comment] 2019-03-15 18:52
![image](https://user-images.githubusercontent.com/39804038/54455290-71ccf700-4729-11e9-9ed6-329be4db6d6d.png)

This is what Landmark is experiencing.

**Comment by davidcarlsonberg** [comment] 2019-03-18 14:35
I believe this is resolved alongside the solution for #1764. Either way I can't reproduce.
![example](https://user-images.githubusercontent.com/7952168/54537811-8b5c8180-4969-11e9-95bb-f0d615472736.gif)

**Comment by tmcconechy** [comment] 2019-03-18 14:41
I am seeing the issue part about the modal being too big. This can be fixed by setting a maxWidth on the modal. But could be addressed. Im not seeing the issue about the columns not aligning. But i think this is a good test case to include (lots of columns, datagrid on a modal)

**Comment by tmcconechy** [comment] 2019-03-18 14:44
```
    <div id="modal-content" style="display: none; max-width: 800px">
      <div id="datagrid">
      </div>
    </div>
```

Does improve the behavior

**Closed** 2019-03-19 14:19 UTC
Labels: [3], for: up for grabs, type: bug :bug:

**Comment by janahintal** [comment] 2019-03-20 10:40
QA Passed. Moving to Done. 
Tested in: https://4170-beta0-enterprise.demo.design.infor.com/components/datagrid/example-modal-datagrid across all OS browsers and devices.

**Comment by claudenbach** [comment] 2019-04-09 20:40
Did this also fix the issue were the column header and data cells do not stay aligned when the horizontal scrollbar is used?

Play the Enterprise-1802.gif (it's contained within the attached Enterprise-1802.zip file) and you'll see the alignment issue.
