### ISSUE TITLE
Line graphs when does not have data crashes 

### ISSUE THREAD

**Issue by tsantosjr** [infor-design/enterprise#4057] opened 2020-06-18 15:50 UTC
**Describe the bug**
Line graph widgets are not working as expected when there is no data to be displayed
* X-axis is loading from left to right
* Other widgets are being affected
* Options such as Configure and About are not working

**To Reproduce**
1. At the minimum, don't do any events that would be audited (e.g. Adding a user)
2. Go to the Homepages and then add line graph widgets such as the Audited Events by Severity.
3. Also, add other widgets for the checking of the affected implementations

**Expected behavior**
Each of the widget's functionality should work as expected regardless if the line graph does have data to display or not.

**Screenshots**
![multiple widgets](https://user-images.githubusercontent.com/67105861/85043059-8581cb80-b1be-11ea-9dc5-fbce25d29361.gif)
![widgets](https://user-images.githubusercontent.com/67105861/85043068-874b8f00-b1be-11ea-9b7d-1e3f022e78b4.gif)

**Platform**
 - Infor Application/Team Name: Infor OS 2020-06
 - OS Version: Windows 10
 - Browser Name: Google Chrome

**Comment by tmcconechy** [comment] 2020-06-18 16:02
This really seems like an application issue. Should this be raised with the team that wrote the widgets?

Otherwise can you make a reduced test case for this issue? As such i don't see any way to run and "fix" this issue? The only thing we can do here is fix any issues we see on the component:

https://master-enterprise.demo.design.infor.com/components/line

**Comment by tsantosjr** [comment] 2020-06-18 16:21
I have also checked with the widget PIC.
However, I have just encountered this issue upon the 2020-06 Infor OS upgrade.

**Comment by tmcconechy** [comment] 2020-06-18 16:52
I do not know about this issue as it seems application specific. If you can reproduce it in the component please provide a way to do so such as a [reduced test case](https://css-tricks.com/reduced-test-cases/)

One thing i can say is in the component if the data is empty it could look like this and should do so automatically.

https://master-enterprise.demo.design.infor.com/components/line/test-empty.html

Our component seems to work fine so must be something in the way the app is providing this info

**Comment by tmcconechy** [comment] 2020-07-17 19:51
Closing as we cannot reproduce

**Closed by tmcconechy** 2020-07-17 19:51 UTC
Labels: [∞], status: cant reproduce, type: bug :bug:
