### ISSUE TITLE
DataGrid: Frozen column header are mismatching/order incorrect, while reselecting the personalize columns

### ISSUE THREAD

**Issue by vsatyamsetty** [infor-design/enterprise#7541] opened 2023-05-24 16:42 UTC
**Describe the bug**
Frozen Columns are mismatching when reselecting the personalize columns in datagrid

**To Reproduce**
Could be replicated here https://main-enterprise.demo.design.infor.com/components/datagrid/example-frozen-columns.html
Select the frozen columns from datagrid.
Initial datagrid when selecting personalize columns.
<img width="754" alt="image" src="https://github.com/infor-design/enterprise/assets/134535184/0e1a36a1-ca1b-4592-ae53-deca7696f81a">

Now deselect Activity column and deselect the Quantity column.
Now again select the Activity column and select the Quantity column.

The result shown as: 
<img width="727" alt="image" src="https://github.com/infor-design/enterprise/assets/134535184/2a07c319-506c-4c63-9014-0804a98e6a1e">

The Frozen column headers are overriding the personalize columns header.

**Expected behavior**
The headers should not move from personalize columns.

**Version**

**Comment by tmcconechy** [comment] 2023-05-24 17:08
Duplicate of https://github.com/infor-design/enterprise/issues/7428

**Comment by vsatyamsetty** [comment] 2023-05-25 06:57
But this still resembles in this url.
https://main-enterprise.demo.design.infor.com/components/datagrid/example-frozen-columns.html
Can you please check and confirm?

**Closed** 2023-05-25 13:16 UTC
Labels: type: bug :bug:, [2], status: duplicate

**Comment by tmcconechy** [comment] 2023-05-25 13:49
Following those steps now:

https://main-enterprise.demo.design.infor.com/components/datagrid/example-frozen-columns.html
- open personalization in ..
- deselect activity and quanity
- open again and select those 2 

Back in the right place. Perhaps it was not updated right away... on the link
