### ISSUE TITLE
Scrollbar appears in the search field when browser is resized

### ISSUE THREAD

**Issue by inforrpunay** [infor-design/enterprise#6772] opened 2022-08-24 02:42 UTC
**Describe the bug**
Scrollbar appears in the search field when it collapsed when browser is resized.

**To Reproduce**

1. Go to 'https://design.infor.com/code/ids-enterprise/4.64.0/demo/components/header/example-flex-toolbar.html'
2. Resize the browser window until the search field collapsed
3. Observe that a scrollbar is added in the collapsed search field

**Expected behavior**
No scrollbar is visible in the collapsed search field

**Version**

- ids-enterprise: v4.64.0

**Screenshots**
![image](https://user-images.githubusercontent.com/55830499/186307257-f0356e09-b68a-4814-aa53-441be0281680.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 104.0.5112.82 (Official Build) (64-bit)

**Comment by tmcconechy** [comment] 2022-08-24 13:12
This is a duplicate of https://github.com/infor-design/enterprise/issues/6705 and its been patched in [4.64.6](https://www.npmjs.com/package/ids-enterprise/v/4.64.6) add fixed in the latest version

**Closed by tmcconechy** 2022-08-24 13:12 UTC
Labels: type: bug :bug:, [2], status: duplicate
