### ISSUE TITLE
Cirlce pager: more actions is not available in iOS mobile

### ISSUE THREAD

**Issue by johnbarcena** [infor-design/enterprise#2935] opened 2019-10-09 09:04 UTC
**Describe the bug**
more actions is not available

**To Reproduce**
1. Go to 'http://4220-beta0-enterprise.demo.design.infor.com/components/pager/example-circlepager.html'
2. Verify 'more actions'

**Expected behavior**
more actions should be available

**Version**
4.22 Beta

**Screenshots**
![image](https://user-images.githubusercontent.com/52902639/66467210-a6821080-eab6-11e9-858f-4ad2656425e0.png)

**Platform**
iPhone XS 12

**Additional context**

**Comment by tmcconechy** [comment] 2019-10-09 13:10
Duplicate of #2800

**Closed by tmcconechy** 2019-10-09 13:10 UTC
Labels: [1], status: duplicate, type: bug :bug:

**Comment by johnbarcena** [comment] 2019-10-16 08:41
Conditional Pass -  menus' are not working and the color sub menu is not available.

**Comment by johnbarcena** [comment] 2019-10-16 08:41
see ticket https://github.com/infor-design/enterprise/issues/2986
