### ISSUE TITLE
Contextual Action Panel: Modal Text Title Overflow in iOS

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3585] opened 2020-03-06 09:38 UTC
**Describe the bug**
header text title overflows when vibrant theme is used in iOS

**To Reproduce**
1. Open iOS Mobile
2. Go To https://master-enterprise.demo.design.infor.com/components/contextualactionpanel/example-index.html?theme=uplift&variant=light
3. Open CAP by clicking the button
4. See error, Ensure that the theme is vibrant

**Expected behavior**
the header text should fit in the modal

**Version**
4.27.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/76071408-22827500-5fd1-11ea-86e8-bd9d73923b73.png)

**Platform**
mobile iOS 

**Additional context**

**Comment by tmcconechy** [comment] 2020-03-06 14:34
Duplicate of #3586

**Comment by tmcconechy** [comment] 2020-03-06 14:34
Consolidated this with the other issue

**Closed by tmcconechy** 2020-03-06 14:34 UTC
