### ISSUE TITLE
Colorpicker: Text and dropdown icon are hidden in small modal/container

### ISSUE THREAD

**Issue by NicholTamayo** [infor-design/enterprise#4930] opened 2021-03-10 03:04 UTC
**Describe the bug**
Observed that colorpicker's text and dropdown icon became hidden when the modal/container width became smaller, it is also not possible to open the colorpicker menu to select color.

![Colorpicker dropdown icon is missing when scrollbar is display in the dialog](https://user-images.githubusercontent.com/79066908/110566746-6b907a80-818b-11eb-86db-9c1cae18e775.gif)

**To Reproduce**
1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/colorpicker/example-sizes'
2. Resize the browser to the smallest width.
3. Zoom in few times. (browser zoom)

**Expected behavior**
The colorpicker retains the text and dropdown icon.

**Version**
- ids-enterprise: 4.37.0

**Screenshots**
![image](https://user-images.githubusercontent.com/79066908/110567297-3a647a00-818c-11eb-867a-71b854255387.png)

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version: Window 10, Big Sur
 - Browser Name: Chrome, Safari
 - Browser Version: Chrome/Version 88.0.4324.190 (Official Build) (64-bit), Safari/Version 14.0.3 (16610.4.3.1.4)

**Comment by tmcconechy** [comment] 2021-03-25 19:12
I think the solution here is probably to make the colorpicker size that is "full width" work better so that it doesnt expand out of the container

**Comment by rob2d** [comment] 2021-03-25 20:55
checking into it

**Comment by rob2d** [comment] 2021-03-25 22:59
I can't test that specific page locally, but it should be good. There are some responsiveness improvements in #5005 which should allow the user to always hit the trigger/expand arrow regardless of the size, and text should flow more naturally when things get squashed.

![image](https://user-images.githubusercontent.com/1799905/112553912-c0431080-8d9b-11eb-8711-f116277df25d.png)

Sidenote: something that could feel better UX-wise is if a user can click the entire color picker input since the color picker resembles a dropdown, yet the user has to click specifically on the down-arrow (so leads to a little bit of pixel-hunting). Didn't address this idea since not familiar enough with the code to do this efficiently yet, but seems to be a matter of adding the same callbacks as the color menu expand. Not sure on priority but perhaps another issue could be opened as an enhancement for that?

**Comment by tmcconechy** [comment] 2021-03-26 12:49
Looks good - I think regarding your comments on that you need to click the arrow. This is because you can also directly enter the text in the field. But you can use down arrow to open like a dropdown.

Perhaps we could make the swatch clickable as well? But thats probably a bit out of scope, but feel free.

**Comment by rob2d** [comment] 2021-03-26 12:53
Oh, I see! Did not realize this functionality there. In terms of the
swatch, I'll try to do that.

**Comment by rob2d** [comment] 2021-03-26 13:19
@tmcconechy I wasn't able to reproduce the functionality with typing directly into the text field. Is this possibly a regression, or maybe a future-facing feature? See:
https://master-enterprise.demo.design.infor.com/components/colorpicker/example-sizes.html

**Comment by tmcconechy** [comment] 2021-03-26 13:30
its an option https://github.com/infor-design/enterprise/blob/master/src/components/colorpicker/colorpicker.js#L19 so probably turned off on that example

**Comment by rob2d** [comment] 2021-03-26 13:40
@tmcconechy oh I see! should have browsed the examples but had a bit of tunnel vision once focused on the original issue. Thanks for pointing that out.

**Closed** 2021-03-31 19:33 UTC
Labels: [2], team: homepages, type: bug :bug:

**Comment by jbrcna** [comment] 2021-04-05 07:53
this is working as expected. v4.50.0-beta2
https://4500-beta2-enterprise.demo.design.infor.com/components/colorpicker/example-sizes.html#maincontent
![image](https://user-images.githubusercontent.com/56722184/113545983-bf24a580-961d-11eb-95af-9606ed8e68c9.png)
