### ISSUE TITLE
Datagrid Mixed selection popupmenu pager took so long to update in Win10 IE 11

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2558] opened 2019-07-30 10:17 UTC
**Describe the bug**
Datagrid Mixed selection popupmenu pager took so long to update in Win10 IE 11

**To Reproduce**
1. Go to https://4200-beta1-enterprise.demo.design.infor.com/components/datagrid/example-mixed-selection-popupmenu.html
2. In my Assets datagrid. Click next page
3. Noticed that it took so long to update

**Expected behavior**
Should not take too long to update to next page

**Version**
Beta 4.20 

**Screenshots**
NA

**Platform**
OS: Windows 10
Browser: IE11

**Additional context**
NA

**Comment by tmcconechy** [comment] 2019-07-30 13:54
Duplicate of #2560

**Closed by tmcconechy** 2019-07-30 13:54 UTC
