### ISSUE TITLE
Pager: stand alone spacing of items

### ISSUE THREAD

**Issue by johnbarcena** [infor-design/enterprise#2939] opened 2019-10-09 11:20 UTC
**Describe the bug**
Pager: example-standalone spacing in between items

**To Reproduce**
1. Go to 'http://4220-beta0-enterprise.demo.design.infor.com/components/pager/example-standalone.html'
2. Change theme to Vibrant/Uplift
3. See error

**Expected behavior**
spacing should be the same as of with Subtle/Soho
![image](https://user-images.githubusercontent.com/52902639/66476515-5f048000-eac8-11e9-8572-d96b759916a2.png)

**Version**
4.22 Beta

**Screenshots**
**Actual**
![image](https://user-images.githubusercontent.com/52902639/66476441-2fee0e80-eac8-11e9-9aca-875b24579e36.png)

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment] 2019-10-09 13:01
Duplicate of #2914

**Comment by tmcconechy** [comment] 2019-10-09 13:01
This is fixed on #2914 and should be fixed in the RC build. WIll move to test in RC to confirm.

**Closed by tmcconechy** 2019-10-09 13:01 UTC
Labels: [2], type: bug :bug:

**Comment by johnbarcena** [comment] 2019-10-11 06:37
Passed QA Across All browsers. RC Build http://4220-rc0-enterprise.demo.design.infor.com/components/pager/example-standalone.html?theme=uplift&variant=light&colors=0563C2
