### ISSUE TITLE
input field font size seems to be not correct for small screen, e.g phones

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise#2009] opened 2019-04-25 07:17 UTC
**Describe the bug**
In `_input.scss`, font-size is set to 1.4rem aka 14px accordingly to root font-size. This causes the issue on small screens like phones that when users focus on an input field, the device will auto zoom in.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/input by phone
2. Tap on input field
3. Observe that browser automatically zooms in

**Expected behavior**
`font-size` for input field should be 16px for small screen so the device won't automatically zoom in, this brings better user experiences.

**Version**

- ids-enterprise: 4.17.1

**Screenshots**
**N.A.**

**Platform**
 - Device: iPhone 8
 - OS Version: iOS 12.2
 - Browser Name: Chrome mobile
 - Browser Version: 73.0.3683.68

**Additional context**
Reference from [StackOverflow](https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone)
Besides, I think we can learn from https://medium.com/ or https://www.airbnb.com/, the typography there looks really good.

**Comment by tmcconechy** [comment] 2019-04-25 12:13
We are working on a new theme called uplift, the font size is already 1.6 there http://master-enterprise.demo.design.infor.com/components/input/example-index.html?theme=uplift however this font is not entirely complete as we have to fix some line up issues but expect to do that in the next (few) releases.

So closing as by design.

**Closed by tmcconechy** 2019-04-25 12:13 UTC
Labels: status: wont fix :no_entry_sign:
