### ISSUE TITLE
DatePicker configured with show time and use current time displays incorrectly on subsequent selections

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#1184] opened 2018-11-07 20:48 UTC
**Describe the bug**
When the DatePicker is configured to show time and to use current time, the DatePicker will display an incorrect time on subsequent selections of the Today button.

**To Reproduce**
1. Using the attached example-timeformat.html
2. Click on the date picker icon on the 'Date-Time Picker in Locale (Time to Current)' field
3. Click on the Today button
4. The current time will display
5. Repeat steps 2 and 3
6. The current time will display with the minutes set to zero
7. Click on the date picker icon on the 'Date-Time Picker 24 Hour in Locale (Time to Current)' field
8. Click on the Today button
9. The current time will display with hours, minutes and seconds
10. Repeat steps 7 and 8
6. The current time will display with the minutes and seconds set to zero

**Expected behavior**
Expect the time portion to correctly display minutes and/or seconds in the current time on a subsequent selection of the Today button.

**Screenshots**
![datepicker using current time](https://user-images.githubusercontent.com/20212079/48159755-b63c1800-e29b-11e8-8fe3-876cdfa33da4.gif)

**Additional context**
Updated example-timeformat.html to add a DatePicker using 24 hour time
[example-timeformat.zip](https://github.com/infor-design/enterprise/files/2559097/example-timeformat.zip)

**Comment by tmcconechy** [comment] 2018-11-07 20:54
@tjamesallen15 Can you pick this one up. Its pretty close to https://github.com/infor-design/enterprise/pull/1175 but i can reproduce it but 

http://master-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html
- go to Time to Current and pick today from the picker
- do it again .. now its the wrong time

**Comment by tmcconechy** [comment] 2018-11-07 21:08
Actually on further review your fix does solve this. Its working fine on master the builds have issues.
Moving to QA to confirm

**Closed by tmcconechy** 2018-11-07 21:08 UTC
Labels: [2], type: bug

**Comment by CindyMercadoReyes** [comment] 2018-11-12 20:21
Moving this ticket to the QA failed bucket due to "Date -Time Picker in Locale(Time to Current) not working correctly for iPhone X and Android Galaxy S9. This test was conducted at 3PM EST and for both iPhone and Galaxy two different time date appear. Please see screen shot attached both. 

![bs_realdroid_mobile_samsung galaxy s9 plus-8 0-1440x2960](https://user-images.githubusercontent.com/39101346/48373040-938c7380-e68e-11e8-938a-7ce36755f966.jpg)
![bs_realios_mobile_iphone x-11 0 3](https://user-images.githubusercontent.com/39101346/48373041-938c7380-e68e-11e8-8149-5a7d0a44f159.jpg)

**Comment by tmcconechy** [comment] 2018-11-13 14:50
@CindyMercadoReyes Im not seeing anything wrong here. When i use the bottom picker it shows me the current time as expected. (IOS X)

**Comment by CindyMercadoReyes** [comment] 2018-11-13 15:15
I retested this issue on my actual device and it's working as expected. The issue is with Browser Stack.  Moving this ticket to the "Done" bucket.
