### ISSUE TITLE
Lookup: Multiselect with search is not working properly

### ISSUE THREAD

**Issue by kvchaudhari** [infor-design/enterprise#2536] opened 2019-07-29 07:28 UTC
**Describe the bug**
For multi select lookup, while search and select record, old selected values got replaced with the new selected values.

**To Reproduce**
1.On browse popup select value 1
2.now again on browse popup search for any value and select it
 >> here value 1 gets replaced with latest selection

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.15]

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment] 2019-07-29 12:55
@kvchaudhari Either this issue is fixed now on 4.19 or later or I'm unclear how to reproduce. Tried the following:
- go to example http://latest-enterprise.demo.design.infor.com/components/lookup/example-multiselect.html
- open the lookup
- select the first row 2142201 and hit apply (2142201 is in the field)
- reopen the list (2142201 is still selected)
- search for "202" in the search box
- select 2241202 and hit apply
- 2142201,2241202 are both in the field as expected

Can you clarify your steps or confirm its working on the 4.19 version?

**Comment by kvchaudhari** [comment] 2019-08-09 07:30
Hi @tmcconechy ,

The example above is client side implementation. In our case we have implemented server side.
Please find the attached video for steps in SOHO 4.19.3 version.

![Steps](https://user-images.githubusercontent.com/24225832/62761887-74980200-baa5-11e9-82de-61550e887a70.gif)

**Comment by tmcconechy** [comment] 2019-08-09 13:54
Hi @kvchaudhari 
Watching the video it looks correct to me? Im not sure what you are getting at on the video or what that is showing?

Can you reproduce the issue on any samples http://latest-enterprise.demo.design.infor.com/components/lookup ?

Or please upload a reduced test case with clear steps on how to reproduce. I tried to make an example of client side paging with filtering but i was not able to reproduce the issue. Here is a starting point for the sample for you for a reduced test case.

```html
<div class="row">
  <div class="twelve columns">

    <div class="field">
      <label for="paging" class="label">Paging</label>
      <input id="paging" data-init="false" class="lookup" name="paging" type="text">
    </div>

  </div>
</div>

<script>

      var columns = [];

      //Define Columns for the Grid.
      columns.push({ id: 'selectionCheckbox', sortable: false, resizable: false, width: 50, formatter: Formatters.SelectionCheckbox, align: 'center'});
      columns.push({ id: 'productId', name: 'Product Id', field: 'productId', filterType: 'integer'});
      columns.push({ id: 'productName', name: 'Product Name', sortable: false, field: 'productName', formatter: Formatters.Hyperlink, filterType: 'text'});
      columns.push({ id: 'activity', hidden: true, name: 'Activity', field: 'activity', filterType: 'text'});
      columns.push({ id: 'quantity', name: 'Quantity', field: 'quantity', filterType: 'integer', filterType: 'integer'});
      columns.push({ id: 'price', name: 'Price', field: 'price', formatter: Formatters.Decimal, filterType: 'decimal'});

      //Get some data via ajax
      var url = '{{basepath}}api/compressors?pageNum=1&pageSize=1000';
      $.getJSON(url, function(data) {
        //Init the Lookup with that data and paging options
        $('#paging').lookup({
            field: 'productId',
            options: {
              columns: columns,
              dataset: data.data,
              selectable: 'multiple',
              paging: true,
              filterable: true,
              pagesize: 5,
              toolbar: {
                results: true,
                dateFilter: false,
                keywordFilter: true,
                advancedFilter: true,
                actions: true,
                views: true,
                rowHeight: false,
                collapsibleFilter: false,
                fullWidth: true
              }
            }
        });

      });
</script>
```


Thanks!

**Comment by tmcconechy** [comment] 2019-08-22 18:24
Closing until further information can be provided as i have been unable to reproduce in any samples.

**Closed by tmcconechy** 2019-08-22 18:24 UTC
Labels: status: cant reproduce
