### ISSUE TITLE
PBWS: Widgets shuffle dynamically after refresh

### ISSUE THREAD

**Issue by hey-yall** [infor-design/enterprise#7903] opened 2023-09-06 18:55 UTC
Bug submitted via Jira ticket [IDS-1594](https://jira.infor.com/browse/IDS-1594?jql=project%20%3D%2030991%20AND%20labels%20%3D%20FSM_PBWS_Buyer_2023.10_bug). 

Environment:
https://mingle-cqa-portal.cqa.inforcloudsuite.com/v2/D820T10_AX1/

> Widgets on the workspace is observed to move dynamically in the following scenarios:
> 
> Every-time the page is refreshed.
> Digital Assistant chat window is opened and closed.
> I have recorded a video as a reference to the issue observed. 
> 
> Tenant: https://mingle-cqa-portal.cqa.inforcloudsuite.com/v2/D820T10_AX1/
> 
> User: [prabhanjan.kulkarni@infor.com](mailto:prabhanjan.kulkarni@infor.com)
> 
> Infor OS version: 2023.10.00 (20230824-194051, 20230824-194053, 3136, 8510)

For more information, view the video attached to the Jira ticket. Thanks so much, dev team!

**Comment by tmcconechy** [comment] 2023-09-06 18:59
This is not really going to be useful to solve the issue or fix it on our side please note our bug reporting guidelines https://github.com/infor-design/enterprise/blob/main/docs/CONTRIBUTING.md#bug-reports

a) I watched the video but dont really see the issue
b) can you provide a reduced test case for the issue. can you reproduce it in any way in our examples if you try? 

Also are you certain that this is a component issue as it does really look like an application issue. However if you can demoonstrate it in our examples we can surely fix it.

**Comment by tmcconechy** [comment] 2024-02-01 15:56
Closing this as unable to reproduce

**Closed by tmcconechy** 2024-02-01 15:56 UTC
Labels: type: bug :bug:, status: cant reproduce, [3]
