### ISSUE TITLE
SOHO-7928: Datagrid - the Soho.Editors.Lookup editor doesn't support mask

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#223] opened 2018-06-22 22:09 UTC
A datagrid column using the Soho.Editors.Lookup does not support mask.   

For example would like to restrict the input to 10 numeric characters.  This is currently not supported.

So the following does not work (even when adding maskMode and maxLength to SohoDataGridColumn)
    columns.push({
      id: 'lookup-click',
      name: 'Lookup Click',
      field: 'productId',
      editor: Soho.Editors.Lookup,
      editorOptions: {editable: true, click: LMLookupClickFunction},
      maskMode: 'number',
      mask: '##########',
      maxLength: 10
    });

**Comment by tmcconechy** [comment] 2018-07-19 16:58
This is a duplicate of https://github.com/infor-design/enterprise/issues/406 (presume a double conversion glitch)

**Closed by tmcconechy** 2018-07-19 16:58 UTC
Labels: for: up for grabs, type: bug
