### ISSUE TITLE
Datagrid: Unable to set custom Tab Sequence

### ISSUE THREAD

**Issue by ablomq** [infor-design/enterprise#8825] opened 2024-06-17 13:55 UTC
**Describe the bug**
We need to set a custom tab sequence. This has worked until version 4.90.0 bur with version 4.91.0 but with Pull Request [#8259](https://github.com/infor-design/enterprise/pull/8259) this is not possible anymore. The DOM will now be updated constantly adding `tabIndex=0` to some cells in the Datagrid. I tried setting the Datagrid property `actionableMode = false` but it did not revert the behaviour to how it was prior to correction #8259. Don't know how to disable correction [#8259](https://github.com/infor-design/enterprise/pull/8259)? (setActiveCell is called whenever the tab key is pressed.)

This is a business requirement we need to continue to support. Since we can't release our new version until this functionality works this is a showstopper for us.

**To Reproduce**
We set a custom Tab sequence after the Datagrid has been rendered by updating the DOM but with correction [#8259](https://github.com/infor-design/enterprise/pull/8259) this is no longer possible since the DOM is constantly updated with new tabIndex values when pressing the tab key.

**Expected behavior**
A way to disable the behaviour introduced by (https://github.com/infor-design/enterprise/pull/8259) so we can override the tab sequence.

**Version**

- ids-enterprise: v4.96.0
- ids-enterprise-ng: v18.0.1

**Screenshots**
The tab sequence should traverse through the open input fields but now the next field:

Should work like this:

![image](https://github.com/infor-design/enterprise/assets/42343009/c2386b54-6fa6-423a-9388-ca286cda315f)

Pressing the Tab key should then get you to the next input field on the next row:

![image](https://github.com/infor-design/enterprise/assets/42343009/089d93c1-f58b-413f-ac41-a263f02cb28d)

But now it works like this:

![image](https://github.com/infor-design/enterprise/assets/42343009/ce3a3bec-d554-4168-a1d2-8eaa0393d75d)

The "Info" field is an action field that should not be part of the tab sequence:

![image](https://github.com/infor-design/enterprise/assets/42343009/e8afa4ca-7ef5-4f37-ba04-e65927c799ac)

**Comment by tmcconechy** [comment] 2024-06-17 14:03
@ablomq do you really mean that you set a custom tab sequence? As i cant see how that could have worked before. Or do you just mean that tabbing in action mode should go to the next / previous inline editor?

**Comment by ablomq** [comment] 2024-06-17 14:19
We have a directive which updates the DOM by setting the tabindex and then field focus on the first field:

![image](https://github.com/infor-design/enterprise/assets/42343009/d15d7ff2-3cbd-4462-bf0a-e0e6c1ed398e)

But now the `tabindex=0` attribute is added to other fields on the same row by the IDS as soon as I press the Tab key.

**Comment by tmcconechy** [comment] 2024-06-17 14:56
Would it be easier to just use the same behavior where tabing is correct? (tabbing in action mode always goes to the next field) rather than changing tabindexes after the fact?

**Comment by ablomq** [comment] 2024-06-17 15:29
Not sure what you mean? Now it's not possible to set a custom tab sequence since tabindex is constantly updated by the datagrid as soon as I press the tab key.

**Comment by tmcconechy** [comment] 2024-06-17 15:35
@ablomq i mean it seems like the default behavior should be that if you have one editable field per row tab goes to the next row. So why go to the trouble of changing all the tabindexes?

But can see if there is some way we can do this and not set the tabindex but im not really sure if there is, was never a known requirement so far to be able to set custom tabindex on cells.

**Comment by GRAMIK0** [comment] 2024-07-03 08:22
@tmcconechy! This issue is a serious issue and stops us to deliver new versions of application Infor Sales Hub. I would be really happy if you could give me estmate when a fix will be released for this bug report.

**Comment by tmcconechy** [comment] 2024-07-03 13:51
@GRAMIK0 the issue is current in progress to be fixed. Would expect if we can find a solution that it will be in the Aug release

**Comment by GRAMIK0** [comment] 2024-07-04 06:20
Please notice that this is an regression error and should therefore be prioritized. This feature has been working for a long time, but seems to have went broken lately.

**Comment by tmcconechy** [comment] 2024-07-05 14:19
@GRAMIK0 this issue is in progress. We had no way of knowing that we cant use a tabindex internally in our data grid.

**Comment by ablomq** [comment] 2024-07-05 14:44
The tab sequence still doesn't work even if I remove all action fields in the grid and set `actionableMode=false`. It's still not possible to tab to the next row. 

![image](https://github.com/infor-design/enterprise/assets/42343009/a0148073-5d43-4e4e-855b-297996de069f)

**Comment by tmcconechy** [comment] 2024-07-05 14:49
@tjamesallen15 is working on it what we will try is

a) not having any internal tabindex
b) fixing the internal keyboard behavior to work as we expect it to and then any overrides you can set your tabindex (although i still dont reccomend messing around with the tabindex)
c) @tjamesallen15 can we make a test that shows a custom tabindex override?

**Comment by tmcconechy** [comment] 2024-07-08 14:34
@GRAMIK0 @ablomq Can you test the setting out https://github.com/infor-design/enterprise/pull/8873 and wether this will work?

**Comment by ablomq** [comment] 2024-07-08 17:06
@tmcconechy By setting the new parameter `overrideTabbing` to true it now works as before :). Excellent work. A big thanks for this speedy resolution. 

Can you make a special build we can use with this fix including the latest from the released 4.97.0 version?

**Comment by tmcconechy** [comment] 2024-07-08 17:36
@ablomq so you would like this added on top of 4.97.0 -> so a 4.97.1 patch? Do you need only that or also the Angular Build that goes with it? (NG 18?)

**Comment by ablomq** [comment] 2024-07-09 06:20
@tmcconechy Yes, a 4.97.1 patch with the Angular Build (NG 18) would be great.

**Comment by GRAMIK0** [comment] 2024-07-09 07:02
Hi @tmcconechy! Great job done! Thank you very much for your help and professionalism.

**Closed** 2024-07-09 11:34 UTC
Labels: type: bug :bug:, [3], priority: high

**Comment by tmcconechy** [comment] 2024-07-09 13:55
ok @GRAMIK0 @ablomq its ready https://www.npmjs.com/package/ids-enterprise-ng/v/18.1.4 (contains 4..97.1.)
