### ISSUE TITLE
Modal: Make Draggable modal windows

### ISSUE THREAD

**Issue by edisonferrer** [infor-design/enterprise#7019] opened 2022-12-07 12:29 UTC
**Is your feature request related to a problem or use case? Please describe.**
Modal windows: Feature request for modal windows to be repositioned by dragging.

**Describe the solution you'd like**
To be able to reposition modal windows when dragging on its header.

**Describe alternatives you've considered**

**Additional context**
previous controls used can be repositioned by dragging its header. 

![draggable modal window](https://user-images.githubusercontent.com/47999751/206180414-4816470e-2338-4f3a-b990-d33f2b622e56.gif)

**Comment by tmcconechy** [comment] 2022-12-07 14:03
This is a duplicate of https://github.com/infor-design/enterprise/issues/4687 which was previously not accepted.

**Comment by inforrpunay** [comment] 2023-10-16 06:29
> This is a duplicate of #4687 which was previously not accepted.

Hi Tim,

How can we bring this back to discussion? We have two customers looking for this feature.

Kind regards,
Raymond

**Comment by tmcconechy** [comment] 2023-10-16 14:35
I'll bring it up again but its been shot down before as its a pattern being used to hide other design issues. Can you make your case by providing the use case/need for it.

**Comment by inforrpunay** [comment] 2023-10-17 05:49
Hi Tim,

A third customer is also asking for this feature. They want the dialog window to be movable so that they can see the data behind it which they usually use when working on the dialog.

Kind regards,
Raymond

**Comment by inforrpunay** [comment] 2023-10-18 00:32
> @inforrpunay perhaps one answer is to show the data they need directly on the modal (in a label ect)... or maybe a split screen pattern

Sadly, that is not how our application works. Our team just renders/displays the data. We do not control where they will appear.

**Comment by inforrpunay** [comment] 2023-10-24 04:13
Hi @tmcconechy, kindly see feedback from the customer:

"Being able to move the text box is a time saver if you need info that is behind the pop-up when typing the note. There is a work around, just more time consuming."

**Comment by hey-yall** [comment] 2023-11-29 15:00
Design resources ticket: https://jira.infor.com/browse/IDS-1821

**Comment by hey-yall** [comment] 2023-12-12 17:09
@inforandy

**Comment by inforandy** [comment] 2023-12-19 14:25
Hi @inforrpunay. Currently we have no plans to develop this functionality, but would you be able to reach out to me and set up some time to better understand the customer request and how we might work around it? Any time in early Jan should work. Thanks!

**Comment by inforrpunay** [comment] 2024-01-04 02:22
Hi @inforandy, would January 9, 8am EST (January 9, 9pm Manila time) be okay?

**Closed** 2024-03-15 05:54 UTC
Labels: type: enhancement :sparkles:, [3], status: duplicate, team: m3
