### ISSUE TITLE
Datagrid Grouping: Issues Selecting and Sorting with Grouping

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2339] opened 2019-06-07 09:46 UTC
**Describe the bug**
http://4190-beta2-enterprise.demo.design.infor.com/components/datagrid/example-grouping-multiselect.html
There is an issue on multiselect after sorting a column

**To Reproduce**
1. Go to http://4190-beta2-enterprise.demo.design.infor.com/components/datagrid/example-grouping-multiselect.html
2. Check the checkbox header
3. Click the Customer ID column header to sort
4. Try toggling the checkbox header, See issue: now it is not properly working

**Expected behavior**
Select all rows should work properly in Datagrid grouping

**Version**
- ids-enterprise: v4.19.0-beta1 to v4.19.0-beta2

**Platform**
 - All devices, OS, and browsers.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment] 2019-06-07 13:40
This is a new example so cant see if it worked or not before. This is partly a duplicate of #2322 2322

**Comment by tmcconechy** [comment] 2019-07-16 18:56
I fixed part of this issue on #2322 so adjusted this bug to just the remaining case/issue.

**Comment by tmcconechy** [comment] 2020-04-09 16:46
this seems to have been fixed now and i can no longer reproduce. moving to QA to retest

**Closed by tmcconechy** 2020-04-09 16:46 UTC
Labels: [3], focus: datagrid, type: bug :bug:

**Comment by janahintal** [comment] 2020-04-13 05:30
This issue is now resolved. Verified in https://master-enterprise.demo.design.infor.com/components/datagrid/example-grouping-multiselect.html?theme=uplift&variant=dark across all platform. Will retest once Beta is deployed.
