### ISSUE TITLE
Tabs: Tabs header focus highlight is off in RTL locale

### ISSUE THREAD

**Issue by bempedragosa** [infor-design/enterprise#8341] opened 2024-01-16 16:08 UTC
**Describe the bug**
Tabs header focus highlight does not match the actual tab in RTL locales

**To Reproduce**

1. https://codepen.io/bemuuchan/pen/KKEaOjg
2. Select tab
3. Check the focus highlight 

**Expected behavior**
The focus highlight should match the selected tab

**Version**

- ids-enterprise: 4.91.0-dev.0

**Screenshots**
<img width="829" alt="image" src="https://github.com/infor-design/enterprise/assets/58026209/81aa1d38-d442-402b-ab58-b648829316fc">

**Platform**
 - Infor Application/Team Name: LMWEB
 - Browser Name: Chrome

**Comment by tmcconechy** [comment] 2024-02-01 20:03
Duplicate of https://github.com/infor-design/enterprise/issues/8405 fixing it there.

**Closed by tmcconechy** 2024-02-01 20:03 UTC
Labels: type: bug :bug:, [2], team: landmark
