### ISSUE TITLE
Calendar: Layout issue on iOS Mobile

### ISSUE THREAD

**Issue by johnbarcena** [infor-design/enterprise#2966] opened 2019-10-11 10:02 UTC
**Describe the bug**
[iOS Mobile] Layout issue. 

**To Reproduce**
1. Open any browser on iOS mobile device
2. Go to 'http://4220-rc0-enterprise.demo.design.infor.com/components/calendar/example-index.html?'
3. Notice the layout issue

**Expected behavior**
Should not have layout issues
the screenshot below is **Android**
![image](https://user-images.githubusercontent.com/52902639/66643247-e3820a80-ec50-11e9-8d60-a8869eea4783.png)

**Version**
4.22 rc0

**Screenshots**
the screenshot below is **iOS**
![image](https://user-images.githubusercontent.com/52902639/66642793-fba55a00-ec4f-11e9-9929-223eb6eb0af1.png)

**Platform**
iOS Mobile

**Additional context**

**Comment by tmcconechy** [comment] 2019-10-11 13:33
We will take care of this when adding the mobile view https://github.com/infor-design/enterprise/issues/925

**Comment by tmcconechy** [comment] 2019-10-11 13:34
Duplicate of #925

**Closed by tmcconechy** 2019-10-11 13:33 UTC

**Comment by johnbarcena** [comment] 2019-10-11 13:48
Taking note of this. Btw, landscape works fine
