### ISSUE TITLE
Fix IDS Enterprise error in the console for the deprecated code

### ISSUE THREAD

**Issue by SasiPalanati** [infor-design/enterprise#2833] opened 2019-09-24 20:26 UTC
**Describe the bug**

Error found in the console in Sales Hub when running soho verion 4.21 IDS Enterprise: "toggleList()" is deprecated. Please use "toggle()" instead.
IDS Enterprise: "()" is deprecated. Please use "()" instead
IDS Enterprise: "Popdown" is deprecated. Please use "Popover" instead

**To Reproduce**

**Expected behavior**
No warning message in the console

**Version**
Soho 4.21

**Screenshots**

**Platform**
both chrome and IE.

**Additional context**

**Comment by tmcconechy** [comment] 2019-09-24 20:28
Can you tell me what code is running each of these messages?

**Comment by tmcconechy** [comment] 2019-10-09 13:23
Closing as i think all of these are fixed on 4.22 and i cannot reproduce following the steps

**Closed by tmcconechy** 2019-10-09 13:23 UTC
Labels: status: cant reproduce
