### ISSUE TITLE
popupmenu position-calculations are off

### ISSUE THREAD

**Issue by kels0** [infor-design/enterprise#1859] opened 2019-03-27 10:24 UTC
**Describe the bug**
When I open my popupmenu from my button (the more menu) the popupmenu-wrapper is positioned about 10 pixels off,
As you can see in the screen-shot it is a gap between the button and the wrapper and this will cause some problems when the wrapper will calculate the height.
![issue](https://user-images.githubusercontent.com/4634476/55068386-03215f00-5082-11e9-8205-67bef4f31cf1.png)

Attaching the result of the calculations also,
![calculatedTop Height](https://user-images.githubusercontent.com/4634476/55068537-614e4200-5082-11e9-957a-b0eb74f086e3.png)

But, If I change the top-value and the height value to auto (by force).

![setittoauto](https://user-images.githubusercontent.com/4634476/55068562-7034f480-5082-11e9-830b-ffee86a70e22.png)

Everything will work fine and no issues is found.
Is this something you are aware of and maybe want to fix? 
I really don't want an **!Important** in my less-file...

**Version**
Soho 4.16.1

**Comment by tmcconechy** [comment] 2019-03-27 13:00
Is it possible to make an example we can drop in to our project and run this? Or can this be reproduced on the sample site? I'm not sure which item in the screen shot actually has a popupmenu but this could be correct because there isnt enough room on the bottom of the button then the algorithm moves it up on the side with the most space and starts scrolling.

If its a button then i'd suggest using the menubutton component so you have an arrow, and the menu will be aligned with that. And that would more realistically follow the correct design:

http://latest-enterprise.demo.design.infor.com/components/menubutton/example-index.html

**Comment by tmcconechy** [comment] 2019-05-14 15:08
Closing as was unable to reproduce this, but if you can create a reproduction just let me know.

**Closed by tmcconechy** 2019-05-14 15:08 UTC
Labels: status: cant reproduce
