### ISSUE TITLE
Datepicker: Error in console is displayed when year 1451 onward is selected in Umalqura

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3071] opened 2019-11-05 08:35 UTC
**Describe the bug**
Datepicker: Error in console is displayed when year 1451 onward is selected in Umalqura.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datepicker/example-umalqura.html
2. Open console
3. Open date picker, then open the month and year dropdown
4. Select year 1451, then click Apply button
5. Select any day
6. Click outside the date picker field to remove focus
7. See issue: error will be displayed in console and date picker cannot be open again

**Expected behavior**
There should be no error in console when year 1451 onward is selected, and date picker should be interactable again.

**Version**
- ids-enterprise: v4.20.0 to v4.23.0-beta0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/68191153-d6ef9880-ffe9-11e9-946d-bda9ca292367.png)

**Platform**
 - All devices, OS, and browsers.

**Additional context**
N/A.

**Comment by tmcconechy** [comment] 2019-11-05 13:40
Duplicate of #3051

**Comment by tmcconechy** [comment] 2019-11-05 13:41
This is a known issue we are working on it. At the moment there is a maxDate in the umalqura calendar which we are looking to address on #3051

**Closed by tmcconechy** 2019-11-05 13:40 UTC
Labels: status: duplicate
