### ISSUE TITLE
Toolbar '...' action is cut off in iOS

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2972] opened 2019-10-14 08:30 UTC
**Describe the bug**
Toolbar '...' action is cut off in iOS devices

**To Reproduce**
1. Open iOS Safari or Chrome Browser in Mobile
2. Go to http://4220-rc0-enterprise.demo.design.infor.com
3. Go to Toolbar action section
4. Click '...'

**Expected behavior**
Should open a popdown option

**Version**
Rc0 4.22

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/66737940-d9098000-ee9f-11e9-9d45-68bdf1b2f8b2.png)

**Platform**
OS: iOS Mobile Devices (iPhone XS)
Browser: Sarafi / Chrome

**Additional context**
N/a

**Comment by tmcconechy** [comment] 2019-10-15 13:49
Duplicate of #2800

**Closed by tmcconechy** 2019-10-15 13:49 UTC
Labels: status: duplicate, type: bug :bug:
