### ISSUE TITLE
Dropdown: Cannot Select "Emtpy" Value

### ISSUE THREAD

**Issue by rowelineeveresurreccion** [infor-design/enterprise#3323] opened 2020-01-14 08:14 UTC
**Describe the bug**
The user cannot select "Emtpy" Dropdown Value.

**To Reproduce**

Tested via local IDS solution: http://localhost:4000/components/datagrid/test-editable-dropdown-width.html

1.	When a defined dropdown option’s value is “empty”, it cannot be selected in the datagrid.

In this example, I’ve added another option to the list with an empty value.

 
![image](https://user-images.githubusercontent.com/50350478/72325742-bd08bb00-36e8-11ea-8bc0-a8c8a4bb36e0.png)

Select the “none” value. It cannot be selected, it will just return to the previous value.

![image](https://user-images.githubusercontent.com/50350478/72325794-d7db2f80-36e8-11ea-945f-36621a15415e.png)

 

**Expected behavior**
The user should be able to select an “Empty” value. 

**Version**
IDS Version: 4.25.0.-dev

**Platform**
 - Google Chrome 
Version 79.0.3945.117 (Official Build) (64-bit)

**Comment by tmcconechy** [comment] 2020-01-14 14:50
We can see if this can be made to work. As a workaround you could do this `/{id: 'opt7', value: 'none', label: '(none)'},` but i get that the value will change. Im not seeing a way to make http://localhost:4000/components/dropdown/test-blank-initially.html work.

**Comment by tmcconechy** [comment] 2020-01-14 14:51
Duplicate of https://github.com/infor-design/enterprise/issues/3313

**Comment by tmcconechy** [comment] 2020-01-14 14:51
Found this already on #3313 so please watch that issue. Will close this in favor.

**Closed by tmcconechy** 2020-01-14 14:51 UTC
Labels: [3], type: bug :bug:
