### ISSUE TITLE
Modal: Cannot scroll after closing modal on an iOS device

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3389] opened 2020-01-27 12:29 UTC
**Describe the bug**
Modal is not working after closing a different modal in iOS device

**To Reproduce**
1. Open iOS mobile and Go to http://4250-rc1-enterprise.demo.design.infor.com/
2. Click Show Modal button
3. Close the Modal 
4. Click any button to open the Message component and then and close the message 
5. Notice that you will not be able to scroll the page nor click another button again. 

**Expected behavior**
Be able to open another modal without issue after opening a modal

**Version**
IDS RC1 4.250

**Screenshots**
N/a

**Platform**
iOS Mobile Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment] 2020-01-27 14:40
Tried this on ios X on browser stack. And could not reproduce it. After opening and closing the modal, i am able to scroll the page and reopen the modal again.

**Closed** 2020-03-12 13:55 UTC
Labels: [2], type: bug :bug:

**Comment by CindyMercadoReyes** [comment] 2020-03-12 17:11
This issue is now resolved. Moving this ticket to the Done column.
