### ISSUE TITLE
Lookup: is-not-editable class has broken readonly

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#5171] opened 2021-05-03 20:31 UTC
**Describe the bug**
When attempting to set a lookup's input to readonly, the field does not display as read only. The readonly attribute does appear in the html. If I take off the is-not-editable class, then it displays correctly.

**To Reproduce**
1. Copy [test-readonly.zip](https://github.com/infor-design/enterprise/files/6417512/test-readonly.zip) into app/views'components/lookup
2. Navigate to '/components/lookup/test-readonly.html'
3. See error

**Expected behavior**
Having the readonly attribute on the html should have the field be read only.

**Version**

- ids-enterprise: [4.51.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/22107636/116929796-88de4400-ac24-11eb-84f7-cf399537549c.png)
![image](https://user-images.githubusercontent.com/22107636/116929876-a4494f00-ac24-11eb-9baf-c7d8d36ac716.png)

**Platform**
 - All
**Additional context**

**Comment by tmcconechy** [comment] 2021-05-03 20:44
This is a duplicate of #5149 and it’s been fixed (can test in 4.51.0-beta0)

**Closed by tmcconechy** 2021-05-03 20:44 UTC
Labels: [1], status: duplicate, team: landmark, type: bug :bug:
