### ISSUE TITLE
RTL: Popupmenu, submenu in wrong position

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#2190] opened 2019-05-20 15:43 UTC
**Describe the bug**
When using Pupupmenu with Submenu in RTL, the submenu is shown to the right of the popupmenu instead of to the left.

**To Reproduce**
1. Go to [https://design.infor.com/code/ids-enterprise/latest/demo/components/popupmenu/test-ajax-submenu.html?locale=he-IL](https://design.infor.com/code/ids-enterprise/latest/demo/components/popupmenu/test-ajax-submenu.html?locale=he-IL)
2. Expand the submenu
3. See behavior

**Expected behavior**
The arrow direction is correct for RTL, and also the reading direction in each item is correct - so the "natural" way for the submenu should be to the **left** of Popupmenu - it is more readable in RTL languages like that.

**Version**

- ids-enterprise: 4.18.1

**Screenshots**
![submenu-rtl-realworld-example](https://user-images.githubusercontent.com/34129313/58034252-d2642000-7b2e-11e9-809a-04f829ac7215.PNG)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version:  Windows 7
 - Browser Name: Chrome & IE11
 - Browser Version: latest

**Additional context**
Thanks!

**Comment by tmcconechy** [comment] 2019-05-20 15:45
And there is enough room on the left?

**Comment by jonathanamiran** [comment] 2019-05-20 15:50
Yes, plenty.
![submenu-rtl-realworld-example-full](https://user-images.githubusercontent.com/34129313/58034798-068c1080-7b30-11e9-8f8a-c0d53c2b0421.PNG)

**Comment by tmcconechy** [comment] 2019-05-20 15:52
OK i see it if i :

1. go to https://design.infor.com/code/ids-enterprise/latest/demo/components/popupmenu/test-ajax-submenu.html?locale=he-IL
2. edit the css of the button to make it `position: relative; ; left: -500px;` so that the button is more to the middle of the page
3. click button and hover the menu

**Comment by rvaja-infor** [comment] 2019-05-21 13:18
We have a similar issue in SunSystems, control library version v4.14.0, where the sub-menu three levels down is being put to the right of its parent in a RTL language.
![7-Arabic-LEN-Menu](https://user-images.githubusercontent.com/45232365/58099255-32140700-7bd3-11e9-96f0-e6dda30db0bf.png)
Probably worth adding a test case to verify that any fix also resolves such issues.

**Comment by tmcconechy** [comment] 2020-03-26 14:51
Duplicate of #1512

**Closed by tmcconechy** 2020-03-26 14:51 UTC
Labels: [2], focus: rtl, type: bug :bug:
