### ISSUE TITLE
Preview: Charts - Legend color positioning issue

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#8160] opened 2023-11-08 13:36 UTC
**Describe the bug**
Focus state overlaps with legend color.

**To Reproduce**

1. Go to https://preview-enterprise.demo.design.infor.com/?theme=new&mode=light&colors=default
2. Make sure you are in Classic version
3. Scroll down to Charts: Vertical Bar Chart, Stacked Bar - Vertical, Stacked Bar - Vertical 100%, Grouped Bar Chart, Line Chart, and Area Chart
4. Click on legends
5. See error 

**Expected behavior**
Focus state and legend color should not overlap.

**Version**

- ids-enterprise: 

**Screenshots**
<img width="709" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/b22171e9-c343-46b2-826b-b85141d571c8">

<img width="709" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/27d5079f-5490-43fa-92b5-8d015e3b15d2">

**Platform**
 - All major browsers

**Comment by tmcconechy** [comment] 2023-11-08 14:59
This is probably an issue in main as well as nothing specifically was changed for this.

**Comment by tmcconechy** [comment] 2023-11-08 14:59
Duplicate of https://github.com/infor-design/enterprise/issues/8159
If the issue exists on main no need for a seperate issue for the preview version

**Closed by tmcconechy** 2023-11-08 14:59 UTC
Labels: type: bug :bug:, [1], priority: minor
