### ISSUE TITLE
Spinners with .field-short have an input that isn't short

### ISSUE THREAD

**Issue by jake-harrington** [infor-design/enterprise#601] opened 2018-08-13 18:12 UTC
**Describe the bug**
.field-short spinbox fields have a full size input

**To Reproduce**
1. Go to http://localhost:4000/components/input/test-short-field-sizes.html
2. Observe the color picker input is taller than the -/+ buttons

**Expected behavior**
The spinbox field should be shorter, like the buttons.

**Screenshots**
![image](https://user-images.githubusercontent.com/39064853/44049657-520aab74-9efa-11e8-897d-8372eb9135d5.png)

**Platform**
- Using enterprise 4.9.x

**Comment by tmcconechy** [comment] 2018-08-13 18:38
This is a duplicate of https://github.com/infor-design/enterprise/issues/547 which has already been fixed.

**Closed by tmcconechy** 2018-08-13 18:38 UTC

**Comment by jake-harrington** [comment] 2018-08-14 13:50
Is this going to be fixed in 4.9.x?

**Comment by tmcconechy** [comment] 2018-08-14 13:52
Would could make a 4.9.1 with it but also 4.10.0 will be released end of the month. Can talk to @clepore about that when he's back next week. Im not sure how to do it 100%

**Comment by tmcconechy** [comment] 2018-08-27 14:00
We are freezing 4.10 today and a beta will be available today to test. Releasing 4.10 in one week.
The problem is QA is working on 4.10 so we dont have resources for QAing a patch release as well.

**Comment by clepore** [comment] 2018-10-12 16:34
Duplicate of #547

**Comment by tmcconechy** [comment] 2018-10-15 14:09
Yes, looks like its sorted now http://master-enterprise.demo.design.infor.com/components/validation/example-short-fields.html
