### ISSUE TITLE
Popover: Squished container and misaligned close button on mobile

### ISSUE THREAD

**Issue by davidcarlsonberg** [infor-design/enterprise#2272] opened 2019-05-30 09:42 UTC
**Describe the bug**
The popover is squished to the side at smaller screen sizes.

**To Reproduce**
- Visit http://localhost:4000/components/popover/example-header-color.html
- Reduce screen size to mobile
- Click "Click To Show Popover" button
  - notice the popover is squished (and the close button is misaligned)

**Expected behavior**
I expect the popover to not look squished and the close button to be properly aligned.

**Version**
v4.20.0

**Screenshots**
<img width="355" alt="bug" src="https://user-images.githubusercontent.com/7952168/58624075-66578980-829d-11e9-9a6e-cc4e6468985a.png">

**Platform**
 - iPhone 5/SE (simulated on Chrome Desktop)
 - MacOS 10.14.5
 - Chrome Version 74.0.3729.169 (Official Build) (64-bit)

**Additional Context**
First reported here: https://github.com/infor-design/enterprise/pull/2267#issuecomment-497118814

**Comment by tmcconechy** [comment] 2019-05-30 12:46
Duplicate of #1576

**Closed by tmcconechy** 2019-05-30 12:46 UTC
