### ISSUE TITLE
List View: Scroll bar UI changes after changing the variant in Windows Chrome 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3172] opened 2019-11-22 11:35 UTC
**Describe the bug**
List View: Scroll bar UI changes after changing the variant in Windows Chrome 

**To Reproduce**
1. Open Windows chrome browser then Go to  http://4230-enterprise.demo.design.infor.com/ or http://master-enterprise.demo.design.infor.com/
2. Search for List View component
3. Change the Theme to Vibrant (Keep in mind the scroll UI)
4.  Now change the Variant to Dark (Notice the change of scroll UI)
5. Also, as I change the Theme, Variant and the Color the Error in console increases 

**Expected behavior**
The scroll UI should be consistent 

**Version**
ids 4.24 smoke testing

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/69422661-27dbec80-0d5f-11ea-820b-92e42c767f5e.png)

**Platform**
Windows 10 Chrome

**Additional context**
N/a

**Comment by tmcconechy** [comment] 2019-11-22 14:36
The error was fixed on https://github.com/infor-design/enterprise/issues/3159 recently.
The problem is this line is only in the light theme, should be added to dark and high contrast:
https://github.com/infor-design/enterprise/blob/master/src/themes/theme-uplift-light.scss#L76

This just needs to be copied to the other files.

**Closed** 2019-12-20 16:34 UTC
Labels: [2], focus: uplift theme, type: bug :bug:

**Comment by jbrcna** [comment] 2020-01-02 10:47
QA **Failed**
Verified in https://master-enterprise.demo.design.infor.com/components/listview/example-index.html

**Notes:**
It works fine in ALL Browsers **Except**  in IE11. nothing seems to be working in IE11 with the current version 4.25.0-dev

**Comment by tmcconechy** [comment] 2020-01-02 16:19
Fixed on https://github.com/infor-design/enterprise/issues/3289 - ready to retest IE 11

**Comment by CindyMercadoReyes** [comment] 2020-01-02 20:42
This issue is now resolved. Moving the ticket to the Done column.
