### ISSUE TITLE
Message: unnecessary scroll bar inside Message - Success Example

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1777] opened 2019-03-12 07:35 UTC
**Describe the bug**
Sink Page: unnecessary scroll bar inside Message - Success Example

**To Reproduce**
Steps to reproduce the behavior :
1. Go to http://4160-rc2-enterprise.demo.design.infor.com or http://4160-rc2-enterprise.demo.design.infor.com/components/message/example-index.html
2. Scroll down to 'Message' 
3. Click Success Example
* Notice that there is an unnecessary scroll bar inside the pop-up message

**Expected behavior**
Should have no unnecessary scroll bar. 

**Version**
v4.16.0

**Screenshots**
<img width="1473" alt="Screen Shot 2019-03-12 at 2 24 54 PM" src="https://user-images.githubusercontent.com/45757016/54182231-dabf2f80-44db-11e9-9cfc-943d94bf9381.png">

**Platform**
- IE 11

**Additional context**
No any additional context.

**Comment by tmcconechy** [comment] 2019-03-12 12:24
Adding a bit of padding to `.modal-content .modal-body-wrapper` seems to fix.

**Comment by tmcconechy** [comment] 2019-11-19 19:47
Duplicate of https://github.com/infor-design/enterprise/issues/2964

**Closed by tmcconechy** 2019-11-19 19:47 UTC
Labels: [1], status: duplicate, type: bug :bug:
