### ISSUE TITLE
Datagrid - when horizontally scrollable then filter is breaking the Header and Body synchronization

### ISSUE THREAD

**Issue by vladimir-marko** [infor-design/enterprise#1041] opened 2018-10-19 11:54 UTC
**Describe the bug**
DataGrid is jumping to most left side when datagrid has more columns as fit on the browser and filter is set on non existing value. As far as filter has still the focus and it can be used then additional editation of filter expression can break position of header and body.

**To Reproduce**
1. https://design.infor.com/code/ids-enterprise/latest/demo/datagrid/example-filter.html?font=source-sans

2. Make smaller horizontal size of the window in the way when scrollbar is appeared and some colums are hidden on right side.
![image](https://user-images.githubusercontent.com/44021524/47214868-90f47200-d39f-11e8-8b0b-ebc4bcd96667.png)

3. Scroll to the right side and put the cursor into most right filter.
![image](https://user-images.githubusercontent.com/44021524/47214948-d2851d00-d39f-11e8-81f7-82ab8491ef7c.png)

4. Write the 41 into the **"Price"** filter
5. First problem appeared. The area of datagrid (header+body) is moved/jumped to most left side.
![image](https://user-images.githubusercontent.com/44021524/47216410-280ff880-d3a5-11e8-8c44-8fee4a51c4ff.png)

6. Now continue to write on keyboard 0.990
7. The position of Header and Body of Datagrid is broken.
   We are able to see the full number in filter 410.990 because the Header is moved to most right side.
And we are able to see the filtered rows but from most left value. The body is on most left side.
![image](https://user-images.githubusercontent.com/44021524/47216350-f8f98700-d3a4-11e8-9ce1-0aba13d6d5e6.png)

**Expected behavior**
1) When the filter is used but there is no match between rows then stay on the place and don't jump at the most left side of the datagrid. And the message **No Data Available** should be displayed on actual part of screen.
![image](https://user-images.githubusercontent.com/44021524/47216287-b768dc00-d3a4-11e8-8d66-0c3a7a77f423.png)

2) When the filter is used and the match is done then stay on place and just display the filtered lines
![image](https://user-images.githubusercontent.com/44021524/47216221-7c66a880-d3a4-11e8-9e52-51be77e53bd7.png)

**Platform**
 - OS Version: Windows 7 Enterprise 64-bit
 - Browser Name: chrome
 - Browser Version: Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by tmcconechy** [comment] 2018-10-19 13:13
Agreed that it should not scroll over to the left. However, im not sure if we can move the icons on the empty message as they are centered in the actual area...

**Comment by vladimir-marko** [comment] 2018-10-19 15:16
yes, it's reasonable to have the message Data Not Available in the center of the data area. The position on center of the visible columns is just improvement which can be accepted by part of users but not by others.

**Comment by tmcconechy** [comment] 2019-06-11 12:43
Are you still seeing this issue on http://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html?font=source-sans i tried to retest but it seems things have changed.

**Comment by tmcconechy** [comment] 2019-07-09 13:47
Was unable to reproduce on the latest 4.20 or 4.19. Very possibly this was fixed on another issue

**Closed by tmcconechy** 2019-07-09 13:47 UTC
Labels: [5], focus: datagrid, status: cant reproduce, type: bug :bug:
