### ISSUE TITLE
Export: Getting warning when exporting Excel file

### ISSUE THREAD

**Issue by cbeck54** [infor-design/enterprise#4286] opened 2020-08-19 22:55 UTC
App Builder recently added the capability to export grid data to an Excel spreadsheet or CSV-formatted file. However, when I export to Excel as an option, I get an error message (see attached screen capture). 
![Excel export error message](https://user-images.githubusercontent.com/48723953/90697583-b927b300-e24c-11ea-8e2c-1e3025991de4.png)
According to Marcus Jonsson, developer on the App Builder team: "This is a IDS issue. It’s perfectly safe to open in Excel, but what they are calling a .xls isn’t truly a .xls file, rather it’s a html/xml file. 
"This is not something that we can change from our end, but feel free to report the issue to IDS and they might be able to do something."
I believe this is something that will cause a good amount of anxiety and disgruntlement on the part of our users. Is it something you guys can fix?

**Comment by tmcconechy** [comment] 2020-08-20 13:38
@cbeck54 this is a duplicate of https://github.com/infor-design/enterprise/issues/2995 ~ we havent found an easy solution for this so far. You can vote up that issue to watch it 👍

**Closed by tmcconechy** 2020-08-20 13:38 UTC
Labels: [5], status: duplicate, type: bug :bug:
