### ISSUE TITLE
SOHO-8110: String-based Autocomplete template settings will not render correctly when multiple elements are nested

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#380] opened 2018-07-17 19:16 UTC
Discovered when testing on SOHO-8076...

One of the code paths in the Autocomplete's process for figuring out a template setting causes many of the nested elements in that template to be removed unexpectedly.

Found here:  https://github.com/infor-design/enterprise/blob/4.7.x/src/components/autocomplete/autocomplete.js#L220

```
$(this.settings.template).text()
```
In the above scenario, a template defined as...

```
<li id="{{listItemId}}" {{#hasValue}}data-value="{{value}}"{{/hasValue}} role="listitem">
 <a href="#" tabindex="-1">
   <span>{{{label}}}</span>
 </a>
</li>
```

...will incorrectly be rendered as...
```
{code:html}
{{{label}}}
{code}
```
I think simply switching to `{{$(this.settings.template).html()}} `would probably work better... but this needs some testing and needs to be confirmed with functional tests.

**Comment by davidcarlsonberg** [comment] 2019-01-17 20:08
I am unable to reproduce this but am also unsure about my method of reproduction.
@EdwardCoyle: are you able to reproduce and add steps here in your spare (haha) moments.

**Comment by tmcconechy** [comment] 2019-10-31 13:38
Closing this as unable to reproduce.

**Closed by tmcconechy** 2019-10-31 13:38 UTC
Labels: [2], status: cant reproduce, type: bug :bug:
