### ISSUE TITLE
Datagrid: Scroll Bar appears in dropdown in responsive view

### ISSUE THREAD

**Issue by iamjamesreyracho** [infor-design/enterprise#6417] opened 2022-05-13 11:25 UTC
**Describe the bug**
In responsive view, the scroll bar appeared in the dropdown menu in Classic version in Win-Chrome and Win-Edge.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-disabled-rows.html
2. In responsive view, scroll towards the end
3. Click a field in Action.

**Expected behavior**
Scroll bar should not appear upon clicking the dropdown menu.

**Version**

- ids-enterprise: v4.64.0-dev

**Screenshots**
Win-Chrome 
![image](https://user-images.githubusercontent.com/98729565/168250298-b6a21743-d8f4-4dc0-a7f9-3c37538c5ade.png)

Win-Edge
![image](https://user-images.githubusercontent.com/98729565/168250352-be48891f-8adf-4f94-93a7-5c85255b8213.png)

**Platform**
 - Browser Name: Chrome, Edge (Wwindows)

**Additional context**
NA

**Comment by tmcconechy** [comment] 2022-05-13 12:51
Not seeing this issue @iamjamesreyracho - what specifically do you mean by responsive view. Also the scroll bar doesnt even look like a windows scroll bar

**Comment by iamjamesreyracho** [comment] 2022-05-13 14:43
When it is in toggle device, that's when the scroll bar appears upon clicking the dropdown menu, Sir Tim.
https://www.screencast.com/t/WMjb2Q55SUL

**Comment by tmcconechy** [comment] 2022-11-22 14:50
Closing older issues we cant reproduce.

**Closed by tmcconechy** 2022-11-22 14:50 UTC
Labels: type: bug :bug:, status: cant reproduce, [2], priority: minor
