### ISSUE TITLE
Datagrid: Some filter is not opening in the column header

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5496] opened 2021-08-06 09:51 UTC
**Describe the bug**
Datagrid: Some filter is not opening in the column header

**To Reproduce**

1. Go to https://4540-beta0-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html
2. In Product Name column, open the filter

**Expected behavior**
Filter should be opened

**Version**
ids-4540-beta0

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/128492427-dd0425b8-4e70-4258-ace0-ace33e5e0e3d.png)

**Platform**
All major browser, OS & Devices 

**Additional context**

**Comment by tmcconechy** [comment] 2021-08-06 13:34
@janahintal do i need any extra steps, with these its opening for me and i cant reproduce

**Comment by tmcconechy** [comment] 2021-10-05 13:45
Closing as unable to reproduce

**Closed by tmcconechy** 2021-10-05 13:45 UTC
Labels: type: bug :bug:, status: cant reproduce
