### ISSUE TITLE
Datagrid: Border disappears when hovering in Uplift Dark

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3408] opened 2020-01-30 06:20 UTC
**Describe the bug**
Datagrid: Border disappears when hovering in Uplift Dark.

**To Reproduce**
1. Go to http://4250-enterprise.demo.design.infor.com/components/datagrid/example-index.html?theme=uplift&variant=dark
2. Hover on the first row or in any row
3. Notice that the column borders are not visible

**Expected behavior**
Column borders should still be visible when hovering in Uplift Dark.

**Version**
- ids-enterprise: v.4.25.0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/73424706-95615600-436a-11ea-87ad-6b5c2ad38dbb.png)

**Platform**
 - All Devices, OS, and browsers.

**Additional context**
N/A

**Comment by deep7102** [comment] 2020-01-31 22:19
Can not reproduced, looks like fixed with some other issue.
http://master-enterprise.demo.design.infor.com/components/datagrid/example-index.html?theme=uplift&variant=dark

**Comment by tmcconechy** [comment] 2020-02-01 00:04
Ok yes I fixed this during a round of color changes

**Closed by tmcconechy** 2020-02-01 00:04 UTC
Labels: [1], focus: uplift theme, type: bug :bug:

**Comment by CindyMercadoReyes** [comment] 2020-02-03 19:25
The issue is now resolved. I tested this issue across browsers and you can now see the borders. Moving this ticket to the Done column.
