### ISSUE TITLE
Pop Over: Alternate Position -  Layout Issue on IE11 when you switch themes

### ISSUE THREAD

**Issue by johnbarcena** [infor-design/enterprise#2955] opened 2019-10-10 11:18 UTC
**Describe the bug**
no details are displayed in pop over when you switch themes.

**To Reproduce**
1. Go to 'http://4220-beta0-enterprise.demo.design.infor.com/components/popover/example-attached-to-textbox.html?'
2. Verify pop over
3. Switch between Themes then Verify Pop-Over

**Expected behavior**
should display details

**Version**
4.22 Beta

**Screenshots**
![image](https://user-images.githubusercontent.com/52902639/66564438-9a6b8100-eb92-11e9-90c2-dd92a284ec38.png)

![image](https://user-images.githubusercontent.com/52902639/66564473-a6574300-eb92-11e9-8fc7-7bd22309d708.png)

**Platform**
IE 11

**Additional context**

**Comment by tmcconechy** [comment] 2019-10-10 13:17
Duplicate of #2954

**Closed by tmcconechy** 2019-10-10 13:17 UTC
