### ISSUE TITLE
Datagrid: Order date overlapping calendar icon in example editable component

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1566] opened 2019-01-30 12:20 UTC
**Describe the bug**
Datagrid: Order date overlapping calendar icon in example editable component

**To Reproduce**
1. Go to https://4150-beta0-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
2. Edit Row Id 1 Order Date to '12/30/2030'
3. Hover to the row
4. Notice that the icon overlaps the date 

**Expected behavior**
Icon should not overlap the text in the column when hovered 

**Version**
v4.15.0

**Screenshots**
<img width="1302" alt="screen shot 2019-01-30 at 8 12 59 pm" src="https://user-images.githubusercontent.com/45757016/51980910-66e93a80-24cc-11e9-9a69-a74d16f1cd8f.png">

**Platform**
All Browsers, OS and Devices

**Additional context**
No Additional context

**Comment by tmcconechy** [comment] 2019-01-30 14:39
This is a duplicate of https://github.com/infor-design/enterprise/issues/1191

**Closed by tmcconechy** 2019-01-30 14:39 UTC
Labels: status: duplicate
