### ISSUE TITLE
Busy Indicator Issue: Overlaps the modal pop-up and disabling the button functions

### ISSUE THREAD

**Issue by kmadamba** [infor-design/enterprise#4113] opened 2020-07-03 02:41 UTC
**Describe the bug**
Busy indicator of the parent form continuously load on the modal which blocks user to perform any action on the modal

**To Reproduce**
1.	Navigate to: https://master-enterprise.demo.design.infor.com/components/busyindicator/test-after-close-modal.html
2.	Click Show Message button
3.	Adjust the width of the modal
a.	Click F12
b.	Select the modal element
 
![image](https://user-images.githubusercontent.com/66233290/86425397-a0ecea80-bd17-11ea-88d8-bf21e8184659.png)

c.	Select element with id=”ids-modal-root” and add 
 
![image](https://user-images.githubusercontent.com/66233290/86425412-b104ca00-bd17-11ea-9dad-60dd11fb99c8.png)

d.	Click Cancel button
e.	Click Start button
f.	Click Show Message button
 
![image](https://user-images.githubusercontent.com/66233290/86425443-ca0d7b00-bd17-11ea-9dfd-45fb941ed355.png)

g.	In the image above, if you try to click Delete or Cancel in the modal, nothing happens. The busy indicator blocks us from clicking those buttons. This means the busy indicator is stacked on top of the modal.

**Expected behavior**

**Version**
- IDS Enterprise Components - 4.30.0-beta.0

**Platform**
- OS Version: Windows 10
- Browser Name: Chrome
- Browser Version: 83.0.4103.116

**Comment by tmcconechy** [comment] 2020-07-06 14:07
Having a hard time following and verifying this issue. Maybe you can upload a working example? What i dont follow is:
- why change the width of id="ids-modal" all this does for me is move it off the page
- "A clear and concise description of what you expected to happen." -> wasnt filled in so not sure why your doing all this?

**Comment by kmadamba** [comment] 2020-07-07 01:46
Hi! 

As per the developer, 

**- Why change the width of id="ids-modal" all this does for me is move if off the page?**

 - We changed the width for replication purposes. Just so the busy indicator and the modal are in the same place and to show the overlapping issue between them

**- A clear and concise description of what is expected to happen**

- Modal and busy indicator should not overlap. Modal and busy indicator must be stack correctly.

**Comment by tmcconechy** [comment] 2020-07-07 13:17
Ok, whats the real case? I still dont get why you are resizing it like that i think you want to resize it by only changing the inner contents not the outer DIV? Perhaps you can make us a runable example so i can better see the issue?

Can you reproduce the issue on any examples here https://master-enterprise.demo.design.infor.com/components/busyindicator/test-inside-modal.html or any example here https://master-enterprise.demo.design.infor.com/components/busyindicator/

**Comment by maeroseb** [comment] 2020-07-08 02:05
Hi Tim. Sorry about how we resize it initially. I tried to reproduce this issue again in [https://master-enterprise.demo.design.infor.com/components/busyindicator/test-after-close-modal.html](url) and this time I adjusted the min-width=80% of the inner content (div class="modal...") for repro purposes.

![image](https://user-images.githubusercontent.com/64888576/86864750-51843100-c100-11ea-92cc-aad79ef01a2c.png)

The issue here is that the busy indicator is displayed on the modal which blocks the user from selecting buttons or from interacting with the modal. We encountered this issue on our end when we had to keep the busy indicator loading in the main form (for process purposes - like needs to wait the action performed in the modal) while a modal is displayed.
![image](https://user-images.githubusercontent.com/64888576/86865372-7200bb00-c101-11ea-8980-f5e3cdf66f28.png)

I hope we were able to explain it better. If not, we would be happy to provide more details for this issue. Thank you.

**Comment by tmcconechy** [comment] 2020-07-08 13:16
I think i get it however the example we have here https://master-enterprise.demo.design.infor.com/components/busyindicator/test-inside-modal.html does not exhibit this issue. So maybe looking at that issue and comparing to what your doing will help you?

**Comment by maeroseb** [comment] 2020-07-09 05:20
I think [https://master-enterprise.demo.design.infor.com/components/busyindicator/test-inside-modal.html](url) is not the right example for this issue since the busy indicator of the modal works as expected, it's the busy indicator of the main form that is not working as expected (it is stack on top of the modal wherein it should be stack behind the modal). Not sure if it's okay to use our work to show more about the issue but providing the following screenshots:

**Main Form with Busy Indicator**
The busy indicator is attached to the process inside Add button click event which awaits for the response from the modal
![image](https://user-images.githubusercontent.com/64888576/86999480-435c1080-c1e5-11ea-96c7-973594864cc9.png)

**On Display of the Modal:**
Busy indicator of the main form is displayed on the modal
![image](https://user-images.githubusercontent.com/64888576/86999506-553db380-c1e5-11ea-9e01-f747ba3d375d.png)

**After Modal Has Been Loaded**
Busy indicator of the main form continuously loading on the modal
![image](https://user-images.githubusercontent.com/64888576/86999615-90d87d80-c1e5-11ea-8bd9-6880c7bce13b.png)

Thank you.

**Comment by tmcconechy** [comment] 2020-07-09 13:08
OK, i get it now. However, not sure we can fix this. Its a bit of an odd case and maybe an over use of the busy indicator. What i would do is maybe...

- click button and open the modal
- show the busy indicator while that loads (only if it takes longer than about 4-6 seconds) like my example
- or you could use the non blocking indicator https://master-enterprise.demo.design.infor.com/components/busyindicator/example-non-blocking.html
- or the workaround of a zindex seems valid for your case

We will be changing the style of the busy indicator in the near future anyways so i think it doesnt make sense to change the busy indicator at this time.

https://github.com/infor-design/enterprise/issues/3422

**Comment by maeroseb** [comment] 2020-07-10 07:30
Hi Tim. For now, we can settle with the zindex workaround. Hopefully this will be addressed as well when busy indicator is changed. Thank you.

**Comment by tmcconechy** [comment] 2020-07-10 13:08
Cool, closing this for now then. Please watch #3422

**Closed by tmcconechy** 2020-07-10 13:08 UTC
Labels: [3], status: cant reproduce, type: bug :bug:
