### ISSUE TITLE
Tooltip: Fix Component Displaying With Delay

### ISSUE THREAD

**Issue by stephanie-infor** [infor-design/enterprise#5315] opened 2021-06-14 20:15 UTC
**Describe the bug**
Tooltip "More" is displaying even when the mouse is no longer hovering over the specified ellipsis.

**To Reproduce**
_See https://jira.infor.com/browse/SCRMPORTALV2-1263 for conditions to reproduce._

1. Login to portal with user 1 (user role)
2. Click ellipsis on an icon from the application switcher
3. Click elsewhere not in a space where icon exists

**Expected behavior**
The tooltip "More" only displays when mouse is hovering over the ellipsis

**Screenshots**
The issue can be seen in the media captures attached.
![tooltip-issue](https://user-images.githubusercontent.com/84295703/121948239-fd78c800-cd24-11eb-8f5c-28709b82c375.gif)

https://user-images.githubusercontent.com/84295703/121948255-010c4f00-cd25-11eb-9f64-74c1a5f32f03.mp4

**Platform**
 - Infor Application/Team Name: Portal
 - Specs: tested and reproduced in Windows - Chrome, and Mac - Chrome

**Comment by tmcconechy** [comment] 2021-06-15 13:00
Is it possible to make a more focused reproduction of this issue? As its very complicated for our developers to fix bugs in your app. In doing so you might find the issue is on your end. Because the issue doesn't have an isolated reproduction this will impact how long it will take to fix this greatly. What you could do is put just the relevant code to reproduce in a stackblitz like https://stackblitz.com/edit/ids-enterprise-4520

From the video i do have two suggestions..
- could you destroy the tooltip (not have a tooltip) 
- if you just have one action in the menu (delete) its probably better to just use a delete icon button or an x to "clear" the icon out. Its extra clicking and would possibly get rid of the issue
- also try a more recent version if you are on an old version

**Comment by stephanie-infor** [comment] 2021-06-17 14:39
Hi @tmcconechy ,  I forwarded the team your response and they stated that they have observed same behavior with soho ng-enterprise demo sample examples.

If they're unable to provide an isolated reproduction, what additional information would be helpful for your team?

Comment provided by Portal dev:
> "sometimes more icon tooltip is showing up when clicking on outside of the icon. Actually here in this pic I am not focused on the more icon I clicked outside of that icon."

![sometimes more tooltip showing up on click of the outside icon](https://user-images.githubusercontent.com/84295703/122418018-ef5ebd80-cf57-11eb-99dc-574fd13b3450.png)

**Comment by tmcconechy** [comment] 2021-06-17 14:46
Basically any information that would allow us to consistently reproduce the issue so we can verify a fix against it.
If the issue is shown in the demo app thats actually helpful. But im not understanding the steps to see it there? The screen shot seems ok to me.

If we could have steps to see it in the demo app (even if intermittent) that would be acceptable.

**Comment by stephanie-infor** [comment] 2021-06-28 18:18
Please see the instructions below. Let me know if this suffices.

1) Step 1 : Click on more icon
![Step1](https://user-images.githubusercontent.com/84295703/123684597-ab9f6a00-d81b-11eb-8d18-50d2c68a804e.png)

2) Step 2 : Click on outside of the card .
![step2](https://user-images.githubusercontent.com/84295703/123684605-ae01c400-d81b-11eb-9afe-586443e2abc0.png)

**Comment by tmcconechy** [comment] 2021-06-28 18:50
Normally: No not really because these comments are around reproducing it in your app. This makes it impossible harder to fix as we cant get to your code and try fixes and possibly even see your code.

So we usually ask for a reduced test case https://css-tricks.com/reduced-test-cases/

The easiest way to do this is take the relevant code from your app to reproduce it and put it in a stackblitz like this:

NG: https://stackblitz.com/edit/ids-quick-start-940
Not NG: https://stackblitz.com/edit/ids-enterprise-4520

From the images I think i can reproduce what your saying in the button on https://main-enterprise.demo.design.infor.com/components/popupmenu/example-index.html

But one thing is it is a feature if you focus the button that the tooltip shows. But maybe we can do something about that so it doesnt show after clicking if that is in fact the bug?

**Comment by tmcconechy** [comment] 2021-11-01 14:43
Closing as unable to reproduce

**Closed by tmcconechy** 2021-11-01 14:43 UTC
Labels: type: support :sos:, [5], status: clarification
