### ISSUE TITLE
Lookup: Paging unselects row when changing page size

### ISSUE THREAD

**Issue by AnaLauraMartinez** [infor-design/enterprise#5473] opened 2020-11-20 14:22 UTC
**Describe the bug**
When the user selects a row but changes page size, the selected row is unselected automatically

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/lookup/example-paging.html
2. Click on lookup
3. Select a row
4. Change the paging size from 5 to 10

**Expected behavior**
Grid should keep the selected row even when the grid is now bigger. 
Note that in a traditional GRID no lookup this does happen so we were expecting to be the same way in the lookup.

**Version**
- ids-enterprise-ng: 8.1.2

**Screenshots**
![image](https://user-images.githubusercontent.com/17933529/99810542-ddc44d00-2b11-11eb-90f7-167227afb586.png)
![image](https://user-images.githubusercontent.com/17933529/99810573-e87ee200-2b11-11eb-8723-b584639bf2d7.png)
![image](https://user-images.githubusercontent.com/17933529/99810602-f3d20d80-2b11-11eb-89f9-fa9af3adcf8f.png)

**Comment by andriivarhanov** [comment] 2021-08-04 12:57
@tmcconechy @jmacaluso711 I can't replicate the issue

https://master-enterprise.demo.design.infor.com/components/lookup/example-paging.html

- Click on lookup
- Select a row
- Modal closes
- Open modal again - row is still selected
- Change the paging size - row is still selected
- Tried with `autoApply` option turned off - same

Also

> Version
> ids-enterprise-ng: 8.1.2

Is it related to angular components? if so, I can't reproduce for angular components as well

Please let me know if I missed something

**Comment by tmcconechy** [comment] 2021-08-04 12:59
@AnaLauraMartinez I cant reproduce this either, the modal just closes when you select

**Comment by tmcconechy** [comment] 2021-08-11 15:35
Closing this as unable to reproduce

**Closed by tmcconechy** 2021-08-11 15:35 UTC
Labels: type: bug :bug:, status: cant reproduce, [3]

**Comment by AnaLauraMartinez** [comment] 2021-08-30 14:12
It seems that it is working now.
