### ISSUE TITLE
Calendar: Button is not aligned in Chrome browser when minimized 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2479] opened 2019-07-11 09:31 UTC
**Describe the bug**
Calendar: Button is not aligned in Chrome browser when minimized 

**To Reproduce**
1. OPen Chrome and Go to http://master-enterprise.demo.design.infor.com/components/calendar/example-index.html
2. Minimize the screen
3. Click day in the calendar a form should open 
4. Delete Date Values 
5. Maximize the screen vertically 

**Expected behavior**
Buttons , fields should be aligned

**Version**
Beta 4.20 

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/61039642-bdef2600-a401-11e9-9f02-7f4b0c6c465b.png)

**Platform**
Chrome Browsers

**Additional context**
NA

**Comment by tmcconechy** [comment] 2019-07-15 13:46
@janahintal I cant seem to reproduce this one. Is there any more steps you can provide me or clarify the above steps? @marknolaninfor Do you see this one?

**Comment by tmcconechy** [comment] 2019-07-16 18:30
Closing this as both me and @cindymecadoreyes could not reproduce

**Closed by tmcconechy** 2019-07-16 18:30 UTC
Labels: [3], status: cant reproduce, type: bug :bug:
