### ISSUE TITLE
Tabs header is cut off after scrolling in Mobile Devices

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2936] opened 2019-10-09 09:16 UTC
**Describe the bug**
Tabs header is cut off after scrolling in Mobile Devices

**To Reproduce**
1. Open Mobile Device browser 
2. Go to http://4220-beta0-enterprise.demo.design.infor.com/components/tabs-header/example-add-tab-button.html 
3. Scroll down

**Expected behavior**
Tab header should not be cut off

**Version**
Beta 4.22

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/66466020-8d786000-eab4-11e9-86ab-ee481a9a6c1e.png)

![image](https://user-images.githubusercontent.com/45757016/66466081-ac76f200-eab4-11e9-92df-c4cac91d8791.png)

**Platform**
Android and iOS devices

**Additional context**
N/a

**Comment by tmcconechy** [comment] 2019-10-09 13:09
Duplicate of #2800

**Closed by tmcconechy** 2019-10-09 13:09 UTC
