### ISSUE TITLE
Datagrid: Document datagrid's performance specs and limitations

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#1912] opened 2019-04-04 16:17 UTC
**Is your feature request related to a problem? Please describe.**
Document the datagrid components performance specs/limitations in relation to dataset sizes along with max rows/columns, etc.

**Describe the solution you'd like**
See https://github.com/infor-design/enterprise/issues/1905 for ideas on what to look for.
- Do some datagrid performance testing/experimentation
- Figure out the limitations on dataset sizes in combination with datagrid configurations before we consider performance a poor user experience
- Write that into the documentation to set the public expectation and limits of what our datagrid will support
- Add any tests to ensure that those standards are supported

**Describe alternatives you've considered**
n/a

**Additional context**
Please take your time and do not rush through this.

**Comment by tmcconechy** [comment] 2019-04-08 14:50
One place to focus on i think is the filter row. I think that this is expensive to render at the moment so i think the problem in the original issue may be the number of columns more than the number of rows. The problem is that components need to be invoked in all the header filter areas.

**Comment by tmcconechy** [comment] 2019-12-05 19:14
Closing this issue in favor of https://github.com/infor-design/enterprise/issues/3026 
Findings are https://github.com/infor-design/enterprise/issues/3026 , so approx 1000 rows per second. Anything over 2000 also has some lagging when scrolling.

So recommended paging be used at this time. Will look to add virtualization support as per https://github.com/infor-design/enterprise/issues/460 and https://github.com/infor-design/enterprise/issues/3026

**Closed by tmcconechy** 2019-12-05 19:14 UTC
Labels: [3], focus: datagrid, type: enhancement :sparkles:, type: support :sos:
