### ISSUE TITLE
Locale: Date Format of UK not working in WEBUI 4.0

### ISSUE THREAD

**Issue by bemariepedragosa** [infor-design/enterprise#3164] opened 2019-11-21 08:30 UTC
**Describe the bug**
Dates with UK format should be DD/MM/YYYY
In Rich client with UK locale set, it shows as DD/MM/YYYY
In 4.0, it shows as MM/DD/YYYY:

**To Reproduce**
1. Set Actor IsoLocale to en_GB
2. Set Localization Settings on Mingle
          Language = English(United Kingdom)
          Locale = English(United Kingdom)
3. Dates with UK format should be DD/MM/YYYY
4. Go to EmployeeSelfService > Take Notes
5. Check the date format.

**Expected behavior**
Dates with UK format should be DD/MM/YYYY

**Suggested Fix**
File: locale.js > parseDate
> pass current locale to calendar
var locale = this.currentLocale.name;
var thisLocaleCalendar = this.calendar(locale);

**Version**
IDS Enterprise Components - v4.23.0-rc.0

**Screenshots**
![image](https://user-images.githubusercontent.com/58026209/69320337-fb9b6f80-0c7b-11ea-9f30-ac482ed10cc2.png)

**Platform**
- OS Version: [e.g. Windows 10]
 - Browser Name [Chrome]
 - Browser Version [Version 78.0.3904.97 (Official Build) (64-bit)]

**Comment by tmcconechy** [comment] 2019-11-21 14:15
@bemariepedragosa The date format for en-GB is in fact https://github.com/infor-design/enterprise/blob/master/src/components/locale/cultures/en-GB.js#L16 `dd/MM/yyyy` so should be something in the way your doing it.

Can you attach a sample were we could debug and reproduce? Maybe you just need to do:

`Locale.set('en-GB')` at the start of your app to use this format (before initializing any components).

**Comment by bemariepedragosa** [comment] 2019-11-26 06:32
Hi @tmcconechy ,

I can replicate it on EmployeeService > Take Notes. I noticed that in locale.js > parseDate, we didn't pass the current locale. After passing the current locale, it works fine. See the code below:

File: locale.js > parseDate

pass current locale to calendar
var locale = this.currentLocale.name;
var thisLocaleCalendar = this.calendar(locale);

**Comment by tmcconechy** [comment] 2019-11-26 13:55
Ok perfect. thanks for the update. Closing...

**Comment by bemariepedragosa** [comment] 2019-11-26 14:02
Hi @tmcconechy ,
What I meant is, my suggested solution for this is to pass the locale to calendar. 
File: locale.js > parseDate

pass current locale to calendar
var locale = this.currentLocale.name;
var thisLocaleCalendar = this.calendar(locale);    << this change.

Thank you!

**Comment by tmcconechy** [comment] 2019-11-26 14:04
Not sure what that might break. I was never able to reproduce this issue. Can you work on a test case we can drop in and test for this issue?

**Comment by bemariepedragosa** [comment] 2019-11-26 14:17
Here are the steps to reproduce.

1. Set Actor IsoLocale to en_GB on Rich Client
2. If it is on Mingle environment, Set Localization Settings
    Language = English(United Kingdom)
    Locale = English(United Kingdom)

3. Go to EmployeeSelfService > Take Notes
4. Create Notes
5. Check the date format

![DATE_FORMAT_UK_4 0](https://user-images.githubusercontent.com/58026209/69641087-81fbeb00-109a-11ea-9e36-01c310c33557.PNG)

**Comment by tmcconechy** [comment] 2019-11-26 14:18
Not sure how i can run those steps. What i mean is a reduced test case. So we can drop it in our project and run it.

**Comment by bemariepedragosa** [comment] 2019-11-26 14:42
You can reproduce it here > https://adm-ghrbs1ahy4-ax1.tam.awsdev.infor.com/hcm/EmployeeSelfService/home?csk.developer=true&csk.ng=true

Go to Settings > Display Apps > In 4.0 > Save. 
Go to Take Notes

**Comment by tmcconechy** [comment] 2019-11-26 14:45
This isnt ideal. We usually ask for a reduced test case so we can have a test in our project and not operate of application code for bugs. I can look at it tho. How do i do this?

1. If it is on Mingle environment, Set Localization Settings ?

**Comment by bemariepedragosa** [comment] 2019-11-26 14:50
You can reproduce it here > https://adm-ghrbs1ahy4-ax1.tam.awsdev.infor.com/hcm/EmployeeSelfService/home?csk.developer=true&csk.ng=true

Go to Settings > Display Apps > In 4.0 > Save.
Go to Take Notes

**Comment by tmcconechy** [comment] 2019-11-26 14:52
I'm sorry but your steps are unclear.

1) How do i login? (If you need to ping me this info on teams so as not to post passwords in public)
2) How do i change the locale the way i am supposed to see the issue?
3) What am i looking at ? Expected  vs Not expected?

**Comment by bemariepedragosa** [comment] 2019-11-26 15:11
1. Login Credentials
    tm.infor.ad1@gmail.com/L@wson123
2. Current locale for this user is en_GB (UK). (Currently can't access the Mingle User Setting page)
3. The date should be 18/11/2019 instead of 11/18/2019
![DATE_FORMAT_UK_4 0](https://user-images.githubusercontent.com/58026209/69644938-50861e00-10a0-11ea-89c7-998339aa877f.PNG)

**Comment by tmcconechy** [comment] 2019-11-26 15:34
Ok, i was able to login and look but still it looks correct to me. Following your steps after getting to the notes page try to run this in the console:

```
Soho.Locale.currentLocale.name  //"en-GB" as expected
Soho.Locale.calendar().dateFormat //{separator: "/", timeSeparator: ":", short: "dd/MM/yyyy", medium: "d MMM yyyy", long: "d MMMM yyyy", …}
```

So the locale data we have does show the short format as `dd/MM/yyyy` which i confirmed with a UK resource is correct for en-GB. So still not seeing a bug.

**Comment by bemariepedragosa** [comment] 2019-11-27 10:26
Thank you @tmcconechy .

**Closed** 2019-11-27 10:25 UTC
Labels: [∞], status: cant reproduce, type: bug :bug:

**Comment by nbcp** [comment] 2019-12-04 01:26
@tmcconechy I believe this is a legitimate issue, tested with the latest version 4.23.0

**Comment by nbcp** [comment] 2019-12-04 02:28
Okay, it looks like the issue originates from this change on #2368:
![image](https://user-images.githubusercontent.com/11013464/70106772-7e122f00-167f-11ea-9b49-b432d764da0f.png)
So what happens for 'en-GB', it goes thru the 1st if block setting `resolveToParent = true` then in the 2nd if block, it will be passed as 2nd argument making `isCurrent = false` for `appendLocaleScript()` which then ends without calling `setCurrentLocale()` onload of **en-GB.js**

So I'm thinking the previous condition should be the correct one since 'en-US' is already being added thru this if block:
```
if (locale && locale !== 'en-US' && !this.cultures['en-US']) {
  this.appendLocaleScript('en-US', false);
}
```
Or do we need that for setting other parent locales besides 'en-US'?

**Comment by nbcp** [comment] 2019-12-04 02:50
The code has changed since ver. 4.19.0 so now not sure what condition do we really need for this, (or rather what do really want from these conditions?) but the issue is still due to **en-GB.js** failing to call `setCurrentLocale()` during onload.

**Comment by tmcconechy** [comment] 2019-12-04 14:02
Ok, this issue was a bit confusing. Let's make a new issue centered around your test case. Can you make it @nbcp ?

One thing remains unclear when I saw your example but the format is correct in it , its showing dd/MM/yyyy as per the correct value for en-GB locale.

I do see it appending the scripts more than once though. Which could potentially be fixed.

Will take a look at the new issue and information when you add it.

**Comment by bemariepedragosa** [comment] 2019-12-04 14:29
Hi @tmcconechy ,
On @nbcp 's example, you can see the correct format on the first load. But when you try to refresh the page, you can see the incorrect format (mm/dd/yyyy) for en-GB locale.

**Comment by tmcconechy** [comment] 2019-12-04 14:57
Ok i see. Ok this helps. Created issue https://github.com/infor-design/enterprise/issues/3208 with this info to clean this all up.

**Comment by bemariepedragosa** [comment] 2019-12-04 14:58
Thanks @tmcconechy

**Comment by tmcconechy** [comment] 2019-12-04 19:09
fixed on PR https://github.com/infor-design/enterprise/pull/3210
