### ISSUE TITLE
Tabs: Focus in the new tab is overlapping the next tab and cut off for long tab names

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2929] opened 2019-10-09 06:15 UTC
**Describe the bug**
Tab focus in the new tab is overlapping the next tab

**To Reproduce**
1. Go to http://4220-beta0-enterprise.demo.design.infor.com/components/tabs/example-add-tab-button.html
2. Populate the Tab Name field "TEST"
3. Populate the Tab Content field "TEST"
4. Leave the Tab Index Blank
5. Click '+' Add tab button
5. Also try to create a Long Tab name 

**Expected behavior**
Focus should be in the new added tab and should not overlap other tabs and should not be cut off for long tab names

**Version**
Beta 4.22

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/66455813-67e05c00-ea9e-11e9-9dc8-a7b4501d49e4.png)

![image](https://user-images.githubusercontent.com/45757016/66456298-d671e980-ea9f-11e9-8180-b30dd0374fce.png)

**Platform**
All Browser, OS and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment] 2019-10-09 13:18
Tested this back to 4.18 and the issue has been in for a while. Will fix at a later date time permitting.

**Comment by tmcconechy** [comment] 2021-02-25 15:08
This is a duplicate of https://github.com/infor-design/enterprise/issues/4877

**Closed by tmcconechy** 2021-02-25 15:08 UTC
Labels: [3], type: bug :bug:
