### ISSUE TITLE
"More" menu layout issue in iOS

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2829] opened 2019-09-24 09:18 UTC
**Describe the bug**
Page header's "More" menu layout issue in iOS.

**To Reproduce**
1. Open browsers (Safari and Chrome) in iPhone 
2. Go to http://latest-enterprise.demo.design.infor.com/ 
3. Click the More (...) button in header
4. See issue: menu will open but with a layout issue

**Expected behavior**
Menu should be properly displayed.

**Version**
- ids-enterprise: v4.21.0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/65498681-e9f15200-deee-11e9-9f37-1c307a858121.png)

**Platform**
 - Device: iPhone
 - Browsers: Safari and Chrome

**Additional context**
N/A

**Comment by tmcconechy** [comment] 2019-09-24 13:51
Duplicate of #2800

**Closed by tmcconechy** 2019-09-24 13:51 UTC
