### ISSUE TITLE
Validation: Issues with checkbox validation

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#3147] opened 2019-11-19 19:04 UTC
**Describe the bug**
A checkbox set as a required field is not working correctly with validation. There seem to be three issues:
1. When tabbing through fields on a form, the checkbox does not validate and an error message is not displayed.
2. When a checkbox is required and checked, the check mark does not display correctly.
3. When a checkbox is in error, scrollIntoView() does not work.

The example file below is from the validation directory and has been modified to include a checkbox.

[example-multiple-errors.zip](https://github.com/infor-design/enterprise/files/3865575/example-multiple-errors.zip)

**To Reproduce**
Steps to reproduce the behavior for issue 1 above:
1. Unzip the attached example-multiple-errors.html to app/views/components/validation
2. Go to http://localhost:4000/components/validation/example-multiple-errors.html
3. Adjust your screen size so the checkbox is off-screen
4. Scroll down to see all the fields
5. Place your cursor into the Username field and tab through all of the fields
6. All fields except the Checkbox field display a 'Required' error message

Steps to reproduce the behavior for issue 2 above:
1. Refresh your browser
2. Go to http://localhost:4000/components/validation/example-multiple-errors.html
3. Scroll to the Checkbox field
4. Check the Checkbox field
5. The check mark does not display in the checkbox; it is incorrectly located next to the red asterisk

Steps to reproduce the behavior for issue 3 above:
1. Refresh your browser
2. Go to http://localhost:4000/components/validation/example-multiple-errors.html
3. Adjust your screen size so the checkbox is off-screen
4. Scroll down to see all the fields
5. Check and uncheck the Checkbox field
6. The Checkbox field should display a 'Required' error message
7. Scroll up to hide the Checkbox field
8. Select the Info icon on the banner right corner and click the 'go to' link
9. The Checkbox field does not scroll into view and is not in focus
10. Test the other fields for this behavior (refresh your browser in between) and they will scroll into view

**Expected behavior**
The expectation is:
1. Validation for a checkbox will execute when tabbing through the fields
2. The checkbox displays correctly when checked and required
3. The checkbox will scroll into view when scrollIntoView() is executed

**Version**

- ids-enterprise: v4.23.0-rc.0

**Screenshots**
![validation-checkbox-issue](https://user-images.githubusercontent.com/20212079/69177389-082d9580-0acd-11ea-910d-cd1288806db8.gif)

**Platform**
 - All

**Additional context**

**Comment by tmcconechy** [comment] 2019-11-19 19:14
Always wonder about required checkboxes. What makes it required? That you have to click it?
Then why not set it? Do you have a concrete use case?

Anyways i dont think much work has been done on them so i can imagine this being an issue.

**Comment by fitzorama** [comment] 2019-11-19 20:08
For Landmark, the validation takes place on the server, so an error is returned indicating based on other input, a checkbox is required. We set the error, but are running into issue 3 where the scrollIntoView() does not work. The other two issues were found creating the example.

**Comment by CindyMercadoReyes** [comment] 2020-02-03 17:23
Moving this ticket to QA failed do to the  check marker for "Required" having alignment issues on the uplift theme. Please see screen shot below.
![Checkbox alignment issue](https://user-images.githubusercontent.com/39101346/73675144-e7aeb980-467f-11ea-9200-8530e624414f.png)

**Comment by tmcconechy** [comment] 2020-02-06 19:46
Added an additional fix for the failed QA case

**Closed by tmcconechy** 2020-02-06 19:46 UTC
Labels: [2], team: landmark, type: bug :bug:

**Comment by jbrcna** [comment] 2020-02-07 11:05
QA FAILED. IDS v4.26.0-dev
Verified in https://master-enterprise.demo.design.infor.com/components/checkboxes/example-index.html
**Firefox / Uplift**
![image](https://user-images.githubusercontent.com/56722184/74024020-ec56d300-49db-11ea-92ad-6b3f6f84a445.png)

**iOS / Uplift**
![image](https://user-images.githubusercontent.com/56722184/74024150-2b852400-49dc-11ea-92b5-14ff3f74fac8.png)

**Comment by jbrcna** [comment] 2020-02-11 06:43
The issue is now resolved. moving this ticket to done.
