### ISSUE TITLE
[All Browsers] Color Picker-Modal: Color palette doesn't close when you don't change the color

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#491] opened 2018-07-24 19:15 UTC
**Describe the bug**
[All Browsers] Color Picker-Modal: Color palette doesn't close when you don't change the color

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/colorpicker/test-modal.html
2.  Open the color picker modal
3.  Don’t change the color in the color picker
4.  Click on the down arrow key and don't click anything in the color palette
5. The “Set Color” window will closes, however the color palette doesn't close. Please see screen shots attached.

**Expected behavior**
The Set Color modal and the color palette should close

Also..
1.  Open the color picker modal
1. open the color picker
1. hit esc

**Expected behavior**
(should not close)

**Screenshots**
![color picker screen shot 2](https://user-images.githubusercontent.com/39101346/43160830-489de232-8f54-11e8-8d31-883e5006b4b9.png)
![color picker screen shot 1](https://user-images.githubusercontent.com/39101346/43160831-48a83e12-8f54-11e8-8513-86f72857e773.png)

**Platform**
 - All Browsers 

**Additional context**
None.

**Comment by tmcconechy** [comment] 2018-07-24 19:21
Not sure if I totally follow the steps here? Specifically

Don’t change the color in the color picker
Click on the down arrow key and don't click anything in the color palette

I tried this
- open the modal
- focus the first input
- down arrow a few times and select a color
- hit enter

It works as expected. Is that what you mean? Maybe clarify the steps..

**Comment by ericangeles** [comment] 2018-07-25 04:42
I actually reproduced the issue in the given steps. Upon opening the modal, it automatically focus the first input, then I just press the down arrow key multiple times. I also tried upper arrow and it produced the same issue. Not sure if it's because of the delay or having a settimeout that causes the issue.

**Comment by tmcconechy** [comment] 2018-07-25 13:35
I still dont see it. Can someone clarify the precise steps.

**Comment by tmcconechy** [comment] 2018-07-26 13:44
Ok my mistake i see it now. I was using the arrow key not clicking the arrow.

**Comment by davidcarlsonberg** [comment] 2018-08-23 17:20
Quick question: is there a reason that `.colorpicker .is-open` should not close on click of `span.trigger`? This added functionality of calling the keydown event is interfering with `.colorpicker` in `.modal` as described in this ticket and all I can see it doing currently is disallowing the closing of `.colorpicker.is-open` on click of `.trigger`.

colorpicker.js line 324
```
toggleList() {
  // code
    if (menu.length) {
      $(document).trigger($.Event('keydown', { keyCode: 27, which: 27 })); // escape

      if (this.isPickerOpen) {
        return;
      }
    }
  // code
}
```

**Comment by davidcarlsonberg** [comment] 2018-08-23 18:25
It works better without, I think. Though. ESC has never closed just the colorpicker since I've been looking at it. Single ESC keypress closes both colorpicker and parent (modal).

**Comment by EdwardCoyle** [comment] 2018-08-23 19:27
I'm not 100% on whether this worked the way the issue describes it (closing of a colorpicker inside of a modal on ESC keypress number 1, then closing the modal on keypress number 2).  If removing that snippet works better, I say go for it and try to fix the keypress functionality.

We have similar functionality implemented inside the Modal that accounts for Dropdown components [here](https://github.com/infor-design/enterprise/blob/master/src/components/modal/modal.js#L597).  Might just need to add this for any kind of open popupmenus and popovers as well.

Also see the code for pressing keycode 27 (ESC) [here](https://github.com/infor-design/enterprise/blob/master/src/components/modal/modal.js#L761)

**Closed** 2018-08-24 12:45 UTC
Labels: [3], type: bug
