### ISSUE TITLE
Locale: Incorrect M/d/yyyy HH... entries in it-IT.js. Should be dd/MM/yyyy HH...

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#4333] opened 2020-09-02 07:48 UTC
Incorrect M/d/yyyy HH... entries in it-IT.js. Should be dd/MM/yyyy HH...

Screenshot attached (end result: incorrect date format in GRC)

![it-IT](https://user-images.githubusercontent.com/66057969/91953014-5b41a380-ed01-11ea-870e-886c6882d95e.png)

**Comment by tmcconechy** [comment] 2020-09-02 13:17
This is a duplicate of https://github.com/infor-design/enterprise/issues/4297 and has been fixed in 4.32

**Closed by tmcconechy** 2020-09-02 13:17 UTC
Labels: [1], status: duplicate, type: bug :bug:
