### ISSUE TITLE
Text Input Field: Required fields focus is not working in Windows 10 IE11

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4136] opened 2020-07-10 10:32 UTC
**Describe the bug**
Text Input Field: Required fields focus is not working in Windows 10 IE11

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/
2.  In the Text Input section leave the Last Name blank and click tab
3.  Notice that the field didn't display as required. 

**Expected behavior**
The field should turn red & mark as required

**Version**
4.31.0 - dev 

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/87145272-a3cd7980-c2db-11ea-8b9f-5b1f35d54fe0.png)

**Platform**
Windows 10 IE 11

**Additional context**
N/a

**Comment by tmcconechy** [comment] 2020-07-10 13:22
Seems like the issue is the deploy is not working because master is from 07/01. Looking into it

**Comment by tmcconechy** [comment] 2020-07-10 14:26
Was a temporary issue (older version with all the IE errors there) and is fixed now.

**Closed by tmcconechy** 2020-07-10 14:26 UTC
Labels: [2], type: regression bug  :leftwards_arrow_with_hook:

**Comment by CindyMercadoReyes** [comment] 2020-07-13 19:27
This issue is now resolved.
