### ISSUE TITLE
Tabs: The contents in Dropdown tab is not disabled after clicking disable all control button 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3304] opened 2020-01-07 15:19 UTC
**Describe the bug**
Tabs: The contents in Dropdown tab is not disabled after clicking disable all control button 

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/tabs/example-enable-disable.html#programmatic-tabs-disabled
2. Click the Dropdown Tab 
3. Select any Tab 
4.  Click disable entire tab control button 

**Expected behavior**
All content and fields should look disabled 

**Version**
4.31 beta 

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/71905639-84765800-31a3-11ea-92c4-8d0a84cf43f9.png)

**Platform**
All OS, Browser and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment] 2020-01-07 15:23
This is super minor - demo app issue. The problem is those tabs only have text. What we could do is apply a style to the text to make it look disabled but its not actionable anyways.

So for now will leave this open and we probably close it someday if we dont get to it

**Comment by tmcconechy** [comment] 2020-02-25 19:32
Descoping this for now

**Closed by tmcconechy** 2020-02-25 19:32 UTC
Labels: [2], priority: minor, type: demo-app bug :beetle:
