### ISSUE TITLE
Datagrid: Selected record turns unselected after switching page

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5140] opened 2021-04-27 12:28 UTC
**Describe the bug**
Datagrid: Selected record turns unselected after switching page

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-grouping-paging.html
2. Select all in  the first page 
3. Switch page
4. Go back to the first page
Notice that the selected records did not remain selected

**Expected behavior**
Selected records should be selected. 

**Version**
4.51 - ids

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/116241104-20601480-a797-11eb-88ad-1f021f4839d3.png)

**Platform**
All major browser & devices

**Additional context**
N/a

**Comment by tmcconechy** [comment] 2021-04-27 13:13
This particular example is set to reset the selections on changing page. This example https://main-enterprise.demo.design.infor.com/components/datagrid/test-paging-multiselect-select-across-page.html will show that feature/setting.

Closing as not a bug

**Closed by tmcconechy** 2021-04-27 13:13 UTC
Labels: [2], status: wont fix :no_entry_sign:, type: bug :bug:
