### ISSUE TITLE
Donut: Legends are NOT appearing at the bottom

### ISSUE THREAD

**Issue by guptaruchi-github** [infor-design/enterprise#5275] opened 2021-06-07 08:35 UTC
**Describe the bug**
Donut legends are NOT appearing at the bottom when legend Placement is set to bottom.

**To Reproduce**

1. Make a component that uses soho-pie as a viewchild
2. Use code below

`<div class="indicators-chart" soho-pie (selected)="onSelected($event)" [legend]="legendOptions" [isDonut]="true" [dataset]="dataSet" [showLegend]="true" [legendPlacement] ="'bottom'" *ngIf="showDonut">`

**Expected behavior**
Donut legends should appear at the bottom of the chart.

**Version**
- ids-enterprise-ng : 9.1.1

**Screenshots**
![image](https://user-images.githubusercontent.com/85481652/120982141-ff2b1480-c795-11eb-891c-87ac7d550664.png)

**Platform**
OS Version: Windows 10 or iOS 8
Browser Name: Chrome
Browser Version: 91.0.4472.77

**Comment by tmcconechy** [comment] 2021-06-07 13:18
Did you try `[legendPlacement] ="bottom"`  ? Do you have a stackblitz for this example?

**Comment by tmcconechy** [comment] 2021-06-07 13:35
![Unknown](https://user-images.githubusercontent.com/814283/121025922-aa76a200-c773-11eb-9492-b532d545d623.png)

As an addition to this issue we can make a button that opens a popup to show all the legend items in the case there is so many the legends dont fit

**Comment by guptaruchi-github** [comment] 2021-06-08 07:29
Strangely it started working with [legendPlacement] ="'bottom'" itself. Though legends are not rendered properly. Please see screenshot below:
![image](https://user-images.githubusercontent.com/85481652/121142177-5b0aa180-c859-11eb-9f83-0048787e39c4.png)

**Comment by tmcconechy** [comment] 2021-06-08 13:16
Yes we should look at the legend formatting. This is an accepted bug and we will schedule the work in the future.

**Comment by ericangeles** [comment] 2021-06-15 10:03
@yohannahbautista I guess the only issue now here is the rendering of UI.

**Comment by tmcconechy** [comment] 2021-06-15 12:44
Yes, the issue is the bottom alignment however its a bit more complicated. When fixing design would like https://github.com/infor-design/enterprise/issues/5292 as well which is a icon menu button that opens a popupmenu that shows the overflow of bottom legend items. So https://github.com/infor-design/enterprise/issues/5292 would go with this fix.

We could even close this one in favor of https://github.com/infor-design/enterprise/issues/5292 as it will solve this. Your welcome to work on this as it was priority.

**Comment by ericangeles** [comment] 2021-06-15 12:54
Will assign to her the #5292.

**Comment by tmcconechy** [comment] 2021-06-15 12:56
ok lets close this and work off https://github.com/infor-design/enterprise/issues/5292

**Closed by tmcconechy** 2021-06-15 12:56 UTC
Labels: [3], team: ln, type: bug :bug:
