### ISSUE TITLE
Icons: Translate icon has wrong color in toolbar

### ISSUE THREAD

**Issue by whernebrink** [infor-design/enterprise#5985] opened 2022-01-03 13:50 UTC
**Describe the bug**
When adding a button with icon in a toolbar, the translate icon has the wrong color.

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-enterprise-10110-ucc8qo?file=src%2Fapp%2Fheader%2Fheader.component.html
2. See toolbar with buttons with icons where the translate icon has wrong color

**Expected behavior**
Translate icon should have same color as the other icons.

**Version**

- ids-enterprise: 4.58.0

**Screenshots**
![image](https://user-images.githubusercontent.com/73601152/147937899-9ca57ebe-2198-4350-936c-47a70340e7ab.png)

**Platform**
 - Infor Application/Team Name: Infor M3
 - OS Version: OSX
 - Browser Name: Firefox and Chrome

**Additional context**
Here is a [Stackblitz](https://stackblitz.com/edit/ids-enterprise-10110-ucc8qo?file=src%2Fapp%2Fheader%2Fheader.component.html)

I _think_ this was working previously, but not 100% sure.

**Comment by tmcconechy** [comment] 2022-01-03 14:39
@whernebrink this is a duplicate of https://github.com/infor-design/enterprise/issues/5870 and yes it was working until design changed the icon. Trying to get them to take a look.

Will close the duplicate so watch that one?
Thanks

**Closed by tmcconechy** 2022-01-03 14:39 UTC
Labels: [2], status: duplicate
