### ISSUE TITLE
Example does not work due to CORS

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise#637] opened 2018-08-21 15:47 UTC
**Describe the bug**
Example does not work due to CORS error

**To Reproduce**
Go to this page for instance
https://design.infor.com/code/ids-enterprise/latest/demo/autocomplete/example-index?font=source-sans

**Expected behavior**
It should display some results as I type

**Screenshots**
https://i.imgur.com/PPB1KrE.png

**Comment by tmcconechy** [comment] 2018-08-21 15:50
This is a duplicate of https://github.com/infor-design/website/issues/628 and is due to the redirects on that site. As a workaround you can look at the versioned sites to check it out.

http://master-enterprise.demo.design.infor.com/components/autocomplete/example-index?font=source-sans

http://490-enterprise.demo.design.infor.com/components/autocomplete/example-index?font=source-sans

**Closed by tmcconechy** 2018-08-21 15:50 UTC
