### ISSUE TITLE
Tree/Datagrid: Grid Header and try allows html to be inserted not just text

### ISSUE THREAD

**Issue by brianpettit** [infor-design/enterprise#5260] opened 2021-06-02 19:02 UTC
I am using a datagrid and when I pass a datasource including `<button onclick="alert('hi')">hi</button>` for a column header, I see "hi" and it's clickable.  Upon clicking, the alert box is shown.

I see this inside a tree component as well.

**Comment by tmcconechy** [comment] 2021-06-02 19:17
@brianpettit when making issues can you please use the issue template here is the markup so you can edit it https://github.com/infor-design/enterprise/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

But normally if you press issues -> new issue there is a template to fill out for this one i need to know more.. I don't really understand what you mean here. So basically need steps to reproduce / example code of what your putting in so i can see whats going on

**Comment by brianpettit** [comment] 2021-06-02 19:36
Not sure what else I can say.  Do you have a sample datagrid I can mess with in stackblitz?  I don't really know how to give you repro steps otherwise?

**Comment by tmcconechy** [comment] 2021-06-02 19:40
I think all i really need is maybe a snippet of where yout put it i guess. Like the code for the grid column and the code for the tree you passed in. I can probably work with that.

But for future take a look at using the template as its really helpful for us and seems like you maybe didnt see it

**Comment by brianpettit** [comment] 2021-06-02 19:53
Go into datagrid-demo-service.ts

Use this "name" in the activity column.

    this.columns.push({
      id: 'activity',
      name: `<button onclick="alert('hi')">hi</button>`,
      filterType: 'text',
      field: 'activity',
      textOverflow: 'ellipsis'
    });

In our code, this is dynamic and comes from external sources.

**Comment by tmcconechy** [comment] 2021-07-29 15:48
Noticed this is a duplicate of https://github.com/infor-design/enterprise/issues/5428
Fixing it this sprint

**Closed by tmcconechy** 2021-07-29 15:48 UTC
Labels: [2], status: duplicate, type: bug :bug:
