### ISSUE TITLE
Pager: standalone checkboxes not working after changing pagesize

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#5664] opened 2021-09-28 08:56 UTC
**Describe the bug**
when you select a pagesize/ # of records per page the checkboxes are not working

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/pager/example-standalone.html
2. Tick any checkboxes
3. Tick `Show Page Size Selector` checkbox
4. Change Records per page
5. Try to check/uncheck the checkboxes.
6. See error

**Expected behavior**
should be able to check/uncheck the checkboxes even after change in pagesize

**Version**

- ids-enterprise: v4.56.0-dev

**Screenshots**
![Large GIF (552x510)](https://user-images.githubusercontent.com/56722184/135055365-af8e1203-f38c-4346-ae7a-6c84fe2332b0.gif)

**Platform**
all

**Additional context**

**Comment by tmcconechy** [comment] 2021-09-28 14:04
Duplicate of https://github.com/infor-design/enterprise/pull/5652 (or will be fixed by it once merged)

**Closed by tmcconechy** 2021-09-28 14:04 UTC

**Comment by jbrcna** [comment] 2021-09-30 03:07
this is now working as expected. thanks @tmcconechy . 
v4.56.0-dev
![Large GIF (552x510)](https://user-images.githubusercontent.com/56722184/135379339-25dc38f8-bf6d-4cc8-b016-7e82a70c5114.gif)
