### ISSUE TITLE
Autocomplete Component: Cursor appearing in the middle of the field box

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#2417] opened 2019-06-20 18:07 UTC
**Describe the bug**
Autocomplete Component: Cursor appearing in the middle of the field box

**To Reproduce**
1. Go to url: https://4193-rc0-enterprise.demo.design.infor.com/
2. Change them to Dark
3. Scroll down to Autocomplete
4. In the States field box type in "New"
5. Select New Jersey from the list box. 
6. You will see the cursor appear in the middle of the field box. Please see screen shot attached. 

**Expected behavior**
The Cursor should not appear in the middle of the field box.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.19.rc0]

**Screenshots**
![bs_win10_IE_11 0 (3)](https://user-images.githubusercontent.com/39101346/59871092-bd182680-9364-11e9-9f79-69554cd6a26a.jpg)

**Platform**
 - OS Version: [Windows 10]
 - Browser Name [IE 11]

**Additional context**
None

**Comment by tmcconechy** [comment] 2019-06-20 18:09
Duplicate of #1129

**Comment by tmcconechy** [comment] 2019-06-20 18:12
I see this issue now even tho #1129 is closed. Consider this minor

**Comment by tmcconechy** [comment] 2020-04-21 20:48
Descoping this issue for now see https://github.com/infor-design/enterprise/issues/3026

**Closed by tmcconechy** 2020-04-21 20:48 UTC
Labels: [2], priority: minor, type: bug :bug:
