### ISSUE TITLE
SohoDataGridComponent - toggleRowSelected() sometimes returns inconsistent results

### ISSUE THREAD

**Issue by matt-sciaretta-infor** [infor-design/enterprise#4796] opened 2021-02-01 21:17 UTC
**Describe the bug**
Hi all, I am working on Stratus and ran across a little bug. The bug is in the SohoDataGridComponent - sohoxi.js - toggleRowSelection(). 

When first adding a new row, the row is marked as "selected". Next, a user would click into the row to add data. The toggleRowSelection() is called and the row is then deselected, even though the row is still technically selected. 

Another way to trigger the behavior is to click in the row editor, then click outside of the datagrid, then click back on the same row editor - it will toggle from selected to unselected each time you click in the same row editor.  thanks

**To Reproduce**
**_I am unable to add a direct link to our environment, but whomever ends up assigned to this - feel free to reach out to me in teams and I can share my screen and reproduce it._** 

**Expected behavior**
In toggleRowSelected() it would be better if it's a single select (not multiselect) to cycle through the rows and deselect all of them before adding the selected status. 

**Version**

- ids-enterprise: **9.1.0**

**Screenshots**

**Platform**
 - Infor Application/Team Name: Stratus
 - Device: pc laptop
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: Version 88.0.4324.104 (Official Build) (64-bit)

**Comment by tmcconechy** [comment] 2021-03-04 14:37
@matt-sciaretta-infor is there anyway you can make an example to reproduce the issue perhaps you can use https://stackblitz.com/edit/ids-quick-start-910 to make an issue

**Comment by tmcconechy** [comment] 2021-03-23 13:42
@matt-sciaretta-infor did we resolve this offline? Im not sure if we need a way to reproduce this. Perhaps you can use my stackblitz and make a reproduction https://stackblitz.com/edit/ids-quick-start-930 or if a call is needed to help make a reproduction ping me in MS teams.

Marking as cant reproduce for now

**Comment by matt-sciaretta-infor** [comment] 2021-03-23 18:48
Thanks Tim,
I’m still working on it on my end. I’ll reach out if I need further help.

**Comment by tmcconechy** [comment] 2021-06-09 13:40
Closing this for now. But if you have the steps to reproduce we can reopen

**Closed by tmcconechy** 2021-06-09 13:40 UTC
Labels: [3], status: cant reproduce, team: stratus, type: bug :bug:
