### ISSUE TITLE
Contextual Action Panel: example-jquery - sort issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3066] opened 2019-11-04 10:05 UTC
**Describe the bug**
The 'Amount' column can only sort the first digit instead of the whole amount.

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/contextualactionpanel/example-jquery.html'
2. Click on 'Contextual Action Panel (Uses JQuery Settings)'
3. Click the 'Amount' header to sort

**Expected behavior**
should sort accordingly

**Version**
4.23

**Screenshots**
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/56722184/68111560-5f0e6900-ff2a-11e9-924b-665e9a069c79.png">

**Platform**
ALL

**Additional context**

**Comment by tmcconechy** [comment] 2019-11-04 14:16
Made a quick fix for this issue we can retest. Will push with current PR.
The problem was the data was actually strings. So not a bug just a funny example

**Closed by tmcconechy** 2019-11-04 14:16 UTC
Labels: [1], type: demo-app bug :beetle:

**Comment by jbrcna** [comment] 2019-11-26 04:26
**QA PASSED**
Verified in http://master-enterprise.demo.design.infor.com/components/contextualactionpanel/example-jquery.html accross all browser and both android & iOS devices. moving this to DONE
