### ISSUE TITLE
DataGrid: Cannot see more than 3 buttons in a grid toolbar

### ISSUE THREAD

**Issue by pooBadiger** [infor-design/enterprise#6921] opened 2022-10-26 08:47 UTC
**Describe the bug**
In a data grid, not able to see more than 3 buttons in a grid toolbar. 

- Add more than 3 buttons inside a soho-toolbar.

 `<soho-toolbar class="contextual-toolbar is-hidden">
            <soho-toolbar-title>
                <div soho-selection-count>{{ "REGISTRY.ZERO_SELECTED" | transloco }}</div>
            </soho-toolbar-title>
            <soho-toolbar-button-set>
                 <button class="btn">
                    <svg class="icon">
                        <svg soho-icon icon="edit"></svg>
                    </svg>
                </button>..............
                 ....<add more than 3 buttons>
</soho-toolbar-button-set>`

**Expected behavior**
- Grid toolbar should show all the added buttons.

**Version**
"ids-enterprise-ng": "13.4.0",

**Screenshots**
![image](https://user-images.githubusercontent.com/93663725/197978748-5589aec8-becd-4d43-a287-b953a32aef5d.png)

**Platform**
 - Infor Application/Team Name: Infor Process intelligence/ Infor PI
 - Device:  Dell laptop
 - OS Version: Windows 11 Enterprise
 - Browser Name: chrome
 - Browser Version: Version 106.0.5249.119 (Official Build) (64-bit)

**Comment by tjamesallen15** [comment] 2022-12-28 03:26
Hello @pooBadiger, I'm trying to reproduce your issue but to no avail. Can you check my screenshots below.

This was screenshot from IDS Main
![image](https://user-images.githubusercontent.com/34049950/209752497-13d76244-bf95-455b-bcb3-73c4183a2d2e.png)

This was screenshot from IDS Angular
![image](https://user-images.githubusercontent.com/34049950/209752553-890bc049-48df-4d1f-a5c3-0436be4b69de.png)

How were you able to reproduce the issue? 

cc @tmcconechy @ericangeles

**Comment by tmcconechy** [comment] 2022-12-28 15:03
I was at the time @tjamesallen15 but maybe we just needed `maxVisibleButtons` set? Can you try to see if it works with a toolbar-flex. I was thinking the problem is a toolbar-flex doesn't work here in contextual toolbar.

So if we make this about sorting toolbar-flex that would be best as the old toolbar has limitations....

@pooBadiger maybe you can try `maxVisibleButtons` as an example

**Comment by pooBadiger** [comment] 2023-01-03 10:31
**maxVisibleButtons** helped! That works! thanks!

**<soho-toolbar class="contextual-toolbar is-hidden" [maxVisibleButtons]="5">**

**Comment by tmcconechy** [comment] 2023-01-03 14:42
ok since we have a lot of items lets push the flex box to next version since we have a way to make this work now.

**Comment by tmcconechy** [comment] 2023-03-10 14:52
To clarify: Make contextual toolbar work with only flex toolbar. Make an example with 5 buttons and ensure it works

**Comment by janahintal** [comment] 2023-03-30 12:21
Hi @tjamesallen15 , noticed that some buttons disappear with no way to click it when in responsive mode. 
![image](https://user-images.githubusercontent.com/45757016/228834018-da3bb32d-f57a-4e0f-80b2-5d182bf3033f.png)

**Comment by tjamesallen15** [comment] 2023-03-31 05:47
> Hi @tjamesallen15 , noticed that some buttons disappear with no way to click it when in responsive mode. ![image](https://user-images.githubusercontent.com/45757016/228834018-da3bb32d-f57a-4e0f-80b2-5d182bf3033f.png)

![image](https://user-images.githubusercontent.com/34049950/229033732-4ed46a37-9247-404c-9d94-0bc6a7cd7996.png)
Hello, this was the screenshot on my end. Cannot reproduced based on your screenshot.

**Comment by tmcconechy** [comment] 2023-03-31 13:11
The button issues with color will likely be fixed by https://github.com/infor-design/enterprise/pull/7363

**Closed** 2023-04-05 11:15 UTC
Labels: type: bug :bug:, [3]
