### ISSUE TITLE
Pop over: Extra Css Class - Layout Issue on IE 11

### ISSUE THREAD

**Issue by johnbarcena** [infor-design/enterprise#2953] opened 2019-10-10 11:04 UTC
**Describe the bug**
No details are shown after you click the button several times or switch themes. 

**To Reproduce**
1. Go to 'http://4220-beta0-enterprise.demo.design.infor.com/components/popover/example-extra-css-class.html'
2. Click on 'button'
3. Click on 'button' again then verify pop over
4. Refresh
5. Click on 'button'
6. Change Theme
7. Click on 'button' again then verify pop over

**Expected behavior**
should display details

**Version**
4.22 Beta

**Screenshots**
![image](https://user-images.githubusercontent.com/52902639/66563267-05678880-eb90-11e9-991e-93edd1bda117.png)

**Platform**
IE 11

**Additional context**
related to #1577

**Comment by tmcconechy** [comment] 2019-10-10 13:24
Duplicate of #2954

**Closed by tmcconechy** 2019-10-10 13:24 UTC
