### ISSUE TITLE
Datagrid : Order date disappear after changing a Theme

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3446] opened 2020-02-06 09:14 UTC
**Describe the bug**
Datagrid : Order date disappear after changing a Theme

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-paging.html?theme=soho&variant=light
2. FIlter Price = 0.99
3. Change theme to Vibrant 

**Expected behavior**
Order Date Column should not disappear 

**Version**
DEV 4.251

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/73922387-0c1ac800-4904-11ea-963a-2a6618a67e7b.png)

**Platform**
All platform 

**Additional context**
N/a

**Comment by tmcconechy** [comment] 2020-02-06 14:59
Duplicate of #3434 so put them together.

**Closed by tmcconechy** 2020-02-06 14:59 UTC
