### ISSUE TITLE
General: Add Sample of tabs within a modal which is triggered on a main tab

### ISSUE THREAD

**Issue by marclouisgenedeguzman** [infor-design/enterprise#5094] opened 2021-04-16 03:07 UTC
**Is your feature request related to a problem or use case? Please describe.**
We were trying to recreate an issue in ids-quick-start wherein tabs inside a modal have issue regarding tab indicator. The modal should be invoked from a container that is under tabs as well.

**Describe the solution you'd like**
We are trying to recreate an issue wherein the tab indicator is messed up when a modal dialog with tabs are invoked from a container under dismissible tabs. The issue is encountered when we upgraded from ids 7.2.4 to 9.1

Below is the screenshot in our application implementation
![image](https://user-images.githubusercontent.com/50192038/114965717-b8aaef00-9ea3-11eb-9ade-0bbe56268e48.png)

The tabs in modal is already available here -> https://master-enterprise.demo.design.infor.com/components/modal/test-tabs.html 

It would be good if in the example if the buttons are contained inside containers that runs under modules tab like below

![image](https://user-images.githubusercontent.com/50192038/114968161-628c7a80-9ea8-11eb-803e-f2de14c27d8a.png)

**Additional context**
 - Infor Application/Team Name: M3 H5 UI Team

**Comment by tmcconechy** [comment] 2021-04-16 13:23
This issue might be fixed on https://github.com/infor-design/enterprise/issues/4877 so can you test out the latest (4.50.1).

As far an example can this example be used as a starting point for you to make a reproduction? https://master-enterprise.demo.design.infor.com/components/tabs/test-modal-error.html

I think probably you should make the reproduction because i really cant see whats going on in your application.

One additional thought is can you make sure you set a width on the container like this example? The tabs will need this when on a modal. https://github.com/infor-design/enterprise/blob/main/app/views/components/tabs/test-modal-error.html#L7 This could be one cause.

**Comment by EdwardCoyle** [comment] 2021-07-07 13:51
@ericangeles @tjamesallen15 This one is related to #4818 and #5164.  Since we're removing the animation, I wouldn't worry about reproducing the sample here because it would specifically be for testing this issue (which will no longer be a problem once the animation's gone).

**Closed** 2021-07-28 13:39 UTC
Labels: [2], team: m3, type: support :sos:

**Comment by jbrcna** [comment] 2021-07-30 12:29
the issue is now resolved. moving this ticket to Done. Thanks
v4.54.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/tabs/test-no-animation-tabs.html
