### ISSUE TITLE
BarChart: Label and top links are not aligned

### ISSUE THREAD

**Issue by hey-yall** [infor-design/enterprise#7442] opened 2023-04-17 15:45 UTC
**Describe the bug**
Can we check the label alignment on bar charts with multiple values?

I suspect that these items have the same X value but some entries have a Y = 0 value, meaning that the code is functioning properly but is causing visual disharmony. Is there a way for us to code an alternative X label alignment when Y = 0?

Also, the link above the bar chart is not aligned with the title. If we need designer input for this item, I can arrange. 

Quote from the original Jira ticket IDS-963 : 

> The labels are not centered when displaying 3-bar values, this creates visual load as it doesn’t comply with the principles of alignment, this creates a problem especially when bar values is zero (see 2nd screenshot). 
> 
> The development team said they applied IDS component, and it renders the label as is. 
> 
> The link “372 - STD LOG/FIN GRP A GIII” is nor aligned with the widget header 

![image](https://user-images.githubusercontent.com/122995837/232539881-b46af77b-9318-4ed3-b851-bffaece320b1.png)

![image](https://user-images.githubusercontent.com/122995837/232539920-fd8b37a4-7d8b-4a00-8723-f613141be894.png)

> Component: Data Visualization - Chart
> 
> Product: LN: Contract Manager - Contract Amount widget
> 
> Contact Person: Sudha Addala, Srinithya Pulavarthy

Linked to Jira ticket [IDS-963](https://jira.infor.com/browse/IDS-963).

**Comment by tmcconechy** [comment] 2023-04-17 15:53
1. NOTE: This seems a column chart not a bar chart?
2. Seems like a duplicate of https://github.com/infor-design/enterprise/issues/7266

Add some sample data to help confirm this is fixed when https://github.com/infor-design/enterprise/issues/7266 is complete. We need the settings and sample data and can test this when https://github.com/infor-design/enterprise/issues/7266 is done.

**Comment by hey-yall** [comment] 2023-04-17 18:27
It's not quite a duplicate since this relates to grouped columns instead of stacked columns, but it can be linked.

Requesting ways to reproduce the issue and sample data from the original requestor.

**Comment by tmcconechy** [comment] 2023-04-17 18:45
Sounds good. We can also get them to try it when the other one is fixed. I think they are highly likely to be related

**Comment by tmcconechy** [comment] 2023-08-25 13:49
Any luck getting a way to reproduce this?

**Closed** 2024-02-01 15:51 UTC
Labels: type: bug :bug:, status: cant reproduce, [3]
