### ISSUE TITLE
File formatting issue when exporting grid data from Appbuilder to Excel	

### ISSUE THREAD

**Issue by felimonocampo** [infor-design/enterprise#5512] opened 2021-08-13 06:20 UTC
**Describe the bug**

When data from a datagrid in Appbuilder is exported to Excel an error is given when the Excel file is being opened. Please find attached the testscript and the .xls file that has been exported.

Could you let me know if this can be fixed?

**To Reproduce**

1. Go to Appbuilder
2. Click on the Project file/Datagrid you wish to export to excel.
3. Datagrid can be exported successfully, However, when you open the file and error displayed as below
4. Error : **"The File format and extension of 'Excel file(.xls)' dont match. The file could be corrupted or unsafe. Unless you trusts its source, don't open it. Do you want to open it anyway?"**

**Expected behavior**
No prompts when opening the exported .xls file

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
- Sample of the Test file - Test1.xls
- Sample of the data as shown on Appbuilder and the error when opening the file - Appbuilder file formatting issue.pdf

**Platform**
 - Infor Application/Team Name: Infor Appbuilder
  - Browser Name: Google Chrome/IE/Mcrosoft Edge

[Appbuilder file formatting issue.pdf](https://github.com/infor-design/enterprise/files/6980282/Appbuilder.file.formatting.issue.pdf)
[Test1.xls](https://github.com/infor-design/enterprise/files/6980284/Test1.xls)

**Comment by tmcconechy** [comment] 2021-08-16 13:23
This is a duplicate of https://github.com/infor-design/enterprise-wc/issues/153 so please watch that issue. We plan on fixing it when/if we can. As a workaround you can use csv format export for now which does not have this message.

Also the message is just a warning

**Closed by tmcconechy** 2021-08-16 13:23 UTC
Labels: type: bug :bug:, [5], status: duplicate
