### ISSUE TITLE
Toolbar-flex: searchfield x icon misaligned

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7436] opened 2023-04-14 10:17 UTC
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/toolbar-flex/example-index.html?colors=default
2. Type a text on searchfield
3.  See error

**Expected behavior**
should be properly aligned

**Version**

- ids-enterprise: v4.83.0-dev

**Screenshots**
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/56722184/231805545-9271e742-f29b-43fd-b811-b7a9d4b8180d.png">

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment] 2023-04-14 14:07
We should probably fix this as it seems to be a recent regression. Can you look later @andriivarhanov ?

**Comment by andriivarhanov** [comment] 2023-04-14 14:08
@tmcconechy should be fixed here https://github.com/infor-design/enterprise/pull/7411

**Comment by jbrcna** [comment] 2023-04-17 13:01
tested locally. Passed
http://localhost:4000/components/toolbar-flex/example-index.html?colors=default
<img width="776" alt="image" src="https://user-images.githubusercontent.com/56722184/232277556-cb9da6f3-bc55-4e4e-bb08-2c03cfc241e3.png">

**Closed** 2023-04-17 14:09 UTC
Labels: type: regression bug  :leftwards_arrow_with_hook:, [2]
