### ISSUE TITLE
Datagrid: Activated row on second page is not highlighted in datagrid mixed mode 

### ISSUE THREAD

**Issue by Michael-Cao** [infor-design/enterprise#4273] opened 2020-08-18 10:43 UTC
**Describe the bug**
If the paging datagrid is in "mixed" mode, on first page, when clicking a row, it becomes highlighted.
now open second page or any subsequent page, when clicking a row, it does not become highlighted.

**To Reproduce**
open second page or subsequent page of a mixed mode datagrid, clicks one row, it should be highlighted, but actually it is not.

**Expected behavior**
If the datagrid is in "mixed" mode, support paging, on first page, when clicking a row, it becomes highlighted.
now open second page or any subsequent page, when clicking a row, it should become highlighted.

**Version**

- ids-enterprise: [e.g. 4.31.0]

**Screenshots**

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: Desktop
 - OS Version: Windows 10 
 - Browser Name: Chrome
 - Browser Version: Version 84.0.4147.125 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment] 2020-08-18 13:32
@Michael-Cao Can you maybe clarify the steps. I'm not able to reproduce this. Here is what i tried:

- go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-mixed-selection.html
- go to page 2 on the top grid
- click row two on page 2 and try and active a row -> this works

**Comment by Michael-Cao** [comment] 2020-08-18 13:43
I tested with enterprise-ng,  I would try the page you provided tomorrow.

**Comment by tmcconechy** [comment] 2020-08-24 13:22
ok closing as duplicate of infor-design/enterprise-ng#900

**Closed by tmcconechy** 2020-08-24 13:22 UTC
Labels: [5], status: cant reproduce, type: bug :bug:
