### ISSUE TITLE
Arabic Locale: The default selected day is lost when selecting a year that is way too far in the future in the date picker.

### ISSUE THREAD

**Issue by jcotaco** [infor-design/enterprise#6017] opened 2022-01-13 03:45 UTC
**Describe the bug**
The default selected day is lost when selecting a year that is way too far in the future in the date picker. This occurs when using the Arabic Locale.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-timeformat.html?locale=ar-SA (Date Time Picker in Locale (Time to Current))
2. Click on the date picker.
3. Select a year 100+ years from now (e.g. 1543) or select any 5-yr digit in the Available from/to fields

**Expected Behavior**
There should be a default selected date. This works ok when the English (United States) locale is used.

**Actual Behavior**
When the future date is 100+ years or is a 5-digit year, the default selected date is lost. And even when there is no selected date, the apply button can still be clicked. Thus displaying the value "Nan" in the field.

![image](https://user-images.githubusercontent.com/72491690/149262152-333627ba-08af-4a24-b782-22fa753cc4bf.png)

**IDS Version**
4.58.3, 4.59

**Platform**
Infor Application/Team Name: Homepages
Device: Laptop
OS Version: Windows 10
Browser Name: Chrome

**Comment by tmcconechy** [comment] 2022-01-13 15:09
I think there might be a limit to the "algorithm" for arabic dates as to how far in the future the date can be. I think 100 should work but a 5 digit date is probably out of scope.

So willing to check for support for 100 years from now but i think 5 digits may be impossible. Is that even a realistic scenario?

**Comment by jcotaco** [comment] 2022-01-14 04:36
Hi @tmcconechy ,

I tested more on this and discovered that the default selected date is lost after setting the year to +60 years for Arabic locale. I agree with you that 5 digits may be an unrealistic scenario. However, it works fine when English (United States) locale is used.
There is an inconsistency somehow. I was thinking that the behavior should be consistent for all locales but if it's not possible, we can settle for support for 100 years for the Arabic locale. :)

Thank you and Regards,
Johanne

**Comment by tmcconechy** [comment] 2022-01-14 15:58
ok just so you know i think this isnt going to be easy i f not downright impossible. The issue is that our data goes from 1356 to the upper limit +60 years and thats it.

https://github.com/infor-design/enterprise/blob/main/src/components/locale/info/umalqura-data.js#L3

Since this calendar works on moon cycles this data is the estimations for those. And im not sure how we could extend it.

One idea is to use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat - which we could try on the new version but would be a big change I think.

**Comment by jcotaco** [comment] 2022-01-17 09:52
Hi Tim,

I've been pondering about this issue. I think the current upper limit we have of 60 years is good enough. I don't think it's worth the trouble especially if this is going to be a big change. Shall we take this as by design then? 

Thank you and Regards,
Johanne

**Comment by tmcconechy** [comment] 2022-01-18 14:30
Yeah sounds good. But i think i will keep this in mind for future versions but will close for now. Thanks!

**Closed by tmcconechy** 2022-01-18 14:30 UTC
Labels: type: bug :bug:, [8], team: homepages
