### ISSUE TITLE
Dropdown: options are not being announced

### ISSUE THREAD

**Issue by JBismonte** [infor-design/enterprise#4844] opened 2021-02-16 05:11 UTC
**Describe the bug**

[VPAT] Custom listbox elements do not expose options to assistive technology. Although each option can be navigated to and activated with a keyboard, the text of the option is not announced to screen reader users.
ARIA roles are implemented in an invalid way, nesting one element with role="option" within another element with role="option". The <li> for each option has a tabindex of 0, making it focusable, but also contains an <a> element which is also focusable. 

**To Reproduce**

1. Open any screen reader(Chrome Vox etc.)
2.  Go to the following URL: https://master-enterprise.demo.design.infor.com/components/dropdown/example-index.html
3. Try to navigate to the dropdown component and try to navigate between the options, the options are not announced.

**Expected behavior**
[VPAT Recommendation]
Ensure that proper identifying information is provided for custom components. Generally, Accessible Rich Internet Application (ARIA) specification roles, properties, and states should be used to indicate the control's name and role and may be needed for state, value, description, or other properties. Appropriate states need to be provided when applicable.
See the ARIA Authoring Practices example for a Collapsible Dropdown Listbox for an accessible implementation:
https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html

**Version**

- ids-enterprise: 4.36.2

**Platform**
 - Infor Application/Team Name: Landmark Client
 - Device: (if applicable) NA
 - OS Version: Windows 10
 - Browser Name: Firefox
 - Browser Version: 85.0

**Additional context**
https://jira.lawson.com/browse/LMCLIENT-34168

**Comment by tmcconechy** [comment] 2021-02-16 14:05
This is a duplicate of https://github.com/infor-design/enterprise/issues/4455 but will keep this one. I'll see if its possible to improve this a bit in the 4.x version but was planning this for 5.0 since could be an extensive change

**Comment by tmcconechy** [comment] 2021-03-16 14:01
This issue was fixed as part of https://github.com/infor-design/enterprise/pull/4883 and the options now announce.
Please follow the steps again to verify on the latest (4.38 and above)

**Closed by tmcconechy** 2021-03-16 14:01 UTC
Labels: [8], priority: high, timebox, type: bug :bug:

**Comment by jbrcna** [comment] 2021-03-18 07:07
the issue is now resolved. v4.39.0-dev
https://master-enterprise.demo.design.infor.com/components/dropdown/example-index.html?layout=nofrills
