### ISSUE TITLE
Datagrid filter not working in Windows 10 IE 11

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2559] opened 2019-07-30 11:21 UTC
**Describe the bug**

**To Reproduce**
1. Go to https://4200-beta1-enterprise.demo.design.infor.com/components/datagrid/example-nested-grids.html
2. In Activity Column, put "inspect and Repair"
3. Filter to not equals

**Expected behavior**
Filter should work properly. 

**Version**
Beta 4.20

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/62125247-2fced700-b2ff-11e9-9b06-bd64b8743ec6.png)

**Platform**
Windows 10 IE 11

**Additional context**
NA

**Comment by tmcconechy** [comment] 2019-07-30 15:00
@janahintal @CindyReyes Im not able to reproduce this it seems to work fine. Are you sure about this issue?
![Screen Shot 2019-07-30 at 10 59 38 AM](https://user-images.githubusercontent.com/814283/62140559-363a6000-b2b9-11e9-8fa0-2028a3fd412b.png)

**Comment by tmcconechy** [comment] 2019-08-22 18:25
Closing until further information can be provided as i have been unable to reproduce in any samples.

**Closed by tmcconechy** 2019-08-22 18:25 UTC
Labels: status: cant reproduce
