### ISSUE TITLE
Datagrid: Row not being unselected in group paging 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2006] opened 2019-04-24 12:05 UTC
**Describe the bug**
Datagrid Row not being unselected in group paging 

**To Reproduce**
1. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/datagrid/example-grouping-paging.html
2. Double click select all checkbox
* notice that the Product Id:214223 in On Hold group is still selected

**Expected behavior**
All records must be unselected. 

**Version**
v4.18.0

**Screenshots**
<img width="1362" alt="Screen Shot 2019-04-24 at 7 46 53 PM" src="https://user-images.githubusercontent.com/45757016/56658099-4e07b400-66cc-11e9-89ec-460f1a841944.png">

**Platform**
All browser, OS and devices. 

**Additional context**
No any other context about the problem here.

**Comment by tmcconechy** [comment] 2019-04-24 14:27
This bug goes back at least to http://4150-enterprise.demo.design.infor.com/components/datagrid/example-grouping-paging.html but i didnt test every version

**Comment by tmcconechy** [comment] 2019-07-08 15:27
Found that this issue is a complete duplicate of https://github.com/infor-design/enterprise/issues/1796 so closing.

**Comment by tmcconechy** [comment] 2019-07-08 15:28
Duplicate of #1796

**Closed by tmcconechy** 2019-07-08 15:27 UTC
Labels: [2], focus: datagrid, type: bug :bug:
