### ISSUE TITLE
Announcement Widget/Hungarian/Date Picker

### ISSUE THREAD

**Issue by sgcrandall** [infor-design/enterprise#812] opened 2018-09-18 13:01 UTC
In hungarian language, if we select date from datepicker and click outside(blur event) then placeholder is adding (please see the gif file attached), this is issue from soho because of this incorrect date we are unable to post an announcement, please move this to soho project.

https://jira.infor.com/browse/TECHSTACK-6748

**Comment by tmcconechy** [comment] 2018-09-18 13:43
Sorry I dont fully understand this issue. Also please follow the bug template so we can get info on how to reproduce this. Im not seeing any way i can reproduce the issue , so really no way we can work on this.

Here is the bug template you should use:
https://github.com/infor-design/enterprise/issues/new?template=bug_report.md

Can you maybe reproduce this on our samples? Also i suggest not using a placeholder on date fields...

**Comment by tmcconechy** [comment] 2018-09-25 13:42
Closing this as its a duplicate of https://github.com/infor-design/enterprise/issues/837 which has a bit more info (though its not enough to debug the issue in any way)

**Closed by tmcconechy** 2018-09-25 13:42 UTC
Labels: status: can't reproduce, type: bug

**Comment by clepore** [comment] 2018-10-12 16:33
Duplicate of #837
