### ISSUE TITLE
Contextual Action Panel Control: Panel won't open again after closing it

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#506] opened 2018-07-26 19:12 UTC
**Describe the bug**
[All Browsers] Contextual Action Panel Control: Panel won't open again after closing it

**To Reproduce**
1. Go to http://490-beta0-sohoxi.demo.design.infor.com/components/contextualactionpanel/example-centered.html
2. Open the Contextual Action Panel
3. Close the panel then Try to open again
4. Panel will not open
4. Affected Pages:
http://490-beta0-sohoxi.demo.design.infor.com/components/contextualactionpanel/example-centered.html
http://490-beta0-sohoxi.demo.design.infor.com/components/contextualactionpanel/example-markup.html
http://490-beta0-sohoxi.demo.design.infor.com/components/contextualactionpanel/example-trigger.html
http://490-beta0-sohoxi.demo.design.infor.com/components/contextualactionpanel/test-alignment.html
http://490-beta0-sohoxi.demo.design.infor.com/components/contextualactionpanel/test-full-content.html
http://490-beta0-sohoxi.demo.design.infor.com/components/contextualactionpanel/test-nested.html
http://490-beta0-sohoxi.demo.design.infor.com/components/contextualactionpanel/test-show-close-button.html
http://490-beta0-sohoxi.demo.design.infor.com/components/contextualactionpanel/test-workspaces-buttons.html

**Expected behavior**
CAP should open again after it's been closed the first time.

**Screenshots**
None

**Platform**
 - All Browsers 

**Additional context**
None

**Comment by tmcconechy** [comment] 2019-01-22 22:01
This is a duplicate of https://github.com/infor-design/enterprise/issues/284 which was fixed

**Closed by tmcconechy** 2019-01-22 22:01 UTC

**Comment by brianjuan** [comment] 2019-01-24 11:32
http://490-beta0-sohoxi.demo.design.infor.com/components/contextualactionpanel/example-centered.html
http://490-beta0-sohoxi.demo.design.infor.com/components/contextualactionpanel/example-centered.html
http://490-beta0-sohoxi.demo.design.infor.com/components/contextualactionpanel/test-full-content.html
http://4150-beta0-enterprise.demo.design.infor.com/components/contextualactionpanel/test-nested.html
Issue still happens on the pages above.

**Comment by tmcconechy** [comment] 2019-01-24 14:08
The issue was only fixed on these three pages. The rest dont matter too much. Im going to go through these and cleanup as part of 1136.

http://4150-beta0-enterprise.demo.design.infor.com/components/contextualactionpanel/example-index.html
http://4150-beta0-enterprise.demo.design.infor.com/components/contextualactionpanel/example-jquery.html
http://4150-beta0-enterprise.demo.design.infor.com/components/contextualactionpanel/example-markup.html
http://4150-beta0-enterprise.demo.design.infor.com/components/contextualactionpanel/example-trigger.html

These pages show the ways you can invoke the CAP. The others are older examples. I'll clean this up as part of 1136

**Comment by brianjuan** [comment] 2019-01-25 02:47
Thanks @tmcconechy for the clarification, I will take note of the page clean up.
Moving this to Done.
