### ISSUE TITLE
Advance File Upload - MAX files limit does not work - Change Error Icon

### ISSUE THREAD

**Issue by inforandy** [infor-design/enterprise#6229] opened 2022-03-25 17:20 UTC
**Describe the bug**
Observed behavior
files limit set to 20
[maxFiles]="maxFileCount"
readonly maxFileCount = 20;
if a batch of 20 files is dragged and dropped into the Adv. File Upload , the component throws mistakenly an error

**To Reproduce**
see above

**Expected behavior**
files should be able to be batch uploaded according to limit set by admin

see original submission here https://jira.infor.com/browse/UXD-4203

**Comment by yohannahbautista** [comment] 2022-04-05 06:56
Hello, I tried reproducing the bug in this page: http://localhost:4000/components/fileupload-advanced/test-max-files.html
by changing maxFiles to 20 and I was able to upload 

I also tried it in NG with this page: http://localhost:4200/ids-enterprise-ng-demo/fileupload-advanced
by updating the maxFiles following the steps posted above and I was able to upload

**Comment by tmcconechy** [comment] 2022-04-05 13:20
I was also not able to reproduce @inforandy can you get together with the WFM team that reported this and ask them how we can reproduce?

**Comment by kevinwhitedesign** [comment] 2022-04-05 18:42
Think this is coming from ENrico Tomada

**Comment by tmcconechy** [comment] 2022-04-05 19:33
Does he have any github ID? Email? Anyways someone please point him here or we really cant do anything.

Thanks

**Comment by kevinwhitedesign** [comment] 2022-04-07 04:12
https://jira.infor.com/browse/UXD-4203 I think the issue is here, maybe it shows more examples of the issue with the component?

**Comment by tmcconechy** [comment] 2022-04-08 13:17
Developer noted on the Jira that this is working now. Closing...

**Closed by tmcconechy** 2022-04-08 13:17 UTC
Labels: type: bug :bug:, status: cant reproduce, [2], team: WFM

**Comment by janahintal** [comment] 2022-04-18 11:18
Hi @yohannahbautista, when I upload 2 or more files in https://main-enterprise.demo.design.infor.com/components/fileupload-advanced/example-failed.html then tick the 'set failed' button, only 1 file has the Error Message and close icon. 

Expected: All files

**Comment by tmcconechy** [comment] 2022-04-18 13:10
This probably ok - right @yohannahbautista as the API is just setting the first one (you can make the api set it on any specific one)
