### ISSUE TITLE
SinkPage: Hierarchy icons looks off

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#8597] opened 2024-04-05 10:16 UTC
**Describe the bug**
Hierarchy: Icons looks off

**To Reproduce**

1. Go to https://4940-beta0-enterprise.demo.design.infor.com/
2. Go to Hierarchy section

**Expected behavior**

**Version**
beta-4940

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/45757016/45b65040-3a83-491c-819f-af622ce6192d)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment] 2024-04-05 11:47
Duplicate of https://github.com/infor-design/enterprise/pull/8588

**Closed by tmcconechy** 2024-04-05 11:47 UTC
