### ISSUE TITLE
Busy indicator not being excluded from being checked for close 

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#2767] opened 2019-09-10 11:54 UTC
**Describe the bug**
The selectors being used to exclude items from the close children for the clickInterceptor() functionality are incorrect and does not allow a busy indicator to display when opening a modal dialog from an accordion menu.

**To Reproduce**
Currently unable to create a suitable example with ids-enterprise, but in Landmark perform the following:
1. Open HCM with Administrator role
2. Click on Hire a Resource in the Nav menu
3. Do not see a busy indicator until the modal displays

**Expected behavior**
Expect to see a busy indicator until modal displays

**Version**

- ids-enterprise:  v4.21.0-beta.1

**Screenshots**
![image](https://user-images.githubusercontent.com/20212079/64611361-e14d3780-d396-11e9-89f6-2b856b8bced3.png)

**Platform**
All

**Additional context**
The issue is the values defined in the const EXCLUDED_FROM_CLOSE_CHILDREN. They should be defined as 
['.expandable-area', '.accordion', '[soho-busyindicator]', '.busy-indicator-container']

instead of 
['.expandable-area', '.accordion', ['soho-busyindicator'], '.busyindicator']

**Comment by tmcconechy** [comment] 2019-09-10 12:49
@fitzorama Since there is no way to reproduce this im not sure what to do about it?
Do we just make the changes in the "additional context" section?
Or should we maybe add a showBusyIndicator/hideBusyIndicator on the Modal API?

**Comment by pwpatton** [comment] 2019-09-10 13:07
We need this fixed in 4.21

**Comment by tmcconechy** [comment] 2019-09-10 13:08
What is it? Ping me im not clear on what this is?

**Comment by pwpatton** [comment] 2019-09-10 13:28
I think if we just fixed the selector issue that would be good enough for 4.21 but we also want to fix the initial load maybe by scoping this siftFor to the accordion app menu instead of it running against the entire dom.

**Closed** 2019-09-10 16:36 UTC
Labels: [3], priority: high, team: landmark, type: regression bug  :leftwards_arrow_with_hook:

**Comment by CindyMercadoReyes** [comment] 2019-09-10 18:36
This issue is now resolved. Moving this ticket to the Done column.
