### ISSUE TITLE
Datagrid saves "select" filters but doesnt display it (saveUserSettings.filters)

### ISSUE THREAD

**Issue by llezcano** [infor-design/enterprise#769] opened 2018-09-07 16:56 UTC
**Describe the bug**
The last selected filter option is not displayed on the column header, in a datagrid using the saveUserSettings option.

**To Reproduce**
1. Select an option from the **select** (dropdown) filter (e.g. Select "Confirmed" on "Status" column filter)
2. Reload the page (F5)
3. The datagrid stills filtered (so, the filter is being applied) but _the selected filter on header is empty_ 

**Expected behavior**
Header displays the filter. (e.g. If "Confirmed" option was selected from "Status" column filter, the datagrid should display "error" after reloading the site) 

**Platform**
 - Browser Name: Firefox

**Additional context**
This is a running instance on JSFiddle, where you can see the error https://jsfiddle.net/llezcano/2gp7tvc6/
I used old soho libraries (I had some issues using Formatter when try to import soho 4.9.0) but the same error happens on newer versions of soho

**Comment by tmcconechy** [comment] 2018-09-10 13:43
Can probably make a test by adding a select filter to this page http://localhost:4000/components/datagrid/test-save-settings.html

**Comment by tmcconechy** [comment] 2018-09-10 18:26
Seems like it works ok here on input fields.
http://master-enterprise.demo.design.infor.com/components/datagrid/test-save-settings.html
- type 0 in "Product Name" and hit enter
- reload page

Are you using the saveOptions option?

**Comment by CristianCosta** [comment] 2018-09-10 18:47
We are using settings.saveUserSettings defined on specs https://design.infor.com/code/ids-enterprise/4.6.1/datagrid#datagrid
We didn't find saveOptions inside datagrid specs.

**Comment by tmcconechy** [comment] 2018-09-10 18:48
Sort yes thats what i meant. See the code for example http://master-enterprise.demo.design.infor.com/components/datagrid/test-save-settings.html

Its here:
https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/test-save-settings.html#L82

Maybe your not saving the filter? I did not test dropdowns since its not on that example. But it is saving on that example as far as i can see. Perhaps a new example is needed if that doest help?

**Comment by CristianCosta** [comment] 2018-09-10 19:27
The example worked fine, but if I remove the body initialization, the issue appears again.
The thing is, in our application, we dont use the initialization because we initialize every single component separately (we use this approach because initializing is pretty expensive https://jira.infor.com/browse/SOHO-7165)

**Comment by tmcconechy** [comment] 2018-09-10 19:40
Ok, i don't have anyway to test this or do anything with. So seems like it may be just an issue with how you are doing it.

What code can you give that shows the issue running i can see with a simple angular directive? 

Guesses:
Seems like it might be a timing issue on your end. Maybe you can debug and see why https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L3810 isnt working (is it an issue with the incorrect Local storage at the time the directive runs ?)

Or maybe you do it manually in your directive? https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/test-save-settings-manual.html

**Comment by tmcconechy** [comment] 2018-09-10 19:46
Ignore my last comment. I debugged the fiddle here is an updated one.

https://jsfiddle.net/L8y1s02j/2/

The problem is that your calling updateColumns at the end which totally replaces the columns. If you dont have to do that you should be ok and you can let the saveColumns feature do that for you. Otherwise they conflict.

**Comment by CristianCosta** [comment] 2018-09-11 15:16
Yes, that's correct. Thanks a lot!

**Comment by tmcconechy** [comment] 2018-09-11 15:17
Ok Great, closing those out then.

**Closed by tmcconechy** 2018-09-11 15:17 UTC
Labels: [2], type: bug

**Comment by CristianCosta** [comment] 2018-09-11 18:58
Hello, It's me again and apologies in advance.

I attached a gif showing the behavior related to _saveUserSettings_. 
It seems it's not working with _selects_ as filterType. I couldn't see it in this example http://master-enterprise.demo.design.infor.com/components/datagrid/test-save-settings.html because it doesn't have any select.

![record save filter over select](https://user-images.githubusercontent.com/9300795/45380864-2733bc00-b5da-11e8-87d6-65f4503e1c54.gif)

As you can see, it saves the id (_5_ at first and _6_ after) established in the text field in the different page refresh but is not saving the option selected in the selector (_Confirmed_ or _Error_).

I used the same fiddle example https://jsfiddle.net/L8y1s02j/2/

**Comment by llezcano** [comment] 2018-09-12 17:32
Hi @tmcconechy. Thanks for looking at our code snippet. Your change worked ! (seems we forgot to remove the updateColumns from the snippet). 

I see that  ` $('body').initialize('en_US');` was added,  but we are not using that method on our app (@CristianCosta have linked and old Technical Question where you explained to me that the best approach is to initialize each directive independently, and avoid the global initialization).

When we remove that line in the snippet, the text input filters stills working, but, select filters don't display any text on header after reloading the site (like in the gif attached on the last comment)

I think this issue should not be closed yet.

**Comment by tmcconechy** [comment] 2018-09-12 17:36
OK, Lets re-raise a new issue just mentioning the fact that the select filters do not work correct.
As this one has gotten a bit convoluted. Sound ok? You dont need a jsfiddle i can reproduce it off http://master-enterprise.demo.design.infor.com/components/datagrid/test-save-settings.html if the select is added.

We can reference this issue

**Comment by llezcano** [comment] 2018-09-12 17:42
sounds good !
