### ISSUE TITLE
Contextual Action Panel in iOS devices is not responsive

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2909] opened 2019-10-08 08:10 UTC
**Describe the bug**
Contextual Action Panel in iOS devices is not responsive

**To Reproduce**
1. Open a Browser in iOS device
2, Go to http://4220-beta0-enterprise.demo.design.infor.com/components/contextualactionpanel/example-index.html

**Expected behavior**
Modal should fit the screen and fields should be responsive

**Version**
Beta 4.22

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/66378489-1bd1e080-e9e6-11e9-8854-69e88afbb839.png)

**Platform**
iOS Devices Safari/Chrome

**Additional context**
N/a

**Comment by tmcconechy** [comment] 2019-10-08 13:31
Should we fix this one in 4.22 @EdwardCoyle as it relates to the new feature you just added?

**Comment by EdwardCoyle** [comment] 2019-10-08 14:06
I think it depends... the new feature is opt-in, specifically to prevent people from being forced to go fullscreen in their implementations.  There's a setting that needs to be enabled, and all the current demoapp samples do not enable it.  

The fact that this sample isn't fullscreen isn't a bug as much as it is the default configuration.

**Comment by tmcconechy** [comment] 2019-10-08 15:05
This appears to be ok to me i tried this on an Ios x device? 

![Screen Shot 2019-10-08 at 11 05 18 AM](https://user-images.githubusercontent.com/814283/66407645-8faac380-e9bb-11e9-8524-3d745bcdbf24.png)

**Comment by tmcconechy** [comment] 2019-10-09 13:24
Closing as i cannot reproduce following the steps.

**Closed by tmcconechy** 2019-10-09 13:24 UTC
Labels: [2], status: cant reproduce, type: bug :bug:
