### ISSUE TITLE
Modal overlapping text and button in responsive view

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2570] opened 2019-07-31 10:42 UTC
**Describe the bug**
Modal overlapping text and button in responsive view

**To Reproduce**
1. Go to https://4200-beta1-enterprise.demo.design.infor.com/components/modal/example-index.html?theme=uplift&variant=contrast&colors=5c5c5c
2, Minimize the screen or use mobile device. 

**Expected behavior**
Text and button should not overlap each other

**Version**
beta 4.20

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/62205793-cf08d280-b3c2-11e9-85b6-882ec683ea28.png)

**Platform**
All OS, Browser and devices. 

**Additional context**
NA

**Comment by tmcconechy** [comment] 2019-07-31 13:12
Duplicate of https://github.com/infor-design/enterprise/issues/2547

**Closed by tmcconechy** 2019-07-31 13:12 UTC
