### ISSUE TITLE
Problem with disappearing nodes when using accordion + context menu

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1349] opened 2018-12-05 17:27 UTC
**Describe the bug**
Nodes are disappearing in the context menu / accordion example (this example never fully worked).

**To Reproduce**
1. Go to http://4130-rc0-enterprise.demo.design.infor.com/components/accordion/test-with-contextmenu.html
1. Click on first header to open
1. Click on item one
1. See error: the accordion closes
1. Open it again and see error: the item 2 node is gone
1. open second "postion" accordion header
1. repeatedly click on item 1
1. see error: the node under it toggles away and back

**Expected behavior**
Should not disappear.

**Version**
4.13 - maybe others

**Additional context**
Unverified if the context menus attached are causing this

**Comment by pwpatton** [comment] 2018-12-05 21:00
We need this fixed in 4.13  :/

**Comment by tmcconechy** [comment] 2018-12-05 21:11
Yes agreed working on a fix

**Comment by tmcconechy** [comment] 2018-12-05 21:20
Update: Have a fix to push in the AM, just need a bit more testing and to write a PR

**Comment by tmcastro** [comment] 2018-12-06 03:10
@tmcconechy I think the issue is mainly caused by how the "panes" are being selected. Before, we used next() and now we are using a combination of nextAll(), not() and first(). Maybe we can change the way we select panes? Something like an attribute to mark which pane is for what header (to make selecting of panes more direct)?

**Closed** 2018-12-06 19:09 UTC
Labels: [3], priority: high, type: regression bug  :leftwards_arrow_with_hook:

**Comment by CindyMercadoReyes** [comment] 2018-12-06 19:38
This issue is now resolved.
