### ISSUE TITLE
Datagrid: Continuous Loading and Virtual Scrolling with possible paging support

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#460] opened 2018-07-17 19:36 UTC
Use case is in cases of a lot of data, as you scroll down the paging to get next page should execute. The pages should be cached, and possibly removed in and out of the dom. This should also help for IE 11 and large amounts of data.

Components:
- list
- datagrid
- tree
- dropdown
- multiselect

There is a design for the list paging which involved clicking a get more rows button at the bottom of the scroll area. This was implemented here:
http://master-enterprise.demo.design.infor.com/components/listview/example-footer-navigation.html

http://master-enterprise.demo.design.infor.com/components/datagrid/example-virtualization.html
For datagrid we have an experimental example this doesn't work perfectly well, to improve i think it needs to remove hidden rows from the top/bottom instead of plunking them in at once. But ideally a system for handing this for all components would be ideal.

Formerly SOHO-3273

One implementation can be reviewed from https://material.angular.io/cdk/scrolling/overview. for ideas.

**Comment by tmcconechy** [comment] 2020-04-21 20:47
This is a duplicate of https://github.com/infor-design/enterprise/issues/3026 (in a way). Rather than keep two issues will work on it with that ticket number

**Closed by tmcconechy** 2020-04-21 20:47 UTC
Labels: [8], type: enhancement :sparkles:
