### ISSUE TITLE
Calendar: Calendar icon misaligned

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1705] opened 2019-02-28 17:39 UTC
**Describe the bug**
Calendar Component: Calendar icon misaligned

**To Reproduce**
1. Go to url: http://4160-beta0-enterprise.demo.design.infor.com/components/calendar/example-index.html
2. Double Click on "Out of Office
3. The calendar icons are misaligned 
4. Please see screen shot attached

**Expected behavior**
Calendar icons should not be misaligned 

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1359" alt="calendar icon alignment issue" src="https://user-images.githubusercontent.com/39101346/53586256-c5e6b180-3b55-11e9-9988-1bb259ede9d4.png">

**Platform**
 - OS Version: [iOS 8]
 - Browser Name [FF]

**Additional context**
None

**Comment by tmcconechy** [comment] 2019-02-28 17:49
im not able to reproduce this. Are the steps correct? Also is the OS version correct?

**Comment by marknolaninfor** [comment] 2019-03-11 23:54
This issue was caused by by #1740, as I was also able to replicate this before by

1. Go to url: /components/calendar/example-index.html
2. double clicking on "Out of Office"
3. The calendar icons are misaligned

**Comment by tmcconechy** [comment] 2019-03-12 12:33
I'm still not seeing this on http://4160-rc3-enterprise.demo.design.infor.com/components/calendar/example-index.html nor http://master-enterprise.demo.design.infor.com/components/calendar/example-index.html

Which browser @marknolaninfor ? Only one click on any out of office in Feb?

**Comment by marknolaninfor** [comment] 2019-03-13 23:44
Replicated on http://latest-enterprise.demo.design.infor.com/components/calendar/example-index.html, but NOT on http://master-enterprise.demo.design.infor.com/components/calendar/example-index.html

A single clicks on the any out of office will work, as it was coded that a user would single click on an event to show the popup for the event and a double click on a date will show the popup for a new event. When you double click on an event both are triggered.

The difference in the master branch is that the double click check to see if the popup is present and does not trigger any additional code, eg causing the datepicker to initialize twice. This mean that a new event can only be created when the popup is not displayed.

**Comment by tmcconechy** [comment] 2019-03-14 13:34
Thanks @marknolaninfor dblclick seems the culprit. I would almost close this but i dont like the way it blinks if you double click. I think we should make double click behave like click so will suggest we do that here to solve this better.

**Closed** 2019-07-08 13:22 UTC
Labels: [2], priority: minor, type: bug :bug:

**Comment by brianjuan** [comment] 2019-07-11 10:53
http://localhost:4000/components/calendar/example-index.html
http://localhost:4000/components/calendar/test-specific-month.html
Passed QA on all browsers, will retest once beta is deployed.
