### ISSUE TITLE
Popover: Close button is misaligned

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2017] opened 2019-04-25 10:24 UTC
**Describe the bug**
Popover close button is misaligned in responsive view 

**To Reproduce**
1. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/popover/example-header-color.html in responsive view 

**Expected behavior**
Close button should be aligned. 

**Version**
v.4.15.0 - v4.18.0

**Screenshots**
<img width="499" alt="Screen Shot 2019-04-25 at 6 29 38 PM" src="https://user-images.githubusercontent.com/45757016/56729742-94bae400-6788-11e9-8423-34801d1f0d20.png">

**Platform**
All Browser, OS and devices

**Additional context**
No any other context about the problem here.

**Comment by tmcconechy** [comment] 2019-04-25 12:45
Duplicate of #1576

**Closed by tmcconechy** 2019-04-25 12:45 UTC
