### ISSUE TITLE
Datagrid: Unable to use the left/right arrow keys on the text in an editable cell.

### ISSUE THREAD

**Issue by jcotaco** [infor-design/enterprise#8457] opened 2024-02-19 14:09 UTC
**Describe the bug**
In an editable cell with a text, it is not possible to use the left/right arrow keys to set the cursor to a certain letter of the text. It moves the focus to the left or right cell instead. Because of this, if the text is misspelled, the full word needs to be selected and re-entered again or the user can use the mouse to set the cursor to the letter that needs correction.

**To Reproduce**

1. Go to https://latest-enterprise.demo.design.infor.com/components/datagrid/example-editable?theme=uplift&variant=light&layout=embedded
2. Click on an editable cell (e.g. Assemble Paint)
3. Set the cursor at letter "m" in the word "Assemble" and press the left/right arrow key.
**Expected behavior**
It is possible to move the cursor from one letter to another by pressing the left/right arrow key.

**Version**

- ids-enterprise: 4.92

**Screenshots**

https://github.com/infor-design/enterprise/assets/72491690/36f3ec1e-47f5-4b0f-b1dc-60d8483c170e

**Platform**
 - Infor Application/Team Name: M3 Widgets
 - Device: (if applicable) - Dell Laptop
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: 121.0.6167.185 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment] 2024-02-19 15:08
I cant reproduce this (it works for me).

- click the cell (initially it selects all text)
- click again on the m to get in cursor mode
- left and right works

https://app.screencastify.com/v3/watch/03ob22v17IYClzLo3dOn

**Comment by jcotaco** [comment] 2024-02-21 05:29
I can still reproduce the issue with IDS 4.92 and 4.92.3. May I kindly ask, what version of IDS are you testing with?

**Comment by jcotaco** [comment] 2024-02-21 06:08
After further testing, it was discovered that pressing Enter key on the cell would resolve the issue. And this might be the reason why it worked for you. 
**Precondition:** Refresh https://latest-enterprise.demo.design.infor.com/components/datagrid/example-editable?theme=uplift&variant=light&layout=embedded
**Steps:**
1. Click on an editable cell (e.g. Assemble Paint)
2. Set the cursor at letter "m" in the word "Assemble" and press the left arrow key.
3. Verify it sets focus on the left cell beside the editable cell.
4. Press the right arrow key to go back to the editable cell.
5. Press Enter key. Take note that the word is highlighted.
6. Set the cursor after letter "m" and press the left/right arrow keys.
Actual Result: After pressing the Enter key on the cell, the left/right arrow keys will start working.

**Comment by ericangeles** [comment] 2024-02-28 15:21
You accidentally reopened this, @tmcconechy ?

**Comment by tmcconechy** [comment] 2024-02-28 15:32
oh sorry i didnt think tha one was merged i didnt test it.

**Comment by whernebrink** [comment] 2024-03-18 08:09
@tmcconechy Do you know when this one will be available?

**Comment by tmcconechy** [comment] 2024-03-18 14:58
This one is in 4.93.0 (ids-enterprise-ng@17.5.9) @whernebrink

**Comment by whernebrink** [comment] 2024-03-20 09:24
@tmcconechy I tried the link above, and I'm unable to use the arrows inside editable cell (also doesn't work in our beta app using 17.5.9)
https://latest-enterprise.demo.design.infor.com/components/datagrid/example-editable?theme=uplift&variant=light&layout=embedded

**Comment by tmcconechy** [comment] 2024-03-26 15:44
@tjamesallen15 can you check this again? Looking at https://latest-enterprise.demo.design.infor.com/components/datagrid/example-editable?theme=uplift&variant=light&layout=embedded and i see what @whernebrink means i cant use left and right arrow when editing in a cell?

**Comment by tjamesallen15** [comment] 2024-03-27 12:42
i think the example page has actionableMode set to false that's why he can't use the left and right keys to transfer. @tmcconechy

**Comment by tmcconechy** [comment] 2024-03-27 12:44
@tjamesallen15 think the arrow keys need to work in both actionableMode modes when in the cell.
So don't tie this to the setting just make it work it in the cell

**Comment by tjamesallen15** [comment] 2024-03-27 12:49
> [@tjamesallen15](https://github.com/tjamesallen15) think the arrow keys need to work in both actionableMode modes when in the cell. So don't tie this to the setting just make it work it in the cell

then what's the use case for the arrows keys in.
- transferring cells
- traversing letters

**Comment by tmcconechy** [comment] 2024-03-27 14:05
@tjamesallen15 

- when inside a cell in edit mode (no matter the actionAbleMode) -> the arrow keys should move around the text in the input
- when not in edit mode arrow keys should work as normal to navigate cells (no matter the actionAbleMode)

**Closed** 2024-04-19 06:18 UTC
Labels: type: bug :bug:, [2], priority: high
