### ISSUE TITLE
Editor: Reset Dirty Not Working on EDGE Browser When There Are Special Characters < > and &

### ISSUE THREAD

**Issue by gilbugauisan** [infor-design/enterprise#6584] opened 2022-06-16 07:01 UTC
**Describe the bug**
Reset dirty not working on EDGE browser only when there are special characters < > and & 

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/editor/test-dirty-tracking-reset.html using EDGE browser.
2. Insert < or > or & in the middle of a sentence
3. Click the 'Reset Dirty' button.

**Expected behavior**
Dirty indicator should be cleared.

**Version**
ids-enterprise@4.62.3 or 4.64.0-dev

**Screenshots**
![Reset Dirty Not Working on EDGE Browser When There Are Special Characters](https://user-images.githubusercontent.com/74726741/174012699-7e98179e-1951-4f67-bc42-fbf0052224ee.gif)

**Platform**
- Infor Landmark
- Device: Laptop
- OS Version: Windows 10
- Browser Name: Microsoft EDGE
- Browser Version: Version 97.0.1072.55 (Official build) (64-bit)

**Additional context**
Working on other browsers

**Comment by tmcconechy** [comment] 2022-06-16 13:28
@gilbugauisan this is a duplicate of https://github.com/infor-design/enterprise/issues/6032 and its been fixed in 4.61 or later.
Also note we changed the name of the base branch from master to main so the master link is older. Please use https://main-enterprise.demo.design.infor.com/ instead now.

You can see you cant reproduce it on this url anymore.
https://main-enterprise.demo.design.infor.com/components/editor/test-dirty-tracking-reset.html

Thanks!

**Comment by tmcconechy** [comment] 2022-06-16 13:28
Duplicate of #6032

**Comment by tmcconechy** [comment] 2022-06-16 13:55
Im a bit confused by what your typing in the video. But i tried puting ^ < > and enter and all cases seem to work ok for me on: https://main-enterprise.demo.design.infor.com/components/editor/test-dirty-tracking-reset.html

Before typing anything didn't work and thats definitely fixed? Whats not working on https://main-enterprise.demo.design.infor.com/components/editor/test-dirty-tracking-reset.html exactly?

**Comment by tmcconechy** [comment] 2022-06-16 13:57
Sorry i wasnt on edge. I DO see it for < or > or & but a lot of cases seem fixed now compared to the older version

**Closed** 2022-07-26 09:05 UTC
Labels: type: bug :bug:, [3], team: landmark

**Comment by jbrcna** [comment] 2022-07-27 07:33
QA Passed
v4.66.0-dev
https://main-enterprise.demo.design.infor.com/components/editor/test-dirty-tracking-reset.html
