### ISSUE TITLE
Angular: Datepicker icon position is not study while scrolling

### ISSUE THREAD

**Issue by manjaripalavancha** [infor-design/enterprise#6359] opened 2022-04-28 10:40 UTC
The existing code is: 
        <input soho-datepicker class="datepicker  /> 

While I'm scrolling  the icon position is not study

![ab88a0b6-ae57-4cf9-81a6-f4a8bf4a3e45](https://user-images.githubusercontent.com/104565263/165734877-4092aea8-c62c-4f10-b5e8-16c31ef38278.jpg)

The version which we are using currently is: 10.14.0 (ids-enterprise-ng)

**Comment by tmcconechy** [comment] 2022-04-28 13:13
@manjaripalavancha i cant reproduce this in demo app at https://github.com/infor-design/enterprise-ng
It looks good:

![Screen Shot 2022-04-28 at 9 10 58 AM](https://user-images.githubusercontent.com/814283/165759909-070f5540-a388-4aec-9fba-87fc3dd1a07e.png)

Note:
- the latest version is https://github.com/infor-design/enterprise-ng/releases/tag/13.3.2 so you can try that?
- i tested this on my end and it works but you could test if it works with a label in a field?

```
<div class="field">
        <label for="statechange" class="label">Datepicker</label>
        <input soho-datepicker name="statechange" dateFormat="MM/dd/yyyy" mode="standard" placeholder="MM/dd/yyyy" [(ngModel)]="model.standard" (change)="onChange($event)"/>
</div>
```

Can also have a invisible label (good for accessibility)
```
<div class="field">
        <label for="statechange" class="label audible">Datepicker</label>
        <input soho-datepicker name="statechange" dateFormat="MM/dd/yyyy" mode="standard" placeholder="MM/dd/yyyy" [(ngModel)]="model.standard" (change)="onChange($event)"/>
</div>
```

**Comment by manjaripalavancha** [comment] 2022-04-28 13:59
Could you please add more filed and try to scroll down
I was able to replicate while scrolling

Before Scroll:
<img width="571" alt="image" src="https://user-images.githubusercontent.com/104565263/165768412-7f9fa772-cdde-405a-9c8c-47450a277368.png">

After Scroll:
<img width="588" alt="image" src="https://user-images.githubusercontent.com/104565263/165768805-91c7aa59-212a-44ec-9a2c-fca2a501fca9.png">

The below is the code I have used:
    <input soho-datepicker id="date-field-md" name="date-field-md" class="datepicker" />

**Comment by tmcconechy** [comment] 2022-04-28 14:05
Can you put the example in https://stackblitz.com/edit/ids-quick-start-1331
Also can you try the latest version?
Or can you reproduce with changes in the demo app?

Screen shots dont 100% help reproduce it for us

**Comment by tmcconechy** [comment] 2022-09-19 18:30
Where you able to add more info on this? @manjaripalavancha

**Comment by tmcconechy** [comment] 2022-11-22 14:50
Closing older issues we cant reproduce.

**Closed by tmcconechy** 2022-11-22 14:50 UTC
Labels: type: bug :bug:, status: cant reproduce, [3]
