### ISSUE TITLE
SinkPage: Masthead - Buttons are not visible when hovering - BETA 4.95

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#8695] opened 2024-05-09 04:09 UTC
**Describe the bug**
Buttons are not visible when hovering in Mac Edge and Safari.

**To Reproduce**

1. Go to https://4950-beta0-enterprise.demo.design.infor.com/
2. Scroll down to `Masthead` component
3. Hover over buttons

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/102151352/981ac50a-f00f-49e2-972c-f27a3a038f4e)

https://github.com/infor-design/enterprise/assets/102151352/c30423fc-074f-477f-9f24-d16db1908666

**Platform**
 - Mac Edge
 - Safari

**Additional context**

**Comment by glenlieorillo** [comment] 2024-05-09 10:37
This has been tested and passed.

https://github.com/infor-design/enterprise/assets/102151352/a72415f7-829c-4b19-92dc-b8cd3fc00c27

**Comment by n-ace-ancog** [comment] 2024-05-09 11:40
Duplicate of #8688.

**Closed** 2024-05-09 13:35 UTC
Labels: type: bug :bug:, [2], status: duplicate
