### ISSUE TITLE
Datagrid - keep the selected records without traversing the page of selected record

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise#4316] opened 2020-08-28 13:11 UTC
**Describe the bug**
In model popup we have Data grid with server side paging. Is there any way to keep the selected records without traversing the page of selected record??

For detailed steps, please check the attached code.

**To Reproduce**
Steps :-
Please run attached project first.

1. Go to datdarid section
2. Click on datagrid-Fixedheader
3. In landing page datagrid select one record from page number 1 and got to page number 2 and select another record.
4. Now click on "Show Selected Values" button
5. Selected Values from page Grid count will get updated with selected records.
6. Now click on show Grid in popup button to open datagrid in popup.
7. Now you can view one selected record on page number 1 
8. Now select one more record on page number 1 and click on "select" button.
9. Now check "Selected values from model popup grid" count. 
10. It will show only 2 records in it.

It is not showing value which we have selected on page number 2. It is not showing values from page which we have not traversed. 

**Expected behavior**
It should show all the selected records. 

**Version**

- ids-enterprise: [v4.31.1]

**Screenshots**

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment] 2020-08-28 14:09
I'm having a hard time following your steps. Can you make them simpler/clearer and update this a bit. Im not certain if im seeing an issue and what you expect. This is what i see:

http://localhost:4200/ids-enterprise-ng-demo/datagrid-fixedheader
- change page size to 25
- select first row
- go to page two -> weird the row is selected? Is that the issue?

Hard for me to tell but maybe you might try the allowSelectAcrossPages datagrid option?

**Comment by kvchaudhari** [comment] 2020-08-28 14:13
We have reproduced this issue on enterprise project -

For UI changes, created fork branch. PSB link -
**https://github.com/kvchaudhari/enterprise-ng**

 Also, created separate API projects, as we are using server side paging. Please run this API project separately, then run UI project. (attached API Project :- Enterprize-ng_API.zip )
[Enterprize-ng_API.zip](https://github.com/infor-design/enterprise/files/5142505/Enterprize-ng_API.zip)

**Comment by tmcconechy** [comment] 2020-08-28 14:23
Can you update the steps so they are more clear? Not really sure what you mean about running it seperate what are the steps for that?

keep the selected records without traversing the page of selected record - not sure what that means?
It is not showing value which we have selected on page number 2. It is not showing values from page which we have not traversed. - not sure what that means?

**Comment by kvchaudhari** [comment] 2020-09-01 15:17
Hi Tim,
Yes we have already added the "allowSelectAcrossPages" in datagrid options.

Below is the sample example -
1. I have already selected 2 records i.e. "123" (from Page No-1) and "789" (from Page No -2). 
2. Open the model pop up, I can see the "123" is selected which is on Page-1. 
3. Now I select one more record "456" on page number 1 and click on "select" button. 
4. I got the output like > "123", "456"

Expected Output should be :- "123" (Page-1), "456" (Page-1), "789" (Page-2)

Issue :- I have visited only Page -1 not on Page-2. It has not fetched the records from Page-2. 
So, it keeps only the history of those records of Page where user had visited.

Please let us know if any more details require.

**Comment by dhumalkishor** [comment] 2020-09-03 13:32
Hi Tim,

Have checked attached project? We have created example based on our usage. Please check and let us know if you require any details. 

Regards,
Kishor

**Comment by dhumalkishor** [comment] 2020-09-11 13:27
Hi Tim,

any updates on this issue?

**Comment by deep7102** [comment] 2020-09-11 16:50
Hi @kvchaudhari @dhumalkishor 

@tmcconechy is on DTO and will be back next week, I was reading thru this issue not 100% sure what expected results we looking here. if like to pre selecte any row with server-side paging before visit the page, as current did not see the possible solution. Or if like to keep selected rows across the pages you can try to add these two settings, hope this help.

```
1) allowSelectAcrossPages: true
2) columnIds: ['productName', 'quantity', 'productId'] // two or more any columns used in grid
```

**Comment by kvchaudhari** [comment] 2020-09-21 05:39
HI @deep7102 ,

We have already consumed these properties in grid options. But it doesn't work for us.

**Comment by tmcconechy** [comment] 2020-09-21 13:27
I still dont really understand how to run this project. Is there any way to make this issue more simple so we can see it on the current examples? I downloaded the project but its not in a format i recognize? Does seem to be an angular project.

Is there any way to see the same issue on http://localhost:4200/ids-enterprise-ng-demo/datagrid-fixedheader

**Comment by tmcconechy** [comment] 2020-09-21 13:38
Can it be reproduced here https://master-enterprise.demo.design.infor.com/components/datagrid/test-paging-multiselect-select-across-page.html ? With some sequence of steps?

**Comment by kvchaudhari** [comment] 2020-10-05 14:44
Hi Tim,

Please take code from URL - **https://github.com/kvchaudhari/enterprise-ng/tree/7.6.x**

We have reproduced this issue on datagrid-fixheader page - http://localhost:4200/ids-enterprise-ng-demo/datagrid-fixedheader

Steps to reproduce issue :- 
1. Click on "Show Popup Grid" button
2. Once popup opens, select any 2 values for Page No - 1 and select any 1 value from Page No -2 and Click on "Select"
3. Selected values will be displayed from Page 1 and Page 2 (i.e. total 3 records)
4. Once again click on "Show Popup Grid" button and **don't visit Page No-2** and Click on "Select"
4. Now it is displaying records from Page No - 1 only. (i.e. 2 records)

E.g. From Page-1 selected "214220, 214221" and Page -2 selected "214248".
Result showing - 214220, 214221
Expected Result - 214220, 214221, 214248

Please let us know if anything require.

**Comment by dhumalkishor** [comment] 2020-10-15 13:31
Hi Tim,
Any updates on this JT?

Regards,
Kishor

**Comment by tmcconechy** [comment] 2020-10-15 13:34
I'll put it in the next sprint. I think this isnt an easy fix as a workaround you could maybe try client side paging?

**Comment by tmcconechy** [comment] 2020-11-30 16:18
I checked into this and its pretty complicated. And its all based on what your doing in the example. I would suggest:

1) Using the lookup instead of a custom modal and redoing all the logic on your end. 
2) Or change to client side paging for this grid

The bug is around this line https://github.com/kvchaudhari/enterprise-ng/blob/7.6.x/src/app/datagrid/datagrid-fixedheader.demo.ts#L238 for the second time the grid is opened the data for the second page isnt there yet. So its selecting "zero" for those rows. Which wont work. So client side paging would prevent that.

The lookup code that solves this is https://github.com/infor-design/enterprise/blob/master/src/components/lookup/lookup.js#L709 which is called initially and every time the page changes. The _selectedRows array is populated with the selected rows that arent on the current page. So you might be able to implement similar logic but seems a bit redundant and out of scope for us to implement for you.

It does work on https://master-enterprise.demo.design.infor.com/components/lookup/example-multiselect-paging-serverside.html but im seeing a bug on the counts. So pushing a fix for that. But the rest of this issue i think is on your end to fix/or change what your doing.

**Closed** 2020-12-01 15:09 UTC
Labels: [5], type: support :sos:

**Comment by dhumalkishor** [comment] 2020-12-09 12:07
Hi Tim,

 We tried with ids-enterprise-ng-demo/lookup example and found one issue there. Please follow below steps to reproduce issue.

1 . Go to ids-enterprise-ng-demo/lookup
2. In Products (Async Results) Multi Select example remove already selected records and click on apply button
Now there is no record selected in lookup.
2. Now click on browse button and open lookup pop up. 
3. In this pop up go to page number 2 and select any record and click on apply button.
4. Now again open that popup and select one record from page 1.

Check previous record get replaced by new one.  Please refer attached video for more details. 
[MultiselectLookup.zip](https://github.com/infor-design/enterprise/files/5665714/MultiselectLookup.zip)



Regards,
Kishor

**Comment by tmcconechy** [comment] 2020-12-09 14:24
I think i see the same issue on https://master-enterprise.demo.design.infor.com/components/lookup/example-multiselect-paging-serverside.html 

1. Open Lookup
1. Click to page 2
1. Select one and apply
1. Reopen
1. Select one on page 1 and apply
1. Should be two selected 

I'm starting to think this is a bit too complicated to allow multi page selection with server side paging because we don't have the data for the pages until you actually go to the page. But you can raise an issue anyways and we can try. The workaround would be to use client side paging.

This issue is around the example submitted so i would consider what you posted a new issue which may or may not be fixable.

**Comment by kvchaudhari** [comment] 2020-12-18 11:19
Hi Tim,

We have added below code in "sohoxi.js" and it looks working fine. Please review the below code and test the functionality.
----------------------------------------------------------------------------------------
selectGridRows: function selectGridRows(val) {
      var selectedId = val;
      var adjust = false;

      if (!val) {
        return;
      }

      if (this.grid && this.settings.options.source) {
        for (var i = this.grid._selectedRows.length - 1; i > -1; i--) {
          if (isNaN(this.grid._selectedRows[i].idx)) {
            this.grid._selectedRows.splice(i, 1);
          }
        }
      } // Multi Select


      if (selectedId.indexOf(this.settings.delimiter) > 1) {
        var selectedIds = selectedId.split(this.settings.delimiter);
        var isFound = false;

        for (var _i = 0; _i < selectedIds.length; _i++) {
          isFound = this.selectRowByValue(this.settings.field, selectedIds[_i]);

          if (this.grid && this.settings.options.source && !isFound) {
            var data = {};
            var foundInData = false;

            for (var j = 0; j < this.grid._selectedRows.length; j++) {
              if (this.grid._selectedRows[j].data[this.settings.field].toString() === selectedIds[_i].toString()) {
                foundInData = true;
              }
            }

            if (!foundInData) {
              data[this.settings.field] = selectedIds[_i];

              this.grid._selectedRows.push({
                data: data
              });
            }

            adjust = true;
          }
        } // There are rows selected off page. Update the count.


        if (adjust) {
          this.modal.element.find('.contextual-toolbar .selection-count').text("".concat(selectedIds.length, " ").concat(Locale.translate('Selected')));
        }

        return;
      }
      _**else {
        var selectedIds = [];
        selectedIds[0] = selectedId;
        var isFound = false;

        for (var _i = 0; _i < selectedIds.length; _i++) {
          isFound = this.selectRowByValue(this.settings.field, selectedIds[_i]);

          if (this.grid && this.settings.options.source && !isFound) {
            var data = {};
            var foundInData = false;

            for (var j = 0; j < this.grid._selectedRows.length; j++) {
              if (this.grid._selectedRows[j].data[this.settings.field].toString() === selectedIds[_i].toString()) {
                foundInData = true;
              }
            }

            if (!foundInData) {
              data[this.settings.field] = selectedIds[_i];

              this.grid._selectedRows.push({
                data: data
              });
            }

            adjust = true;
          }
        } // There are rows selected off page. Update the count.


        if (adjust) {
          this.modal.element.find('.contextual-toolbar .selection-count').text("".concat(selectedIds.length, " ").concat(Locale.translate('Selected')));
        }

        return;
      }**_

      this.selectRowByValue(this.settings.field, selectedId);
    },
