### ISSUE TITLE
Toolbar: Toolbar input missing on responsive/mobile view(454x823 below)

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5388] opened 2021-07-02 08:10 UTC
**Describe the bug**
Toolbar input missing on responsive/mobile view(454x823 below)

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/toolbar/example-toolbar-input.html
2. See error

**Expected behavior**
Toolbar input should be responsive

**Version**
v4.53.0-dev

**Screenshots**
Responsive view(454x823 below)
<img width="299" alt="Screen Shot 2021-07-02 at 4 07 33 PM" src="https://user-images.githubusercontent.com/84306838/124242711-9f831780-db4f-11eb-9cff-7779c3cef508.png">

iPhone 12 Pro Max(actual device)
<img width="357" alt="Screen Shot 2021-07-02 at 4 08 08 PM" src="https://user-images.githubusercontent.com/84306838/124242782-b590d800-db4f-11eb-85f0-d39a51981ca3.png">

Samsung Galaxy S20+(browserstack)
<img width="373" alt="Screen Shot 2021-07-02 at 4 08 31 PM" src="https://user-images.githubusercontent.com/84306838/124243001-ee30b180-db4f-11eb-9163-543f6e68691a.png">

**Platform**
Responsive view and mobile devices(454x823 below)

**Additional context**
N/A

**Comment by EdwardCoyle** [comment] 2021-07-13 16:45
This one's a weird case because:
- In this example specifically, the input field is not a Searchfield, by design.
- The only items that will spill over to the Overflow menu are buttons and menu buttons.  Inputs and Searchfields won't do this.
- The input field is too big to fit alongside the other elements in this view, so it's hidden but not overflowed.

Ideally, someone wouldn't be using a regular input inside the Toolbar at all, opting for Searchfield instead, or moving this field somewhere outside the Toolbar.  Maybe we should consider scrapping this example?

**Comment by tmcconechy** [comment] 2021-07-13 16:47
Yeah maybe simply move this over to a test? Im good with that for sure

**Closed** 2022-03-23 08:26 UTC
Labels: type: bug :bug:, priority: minor, [2]

**Comment by CindyMercadoReyes** [comment] 2022-03-23 19:47
This issue is now resolved.

**Comment by davidcarlsonberg** [comment] 2022-03-23 20:35
So make this a test file instead of an example file?

**Comment by tmcconechy** [comment] 2022-03-24 13:14
Yeah i was thinking that it could just be a test. But its ok now, not a big deal and this is done and closed
