### ISSUE TITLE
Lookup: Not showing selected value from widget configuration

### ISSUE THREAD

**Issue by spathak21** [infor-design/enterprise#4732] opened 2021-01-11 11:35 UTC
**Describe the bug**
Lookup control as one of the setting used in widget configuration not showing the selected item.

**To Reproduce**
1. Go to 'https://mingle-ci01-portal.mingle.awsdev.infor.com/INFORGRCCI01_TST/'
2. Go to homepages
3. Add 'Infor GRC Violation Count' widget on home page.(Issue is for all widgets but for eg refer Infor GRC Violation Count widget.
4. Go to 'Configure..' option from three dots available on widget.
5. Check 'Application Instances'/'Data sources'/'Analysis' filter.
6. As per requirement we have selected 'All' as by default value.
7. Right now neither it is showing 'All' or any other selected value from lookup.

**Expected behavior**
Lookup should show selected value.

**Version**
Infor Ming.le Homepages 2021-03
IDS Version : 4.35.0

**Screenshots**
![image](https://user-images.githubusercontent.com/58286807/104177686-2bcd4100-542f-11eb-8db9-af65eb3b59eb.png)

**Platform**
OS Version: Windows 10
Browser Name: Chrome, IE

**Additional context**

**Comment by tmcconechy** [comment] 2021-01-11 14:18
I was unable to login to that link and check it out. Normally we only accept bugs with a reduced test case so we can debug the issue. See if you can modify the current examples to show the issue and upload. Or perhaps create an example in stackblitz to illustrate the issue / question https://stackblitz.com/

Or can you reproduce it here? https://master-enterprise.demo.design.infor.com/components/lookup ?

Is this a general question? For example how do i mark all items selected when opening the lookup?
Or maybe its just an application issue? If you are trying to populate the field you just set the value on the input directly.

As it stands I cant reproduce this issue

**Comment by spathak21** [comment] 2021-01-13 11:49
Hi Tim,
I have attached the simple widget example where I have facing the issue. Let us know it is sufficient to reproduce at your end.
Thanks,
Supriya.
[infor.approva.lookupwidget.zip](https://github.com/infor-design/enterprise/files/5808374/infor.approva.lookupwidget.zip)

**Comment by tmcconechy** [comment] 2021-01-13 15:00
Can you try and reduce the example down so its just showing the UI issue. Preferably that means not needing a back end and maybe just a single Html fill I can run in the browser.

Looking at this that you sent im really not sure where to start in the code. ( i dont generall use home pages as we are at a lower level - just the UI)

here is a good article https://css-tricks.com/reduced-test-cases/ following the practice helps us so much in fixing bugs...

**Comment by spathak21** [comment] 2021-01-15 06:33
For simple html I have downloaded the **enterprise-ng-9.0.0** which uses 4.35.0 but facing lots of problem while starting it. npm install is completed but facing the issue related to  SOHO eg below-

**public onChangeTheme(ev: SohoChangeThemePersonalizeEvent) {
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/personalize-menu/personalize-menu.component.ts:121:29 - error TS2304: Cannot find name 'SohoChangeColorsPersonalizeEvent'.**

Could you please help me to solve those error, so I can reproduce in that environment.
Also please share if the steps are available to up the ids demo project.
cmd run as so far in my localhost - npm install, npm start.
Thanks,
Supriya.

**Comment by volante007** [comment] 2021-01-15 09:53
I think it's this
https://github.com/infor-design/enterprise-ng/issues/972

**Comment by tmcconechy** [comment] 2021-01-15 16:59
@spathak21 see if this helps https://github.com/infor-design/enterprise-ng/blob/master/docs/DEVELOPER.md#install
Im working on a https://stackblitz.com/edit/ids-quick-start where you can reproduce issues but its broken at the moment so will fix that next week.

If you can confirm infor-design/enterprise-ng#972 the issue then we may need need a reproduction from you then

**Comment by spathak21** [comment] 2021-01-18 07:45
Yes Tim, we have facing the similar issue as like  infor-design/enterprise-ng#972.
We have also wrote the on change event of lookup and it shows the blank value on lookup. But on commenting the lookup change event it shows the selected value properly.
On change event which we have wrote as below-
**onConnectionChange(event: any) {
        this.violationFilterOption.applicationinstances = [];
        for (const element of event) {
            this.violationFilterOption.applicationinstances.push(element.data);
        }
    }**
Thanks,
Supriya.

**Comment by tmcconechy** [comment] 2021-01-18 18:55
Ok let’s follow up that it’s fixed once that issue is resolved

**Comment by dhumalkishor** [comment] 2021-01-19 06:17
Hi Tim,

when we can expect fix for this issue? Is there any plan to provide patch for 4.35.0 version?

Regards,
Kishor

**Comment by tmcconechy** [comment] 2021-01-19 14:21
I was going to patch an NG version today. As this is an NG fix. Thinking about doing it on 9.1.x (NG 11) does that work?

**Comment by tmcconechy** [comment] 2021-01-19 14:23
Closing this in favor of https://github.com/infor-design/enterprise-ng/issues/972

**Closed by tmcconechy** 2021-01-19 14:23 UTC
Labels: [3], status: clarification, type: support :sos:

**Comment by tralarn** [comment] 2021-01-19 14:59
Yes, NG 9.1.x is good!

/Fredrik
