### ISSUE TITLE
The close icon on the soho-toolbar-searchfield component cannot be focused using the keyboard

### ISSUE THREAD

**Issue by ceszilla** [infor-design/enterprise#4780] opened 2021-01-27 04:06 UTC
**Describe the bug**
[VPAT] The close icon on the soho-toolbar-searchfield component cannot be focused using the keyboard

**To Reproduce**
On the soho toolbar search field, type in a search text. Notice that the close icon will appear. This image though, cannot be focused using the keyboard.

**Expected behavior**
Buttons should be focusable using the keyboard

**Version**
- ids-enterprise: v4.36.2

**Screenshots**
Can be found in the ticket linked below

**Platform**
 - Infor Application/Team Name: Landmark Client
 - Device: (if applicable) N/A
 - OS Version: Windows 10 Ent
 - Browser Name: Chrome
 - Browser Version: 88.0.4324.104 (Official Build) (64-bit)

**Additional context**
https://jira.lawson.com/browse/LMCLIENT-34042

**Comment by tmcconechy** [comment] 2021-01-27 14:59
Going to call this a duplicate of https://github.com/infor-design/enterprise/issues/4127
For version 5.0 we have added a setting to enable tabbing to trigger fields but didnt complete it yet so did not close it. But its also bit complicated/disruptive because the users will complain about the extra tab stops and we didnt add this to the latest version.

Also not that alt+delete will clear the text or backspace can be used with the keyboard. https://master-enterprise.demo.design.infor.com/components/searchfield/test-clearable.html

**Closed by tmcconechy** 2021-01-27 14:59 UTC
Labels: status: duplicate, type: bug :bug:
