### ISSUE TITLE
DataGrid: Render/Set Active Cell Issue when Grids on multiple tabs, since v4.24

### ISSUE THREAD

**Issue by nbeare-infor** [infor-design/enterprise#3348] opened 2020-01-20 14:35 UTC
Since code which set the activeCell (if not already set), was removed from the afterRender 

```
function, pages on which multiple tabs containing Grids, give a TypeError in the setActiveCell function:-
_TypeError: Cannot read property 'find' of null
    at Datagrid.setActiveCell (sohoxi.js:86114)
    at Datagrid.afterRender (sohoxi.js:79814)_
.
.
.
```

An Error results when a page contains multiple tabs where more than 1 tab has a DataGrid on it.

**To Reproduce**
Steps to reproduce the behavior:-
1. Invoke the page with the tab controller which has more than one tab containing a DataGrid
2. See error

**Expected behavior**
The page should render without complaint.

**Version**
v4-24-0

**Screenshots**
Having selected a row from the Datagrid on the Initial page:-
![Screen1](https://user-images.githubusercontent.com/49482971/72733792-7a375f00-3b90-11ea-8ad8-8d7171b3ad4f.png)

a second page should render with the initial tab containing another Datagrid, displayed:-
![View2Tab1DefaultGrid](https://user-images.githubusercontent.com/49482971/72733870-a81ca380-3b90-11ea-8b28-4c8b70c6836c.png)

Clicking the second tab should display that tab with a third Datagrid on it:-
![View2Tab2Grid](https://user-images.githubusercontent.com/49482971/72734067-f92c9780-3b90-11ea-8796-2ae1a6db65f0.png)

Instead, errors setting the active cell before the second screen is displayed.

**Platform**
 - Device: HP Elitebook
 - OS: Windows 10
 - Browser Name: chrome
 - Browser Version: latest (79.0.3945.117)

**Comment by tmcconechy** [comment] 2020-01-21 17:30
Both me and @deep7102 tried to make an example to reproduce this and could not. We tried the following example with a tab on page one and one on page three.

```
<div class="row">
	<div class="twelve columns">

		<div id="tabs-normal" class="tab-container">
			<ul class="tab-list">
				<li class="tab is-selected"><a href="#tabs-normal-contracts">Contracts</a></li>
				<li class="tab"><a href="#tabs-normal-opportunities">Opportunities</a></li>
				<li class="tab"><a href="#tabs-normal-attachments">Attachments</a></li>
				<li class="tab"><a href="#tabs-normal-contacts">Contacts</a></li>
				<li class="tab"><a href="#tabs-normal-notes">Notes</a></li>
			</ul>
			<div id="tabs-normal-contracts" class="tab-panel">
				<div id="datagrid2">
				</div>
			</div>
			<div id="tabs-normal-opportunities" class="tab-panel">
				<p>Bricks-and-clicks? Evolve ubiquitous matrix B2B 24/365 vertical 24/365 platforms standards-compliant global leverage
					dynamic 24/365 intuitive ROI seamless rss-capable. Cutting-edge grow morph web services leverage; ROI, unleash reinvent
					innovative podcasts citizen-media networking.</p>
			</div>
			<div id="tabs-normal-attachments" class="tab-panel">
				<div class="contextual-toolbar toolbar is-hidden">
					<div class="title selection-count">1 Selected</div>
					<div class="buttonset">
						<button class="btn" type="button" id="remove-btn">
          <svg class="icon" focusable="false" aria-hidden="true" role="presentation">
            <use xlink:href="#icon-delete"></use>
          </svg>
          <span>Remove</span>
        </button>
					</div>
				</div>

				<div id="datagrid">
				</div>
			</div>
			<div id="tabs-normal-contacts" class="tab-panel top-padding">
				<p>Bricks-and-clicks? Evolve ubiquitous matrix B2B 24/365 vertical 24/365 platforms standards-compliant global leverage
					dynamic 24/365 intuitive ROI seamless rss-capable. Cutting-edge grow morph web services leverage; ROI, unleash reinvent
					innovative podcasts citizen-media networking.</p>
			</div>
			<div id="tabs-normal-notes" class="tab-panel">
				<p> Post incentivize; rich-clientAPIs customized revolutionize 24/365 killer incentivize integrate intuitive utilize!</p>
			</div>
		</div>

	</div>
</div>

<script>
  $('body').one('initialized', function () {
        var grid,
          columns = [],
          data = [];

        // Some Sample Data
        data.push({ id: 1, productId: 2142201, productName: 'Compressor', activity:  'Assemble Paint', quantity: 0, price: 210.99, status: 'OK', orderDate: new Date(2014, 12, 8), action: 'Action'});
        data.push({ id: 2, productId: 2241202, productName: 'Different Compressor', activity:  'Inspect and Repair', quantity: 2, price: 210.99, status: '', orderDate: new Date(2015, 7, 3), action: 'On Hold'});
        data.push({ id: 3, productId: 2342203, productName: 'Compressor', activity:  'Inspect and Repair', quantity: 1, price: 120.99, status: null, orderDate: new Date(2014, 6, 3), action: 'Action'});
        data.push({ id: 4, productId: 2445204, productName: 'Another Compressor', activity:  'Assemble Paint', quantity: 3, price: 210.99, status: 'OK', orderDate: new Date(2015, 3, 3), action: 'Action'});
        data.push({ id: 5, productId: 2542205, productName: 'I Love Compressors', activity:  'Inspect and Repair', quantity: 4, price: 210.99, status: 'OK', orderDate: new Date(2015, 5, 5), action: 'On Hold'});
        data.push({ id: 5, productId: 2642205, productName: 'Air Compressors', activity:  'Inspect and Repair', quantity: 41, price: 120.99, status: 'OK', orderDate: new Date(2014, 6, 9), action: 'On Hold'});
        data.push({ id: 6, productId: 2642206, productName: 'Some Compressor', activity:  'inspect and Repair', quantity: 41, price: 123.99, status: 'OK', orderDate: new Date(2014, 6, 9), action: 'On Hold'});

        //Define Columns for the Grid.
        columns.push({ id: 'selectionCheckbox', sortable: false, resizable: false, formatter: Formatters.SelectionCheckbox, align: 'center'});
        columns.push({ id: 'productId', name: 'Product Id', field: 'productId', formatter: Formatters.Readonly});
        columns.push({ id: 'productName', name: 'Product Name', sortable: false, field: 'productName', formatter: Formatters.Hyperlink});
        columns.push({ id: 'quantity', name: 'Quantity', field: 'quantity'});
        columns.push({ id: 'price', name: 'Price', field: 'price', formatter: Formatters.Decimal});
        columns.push({ id: 'orderDate', name: 'Order Date', field: 'orderDate', formatter: Formatters.Date, dateFormat: 'M/d/yyyy'});

        //Init and get the api for the grid
        grid = $('#datagrid, #datagrid2').datagrid({
          columns: columns,
          dataset: data,
          selectable: 'multiple',
          toolbar: {title: 'Data Grid Header Title', personalize: true, results: true, actions: true, rowHeight: true, selectCount: true}
        }).on('selected', function (e, args, action) {
          console.log(args.length, action);
        }).data('datagrid');

        // Set Rows as Selected via the API
        //grid.selectedRows([0]);
        //grid.selectRow(0);
  });

</script>
```

Drop this into app/views/components/datagrid/test-in-tabs.html and run http://localhost:4000/components/datagrid/test-in-tabs.html

Could you @nbeare-infor add an example so we can see the issue and update the steps? We tried this on master?

**Comment by tmcconechy** [comment] 2020-01-31 21:01
Closing this issue we were unable to reproduce, if you have a better example please feel free to add it with new steps.

**Closed by tmcconechy** 2020-01-31 21:01 UTC
Labels: [2], status: cant reproduce, type: regression bug  :leftwards_arrow_with_hook:
