### ISSUE TITLE
Tabs module '+' focus is not aligned 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3225] opened 2019-12-10 10:32 UTC
**Describe the bug**
Tabs module '+' focus is not aligned 

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/tabs-module/example-toolbar-with-spillover.html#order-123456
2. Click '+' button 

**Expected behavior**
Focus should be aligned 

**Version**
Beta 4.24

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/70522076-605f3100-1b7b-11ea-9a0e-fef2ec875732.png)

**Platform**
All Browsers & OS

**Additional context**
N/a

**Comment by tmcconechy** [comment] 2019-12-10 14:35
Hmm mine is looking OK?
![Screen Shot 2019-12-10 at 9 34 48 AM](https://user-images.githubusercontent.com/814283/70538591-5d8b1e80-1b30-11ea-8d54-9d1634ab9c94.png)

**Comment by tmcconechy** [comment] 2020-01-07 14:45
Was not able to reproduce this issue so closing.

**Closed by tmcconechy** 2020-01-07 14:45 UTC
Labels: [2], status: cant reproduce, type: bug :bug:
