### ISSUE TITLE
Datagrid - Saved row height setting not reflected correctly in toolbar menu

### ISSUE THREAD

**Issue by dmcodrum** [infor-design/enterprise#3550] opened 2020-02-26 19:35 UTC
**Describe the bug**
For datagrids where the row height settings are saved, the selected ('checked') row height is always set to Normal, not the saved, and correctly displayed, row height.

**To Reproduce**
1. Execute the 'Test-Save-Settings' datagrid demo. '../components/datagrid/test-save-settings.html'
2. In the datagrid toolbar change the row height to 'Short'.
3. Note row height is now short.
4. Open datagrid toolbar again, note 'Short' is the checked row height.
5. Reload the 'Test-Save-Settings' page.
6. Note the displayed row height is short - as expected.
7.  Open datagrid toolbar , note 'Normal' is the checked row height.

**Expected behavior**
In step 7 above, the checked row height should be 'Short'.

**Version**
IDS:  4.25.2
IDS NG: 6.4.1 

**Screenshots**
![image](https://user-images.githubusercontent.com/39279254/75380436-0da53380-58a5-11ea-9c36-d4d129fd684f.png)

**Platform**
 - OS Version: Windows 10 
 - Browser Name: chrome
 - Browser Version:  80.0.3987.122 

**Additional context**

**Comment by andriivarhanov** [comment] 2021-08-10 13:50
@tmcconechy I can't reproduce, most likely it's been fixed when short changed to small and added extra small option.

tested on:
http://localhost:4000/components/datagrid/test-save-settings.html
http://localhost:4000/components/datagrid/test-group-editable-addrow.html (saveUserSettings enabled)
http://localhost:4000/components/datagrid/test-group-headers-landmark.html (saveUserSettings enabled)

**Comment by tmcconechy** [comment] 2021-08-10 13:52
thanks @andriivarhanov your right i cant reproduce either. closing this. considering we changed all the option names i assume it was fixed then.

**Closed by tmcconechy** 2021-08-10 13:52 UTC
Labels: type: bug :bug:, [3], focus: datagrid

**Comment by jbrcna** [comment] 2021-08-11 05:38
This is now working as expected. moving this ticket to Done.
verified in v4.55.0-dev
https://main-enterprise.demo.design.infor.com/components/datagrid/test-save-settings
![Large GIF (1348x444)](https://user-images.githubusercontent.com/56722184/128974892-00808ab0-6d33-472a-926f-e85c476de9a2.gif)
