### ISSUE TITLE
Forms: Alignment issue on dropdown inside a compact form

### ISSUE THREAD

**Issue by chamilledyan** [infor-design/enterprise#4434] opened 2020-09-29 16:00 UTC
**Describe the bug**
Dropdown is not aligned with input text box if fields are inside a compact form & compound-field

**To Reproduce**
1. Create a form with class="form-layout-compact"
2. Create a <div class="compound-field">
3. Inside compound field, create a input text and a dropdown
![image](https://user-images.githubusercontent.com/68043861/94582871-5a277600-02af-11eb-8b25-88d9f44975a5.png)

**Expected behavior**
Elements should be aligned

**Version**

- ids-enterprise:  4.32.1

**Screenshots**
![image](https://user-images.githubusercontent.com/68043861/94582908-690e2880-02af-11eb-893d-173cc856464c.png)
![image](https://user-images.githubusercontent.com/68043861/94582948-74f9ea80-02af-11eb-82f7-172e1a9168f9.png)
[compact-form.txt](https://github.com/infor-design/enterprise/files/5300331/compact-form.txt)

**Platform**
 - Infor Application/Team Name: Mobile Supply Chain Mgt
 - Device: Desktop
 - OS Version: Windows 10
 - Browser Name: Microsoft Edge Chrome
 - Browser Version: 85.0.4183.121

**Additional context**

**Comment by tmcconechy** [comment] 2021-04-16 16:37
Closing this as the issue is rather old and i cant seem to reproduce it on https://main-enterprise.demo.design.infor.com/components/form/example-compact-mode.html anymore

**Closed by tmcconechy** 2021-04-16 16:37 UTC
Labels: [3], type: bug :bug:
