### ISSUE TITLE
Dropdown: Dropdown Error Message no longer appears after $('body').resetForm();

### ISSUE THREAD

**Issue by jeffuycoque** [infor-design/enterprise#2501] opened 2019-07-17 07:53 UTC
**Describe the bug**
On our application, the undo/clear button resets our field values using $('body').resetForm() However the dropdown Error Message would no longer appear after resetForm.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/dropdown/example-validation.html
2. Select Blank Value to trigger required validation
3. Open Developer Tool and on console execute $('body').resetForm() 
4. Select Blank Value to trigger required validation

**Expected behavior**
Error message should appear
![image](https://user-images.githubusercontent.com/49975141/61356882-d059db80-a8a9-11e9-9b4f-37ec955b8f6f.png)

**Actual behavior**
Error message is not being rendered
![image](https://user-images.githubusercontent.com/49975141/61356653-60e3ec00-a8a9-11e9-8aa5-0f786727ecd6.png)

Upon checking the resetForm doesn't clear the existing rulte type message of the dropdown field
![image](https://user-images.githubusercontent.com/49975141/61356814-c20bbf80-a8a9-11e9-8e8b-feaade07c3ea.png)

There is a logic in addMessage function of validator.js that checks if there is an existing dataMsg for the dropdown field. If the dataMsg is available, the function exits without going through the this.showInlineMessage(field, rule, isHelpMessage); code that would show the Error Icon and Message.

![image](https://user-images.githubusercontent.com/49975141/61357127-4eb67d80-a8aa-11e9-81ff-69020d28ad37.png)

Code that renders the Error Message
![image](https://user-images.githubusercontent.com/49975141/61357289-87eeed80-a8aa-11e9-8078-93595903c10a.png)

Our expected fix would be to add removeErrorMessage for the dropdown fields cleared using $('body').resetForm()

**Platform**
OS Version: Windows 10
Browser Name: Google Chrome

**Comment by tmcconechy** [comment] 2019-07-17 13:30
Tested this back to 4.15 and seeing the same issue. So this hasn't worked for some time.
@jeffuycoque If you do see a fix and feel like making a pull request for the fix please do 👍and we can review. If not we will get to this in the future.

**Comment by tmcconechy** [comment] 2020-10-06 15:45
This issue is a duplicate of https://github.com/infor-design/enterprise/issues/4259 and i retested it and it has been fixed over there.

**Closed by tmcconechy** 2020-10-06 15:45 UTC
Labels: [3], team: pathway, type: bug :bug:
