### ISSUE TITLE
Popover: attribute is not replaced in outer div

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#5257] opened 2021-06-01 18:18 UTC
**Describe the bug**
When updating our popovers with the name attribute I noticed that if another popover is opened after the first, the popover still keepd the name from the first popover on the outer popover div.

**To Reproduce**

1. Go to '...' .... Not sure, probably need a new test case. I'll see if I can add that later.

**Expected behavior**
The name (other attirbute) of all elements for the second popover should be updated to the new name.

**Version**

- ids-enterprise: 4.51.1

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/120348772-c7d3e800-c2fd-11eb-8890-3602c7a132ce.png)

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 90.0.4430.212 (Official Build) (64-bit)

**Additional context**

**Comment by SofiK** [comment] 2021-06-01 18:20
If the intension is that I should have the same

**Comment by SofiK** [comment] 2021-06-01 18:21
woops, accidentally closed this issue. Will see if I can create a test html.

**Comment by tmcconechy** [comment] 2021-07-08 13:18
@SofiK we tried to look at this but we couldn't figure out how you are adding that name. So we will need more info to reproduce this.

Thanks!

**Comment by tmcconechy** [comment] 2021-07-29 15:11
Closing this as unable to reproduce

**Closed by tmcconechy** 2021-07-29 15:11 UTC
Labels: [2], status: clarification, team: homepages, type: bug :bug:
