### ISSUE TITLE
Datagrid - Deselect not updating row count with setting selectOnlyCurrentPage ON

### ISSUE THREAD

**Issue by AnaLauraMartinez** [infor-design/enterprise#4921] opened 2021-03-08 19:34 UTC
Description:
Datagrid has the selectOnlyCurrentPage ON
1. The user selects all (count shows as 20 rows)
2. goes to the next page and selects 10 rows (count shows 30 rows)
3. return to the previous page and uncheck Select all (count is not updated)

Bug:
Count is not updated when deselect rows

Expected:
Count should reflect the deselect of the 20 rows of the first page and show count = 10 rows (from the second page)

Current workaround:
Deselect manually each row does update the count

**Version**
"ids-enterprise-ng": "^9.1.5",
"ids-identity": "^3.0.5",

**Comment by tmcconechy** [comment] 2021-08-12 15:26
https://main-enterprise.demo.design.infor.com/components/datagrid/test-paging-select-clientside-multiple-current-page.html might be reproducing this

**Comment by tmcconechy** [comment] 2021-08-12 15:27
@AnaLauraMartinez are you doing this server or client side? Also do you have a screen shot? want to see where the counts are

**Comment by andriivarhanov** [comment] 2021-08-12 15:55
@tmcconechy I have no luck reproducing it,
layouts are:
https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
https://main-enterprise.demo.design.infor.com/components/datagrid/example-grouping-editable.html
https://main-enterprise.demo.design.infor.com/components/datagrid/example-mixed-selection.html

`selectOnlyCurrentPage ` setting doesn't exist, there is `selectAllCurrentPage` probably the same

**Comment by AnaLauraMartinez** [comment] 2021-08-12 19:26
You are correct it is selectAllCurrentPage. I will post a video of the issue shortly
![image](https://user-images.githubusercontent.com/17933529/129256866-663ce8f3-6f72-4918-bb3e-18ce6fe91feb.png)

**Comment by AnaLauraMartinez** [comment] 2021-08-12 19:29
[](url)

**Comment by AnaLauraMartinez** [comment] 2021-08-12 19:32
[](url)
![image](https://user-images.githubusercontent.com/17933529/129257427-1f933956-ca72-4bd9-99bd-57b90c72eb41.png)
![image](https://user-images.githubusercontent.com/17933529/129257462-aea4122a-3099-4488-a8a1-2e6d6d78ab5b.png)
![image](https://user-images.githubusercontent.com/17933529/129257519-63f05aba-c916-4a67-8bc8-2d07a2ae86e1.png)
![image](https://user-images.githubusercontent.com/17933529/129257593-13d3e919-76e2-4004-a43d-8ce67663ba84.png)
![image](https://user-images.githubusercontent.com/17933529/129257644-7a8c97bd-8c89-499b-9913-a53965850737.png)

I have a video but it is too big to load.

**Comment by tmcconechy** [comment] 2021-08-12 19:37
I think you can reproduce it https://main-enterprise.demo.design.infor.com/components/datagrid/test-paging-select-clientside-multiple-current-page.html @andriivarhanov its just missing the toolbar on https://main-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html that you could add to that example to see the counts

But if you try https://main-enterprise.demo.design.infor.com/components/datagrid/test-paging-select-clientside-multiple-current-page.html  as is you can see it

- select all on page one
- go to page 2
- select all on page two
- go back (shouldnt be selected as its not current page)

Is that your expectation as well @AnaLauraMartinez  ?

**Comment by AnaLauraMartinez** [comment] 2021-08-12 20:46
The problem is the counter. In the first screen shot I am in page 2 I selected all (25 rows), then go to page 3 select 2 more the counter says 27 rows when I go back to page 2  I click in deselect all and the counter never changes to 2 which are the rows in page 3 that still selected. It stays as 27.

It is not so much the select button but the row counter that is wrong.

**Comment by tmcconechy** [comment] 2021-08-12 20:47
So its ok with what it selects just the count is wrong 👍🏻

**Comment by AnaLauraMartinez** [comment] 2021-08-12 20:47
correct

**Comment by ericangeles** [comment] 2021-09-09 10:14
@tmcconechy I think this has been fixed on `4.53.x`. I see that they are using `9.1.5` NG so I tested the `4.38.x` assuming that this was the version of the EP in NG.

I created a test page client-side with the toolbar and it's working as expected. I checked the `4.38.x` and do the same and that's when I saw the issue.

And also, I dug into the versions of EP and the count issue occurs up until `4.52.x` but fixed on `4.53.x` EP.

**Comment by AnaLauraMartinez** [comment] 2021-09-09 11:49
I tested in our new upgraded environment 10.2.1 and it is resolved.

**Comment by ericangeles** [comment] 2021-09-09 11:51
Glad to hear that @AnaLauraMartinez

**Comment by ericangeles** [comment] 2021-09-09 12:05
I'll PR the test page for further testing.

**Comment by AnaLauraMartinez** [comment] 2021-09-10 15:39
While testing I found a bug. 

1. Select all in the first page.
2. Go to second page and select all records.
3. Go back to the first page and click deselect, it looks like only the first page rows were unselected, counter is updated. 
4. Click to the next page. Counter disappears and no records are selected.

Expected: it should only deselect the rows in the first page and keep counter and rows selected in the rest of the pages.

**Closed** 2021-09-13 13:18 UTC
Labels: type: bug :bug:, [3], team: ion

**Comment by ericangeles** [comment] 2021-09-14 12:16
@AnaLauraMartinez, it works fine on the PR test page. Where did you test it by the way? I did the following steps you mentioned above.

- Selected all on Page 1
- Move to Page 2 and select all (current count is 20)
- Go back to Page 1 and de-select all (count change to 10)
- Move back again to Page 2 (current count is 10)
- I moved to different pages and the count is still 10 (did not change or remove the count)

**Comment by AnaLauraMartinez** [comment] 2021-09-14 13:30
I tested on the demo examples for 10.6.x datagrid-paging-service.demo.ts/html

**Comment by AnaLauraMartinez** [comment] 2021-09-14 13:36
I can also see a deselect for all records when moving from page to page.
1. Select in page 1 all
2. go to page 2 do nothing
3. go to page 1 

Nothing is selected anymore.

**Comment by ericangeles** [comment] 2021-09-14 14:36
Do you have a stack blitz so we can check your implementation? I tested `datagrid-dirty-indication.html` on the NG repo, and it seems to work well. I just added the `selectAllCurrentPage: true` since it has a count toolbar. Maybe add a couple of data to show more paging.

**Comment by tmcconechy** [comment] 2021-09-14 14:38
also maybe we need a new issue even tho this is related just to clean up the history here.

**Comment by janahintal** [comment] 2021-09-16 11:48
QA Passed. This issue is now resolved in https://main-enterprise.demo.design.infor.com/components/datagrid/test-count-in-select-all-current-page-setting

![image](https://user-images.githubusercontent.com/45757016/133606825-cadd8dfd-34dd-431b-9a35-1cc51c312c6c.png)
![image](https://user-images.githubusercontent.com/45757016/133606908-4a83254a-7560-4aef-866a-ba8157779764.png)
