### ISSUE TITLE
Pager: Misaligned "Records Per Page" button in Mobile breakpoints

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#4044] opened 2020-06-15 16:14 UTC
**Describe the bug**
When a pager bar is constrained to a small horizontal area, sometimes the "Records Per Page" button needs to shift to remain visible, and it doesn't always appear to align correctly.  It usually sits on a line beneath the other pager controls, and becomes aligned to the right.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/test-modal-datagrid-two-columns.html
2. Click on "Open Modal"
3. Shrink the browser viewport to a small width to force the records per page button to move.
4. See that it appears to sit underneath the other controls and aligns to the right.

**Expected behavior**
I think if the button is too big to fit here, it should either:
- Push down to the next line and become centered underneath the other pager controls
- Convert to the "collapsed"-style Records Per Page button used by the List/Detail pattern in some cases, [as seen here](https://master-enterprise.demo.design.infor.com/patterns/list-detail-paging-pagesize-selector.html).

**Version**
Discovered in `v4.30.0-dev`

**Screenshots**
![Screen Shot 2020-06-15 at 12 06 59 PM](https://user-images.githubusercontent.com/3249601/84680618-f5fbc480-af00-11ea-9e9e-9e460dfc741f.png)

**Platform**
 - Any mobile device in portrait orientation

**Additional context**
Discovered while testing #4009

**Comment by tmcconechy** [comment] 2020-06-15 17:13
Yeah this is a known issue. Maybe it should go to the small page size selector we implemented?

**Comment by tmcconechy** [comment] 2020-12-14 19:33
Duplicate of https://github.com/infor-design/enterprise/issues/4675

**Closed by tmcconechy** 2020-12-14 19:33 UTC
Labels: [2], priority: minor, type: bug :bug:
