### ISSUE TITLE
Toolbar Flex Component: High contrast theme not appearing correctly

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1280] opened 2018-11-26 17:28 UTC
**Describe the bug**
Toolbar Flex Component: High contrast theme not appearing correctly

**To Reproduce**
1. Go to URL: http://4130-beta0-enterprise.demo.design.infor.com/components/toolbar-flex/test-gauntlet.html
2. Change the theme to High Contrast
3. The "Text Button" Menu Button" For the first top row the theme is now appearing correctly. 
4. Please see screen shot attached. 

**Expected behavior**
The high contrast them should be consistent 

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![toolbar flex high contrast theme](https://user-images.githubusercontent.com/39101346/49030863-84b9bc80-f176-11e8-9b84-21ee510112b3.png)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [iOS 8]
 - Browser Name [Chrome, safari]

**Additional context**
None

**Comment by tmcconechy** [comment] 2018-11-26 17:37
This is a duplicate of https://github.com/infor-design/enterprise/issues/1249 adding to the QA list so this page can be rechecked after that is merged.

**Closed by tmcconechy** 2018-11-26 17:37 UTC
Labels: status: duplicate

**Comment by brianjuan** [comment] 2018-12-03 12:00
https://4130-rc0-enterprise.demo.design.infor.com/components/toolbar-flex/test-gauntlet.html
Passed QA testing on all browsers, moving to Done.
