### ISSUE TITLE
Sinkpage: Text Input Field - Email Address Checker icon misaligned

### ISSUE THREAD

**Issue by iamjamesreyracho** [infor-design/enterprise#6373] opened 2022-05-04 06:46 UTC
**Describe the bug**
The icon in the email address checker is misaligned in responsive view.

**To Reproduce**

1. Go to https://4630-beta0-enterprise.demo.design.infor.com/
2. Scroll down to Text Input Field
3. Input text in Email Address - checker, then press enter

**Expected behavior**
![image](https://user-images.githubusercontent.com/98729565/166631955-bcc5b2a4-7ea9-4f85-a790-eb02c6f8177f.png)

**Version**

- ids-enterprise: v4.63.0-beta.0

**Screenshots**
![ss](https://user-images.githubusercontent.com/98729565/166652785-45ea118d-af84-4a19-9c19-14091f02517e.png)

**Platform**
 - Browser Name: Chrome (Version 101.0.4951.54 (Official Build) (64-bit))

**Additional context**
viewport: 320-350 width

**Comment by ericangeles** [comment] 2022-05-04 11:45
The issue appears on `343px` and below.

**Comment by tmcconechy** [comment] 2022-05-24 13:33
Duplicate of https://github.com/infor-design/enterprise/issues/6480 will close to just have one issue

**Closed by tmcconechy** 2022-05-24 13:33 UTC
Labels: type: bug :bug:, priority: trival, [1]
