### ISSUE TITLE
Editor Component: Clear Formatting Not Working On Mobile

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1160] opened 2018-11-05 19:21 UTC
**Describe the bug**
Editor Component: Clear formatting Not Working On Mobile

**To Reproduce**
1. Go to http://4120-rc2-enterprise.demo.design.infor.com/components/editor/example-index.html
2. Click and highlight text within the text editor
3. Click on Bold and underline
4. Click on the "Clear Formatting"
5. The "Clear Formatting" feature doesn't work

**Expected behavior**
The clear formatting feature should work on all mobile devices

**Screenshots**
![bs_realios_mobile_iphone x-11 0 9](https://user-images.githubusercontent.com/39101346/48021204-fe293680-e105-11e8-9ee7-fed51f0d6da3.jpg)

**Platform**
 - Device iPhone X 

**Additional context**
No

**Comment by tmcconechy** [comment] 2018-11-05 19:42
Not sure if there is any fix for this, because the problem is you need to select the text to make this work. But im not able to click to select the text. So that needs to be solved first

**Closed** 2018-11-20 15:32 UTC
Labels: [∞], type: bug

**Comment by tmcconechy** [comment] 2018-11-20 15:34
We wont be able to fix this as the mobile device needs selection to do the clear formatting.
But that goes away when the list is mobile. We can only do basic editing on mobile.
