### ISSUE TITLE
Stacked Column Chart: Not showing actual value of data point

### ISSUE THREAD

**Issue by spathak21** [infor-design/enterprise#3196] opened 2019-11-28 07:37 UTC
**Describe the bug**
Stacked column chart not showing actual value of data point

**To Reproduce**
1.Set up your enterprise project 'https://github.com/infor-design/enterprise'
2.Go To https://github.com/infor-design/enterprise/blob/master/app/views/components/bar-stacked/example-index.html
3.Set dataset to following

```
 var dataset  = [
    {
      'data': [
        {
          'name': 'IDM Administrator',
          'value': 56
        },
        {
          'name': 'IDM Super User',
          'value': 47
        },
        {
          'name': 'IDM Advanced User',
          'value': 24
        },
        {
          'name': 'IDM Related Information User',
          'value': 23
        }
      ],
      'name': 'High',
      'color': '#e84f4f'
    }
    ,
    {
      "data": [
        {
          "name": "IDM Administrator",
          "value": 0
        },
        {
          "name": "IDM Super User",
          "value": 0
        },
        {
          "name": "IDM Advanced User",
          "value": 0
        },
        {
          "name": "IDM Related Information User",
          "value": 0
        }
      ],
      "name": "Medium",
      "color": "#ff9426"
    },
    {
      "data": [
        {
          "name": "IDM Administrator",
          "value": 0
        },
        {
          "name": "IDM Super User",
          "value": 0
        },
        {
          "name": "IDM Advanced User",
          "value": 0
        },
        {
          "name": "IDM Related Information User",
          "value": 0
        }
      ],
      "name": "Low",
      "color": "#ffd726"
    },
    {
      "data": [
        {
          "name": "IDM Administrator",
          "value": 0
        },
        {
          "name": "IDM Super User",
          "value": 0
        },
        {
          "name": "IDM Advanced User",
          "value": 0
        },
        {
          "name": "IDM Related Information User",
          "value": 0
        }
      ],
      "name": "Informational",
      "color": "#54a1d3"
    }
  ];
```

**Expected behavior**
Stacked column chart should show actual value on chart of data point

**Version**
- ids-enterprise: v4.22.0

**Screenshots**
![Stacked-Column-Chart](https://user-images.githubusercontent.com/58286807/69786156-d9f03a00-11df-11ea-83ac-6149f95074fe.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome, IE

**Additional context**
In attached screenshot for 'rajeev.diboliya' have violation count 23 but from chart it say he have violation count 24.

**Comment by deep7102** [comment] 2020-01-22 15:32
Hi @spathak21 
1) The link in directions is for `bar-stacked`.
2) The `dataset` you provided is not matching with screenshots above.

**Comment by tmcconechy** [comment] 2020-01-31 21:02
Closing this issue we were unable to reproduce as the data did not match in the steps. Feel free to provide new info and we can try and reopen it.

**Closed by tmcconechy** 2020-01-31 21:02 UTC
Labels: [3], status: cant reproduce, type: bug :bug:
