### ISSUE TITLE
Modal: Modal close is being blocked when clicking a close button while a popupmenu or dropdown is open

### ISSUE THREAD

**Issue by aaronpikkarainen** [infor-design/enterprise#6048] opened 2022-01-20 16:05 UTC
**Describe the bug**
Closing a modal is being blocked while a popupmenu or dropdown is open. This is causing modals to not respond/close when clicking their buttons. It is also blocking the destroy process of a Contextual Action Panel in our Angular application (I believe one fix will resolve both issues). There is logic in the modal.js close function which aborts the close if there are any open sub components, which causes some issues (see comments below).

**To Reproduce**

1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/popupmenu/test-modal.html
2. Open the modal
3. Click one of the Menu Buttons to open the Popupmenu
4. With the popupmenu still open, click the Cancel or Save buttons, and notice the modal doesn't get closed. (A 2nd click with the popupmenu closed will allow the modal to close.)
5. The same problem can also be seen at the following example when a Dropdown field is open: https://design.infor.com/code/ids-enterprise/latest/demo/components/modal/example-close-btn.html

**Expected behavior**
Clicking a modal close button should work even when a popupmenu or dropdown is open.

**Version**
- ids-enterprise: v4.59.1

**Screenshots**

![image](https://user-images.githubusercontent.com/14128010/150376039-1c13d1db-c6cf-4961-9973-b2fab72b4d1c.png)

![image](https://user-images.githubusercontent.com/14128010/150376069-838c3caf-6430-406d-8775-874ff7f12490.png)

**Platform**
 - Infor Application/Team Name: CSD
 - Device: Laptop
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 97.0.4692.71 (Official Build) (64-bit)

**Comment by aaronpikkarainen** [comment] 2022-01-20 20:06
Thanks, Tim. I looked into this a bit further, and I see now that the modal button click events are firing ok, but there is logic in the modal.js close function that is aborting the close when there are any open sub components.

`
if (!force && (!this.visible || this.openSubComponents.length)) {
  return true;
}
`

It's definitely going to be an issue for folks. When the user clicks a modal button, our application runs the business logic for that button and then calls the destroy or close function to close the modal. If the modal doesn't close on the first click, then the user will click the button again, which will cause our application logic to run a 2nd time and duplicate any transactions, api calls, etc. Hopefully this behavior in the modal code can change so it doesn't cause these problems for teams.

It also becomes an issue when destroying a CAP control. The CAP will get destroyed, but the Modal will abort the close, which causes a half destroyed modal to remain on the screen.

**Comment by tmcconechy** [comment] 2022-01-20 20:10
ok, looking again here if i open a menu https://main-enterprise.demo.design.infor.com/components/button/example-menubutton.html and click the .. button it doesnt do this. So maybe im mistaken. Will add it to a sprint and investigate further

**Comment by aaronpikkarainen** [comment] 2022-01-20 20:33
The issue this causes with the half destroyed CAP modal can be seen in /contextualactionpanel/test-destroy.html if you move the Destroy button above the dropdown field so that it is visible/clickable while the dropdown is open.

The attached file makes that slight change:

[test-destroy.zip](https://github.com/infor-design/enterprise/files/7908320/test-destroy.zip)

**Half-Destroyed CAP**
![image](https://user-images.githubusercontent.com/14128010/150417658-4dc5fbe6-08c5-465a-a805-b2031d5193a0.png)

**Comment by EdwardCoyle** [comment] 2022-01-26 21:17
We should definitely fix the partial destroy and make sure CAP's are fully removed.

Regarding closing behavior:  Preventing the Modal from closing when its child components with popups/menus are open was a feature request from other Infor teams we fulfilled -- originally added to prevent unintended behavior in https://github.com/infor-design/enterprise/pull/3717.  However we also did patch specifically clicking once to close using the `.btn-close` X buttons in CAPs, so this change to make it work on all buttons in Modals wouldn't be totally inconsistent: https://github.com/infor-design/enterprise/pull/4221

As a workaround, @aaronpikkarainen you may want to see if you can attach the logic for form submission against modal contents to the IDS Modal `afterclose` event, which will only go off [if the close actually occurs](https://github.com/infor-design/enterprise/blob/main/src/components/modal/modal.js#L1426)

**Comment by EdwardCoyle** [comment] 2022-01-26 21:17
cc @inforandy

**Comment by EdwardCoyle** [comment] 2022-02-23 17:43
@tmcconechy @inforandy 

We've reviewed this one's current behavior -- The Modal should allow for clicking any buttons that close the modal to immediately close, regardless of if there is an open menu inside the Modal's boundaries.

Note that previously, we specifically prevented closing modals when a Popup was open:  
- https://github.com/infor-design/enterprise/blob/main/src/components/modal/modal.js#L1376
- https://github.com/infor-design/enterprise/blob/main/src/components/modal/modal.js#L1227

This functionality overall should still exist (fx if you click outside of the modal and a menu is displayed, the modal shouldn't close).  However, clicking directly on any modal buttons should cause the modal to close immediately.

For future reference:  If an application DOES NOT want the modal to close when an inner menu is open, you could potentially check the modal's `openSubComponents` property in a [`beforeclose` event](https://github.com/infor-design/enterprise/blob/main/src/components/modal/modal.js#L1380), and veto if needed

**Closed** 2022-03-21 13:33 UTC
Labels: type: bug :bug:, [3], team: CSD

**Comment by jbrcna** [comment] 2022-03-23 04:28
This has been QA tested and passed on v4.62.0-dev.
https://main-enterprise.demo.design.infor.com/components/popupmenu/test-modal.html
![Large GIF (982x548)](https://user-images.githubusercontent.com/56722184/159624068-12f8c1b1-00f5-4502-b3b5-4723b5ce88f5.gif)
