### ISSUE TITLE
Dropdown control: example-ajax-managed Vibrant theme issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3076] opened 2019-11-06 10:01 UTC
**Describe the bug**
dropdown looks doubled using Vibrant theme

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/dropdown/example-ajax-managed.html?theme=uplift&variant=light&colors=0563C2'
2. Resize Browser to 320 x 568 or if you still can't see it resize a little bit vertically
3. See error

**Expected behavior**
<img width="523" alt="image" src="https://user-images.githubusercontent.com/56722184/68287258-6a45ce00-00bd-11ea-9914-d06b5dcc881d.png">

**Version**
4.23

**Screenshots**
<img width="574" alt="image" src="https://user-images.githubusercontent.com/56722184/68286978-f0154980-00bc-11ea-8f7a-f268bb0ff0c7.png">

**Platform**
ALL Browser

**Additional context**
[Example No Search](http://master-enterprise.demo.design.infor.com/components/dropdown/example-no-search.html) has the same issue
<img width="673" alt="image" src="https://user-images.githubusercontent.com/56722184/68288192-ea206800-00be-11ea-850c-a15d1627534d.png">

**Comment by tmcconechy** [comment] 2019-11-06 14:45
Duplicate of ##3058

**Closed by tmcconechy** 2019-11-06 14:45 UTC
