### ISSUE TITLE
Editor: While typing the text, cursor is moving to starting point

### ISSUE THREAD

**Issue by suryakumard** [infor-design/enterprise#4569] opened 2020-10-30 15:40 UTC
**Describe the bug**
 Editor(**Ids-Enterprise-ng**) : while typing the text, cursor is moving to starting point.
**To Reproduce**
Steps to reproduce the behavior :

1. Open the Rich text editor.
2. Type some text and idle for a second.
3. Cursor is moving to starting point.

**Expected behavior**
Cursor should stay at current position.

**Version**
ids-enterprise-ng: [v8.0.3]

**Screenshots**
![Richtext_error](https://user-images.githubusercontent.com/16288473/97725120-cb975600-1af3-11eb-92b8-8a97b303281a.JPG)

**Platform**
All major browser

**Additional context**

**Comment by tmcconechy** [comment] 2020-10-30 16:25
Actually this might not be what i thought it was i thought this was about tabbing into the editor and it goes to the front of the text not the end.

I'm not seeing it move after typing? Can you reproduce here?

https://master-enterprise.demo.design.infor.com/components/editor/example-index.html

**Comment by tmcconechy** [comment] 2021-03-11 19:17
Was not able to reproduce this so closing

**Closed by tmcconechy** 2021-03-11 19:17 UTC
Labels: [2], status: clarification, type: bug :bug:
