### ISSUE TITLE
Notification: Cannot interact with the page header

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1858] opened 2019-03-27 10:15 UTC
**Describe the bug**
Notification: Cannot interact with the page header, unless you dismissed all the notifications.

**To Reproduce**
1. Go to https://4170-rc0-enterprise.demo.design.infor.com/components/notification/example-index.html#
2. Click the ... menu in the page header
3. See issue: menu will not open
4. Dismiss all the notifications by clicking on their x button
5. Click the ... menu, now the menu can be opened 

**Expected behavior**
User should be able to interact on the page header

**Version**
- ids-enterprise: v4.11.0 - v4.17.0-rc0

**Screenshots**
No screenshots applicable.

**Platform**
 - All Devices, OS and browsers.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment] 2019-03-27 13:10
This is a duplicate of #1639

**Closed by tmcconechy** 2019-03-27 13:10 UTC

**Comment by brianjuan** [comment] 2019-03-28 02:29
This is noted @tmcconechy , will watch #1639 instead. Thanks.
