### ISSUE TITLE
About: Operating System Version Appearing Twice

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#2416] opened 2019-06-20 18:02 UTC
**Describe the bug**
About Component: Operating System Version Appearing Twice

**To Reproduce**
1. Go to url: https://4193-rc0-enterprise.demo.design.infor.com/
2. Scroll down to "Show About Screen" Click on the button
3. The Operating System version is appearing twice. Please see screen shot attached. 

**Expected behavior**
The operating system version shouldn't appear twice.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.19.rc0]

**Screenshots**
![bs_win10_IE_11 0 (4)](https://user-images.githubusercontent.com/39101346/59870617-dd93b100-9363-11e9-87f8-8b5c1da90468.jpg)

**Platform**
 - OS Version: [ Windows 10]
 - Browser Name [IE 11]

**Additional context**
None

**Comment by tmcconechy** [comment] 2019-12-16 20:24
Duplicate of #1650 1650

**Closed by tmcconechy** 2019-12-16 20:24 UTC
Labels: [2], priority: minor, type: bug :bug:
