### ISSUE TITLE
Timepicker: Unable to re-open Timepicker [ EDGE ]

### ISSUE THREAD

**Issue by johnbarcena** [infor-design/enterprise#2974] opened 2019-10-14 09:44 UTC
**Describe the bug**
- Unable to re-open the Timepicker whether you set the time or not
- Unable to update time

**To Reproduce**
1. Go to 'http://4220-rc0-enterprise.demo.design.infor.com/'
2. Click on Timepicker icon
3. Select time then click on "Set Time"
4. Open again using the icon.
5. Change the time then "Set Time" again.
6. Notice that the TimePicker doesn't close and does not update the time
7. Click anywhere to lose focus
8. Click the icon again to re-open
9. Timepicker won't show

OR 

1. Go to 'http://4220-rc0-enterprise.demo.design.infor.com/'
2. Click on Timepicker icon
3. Click anywhere to lose focus
4. Click the icon again to re-open
5. Timepicker won't show

**Expected behavior**
should be able to update, close, and re-open the timepicker

**Version**
4.220 rc0

**Screenshots**
![Timepicker-4220-rc0](https://user-images.githubusercontent.com/52902639/66742205-bbd9af00-eea9-11e9-962c-2361ad7bd6df.gif)

**Platform**
EDGE

**Additional context**
somewhat related to Unable to close TimePicker after setting the value then opening again #805

**Comment by tmcconechy** [comment] 2019-10-15 13:58
@EdwardCoyle @deep7102  are you able to reproduce this? I am not it seems to be working fine.
Also try http://4220-rc0-enterprise.demo.design.infor.com/components/timepicker/example-index.html

Marking as cannot reproduce

**Comment by EdwardCoyle** [comment] 2019-10-15 14:24
Tested on Win 10/Edge 18, was not seeing the issue:

![Oct-15-2019-10_18-AM](https://user-images.githubusercontent.com/3249601/66840353-ec672a80-ef35-11e9-8f72-8e560c4567cc.gif)

**Comment by deep7102** [comment] 2019-10-15 14:35
Same here cannot reproduce, I tested on vm win10 ie edge.

**Closed** 2019-10-15 14:47 UTC
Labels: status: cant reproduce, status: wont fix :no_entry_sign:, type: bug :bug:
