### ISSUE TITLE
Datagrid filters are not working properly

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2731] opened 2019-09-05 04:46 UTC
**Describe the bug**
Datagrid filters are not working properly

**To Reproduce**
1. Go to http://4210-beta1-enterprise.demo.design.infor.com/components/datagrid/example-paging.html and all any other grids that has filter
2. Click on QTY filter and play with each filters

**Expected behavior**
Filters should work accordingly 

**Version**
Beta 4.21

**Screenshots**
QTY > 8
![image](https://user-images.githubusercontent.com/45757016/64312484-bea7d100-cfda-11e9-9ae3-4b4ff88e53fe.png)

QTY filtered to is not empty
![image](https://user-images.githubusercontent.com/45757016/64312526-eb5be880-cfda-11e9-9958-64524e697c6f.png)

QTY filtered to is empty 
![image](https://user-images.githubusercontent.com/45757016/64312557-0a5a7a80-cfdb-11e9-871a-44cb907832b7.png)

**Platform**
All browser, OS and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment] 2019-09-05 13:39
Duplicate of #2709

**Comment by tmcconechy** [comment] 2019-09-05 13:39
Closing as dup but i would just retest this with 2709 in beta 2

**Closed** 2019-09-05 13:40 UTC
Labels: status: duplicate, type: bug :bug:
