### ISSUE TITLE
Datagrid: Page looks broken after the user closes the "Personalize Columns" dialog

### ISSUE THREAD

**Issue by MickalWang** [infor-design/enterprise#3255] opened 2019-12-16 10:39 UTC
**Describe the bug**
The web page will get broken after the user closes the "Personalize Columns" dialog even if the user hasn't done any operation in that dialog.

**To Reproduce**
1. Open the demo 'datagrid-test-settings' in the ids-enterprise-ng-demo project.
2. Click the 'Personalize' button and the 'Personalize Columns' dialog pops up.
3. You can choose to check/uncheck options in the list or do nothing in the dialog. Then close the dialog.
4. Click the 'Reset Columns' button  and the dataGrid will disappear.
5. Actually the dataGrid will disappear even if we don't open the "Personalize Columns" dialog and just click the  'Reset Columns' button. So I think the issue exists for the datagrid with "Personalize Columns" function.

**Expected behavior**
The dataGrid should be returned to the original appearance with pre-set columns.

**Version**

- ids-enterprise: 4.22.0-dev

**Platform**
 - OS Version: Windows 10 
 - Browser Name: chrome
 - Browser Version: 78.0.3904.108

**Comment by tmcconechy** [comment] 2019-12-16 14:02
I just retested this on http://localhost:4200/ids-enterprise-ng-demo/datagrid-test-settings on the latest master (which is going to be 6.3 which is now in beta).

This issue seems to be now fixed. We made some improvements to the dialog in EP 4.24 so should be all good now. Feel free to test on 6.3.0-beta

**Closed by tmcconechy** 2019-12-16 14:02 UTC
Labels: [3], focus: datagrid, status: cant reproduce

**Comment by tmcconechy** [comment] 2019-12-16 14:13
Maybe actually this is https://github.com/infor-design/enterprise-ng/issues/688 so that one CAN be reproduced so use that as a reference
