### ISSUE TITLE
Header/Toolbar/Button: Barely visible button text on hover when the button is in a toolbar and a header in light theme/alabaster

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#8045] opened 2023-10-06 12:21 UTC
**Describe the bug**
In light theme and alabaster color - when hovering a button that is in a toolbar and a header, the text becomes white, making it barely visible.

[Link to the relevant CSS rule](https://github.com/infor-design/enterprise/blob/92026eda6817ab6ba8ccbf3fc16f0d7f69b7d76a/src/components/header/_header-new.scss#L249-L262)

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/header/example-flex-toolbar.html?colors=ffffff
2. Hover over any button except the disabled one and the "..." menu.
3. Notice the button text color.

**Expected behavior**
The button text color should probably be the same color as the button icon.

**Version**
- ids-enterprise: `4.87.0`

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/63045013/69e22e8c-aec9-40e3-8070-96b975eb39f2)

**Platform**
 - Infor Application/Team Name: OS Portal

**Comment by tmcconechy** [comment] 2023-10-06 14:26
This is a duplicate of https://github.com/infor-design/enterprise/issues/7943
And is fixed now on main and in 4.88 (soon) https://main-enterprise.demo.design.infor.com/components/header/example-flex-toolbar.html?colors=ffffff

**Closed by tmcconechy** 2023-10-06 14:26 UTC
Labels: type: bug :bug:, [2], status: duplicate
