### ISSUE TITLE
Datagrid: Component remove row or removeSelected issue

### ISSUE THREAD

**Issue by mrichardson24** [infor-design/enterprise#4909] opened 2021-03-03 14:09 UTC
**Describe the Issue**
When user used IDS component datagrid with pagination and the page has functionality to remove a row or selected row
then used .removeRow or .removeSelected to remove row data in ex. page 2 after the call of the said functions the page return to page 1.

**To Reproduce**
Steps to see the question or problem:
1. Go to page with datagrid that has pagination implementation and removed row.
2. Go to another page ex. page 2 of the component datagrid.
3. Do removed row
4. Current page will be back to page 1.

**What are you trying to do**
On the page where the row will be remove ex. page 2, the page should retained in page 2.

**What did you try so far**
both .removeRow or .removeSelected api function.

**Version**
- ids-enterprise: v4.30.0

**Screenshots**
If applicable, add screenshots to help explain your question or problem.
![image](https://user-images.githubusercontent.com/79984299/109817538-feea1d00-7c6c-11eb-84fe-b726e5b4bfe2.png)

**Platform**
 - OS Version: [Windows 10]
 - Browser Name [Chrome]
 - Browser Version [Version 88.0.4324.190 (Official Build) (64-bit)]

**Additional  Context**
Add any other context about the question or problem here, including the use case if relevant.

**Comment by tmcconechy** [comment] 2021-03-03 14:46
Trying to follow the steps. What is the page link in the screen shot where i can reproduce it i.e. "Go to page with datagrid that has pagination implementation and removed row." what page is that? Please update steps so i can see it?

Thanks

**Comment by tmcconechy** [comment] 2021-03-24 17:21
Closing due to not being able to reproduce

**Closed by tmcconechy** 2021-03-24 17:21 UTC
Labels: [2], status: clarification, type: bug :bug:
