### ISSUE TITLE
Tab: Loses its focus in Mobile and Responsive view

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2928] opened 2019-10-09 04:48 UTC
**Describe the bug**
Tab loses its focus in Mobile and Responsive view

**To Reproduce**
1. Open a Mobile Device and Go to http://4220-beta0-enterprise.demo.design.infor.com/components/tabs/example-index.html?theme=soho&variant=light&colors=0563C2
2. Click the drop down filter and click Notes
Focus and tab should be in Notes tab
3. Click Contracts 
Focus and tab should be in Contracts tab

**Expected behavior**
The tab should focus on selected tab

**Version**
Beta 4.22

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/66452441-0a92dd80-ea93-11e9-8754-a18a8d5e957b.png)

**Platform**
Mobile Devices (Android and iOS)
Responsive View for all Browser and OS

**Additional context**
N/a

**Comment by tmcconechy** [comment] 2019-10-09 13:21
Im not able to reproduce this issue. Any other steps you can give? I tried IOS X - iphone

**Comment by tmcconechy** [comment] 2019-10-31 13:37
Closing this as too minor to worry about / not able to reproduce easily.

**Closed by tmcconechy** 2019-10-31 13:37 UTC
Labels: priority: minor, status: cant reproduce, type: bug :bug:
