### ISSUE TITLE
Message: Icon is misaligned

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise#7761] opened 2023-08-03 12:24 UTC
**Describe the bug**
The Message dialog (`SohoMessageService.[error|alert|info]()`) icon is misaligned and slightly clipped.

**To Reproduce**

1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/message/example-index?theme=uplift&variant=light
2. Click on any of the Error, Alert, Success, Info example buttons
3. Notice the icon in the dialog title

**Expected behavior**
The icon should not be clipped at the top, and I'm guessing it should be centered

**Version**

- ids-enterprise: 4.85.0

**Screenshots**
<img width="408" alt="image" src="https://github.com/infor-design/enterprise/assets/4991954/daa32bcd-98af-4310-87bf-1f6a34a056cb">

**Additional context**
Issue discovered when calling `SohoMessageService.error()`.

**Comment by tmcconechy** [comment] 2023-08-03 13:59
This is a duplicate of https://github.com/infor-design/enterprise/pull/7749 which was recently fixed (now in 4.86 beta).

**Closed by tmcconechy** 2023-08-03 13:59 UTC
Labels: type: bug :bug:, [1], status: duplicate
