### ISSUE TITLE
WeekView: Implementation issues and Questions

### ISSUE THREAD

**Issue by infor-mahesh** [infor-design/enterprise#7709] opened 2023-07-13 07:37 UTC
**Describe the Issue**
I am facing an issue while implementing a week view feature. Initially, when the data is loaded, clicking on a specific date displays the corresponding data, which is working fine. However, I want to load the data on a weekly basis, so when the "next week" button is clicked, the input data should update and be displayed. The problem arises when I try to implement this functionality before the data is loaded. The week is rendered before the data is updated, causing a mismatch. For example, when I click "next" twice and then go back, the data is rendered.

**To Reproduce**
Steps to see the question or problem:
1.implement week view component, render the data when certain week/date is clicked

**What are you trying to do**
When the entire data is loaded at once, it causes performance issues. Therefore, I would like to update the data in the week view dynamically when a specific date is selected. So, whenever the user clicks on a particular date, an API call is made to fetch the corresponding data, and then it is rendered in the week view 

**What did you try so far**
Within the onRenderWeek($event) method, I extract the current visible dates from the events in the week view. Using these dates, I make an API call and assign the response to a variable. Subsequently, I pass this variable as an attribute in the response parameter within the onRenderWeekCallback method.

By default, the onRenderWeekCallback method is called first, followed by the onRenderWeek($event) method. However, this order of execution results in the rendering happening first and then the data update. Ideally, the data should be updated first, and then the rendering should occur.

**Version**

sdk version - Infor_WidgetSDK_3.24.0
- "ids-enterprise-ng": "15.4.2",

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/139130328/5349344c-8062-42c9-9dc7-9d97c3541126)
![image](https://github.com/infor-design/enterprise/assets/139130328/2ec142b4-ee96-4418-aa6d-df03f8f0643e)
![image](https://github.com/infor-design/enterprise/assets/139130328/225e795f-98c8-4cb6-8ff2-7f51aecf3d42)

**Comment by tmcconechy** [comment] 2023-07-13 14:13
This issue doesn't 100% make sense to me. We might need a working example. If we do then just modify our current examples and add a copy to the issue we can run.

But to load the data async we do have an example and it is this one:
https://main-enterprise.demo.design.infor.com/components/week-view/test-ajax-events.html

In the example we are using onRenderWeek https://github.com/infor-design/enterprise/blob/main/app/views/components/week-view/test-ajax-events.html#L18 and simulating a JSON that returns the data for the weekview.

Not its returning ALL data. So you might want to just return only the data for the week being shown. Not all data every time.

Anything more needed just update that example so we can see what going on

**Comment by infor-mahesh** [comment] 2023-07-17 05:44
Hi @jdilag90 ,
i have tried using this 
**to get the week's start date: args.settings.startDate
to get the week's end date: args.settings.endDate**
in onRenderWeek 

The current implementation works, but there is an issue. If I set a delay of at least 1.2 seconds using delay(1200), it works fine. However, if the delay is set to less than 1.2 seconds, the onRenderWeek function is called immediately, and onRenderWeekCallback doesn't get a chance to execute completely. This behavior is causing unexpected results and needs to be addressed to ensure proper execution flow.

**Comment by tmcconechy** [comment] 2023-07-17 13:14
@infor-mahesh to clarify the example just adds a delay to simulate an ajax call. On your end you dont need an extra delay for no reason. Just do an ajax call then send the data back in the response https://github.com/infor-design/enterprise/blob/main/app/views/components/week-view/test-ajax-events.html#L25

If not working please put together a runnable example.

**Comment by tmcconechy** [comment] 2023-07-18 13:23
Closing as answered

**Closed by tmcconechy** 2023-07-18 13:23 UTC
Labels: type: support :sos:, [1]

**Comment by infor-mahesh** [comment] 2023-07-20 09:39
Hello, could you please review the code snippet below? I'm facing an issue with the current implementation. The problem is that the render method doesn't wait for the API call to complete before returning the response, causing incomplete data display. As a temporary solution, I've added a delay of 2-5 seconds to ensure all API calls finish before providing the data to show. However, I believe there is a better way to handle this situation. Any suggestions would be greatly appreciated. Thank you!

`
public onRenderWeekCallback = (_node: Node, response: Function, args) =>
 {
		

		console.log(args.settings.startDate);

		console.log("on render call back");
		let start = args.settings.startDate;
		let end = args.settings.endDate;
		let dateToConvert: Date;
		let convertedDate: string;
		Object.entries(event).forEach(([key, value]) => {
			if (key == "startDate") {
				start = value;
			}
			if (key == "endDate") {
				end = value;
			}
			console.log(`Key: ${key}, Value: ${value}`);
		});
		dateToConvert = new Date(start);
		start = this.datePipe.transform(dateToConvert, "yyyy-MM-dd");
		dateToConvert = new Date(end);
		end = this.datePipe.transform(dateToConvert, "yyyy-MM-dd");

		console.log(
			"the data coming from event = start = " + start + "and end = " + end,
		);

		this.getShiftDetailLayers(start, end);
		this.getLtaOverrides(start, end);
		this.changeDetectorRef.detectChanges();
		console.log("the unique list = ");
		console.log(this.ucalenderItems);
		this.setBusy(true);
	//	this.delay(3000).then(() => {
			console.log("Second line");
			response(this.ucalenderItems, calanderEventTypes);

			this.changeDetectorRef.detectChanges();
			this.setBusy(false);
	//	});

		this.setBusy(false);
	};`

**Comment by tmcconechy** [comment] 2023-07-20 13:48
https://github.com/infor-design/enterprise-ng/blob/main/src/app/week-view/week-view.demo.ts#L51 this is how we did it. As soon as you set the response() it should load. Should not matter how long it takes unless your doing something strange.

As you can see whenever you call it it loads that data in the weekview https://github.com/infor-design/enterprise/blob/main/src/components/week-view/week-view.js#L184

**Comment by infor-mahesh** [comment] 2023-07-20 19:38
Hi i have updated it accordingly still the issue of rendering is happening,

		this.getCurrentUser().subscribe((data) => {
			console.log(`executed current user`);
			this.getShiftDetailLayers(start, end).subscribe((data) => {
				console.log(`completed shiftdetailslayers`);
				this.getLtaOverrides(start, end).subscribe((data) => {
					console.log(`completed lta overrides`);
					this.convertDataSetToCalanderDataSet(this.completeShiftDetailList);
					console.log("completed final data set to pass");
					response(this.ucalenderItems, calanderEventTypes);
					console.log("data set passed");

					this.showStackedView();
					this.setBusy(false);
				});
			});
		});

 If possible, could we schedule a call to discuss this further? This way, I can provide more context and clarify the issue better. Thank you!"

**Comment by tmcconechy** [comment] 2023-07-20 19:57
With our deadlines we dont usually have a lot of time for smaller problems like this (we would be in meetings all the time).
But if you think its a bug maybe you can put together an example and make this into something like....

1. steps to reproduce
2. runnable code

Templates for reproduction:
https://stackblitz.com/edit/ids-enterprise-4860?file=index.js
https://stackblitz.com/edit/ids-quick-start-1651?file=src%2Fapp%2Fapp.component.ts

The simpler the better. Also on your end my advise would be to simplify the issue as much as possible.
Another suggestion is to preload the data.. (may not be possible if a lot for each page)
And what if you set the response last?

**Comment by jdilag90** [comment] 2023-07-20 21:27
Hi,
Hopefully this code snippet helps.
I'm emulating the nested async calls you have and also adding a setTimeout at the end.
Events are rendered at the very end of the async call stack when `response()` is invoked.

![weekview-ex](https://github.com/infor-design/enterprise/assets/98347152/3350ad80-7c96-4d81-a992-2f4e14fc3958)

**Comment by infor-mahesh** [comment] 2023-07-21 05:19
hi @jdilag90,
i am calling 2 apis so if i am keeping delay of hardcoded then if api is late by that time then the rendering is not happening, and moreover if used delay then it impacts performance. i cannot load all the data prior because it also causes performance issue

**Comment by tmcconechy** [comment] 2023-07-21 13:24
I think @jdilag90 is correct on this issue. Since you are doing more than one api call you need to wait for both of them before calling response.

the component works as expected. Try googling “how to wait for two Ajax calls to complete”.

1. one way as as shown in the previous comment
2. Another idea is using https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all
3. you could also try to get your backend to work on one Ajax call. Check with your team on that
4. Or you could just set the event data directly with the main api
