### ISSUE TITLE
Datepicker: Change event not trigering when selecting a single date in Date Range component

### ISSUE THREAD

**Issue by Venketkm** [infor-design/enterprise#4075] opened 2020-06-23 14:45 UTC
**Describe the bug**

**To Reproduce**
1. Go To Date Range component at http://localhost:4000/components/datepicker/example-range.html
2. click on the button in "Range - no initial value"
	select 6/3/2020 - 6/3/2020 (same day)'....'
3. We are getting 1 console logs for above action
First -  >     6/3/2020

**Expected behavior**
We should get 2 console logs for above action
First -  >     6/3/2020
Second  --->  6/3/2020 - 6/3/2020  

**Version**

- IDS Enterprise 4.28.0/ IDS Enterprise NG 7.1.0.

**Additional context**
We are getting two logs when we select separate dates in Date range component.

**Comment by tmcconechy** [comment] 2020-06-23 14:46
Similar to https://github.com/infor-design/enterprise-ng/issues/853

**Comment by lipetzan** [comment] 2020-06-23 21:34
Was a patch for 4.27 discussed?

**Comment by tmcconechy** [comment] 2020-06-23 21:36
No, But if really needed i can do. The problem is i have to patch 4.27 , 4.28 and 4.29 and then make 3 NG patches so probably take me an entire day of work

**Comment by tmcconechy** [comment] 2020-06-23 21:43
@pwpatton do you think it would work if i just made a 4.27 patch for EP only and you include just that and i dont patch every other version? Maybe a bit confusing i guess

**Comment by lipetzan** [comment] 2020-06-23 21:46
Well,  we (Landmark) went from 4.27 to 4.30 so we would only need 4.27 and 4.30+.

**Comment by tmcconechy** [comment] 2020-06-23 21:47
ok that makes it easier if we just do that.. if you need it nod yes. The other part im wondering is if you can just pull in EP to patch? Or if you really need the NG part too?

**Comment by lipetzan** [comment] 2020-06-23 21:54
I'm pretty sure we specifiy ng and that pulls along the ep.  I can't really answer for 100%. Sorry.

**Comment by tmcconechy** [comment] 2020-06-23 21:55
Yeah think so well at least just two things and not 6. So do you want me to patch a 4.27?

**Comment by lipetzan** [comment] 2020-06-23 21:57
Yes please.  Fixes for 4.27 and 4.30+.  Awesome.

**Comment by tmcconechy** [comment] 2020-06-23 21:59
Ok cool https://github.com/infor-design/enterprise/pull/4076/files isnt merged yet. Should be tomorrow. Then i can make the patch

**Comment by lipetzan** [comment] 2020-06-23 22:03
Turns out I'm a liar.  We do need 28 too.  Our July is 27 and our August is 28 (but I thought was 30).  Doable?  27 the priority.

**Closed** 2020-06-24 13:18 UTC
Labels: [2], priority: high, team: landmark, type: bug :bug:, type: regression bug  :leftwards_arrow_with_hook:

**Comment by Venketkm** [comment] 2020-06-24 16:46
I see issue is closed. Is the issue fixed ?

**Comment by tmcconechy** [comment] 2020-06-24 16:49
Yes. Closed by a Pull request with a fix. Will be fixed in 4.30

**Comment by janahintal** [comment] 2020-06-25 07:10
This issue is now resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/datepicker/example-range.html & https://master-enterprise.demo.design.infor.com/components/datepicker/test-change-event.html
![image](https://user-images.githubusercontent.com/45757016/85672870-e7c65900-b6f5-11ea-8696-e79741aa9acf.png)

**Comment by lipetzan** [comment] 2020-06-25 13:14
We might need to re-open.  QA found that using "Apply" to select "today's" date vs. clicking on the date itself still has issues.

**Comment by tmcconechy** [comment] 2020-06-25 13:15
What are the steps?

**Comment by tmcconechy** [comment] 2020-06-25 13:19
using https://github.com/infor-design/enterprise/issues/4087 and wont reopen this
