### ISSUE TITLE
Contextual Action Panel with full content: Alignment issue on the X button

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2024] opened 2019-04-25 12:23 UTC
**Describe the bug**
Contextual Action Panel with full content: Alignment issue on the X button.

**To Reproduce**
1. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/contextualactionpanel/test-full-content.html
2. Open Contextual Action Panel
3. See issue: X button is misaligned

**Expected behavior**
X button should be correctly aligned

**Version**
- ids-enterprise: v4.7.0 - v4.18.0-beta0

**Screenshots**
<img width="1221" alt="Screen Shot 2019-04-25 at 8 19 18 PM" src="https://user-images.githubusercontent.com/39508864/56735355-d1daa280-6797-11e9-811f-4e5670c83165.png">

**Platform**
 - All Devices, OS, and browsers

**Additional context**
No additional context.

**Comment by tmcconechy** [comment] 2019-04-25 12:26
Duplicate of #1943

**Closed** 2019-04-25 12:26 UTC
Labels: status: duplicate
