### ISSUE TITLE
Datagrid: Special Characters are decoded onEnterEditMode

### ISSUE THREAD

**Issue by marclouisgenedeguzman** [infor-design/enterprise#4382] opened 2020-09-17 10:38 UTC
**Describe the bug**
Entering special character '&' is converted to &amp; onEnterEditMode

**To Reproduce**
1. Type & on editable cell
2. focus on other cell
3. go back to cell with typed & ('&' is decoded as &amp;)

**Expected behavior**
& characters is not decoded

![Special Characters Decoded](https://user-images.githubusercontent.com/50192038/93459812-e3849300-f914-11ea-8c2d-746d1233f097.gif)

**Version**
- ids-enterprise-ng 7.2.4

**Screenshots**

**Platform**
 - Infor Application/Team Name: User Productivity Team
 - Device: N/A
 - OS Version: Windows 10
 - Browser Name: Google Chrome
 - Browser Version: Version 85.0.4183.83 (Official Build) (64-bit)

**Additional context**
Tagging @lucacolumbu 
Cannot replicate scenario on ids samples, peer investigation with soho teams needed
Recording is from DEVAPP

**Comment by tmcconechy** [comment] 2020-09-17 13:21
Ok, let me know when you can reproduce the issue. I think its possible that https://github.com/infor-design/enterprise/pull/4174 is the same issue so you could try the latest.

What do you mean by "peer investigation with soho teams"?

**Comment by tmcconechy** [comment] 2020-10-14 18:00
I think this might be a duplicate of https://github.com/infor-design/enterprise/issues/4028 - if you want you can test 4.32 or later (4.33 current)

**Comment by marclouisgenedeguzman** [comment] 2020-10-15 03:54
@tmcconechy, we can cancel this ticket, we have some work around of decoding editable cell values onBeforeEnterEditMode. Thanks,

**Comment by tmcconechy** [comment] 2020-10-15 13:56
ok sounds good. From described it also may be fixed on #4028 so to avoid workarounds you might try the latest version

**Closed by tmcconechy** 2020-10-15 13:56 UTC
Labels: [3], focus: datagrid, status: clarification, team: m3, type: bug :bug:
