### ISSUE TITLE
Datagrid: "Is Not Empty" filter is returning empty column values

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2002] opened 2019-04-24 08:40 UTC
**Describe the bug**
Datagrid: "Is Not Empty" filter is returning empty column values.

**To Reproduce**
1. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
2. Select "Is Not Empty" filter on the Product ID column
3. See issue: Empty Product ID columns are still displayed

**Expected behavior**
"Is Not Empty" column filter should not return empty column values

**Version**
- ids-enterprise: v4.17.0 - v4.18.0-beta0

**Screenshots**
<img width="1254" alt="Screen Shot 2019-04-24 at 4 37 25 PM" src="https://user-images.githubusercontent.com/39508864/56644958-51d90d80-66af-11e9-8f44-b68a1fe401f8.png">

**Platform**
 - All Devices, OS, and browsers.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment] 2019-04-24 14:45
Issue goes back at least to 4.16.2 when this column was added to the example

**Comment by tmcconechy** [comment] 2020-01-31 20:58
Can no longer reproduce this issue seems ok on http://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html now. Moving this to QA to verify in case i missed something

**Closed by tmcconechy** 2020-01-31 20:58 UTC
Labels: [2], focus: datagrid, type: bug :bug:

**Comment by CindyMercadoReyes** [comment] 2020-02-03 18:57
This issue was tested across browsers and the issue is now resolved.  Moving this ticket to the Done column.
