### ISSUE TITLE
Colorpicker States Component: tooltip stays activated after the color picker palette is closed.

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1290] opened 2018-11-27 15:53 UTC
**Describe the bug**
Colorpicker States Component: tooltip stays activated after the color picker palette is closed.

**To Reproduce**
1. Go to url: http://4130-beta0-enterprise.demo.design.infor.com/components/colorpicker/test-states.html
2. Click on the "Normal (Non-Editable) drop down list box
3. Select the color "Slate08 and close the dropdown list box. 
4. When the user closes the color palette the tooltip stays opened unless you click anywhere in the UI. Please see screen shot attached. 

**Expected behavior**
The tooltip should close once the color palette is close.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1377" alt="colorpicker tooltip" src="https://user-images.githubusercontent.com/39101346/49093529-4a155a00-f232-11e8-8014-ec6ca9201d7d.png">

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [iOS 8]
 - Browser Name [Chrome]

**Additional context**
None

**Comment by tmcconechy** [comment] 2018-11-27 16:03
Closing as this a duplicate of https://github.com/infor-design/enterprise/issues/1273

**Closed by tmcconechy** 2018-11-27 16:03 UTC
