### ISSUE TITLE
Datagrid Active Cell Indicator is cropped for multiline on Edge and IE

### ISSUE THREAD

**Issue by NathanLouisBarcial** [infor-design/enterprise#1644] opened 2019-02-19 06:53 UTC
**Describe the bug**
Datagrid Active Cell Indicator is cropped on Edge and IE when one of the columns is multiline

**To Reproduce**
1. Go to 'http://localhost:4000/components/datagrid/test-long-text.html'
2. Set the cellNavigation = false settings of the datagrid.
`$('#datagrid').datagrid({
        columns: columns,
        selectable: 'multiple',
        dataset: data,
		editable: true,
		cellNavigation: false
      });`

3. Click on the first row and see the active cell indicator/highlight:
![image](https://user-images.githubusercontent.com/41028784/52995548-edeb5c00-3455-11e9-8c2c-8a98e622a6de.png)

4. This only occurs on Microsoft Edge and Internet Explorer. Not a major issue. Just wanted to know if this can be fixed or will be left as is. Thanks.

**Platform**
 - OS Version: Windows 10
 - Browser Name: Microsoft Edge/Internet Explorer

**Comment by tmcconechy** [comment] 2019-02-19 13:51
The problem is that the height is automatic on those cells. Can think of three solutions.

1. Add a rowHeight variable - will mean all rows set to a static height non dynamic
2. Calculate the row height on render (by setting) and set the height to the height for every row. (Double render === slower)
3. Add a rowHeight function - that will let you set row height in a calculated / dynamic function.

**Comment by NathanLouisBarcial** [comment] 2019-02-22 00:14
Thanks for the suggested solutions, will get back to you if we'll be able to apply these. Thank you.

**Comment by NathanLouisBarcial** [comment] 2019-03-19 03:05
Hi @tmcconechy tried these and this may not work for us since it will mean additional calculations for a minor issue. Looking at this example in Google Chrome, and it actually works fine in other browsers except ie/edge. Can this be fixed on your end, if it will be too much work then we can accept this since it rarely occurs on our app. Thank you for your response.

**Comment by tmcconechy** [comment] 2019-03-19 12:52
OK we'll see what i can come up with for a fix when we can.

**Comment by sharmainerivera** [comment] 2020-05-14 02:45
Hi, @tmcconechy. 

We just tested this issue on the newest version of Microsoft Edge and it renders properly:
![image](https://user-images.githubusercontent.com/61222084/81886556-904dad00-95cf-11ea-9aee-fc1606e8cab4.png)

![image](https://user-images.githubusercontent.com/61222084/81886576-a0658c80-95cf-11ea-81b8-e0ca9f02ae97.png)

For IE and older Edge versions, the issue still occurs:
![image](https://user-images.githubusercontent.com/61222084/81886623-bffcb500-95cf-11ea-834f-6b3011fcad7a.png)

**Comment by tmcconechy** [comment] 2020-05-14 13:26
I think this is a duplicate of another issue (which i cant seem to locate at the moment). I was working on this. But as far as i see i do not see this issue on IE 11 and Edge on the latest dev version.

https://master-enterprise.demo.design.infor.com/components/datagrid/test-long-text.html

![Screen Shot 2020-05-14 at 9 23 48 AM](https://user-images.githubusercontent.com/814283/81939888-eb2dd700-95c4-11ea-997c-e780668e738f.png)

I think i have fixed this. BTW we probably wouldnt fix it for IE11 going forward as its somewhat minor

**Comment by tmcconechy** [comment] 2020-05-14 13:28
OK i see i missed a step about disabling cell navigation. So yes still in issue, although i partly fixed this without cell navigation setting changed... We do have it scheduled for next sprint. So will take a look then

**Closed** 2020-06-05 17:58 UTC
Labels: [3], focus: datagrid, team: pathway, type: bug :bug:

**Comment by janahintal** [comment] 2020-06-11 05:27
QA Passed. Thank you!
Verified in 
https://master-enterprise.demo.design.infor.com/components/datagrid/test-long-text-no-cell-navigation & https://master-enterprise.demo.design.infor.com/components/datagrid/example-singleselect.html?theme=uplift&variant=dark

![image](https://user-images.githubusercontent.com/45757016/84348224-03563d80-abe7-11ea-89bd-18c1f06c45a8.png)
