### ISSUE TITLE
Popover Component: Alignment Issue for the "Apply" button

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#3292] opened 2020-01-02 20:07 UTC
**Describe the bug**
Popover Component: Alignment Issue for the "Apply" button

**To Reproduce**
1. Go to url: http://master-enterprise.demo.design.infor.com/
2. Scroll down to Popover section
3. Change the theme to Vibrant and Variant to Dark
4. Click on "Click To Show Popover"
5. The error here is that the "Apply" button is not correct. Please see screen shot attached. 

**Expected behavior**
The "Apply" button sure be aligned correctly within the "ABC Engine Company" text box 

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![bs_win10_Edge_79 0 beta](https://user-images.githubusercontent.com/39101346/71689977-62c73c00-2d71-11ea-9aea-e29daae2e6e5.jpg)

**Platform**
 - OS Version: [e.g. Windows 10]
 - Browser Name [Edge 79]

**Additional context**
None

**Comment by tmcconechy** [comment] 2020-01-02 20:12
Duplicate of #2621

**Closed by tmcconechy** 2020-01-02 20:12 UTC
