### ISSUE TITLE
SearchField: Able to select All results for "searchText" also

### ISSUE THREAD

**Issue by VINAYREDDY59** [infor-design/enterprise#2508] opened 2019-07-18 09:47 UTC
**Describe the bug**
When try to search for some text then it giving me the results for that by showing " All results for <text> " am able select that text also and it is loading in the search field which is a bug.
Also the issue is  https://jira.infor.com/browse/IONDEV-44454 QA reported this bug.

**To Reproduce**
1. Go to Search field
2. Click on input text field
3. You will see the search results and message "All results for"
4. Try to select that text also.
5. It'll load the text in search field.

**Expected behavior**
"All results for" should not be selected like "no results"
And text should be relatable like partial results and All results.
**Screenshots**
![image](https://user-images.githubusercontent.com/31958563/61447685-09a84f00-a96f-11e9-8ff0-eb8369aee903.png)
![image](https://user-images.githubusercontent.com/31958563/61447719-1b89f200-a96f-11e9-9e0c-decf627a7cdd.png)

**Comment by tmcconechy** [comment] 2019-07-18 11:40
Duplicate of #2329

**Comment by tmcconechy** [comment] 2019-07-18 11:43
This has been discussed on previous issues https://github.com/infor-design/enterprise/pull/1010#issuecomment-432655589 and https://github.com/infor-design/enterprise/issues/2329

We decided this is not a bug because the idea is if you select that it should do something and show all those things. If you dont want this you can disable the All results link as per http://master-enterprise.demo.design.infor.com/components/searchfield/example-no-all-results-link.html this can be done by setting: `showAllResults: false`

**Closed by tmcconechy** 2019-07-18 11:43 UTC
