### ISSUE TITLE
Two missing About Box translations in non-US locale

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#1226] opened 2018-11-16 09:02 UTC
Use the example About Box code on IDS site (https://design.infor.com/code/ids-enterprise/latest/demo/components/about/example-index?font=source-sans&nofrills=true), but change the locale from en-US to en-GB, fr-FR, or any non-US locale as far as I can see. The Version and Operating System fields are not translated (appear in square brackets).

![image](https://user-images.githubusercontent.com/44396995/48611444-31798a00-e97e-11e8-88fd-ecbd37212c7a.png)
![image](https://user-images.githubusercontent.com/44396995/48611483-45bd8700-e97e-11e8-8395-6920184ca610.png)

**Comment by tmcconechy** [comment] 2018-11-16 14:42
This is a duplicate of https://github.com/infor-design/enterprise/issues/557 - the translation team is translating all our strings now, expect them back, hopefully for Dec-Jan release. You can watch that ticket, soon, as i get them back i will add these in against that ticket and this should work.

BTW the [] is our indication that the string was not found, but you probably figured that...

**Closed by tmcconechy** 2018-11-16 14:42 UTC
