### ISSUE TITLE
Circle pager: keyboard keys not working in Safari

### ISSUE THREAD

**Issue by johnbarcena** [infor-design/enterprise#2934] opened 2019-10-09 08:59 UTC
**Describe the bug**
Keyboard keys {ENTER} and arrow keys are not working in Safari browser

**To Reproduce**
1. Open Safari
2. Go to 'http://4220-beta0-enterprise.demo.design.infor.com/components/pager/example-circlepager.html'
3. Click circle pager then verify the arrow keys ←→
-this should go to previous/next slide
4. Click prev/next then verify ENTER key
-this should go to previous/next slide

**Expected behavior**
keyboard keys should work accordingly

**Version**
4.22 beta

**Screenshots**

**Platform**
 Safari

**Additional context**

**Comment by tmcconechy** [comment] 2019-10-09 13:14
I wasnt entirely able to reproduce this issue but since the buttons are not part of the component im not really worried about this issue so will close this and look for other issues to prioritize.

**Closed by tmcconechy** 2019-10-09 13:14 UTC
Labels: [1], status: wont fix :no_entry_sign:, type: demo-app bug :beetle:
