### ISSUE TITLE
Datagrid unable to select pagesize with Chrome on Android on certain devices

### ISSUE THREAD

**Issue by petterbr** [infor-design/enterprise#1613] opened 2019-02-11 12:59 UTC
**Describe the bug**
The page size selection usually located in the bottom right corner of a datagrid is not visible on certain Android devices running Chrome. 

**To Reproduce**
1. Use browser/device simulation, for instance Browserstack. Select Samsumg Galaxy 9, Google Chrome browser.
2. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-paging?font=source-sans
3. Observe that the page size selector is not visible.

**Comment by tmcconechy** [comment] 2019-02-11 14:17
Duplicate of #1459

Closing this as plan to expand this to work on narrower devices with that request. At the moment this was done on purpose as the page size selector would not fit. So on smaller devices we hide this and remove this functionality. But we may sometime change this to fit with a smaller dropdown with just the number - if that doesn't fit then it will again disappear.

**Closed** 2019-02-11 15:16 UTC
Labels: status: duplicate
