### ISSUE TITLE
Searchfield: Background color is now white

### ISSUE THREAD

**Issue by inforrpunay** [infor-design/enterprise#6511] opened 2022-05-30 01:28 UTC
**Describe the bug**
Previously, the background color used by search field is a darker shade of the header's background color. Now it is always white.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/4.61.0/demo/components/header/example-flex-toolbar.html
2. Here you can see that the search field's color looks like a darker shade of the header background color
3. Go to https://design.infor.com/code/ids-enterprise/4.63.0/demo/components/header/example-flex-toolbar.html
4. Here you can see that the search field's color is now white

**Expected behavior**
We expect it to be like before where the field's color is a darker shade of the header. Is the change intended?

**Version**
- ids-enterprise-ng: v4.63.0

**Comment by tmcconechy** [comment] 2022-06-07 18:09
Since this change is as intended. Will close this for now.

**Closed by tmcconechy** 2022-06-07 18:09 UTC
Labels: for: design, type: bug :bug:, [2], team: m3
