### ISSUE TITLE
DataGrid - Save settings sort is not working with pager

### ISSUE THREAD

**Issue by sanjeewasap** [infor-design/enterprise#6811] opened 2022-09-12 03:47 UTC
**Describe the bug**
In SOHO data grid when save settings enabled, if we do paginate and refresh the browser, it always loads first page data. The paginator page number is correct. But data is sorted wrong.

Use following links.
https://main-enterprise.demo.design.infor.com/components/datagrid/test-save-settings.html
https://main-enterprise.demo.design.infor.com/components/datagrid/test-save-settings-manual.html

**To Reproduce**
1. Go to 2nd page of the data grid.
2. Click sort on the product id column and notice the order twice to change the order
3. Refresh the page 

**Expected behavior**
Correct data order should be loaded to the active page and sorting should be maintained.

**Version**
- ids-enterprise: [v4.67.0-dev]

**Platform**
 - Infor Application/Team Name: Infor IAD
 - OS Version: Windows 10
 - Browser Name: chrome

**Comment by ericangeles** [comment] 2022-09-12 09:42
Both links are working when I followed your steps. I also play around with the filters and both sample pages work.

**Comment by ericangeles** [comment] 2022-09-12 11:38
I've also tested it on Windows 10 & 11 Chrome (via BrowserStack) it's working too.

**Comment by tmcconechy** [comment] 2022-09-12 13:13
@ericangeles i updated the steps. You need to sort but this was not mentioned on this issue but was when i discussed it with @sanjeewasap

**Comment by sanjeewasap** [comment] 2022-09-22 01:20
Thank you @tmcconechy @ericangeles 
Any update on this?

**Comment by tmcconechy** [comment] 2022-09-22 11:39
We plan too work on it next sprint (Oct - Nov time frame)

**Comment by sanjeewasap** [comment] 2022-09-23 01:32
Ok @tmcconechy. Thank you for the update.

**Comment by thogr** [comment] 2023-02-14 11:24
@tmcconechy What has happened to this?

**Comment by tmcconechy** [comment] 2023-02-14 16:15
Not really sure @thogr I think maybe we couldnt reproduce at the time so it got dropped and had lack of activity. If you try the sort it does look like it works if you press it once because you didnt really change the sort.

So I updated the steps @ericangeles I can definitely still see the issue. Lets take a look next sprint @ericangeles 

A possibly fix might be to do the paging first before sorting. Maybe the is some workaround in there restoring them separately?

**Comment by ericangeles** [comment] 2023-02-15 05:55
Sure, we can do it in the next sprint.

**Comment by tmcconechy** [comment] 2023-03-31 17:06
@ericangeles to be clear - check the actual sort order of the items. The UI looks correct but the data is incorrectly sorted

**Comment by sanjeewasap** [comment] 2023-05-17 10:58
Hi @danielortiz1982 @tmcconechy can I know the status on this?

**Comment by tmcconechy** [comment] 2023-05-17 12:49
We did not have time for this yet. However, we do plan on working on it it the new few weeks. Could make an early June release if there are no issues resolving it.

**Closed** 2023-05-31 13:22 UTC
Labels: type: regression bug  :leftwards_arrow_with_hook:, [3]

**Comment by sanjeewasap** [comment] 2023-06-08 04:51
@tmcconechy Is this fix included in "ids-enterprise-ng: 15.3.2"

**Comment by tmcconechy** [comment] 2023-06-08 13:48
No it will be in EP 4.84.0 and will make a 16.4.0 or 15.4.0 with it in for NG 16 and 15 (will make this shortly and post in notifications)

**Comment by sanjeewasap** [comment] 2023-06-09 04:52
Thank you @tmcconechy for the update.

**Comment by sanjeewasap** [comment] 2023-07-04 06:18
@tmcconechy now we are having IDS 15.4.4 version. I can see still we are having the above issue.

**Comment by tmcconechy** [comment] 2023-07-07 14:56
@sanjeewasap If i try the exact steps above does it not seem fixed? (on main links)

**Comment by sanjeewasap** [comment] 2023-07-09 01:20
In the main links working. I am asking in this version "IDS 15.4.4 version"
https://github.com/infor-design/enterprise/issues/6811#issuecomment-1619568224

**Comment by sanjeewasap** [comment] 2023-07-10 11:14
@tmcconechy Can you check this recording

![image](https://github.com/infor-design/enterprise/assets/16222358/d33fd230-f8cd-44c2-a630-b8a2018ef7d0)

[screencast-localhost_4200-2023.07.10-11_30_13.webm](https://github.com/infor-design/enterprise/assets/16222358/7a33c3d2-a067-426b-8ef9-aca75ac557b8)

**Comment by tmcconechy** [comment] 2023-07-10 13:57
@sanjeewasap I'm a little confused but we need to establish two things.

1. Does the original steps indeed seem fixed on main? 
2. If so then i would just try `15.4.5` as its the latest NG version with the latest 4.84.x from a few days ago.

Perhaps that will work I thought the fix was in 4.84.0 but if thats not the case. Safest to just try the latest patch
