### ISSUE TITLE
Datagrid Reset to Default does not reset filtered fields

### ISSUE THREAD

**Issue by NathanLouisBarcial** [infor-design/enterprise#757] opened 2018-09-05 22:57 UTC
**Describe the bug**
Using the Reset to Default function does not reset the data shown when filtered.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-grouped-headers.html
2. Filter the 'Quantity' column. (e.g. filtered to records containing '1')
3. Click on the 'More' ellipses and click on the 'Reset to Default'

**Expected behavior**
The filtered value should be removed and all records should be shown again.

**Actual behavior**
The filter was removed from the filter textbox but the data shown are still the filtered values.

**Screenshots**
1) Filtered Value:
![image](https://user-images.githubusercontent.com/41028784/45125330-95bee700-b1a0-11e8-9a68-ebb4b9ff03b9.png)

2) Clicking on Reset to Default
![image](https://user-images.githubusercontent.com/41028784/45125362-b25b1f00-b1a0-11e8-93c7-a216f1480367.png)

3) Filtered value is removed but data still shown are the filtered values.
![image](https://user-images.githubusercontent.com/41028784/45125401-d9b1ec00-b1a0-11e8-9ce5-db72e897bd74.png)

**Platform**
 - All Devices and Browsers

**Comment by tmcconechy** [comment] 2018-10-01 13:59
We noticed that this issue is the same as https://github.com/infor-design/enterprise/issues/847 so closing this as a duplicate

**Closed by tmcconechy** 2018-10-01 13:59 UTC
Labels: [5], type: bug

**Comment by clepore** [comment] 2018-10-12 16:34
Duplicate of #847
