### ISSUE TITLE
HTML Markup in Message control is no longer rendered

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#1288] opened 2018-11-27 10:21 UTC
In the 4.4.0, and earlier, versions of SoHo Xi, we were able to add HTML markup to the text that is displayed by calling the message() function; e.g.

![image](https://user-images.githubusercontent.com/44396995/49074647-ffddaa00-f22c-11e8-89a8-87dddd20e832.png)

Calling the exact same method, with the same text and markup, in 4.12.x seems to strip all the HTML elements out;

![image](https://user-images.githubusercontent.com/44396995/49074727-34e9fc80-f22d-11e8-8ada-1547f9cd41f6.png)

Even if we use \n to try and put a line break in, that is also removed.

The documentation says "You have control over the message contents..." but this no longer appears to be the case.

Is there any way we can use the message() method but have some control over the text formatting/layout?

**Comment by tmcconechy** [comment] 2018-11-27 14:42
This is a duplicate of https://github.com/infor-design/enterprise/issues/379 we recently fixed it.
But to be sure, can you list all the tags you use i the dialog. I think we might have to add a few more like `<a>` tags. At the moment we decided on these https://github.com/infor-design/enterprise/pull/1275/files#diff-649ef39fc89be76f438d0f818d90a24fR49

**Comment by tmcconechy** [comment] 2018-11-27 14:42
Just leave a note on #379 if additional tags are needed. CC @davidcarlsonberg

**Closed by tmcconechy** 2018-11-27 14:42 UTC
Labels: status: duplicate

**Comment by sanx72** [comment] 2018-11-27 14:47
OK, have managed to find a workaround, should any one need it...

```
	$('body').message({
		title: "Test",
		message: "message",
		status: "alert",
		buttons: [{
            text: Locale.translate('Close'),
            click: function() {
                $(this).modal('close');
            },
            isDefault: true
        }]		
	});
	
	$('div.modal.message').on('beforeopen', function() {
		$('div.modal-body > p.message').html("Line 1<br/><br/>Line 2");
	});	
```
