### ISSUE TITLE
Popover details is overlapping and does't display the details in IE11

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2591] opened 2019-08-02 15:01 UTC
**Describe the bug**
Popover details is overlapping and does't display the details in IE11

**To Reproduce**
1. Goto https://4200-beta1-enterprise.demo.design.infor.com/components/popover/example-index.html
2. click popover button 
 - notice that the 'Apply' button is misaligned 
3. Open IE 11 and Goto https://4200-beta1-enterprise.demo.design.infor.com/components/popover/example-index.html
4. Click popover button 
 - Notice that the details did not display 

**Expected behavior**
Popover should 
- details should not be misaligned 
- should display the details in IE 11

**Version**
Beta 4.20

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/62378774-28663280-b578-11e9-86b6-c96cfc3f3df7.png)
![image](https://user-images.githubusercontent.com/45757016/62378805-361bb800-b578-11e9-9d74-9675ecb6666e.png)

**Platform**
All browser, OS and devices 

**Additional context**
No any other context about the problem here.

**Comment by tmcconechy** [comment] 2020-02-10 17:46
Duplicate of #2621

**Closed by tmcconechy** 2020-02-10 17:46 UTC
Labels: [3], priority: minor, type: demo-app bug :beetle:
