### ISSUE TITLE
Contextmenu: Does not open in iOS after long press

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2349] opened 2019-06-10 10:32 UTC
**Describe the bug**
Contextmenu: Does not open in iOS after long press.

**To Reproduce**
1. Open browser in iOS
2. Go to http://4190-beta2-enterprise.demo.design.infor.com/components/contextmenu/example-page-rightclick.html
3. Long press anywhere in the page
4. See issue: Contextmenu does not open

**Expected behavior**
Contextmenu should open in iOS after long press

**Version**
- ids-enterprise: v4.7.0 to v4.19.0-beta2

**Screenshots**
No screenshot applicable.

**Platform**
 - iOS Safari, iOS Chrome

**Additional context**
No additional context.

**Comment by tmcconechy** [comment] 2019-06-10 13:34
This issue is really wierd @EdwardCoyle I know this worked but i cant find any version where it works (checked back to 4.16.2)

**Comment by marknolaninfor** [comment] 2019-06-12 02:25
I have tested this on my iphone with my local environment and found that it did work. To work the trigger has to be right-click and the env.os.name has to return ios. This is based on the user agent so you can sort of also test this within the developer tools by using the mobile tools.

I wonder if it is not setting the env.os.name correctly for the device, another test is 
http://localhost:4000/components/popupmenu/example-trigger-right-click.html

**Comment by tmcconechy** [comment] 2019-06-12 13:36
You right @marknolaninfor Im seeing it working on my iphone as well. But as i hold and press i noticed its not possible to select something easily from the menu.So i think we should look a bit more here.

**Comment by marknolaninfor** [comment] 2019-06-13 03:13
It is this section of code the stops the click from happening on an ios device. Line 811 in popupmenu.

              // iOS needs this prevented to prevent its own longpress feature in Safari
              if (env.os.name === 'ios') {
                e.preventDefault();
              }

**Comment by davidcarlsonberg** [comment] 2019-07-16 11:01
I am having no issues and cannot reproduce the issue. Tested on iOS Chrome and iOS Safari.

**Comment by tmcconechy** [comment] 2019-07-16 13:41
Ok closing this off then since i made it. I think what i was seeing is it doesnt seem to work on browser stack but it does work ok on xcode ios simulator and my iphone. So maybe a limitation there we cant deal with. (Note to QA there)

Im not seeing any issue with selecting an item once it opens anymore either

**Closed by tmcconechy** 2019-07-16 13:41 UTC
Labels: [3], status: cant reproduce, type: bug :bug:

**Comment by CindyMercadoReyes** [comment] 2019-07-16 15:35
This issue is now resolved.
