### ISSUE TITLE
Tabs: Count header label is too near in the tab focus in uplift theme

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2744] opened 2019-09-06 05:26 UTC
**Describe the bug**
Tabs count header label is too near in the tab focus in uplift theme
**To Reproduce**
1. Go to http://4210-beta1-enterprise.demo.design.infor.com/components/tabs/example-counts.html?theme=uplift&variant=light&colors=0563C2
2. Switch to uplift theme

**Expected behavior**
Header label and focus should align consistently 

**Version**
Beta 4.21

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/64403102-f29df780-d0a9-11e9-9c90-b4d4aedf9f19.png)

**Platform**
All OS, Browser and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment] 2019-09-11 19:15
Duplicate of #2743

**Closed by tmcconechy** 2019-09-11 19:15 UTC
Labels: [2], status: duplicate, type: demo-app bug :beetle:

**Comment by janahintal** [comment] 2019-09-25 07:21
QA Passed. Will move to Done. 
Verified in http://master-enterprise.demo.design.infor.com/components/tabs/example-counts.html?theme=uplift&variant=light&colors=0563C2
