### ISSUE TITLE
MultiSelect - Values and Checkbox are overlapped on Google Chrome only

### ISSUE THREAD

**Issue by msanchez-dev** [infor-design/enterprise#3092] opened 2019-11-12 06:58 UTC
Repro Step:
1. Create a SohoMultiselect (make sure browser is Google Chrome)

Expected Behavior: Checkbox is at the top-left and will not overlap the label
Actual Behavior: Checkbox and value from multiselect options overlap each other

Note: This only happens on Google Chrome. Renders well on Mozilla, Internet Explorer, and Edge

Tested on Google Chrome Version 78.0.3904.87 (Official Build) (64-bit)

Chrome (Incorrect):
<img width="159" alt="Chrome" src="https://user-images.githubusercontent.com/57656263/68648735-1d01aa80-055c-11ea-85f1-c1d93e890a31.PNG">

Internet Explorer (Correct):
<img width="171" alt="IE" src="https://user-images.githubusercontent.com/57656263/68648761-268b1280-055c-11ea-8c89-f907be4e0b02.PNG">

Initial Investigation: There's a special CSS for IE and Firefox that will set margin-left of the listitem to -23px; that's why the checkbox is on left most -- making it to display correctly. Unlike in Google Chrome where it uses margin-left: 10px;Applying margin-left: -23px for Google Chrome will fix the problem.

Any reason why there's a special CSS for IE and Firefox, but not on Chrome?

**Comment by tmcconechy** [comment] 2019-11-12 14:42
@msanchez-dev Please use the issue template to fill out this issue https://github.com/infor-design/enterprise/issues/new/choose you can edit the issue and copy the template in. We need all this information in order to look at this issue.

In particular you do not mention or have any way to reproduce this issue and do not mention the version.It is possible this issue is fixed as we had issues like this here https://github.com/infor-design/enterprise/issues?utf8=%E2%9C%93&q=is%3Aissue+checkbox+multiselect+align

And i cannot reproduce this on our examples http://latest-enterprise.demo.design.infor.com/components/multiselect

**Comment by tmcconechy** [comment] 2020-01-07 14:45
Was not able to reproduce this issue so closing.

**Closed by tmcconechy** 2020-01-07 14:45 UTC
Labels: [3], focus: dropdown, status: cant reproduce, status: on hold :pause_button:, type: bug :bug:
