### ISSUE TITLE
Misc: Some Enhancement suggestions

### ISSUE THREAD

**Issue by jimmy-xie** [infor-design/enterprise#3184] opened 2019-11-26 10:02 UTC
1. The tab box can’t be 100% width of the page, it commonly has the same width as its panel, such as twelve columns. [sample link]( https://github.com/infor-design/enterprise/blob/4.23.0/app/views/components/tabs/example-index.html)
I think it should be better if there is a setting to make it full width.

2. The title of the toolbar button set always have a little bit indentation, and cant’ be aligned with the content below when it is not used in header. [sample link](https://github.com/infor-design/enterprise/blob/4.23.0/app/views/components/toolbar/example-index.html)
I think it should be better if there is a setting to cancel the indentation.

3. The list view doesn’t have the border on both left and right side. The sample on the design page has the border just because it is contained by a card frame [sample link](https://github.com/infor-design/enterprise/blob/4.23.0/app/views/components/listview/example-index.html)
There is still one problem if I use a card frame outside, because the height and width of card is not that proper and I have only one card on this page.
So I think it should be better to have a setting to control the border of list view
as follow are my work, first is the prototype, and second is the code works
<img width="643" alt="prototype" src="https://user-images.githubusercontent.com/54137303/69619534-a645d080-1076-11ea-8f3b-63142fca4b95.png">
<img width="962" alt="mycodever" src="https://user-images.githubusercontent.com/54137303/69619552-ab0a8480-1076-11ea-9a30-a6fa0e0330d4.png">

**Comment by tmcconechy** [comment] 2019-11-26 14:29
1. is possible if you use the `full-width` class. For example
```
<div class="full-width">
   <!-- Tab or whatever content -->
</div>
```
2. This is by design or it would be flush with the contents on the left. But if you really want to do this on a one off scenario, just adjust it with some css.
3. I'm not sure what you mean there. Your screen shot looks fine. Can you provide a reduced test case?

**Comment by ericangeles** [comment] 2019-11-27 05:58
Hi @tmcconechy , Jimmy seek a consultation on our UX team here in Manila and I upon checking his code, he's using the Angular wrapper. Not quite sure if styling will be done on the NG side.

**Comment by tmcconechy** [comment] 2019-11-27 12:23
Ok I would probably suggest just leaving point 2. as is then. We don’t want to change it and break things and it seems very minor. Plus this is the first time anyone mentioned it

**Comment by jimmy-xie** [comment] 2019-11-29 01:14
Thank you all and now I have found some alternative solutions in css, but it is still no way to make the tabs shown close to the UX Design. Or shall I put the tabs in the header instead? Then it will be a blue one

**Comment by tmcconechy** [comment] 2019-12-03 14:36
Ok, Since that was the design i would suggest you just leave it as is.
You do have the option to put them in the header if that matches your application structure. In that case the tabs are considered more of a top level navigation device.

Given all that will close this bug out for now. But we can still discuss

**Closed by tmcconechy** 2019-12-03 14:36 UTC
Labels: [2], type: support :sos:
