### ISSUE TITLE
Lookup Modal Component: Can't change selection of a product ID

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#928] opened 2018-10-04 16:22 UTC
**Describe the bug**
Lookup Modal Component: Can't change selection of a product ID

**To Reproduce**
1. Go to URL: http://4110-beta1-enterprise.demo.design.infor.com/components/lookup/test-modal-lookup.html
2. Click on "Select State" 
3. Click on the "Lookup" button and select "Different Compressor" and click the submit button
4. Click on "Select State" again and click on the Lookup button
5. The user is unable to select a different product from the lookup list and the user has to click on the "Cancel" button to get out of the lookup window.

**Expected behavior**
The user should have the ability to select a different product ID from the lookup window

**Screenshots**
<img width="1236" alt="lookup2" src="https://user-images.githubusercontent.com/39101346/46488254-21dc2280-c7d0-11e8-84a7-5a281cd60ead.png">

**Platform**
- MAC Chrome
**Additional context**
None

**Comment by tmcconechy** [comment] 2018-10-04 17:41
This seems like an example issue, the main goal of this example is just to show you can open a lookup from a modal, but something must be off on the settings applied to the look up component here.

**Comment by tmcconechy** [comment] 2018-10-09 16:15
Fixed this as it was really the same issue as https://github.com/infor-design/enterprise/pull/958

**Comment by clepore** [comment] 2018-10-12 16:31
Duplicate of #958

**Closed by clepore** 2018-10-12 16:31 UTC
Labels: status: duplicate
