### ISSUE TITLE
SOHO-6821: 4.0 Mask and 4.0 Locale need to support unicode charset for current locale

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#439] opened 2018-07-17 19:34 UTC
In some languages, the unicode charset is not being used for numbers and Arabic numbers are displayed.

Particularly for Hindi (hi-IN) and Chinese (zh-Hans-CN-u-nu-hanidec) and arabic (ar-EG), the Mask is blocking the input when the unicode charset is used.

Need to:
1) Provide a way to format a number as one of those languages (formatNumber and/or toLocaleString https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString#Using_locales)
2) Allow a mask like `###` to accept characters typed in a hi-IN/zh-Hans/ar-EG keyboard)

Notes:
Masking with unicode regex
digits: https://regexr.com/4a5c7
non digits: https://regexr.com/4a5nr

**Comment by tmcconechy** [comment] 2019-02-21 18:52
@fitzorama - What more information can you give me on this. Trying to figure out what i need to check in Locale to make this work.

How can i test this is working correctly?

**Comment by tmcconechy** [comment] 2019-02-23 11:55
Duplicate of #441 closing this as the other has better info

**Comment by tmcconechy** [comment] 2019-02-23 12:06
Closed wrong one

**Comment by tmcconechy** [comment] 2019-02-23 12:23
Some information: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString#Using_locales

**Closed** 2019-03-15 12:46 UTC
Labels: [5], type: bug :bug:

**Comment by janahintal** [comment] 2019-03-25 06:54
Hi, I tried testing the components in Arabic yet I could not populate the Alphanumeric field in http://4170-beta0-enterprise.demo.design.infor.com/components/mask/example-index.html. May I ask if this is expected? 
<img width="795" alt="Screen Shot 2019-03-25 at 2 52 46 PM" src="https://user-images.githubusercontent.com/45757016/54900332-cd5b6980-4f0d-11e9-88cf-1d8c4aceefef.png">

**Comment by tmcconechy** [comment] 2019-03-25 14:01
That example uses a different regex, and i was more focused on number masks for this feature. I think we could edit the alpha numeric ones too. But it wasnt in scope. So lets make a new bug for that for a later date?

**Comment by janahintal** [comment] 2019-03-26 03:02
> That example uses a different regex, and i was more focused on number masks for this feature. I think we could edit the alpha numeric ones too. But it wasn't in scope. So let's make a new bug for that for a later date?
> 
> @janahintal I created an issue #1846 to cover that part and moved this back to retest, we will cover the alphanumeric later. 👍

Thanks @tmcconechy :)
