### ISSUE TITLE
Calendar: Monthview dropdown/button looks cropped in iOS

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3211] opened 2019-12-05 12:02 UTC
**Describe the bug**
on iPhone that has smaller screen the monthview button is cropped

**To Reproduce**
1. Go to https://4230-enterprise.demo.design.infor.com/components/calendar 
or
https://master-enterprise.demo.design.infor.com/components/calendar
2. See Error

**Expected behavior**
monthview button/drop-down should be aligned properly

**Version**
v4230 

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/70231037-86a85980-1794-11ea-8dd2-72ec72902caa.png)

**Platform**
iPhone XS, iPhone 8 (any other iPhones with smaller screens)
iOS 12

**Additional context**

**Comment by tmcconechy** [comment] 2019-12-05 14:07
Duplicate of #925

**Comment by tmcconechy** [comment] 2019-12-05 14:07
This will be handled when feature #925 is done, so closing as duplicate

**Closed by tmcconechy** 2019-12-05 14:07 UTC
Labels: [3], status: duplicate, type: bug :bug:
