### ISSUE TITLE
Sink Page Uplift: Button is outside the popover

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2621] opened 2019-08-07 08:52 UTC
**Describe the bug**
Sink Page Uplift: Button is outside the popover

**To Reproduce**
1. Go to http://4200-rc1-enterprise.demo.design.infor.com/
2. Change the theme to Uplift
3. Scroll down then click the "Click to Show Popover" button
4. See issue: button is outside the popover

**Expected behavior**
Button should be inside the popover.

**Version**
- ids-enterprise: v4.20.0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/62609053-a4bf9380-b933-11e9-9ac5-531ca043d224.png)

**Platform**
 - All devices, OS, and browsers.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment] 2019-08-07 13:01
I thought this was fixed. But this can still be reproduced on http://master-enterprise.demo.design.infor.com/components/popover/example-index.html?theme=uplift&variant=light&colors=0563C2 as well as the kitchen sink page.

This is only a demo app issue so not critical.

**Comment by brianjuan** [comment] 2019-08-07 13:10
Hi @tmcconechy, yeah it was fixed on this page https://master-enterprise.demo.design.infor.com/components/popover/example-alternate-positions.html as part of the other ticket.

**Comment by tmcconechy** [comment] 2019-08-07 13:11
Ok, thanks @brianjuan I think we just need to fix the example-index as well. Not very important just a demo issue

**Comment by brianjuan** [comment] 2019-08-07 13:21
Thanks @tmcconechy!

**Comment by tmcconechy** [comment] 2020-01-02 20:13
Lets fix this because it has been raised at least 5 -6 times. I suggest removing the button from the popup and simplifying the example

**Comment by tmcconechy** [comment] 2020-02-18 19:42
This was fixed on another ticket

**Closed by tmcconechy** 2020-02-18 19:42 UTC
Labels: [2], priority: minor, type: demo-app bug :beetle:
