### ISSUE TITLE
Validation: After resetForm its showing the “Required” error message for focus input field.

### ISSUE THREAD

**Issue by cshirole** [infor-design/enterprise#2654] opened 2019-08-14 09:26 UTC
**Describe the bug**
After resetting form, there is one error message appearing that field is  “Required”.

Please note that the case is only reproducing when the focus is on form field and then submit form.
If after inputting data into field and before submitting it, we click somewhere else on plane page then submit it, in this case its not reproducing.

**To Reproduce**
1.Set up your enterprise project ' https://github.com/infor-design/enterprise-ng.git’
2.Replace “validation-form.demo.html” and "validation-form.demo.ts" with attached files
3.Fill the data and click on reset button.
  It shows the “Required” field error message for last focus input field. 
  For more clarification please check the attached video.

**Expected behavior**
Required message should not get displayed after reset form

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

[Validation_Error.zip](https://github.com/infor-design/enterprise/files/3500692/Validation_Error.zip)

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by cshirole** [comment] 2019-08-14 09:29
Hello,
This issue was reported by Nilam Thakur, as she does not have access to github I created the issue.

Thanks.

**Comment by tmcconechy** [comment] 2019-08-14 13:22
I was able to workaround this by:
- adding class disable-validation to all inputs
- restetForm in both Soho and Ng Forms
- remove  class disable-validation to all inputs (in a timeout)

Idea would be to do something similar in the resetForm soho function. Additionally make this cleaner to call in NG.

Also btw @cshirole anyone can have an Github ID that has some email address. You just need to signup.

**Comment by tmcconechy** [comment] 2020-10-06 15:45
This issue is a duplicate of #4259 and i retested it and it has been fixed over there.

**Closed by tmcconechy** 2020-10-06 15:45 UTC
Labels: [3], type: bug :bug:
