### ISSUE TITLE
Datagrid: long tooltip is not pointed to the hovered data in uplift theme

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3397] opened 2020-01-28 10:50 UTC
**Describe the bug**
Datagrid: long tooltip is not pointed to the hovered data in uplift theme

**To Reproduce**
1. Go to http://4250-rc1-enterprise.demo.design.infor.com/components/datagrid/example-tooltips.html?theme=uplift&variant=light
2. Click the Activity Sort filter
3. Hover to the 2nd row of Activity Column 

**Expected behavior**
Tooltip should be pointed in the hovered data. 

**Version**
IDS 4.250 rc1

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/73253410-72626500-41f7-11ea-9d76-2729cbcb81ae.png)

**Platform**
All browser, OS and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment] 2020-01-28 13:59
Duplicate of #1983

**Closed by tmcconechy** 2020-01-28 13:59 UTC
Labels: [2], priority: minor, type: bug :bug:
