### ISSUE TITLE
Listview: Search function not working

### ISSUE THREAD

**Issue by micheal-cao** [infor-design/enterprise#2580] opened 2019-08-01 16:12 UTC
**Describe the bug**
Searching function does not function in list view. 
This issue is related to [https://github.com/infor-design/enterprise-ng/issues/466]
**To Reproduce**
1. Setup latest environment for enterprise-ng (5.4.x),
2. Open list view page, and try to enter something in search box in the last list view,
3. No items were filtered.

**Expected behavior**
matched text should be highlighted, and unmatched items should be filtered.

**Version**
- ids-enterprise: v4.19.4

**Screenshots**
![image](https://user-images.githubusercontent.com/39074182/62309534-40777c80-b4ba-11e9-9a51-cfbf87a75eb0.png)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: Chrome
 - Browser Version: Version 75.0.3770.142 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment] 2019-08-01 16:13
Duplicate of #infor-design/enterprise-ng/issues/466

**Closed by tmcconechy** 2019-08-01 16:13 UTC
