### ISSUE TITLE
Locale: 2 of sets of "month" strings are needed

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#6122] opened 2022-02-14 15:02 UTC
**Locale: 2 of sets of "month" strings are needed**

From linguists: "Names of months do take lowercase initial within a phrase/string, but not at the start like here. We need separate strings for such occurrences"

sv-SE-messages.js, for example, only contains the following string:
id: 'MonthWideFeb', value: 'Februari'

Do you automatically convert F to lowercase f?

![image](https://user-images.githubusercontent.com/66057969/153888516-592d33d5-081d-4711-a1d3-08ff13a70f5d.png)

Translations are maintained by Henry.Wondergem@infor.com

**Comment by tmcconechy** [comment] 2022-02-14 15:27
No we just put the date in there that they give us. I think most of the cases will be like this in the calendar.
But they could also be in an input field or on a form.

We can provide two sets but we would need to understand the rules... I.E. when do we show the lower case ones and when do we show the upper case ones for each locale? And are some locales always upper case ect?

**Comment by cpinatel7** [comment] 2022-02-14 15:38
Linguists will determine whether it should be lowercase or uppercase based on the context provided in the associated comment:

**Comment by tmcconechy** [comment] 2022-02-14 15:51
Yes but we are using the same string in multiple places... So we would need to know which places to check or some general rule to get started?

**Comment by tmcconechy** [comment] 2022-02-17 16:48
@hwondergem @cpinatel7 

Is this for both lengths of months? I.E.

February
Feb

**Comment by hwondergem** [comment] 2022-02-18 12:48
@tmcconechy, I checked with our Lead Editor Roger: 
"I don’t know of any specific instance where the short form is used as part of a longer string.  But, if I saw one, I wouldn’t be surprised, and I wouldn’t think it was incorrect.  Yes, English month names, long and short forms,  always start with a capital."

**Comment by tmcconechy** [comment] 2022-02-18 17:06
@hwondergem put placeholders in en-messages.js in prep for this.

**Comment by cpinatel7** [comment] 2023-03-08 10:17
Still required. Thanks

**Comment by tmcconechy** [comment] 2023-03-08 14:46
This may be fixed in the new web components. Will check soon.

**Comment by tmcconechy** [comment] 2023-03-31 18:31
https://main.wc.design.infor.com/ids-date-picker/example.html -> dont think this is fixed? But we do have two sets of strings now. Im just a little unclear when and where we should use them?

Is this specific to the date picker? Because we need to tell it which set to use and it can only use one set. So however it was translated in the longer string will appear.

Not sure how to verify this futher

**Comment by cpinatel7** [comment] 2023-04-04 09:01
re: But we do have two sets of strings now

Could you please confirm?
One set with lowercase letters e.g. january, february, march, etc.
and
One set with uppercase letters e.g. January, February, March, etc.

What do the associated string comments say?

Thanks

**Comment by tmcconechy** [comment] 2023-04-04 14:56
Ok done. Added these here https://github.com/infor-design/enterprise-wc/pull/1218 and on the server for translation. For some reason they were there but not in lower case.

But the problem is on the date picker https://main-enterprise.demo.design.infor.com/components/datepicker/example-index.html I can only show one or the other. I cant pick and choose to show lower case or upper case. So maybe we just translate the strings to the right case? Or i always show lower case?

**Comment by cpinatel7** [comment] 2023-04-04 15:26
For Date Picker, translations corresponding to the English uppercase set should be used.
re: Or i always show lower case?
No no no :).
In other cases, developers need to decide whether they want to use the uppercase set or lowercase set for English strings.  Translations for these sets should be used accordingly. Strings / translations mustn't be converted from lower to uppercase or from upper to lowercase.
Thanks

**Comment by cpinatel7** [comment] 2023-04-04 15:42
Depending on the context

Example:
![image](https://user-images.githubusercontent.com/66057969/229844851-7bcea205-ec73-418d-8646-22c9700d4274.png)

Should the upper or lowercase set be used?
In this context, uppercase set is to be used in English. Translations corresponding to the English uppercase set should be used

**Comment by tmcconechy** [comment] 2023-04-04 15:56
OK, thats the current situation. https://main-enterprise.demo.design.infor.com/components/datepicker/example-index.html When would lower case be used?

**Comment by tmcconechy** [comment] 2023-04-04 16:43
But thats what im saying. If we make two different strings in lower and upper case it wont automatically fix this. It will just show the upper case one. Unless we have specific rules of what languages are lower case. Or you just translate some strings in lower case and some in upper case of the original set of strings.

**Comment by cpinatel7** [comment] 2023-04-04 16:50
Please see below. The Swedish translation is value: 'Februari' but it's displayed as:

![image](https://user-images.githubusercontent.com/66057969/229861223-bee4d1de-23c7-46c4-88ec-0c9297587366.png)

In English, lower 'f' is probably converted to upper 'F'. We don't want any automated conversion in any languages.

The uppercase set is to be used in English. Translations corresponding to the English uppercase set should be used too.

**Comment by tmcconechy** [comment] 2023-04-04 17:08
OK, so if i follow we can do this.

- all strings are always as translated February -> whatever
- we have a second set that as an option "can" be used by developers as a setting that shows it in lower case (not the default)

**Comment by cpinatel7** [comment] 2023-04-04 17:10
Yes, please. Thanks for your help

**Comment by tmcconechy** [comment] 2023-05-16 15:56
As of 4.84 the strings are availble if you need to use them. But we still use the default string in the code.

**Closed by tmcconechy** 2023-05-16 15:56 UTC
Labels: type: bug :bug:, [3], focus: translation

**Comment by cpinatel7** [comment] 2023-05-17 15:38
@tmcconechy 
re: But we still use the default string in the code
I think this means that for Date Picker, you use the uppercase set for English. Could you please confirm?
Thanks

**Comment by tmcconechy** [comment] 2023-05-17 16:01
Yes we still use the uppercase english set. Then whatever thats gets translated to for each locale.

**Comment by cpinatel7** [comment] 2023-05-17 16:05
Thanks
