### ISSUE TITLE
Datagrid: Keyword highlighting no longer works in paged tables

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#2797] opened 2019-09-16 14:42 UTC
Since upgrading to version 4.20.1, when you enter a keyword search in the DataGrid, it no longer highlights the matched string in the table rows. This used to work in older releases.

Working Example: https://design.infor.com/code/ids-enterprise/4.14.0/demo/components/datagrid/example-paging-client-side

Non-working Example: https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-paging-client-side

Hint: sohoxi.js keywordSearch method on the DataGrid looks like the problem...

`      if (!this.settings.paging) {
        this.highlightSearchRows(term);
      }`

We've actually documented this as a feature in our Product Guides across multiple tables, so I'd like the functionality re-instated.

**Comment by tmcconechy** [comment] 2019-09-16 14:47
Can you explain the hint more? I'll address this in the current sprint, this was unintended.

**Comment by sanx72** [comment] 2019-09-16 14:51
I just had a look in the DataGrid's keywordSearch method to see what was happening and the code snipet I provided is there at the bottom of the method, which looks to me that keyword highlighting was deliberately turned off for tables where paging is set to true (as in the example, and in most of our tables).

**Comment by tmcconechy** [comment] 2019-09-16 14:52
OK i will have a look tried to look at the blame there https://github.com/infor-design/enterprise/blame/a806d2acbac9ba3a82b8f9e723a95bfb685aec0d/src/components/datagrid/datagrid.js#L6485 but thats been there 2 years.

**Comment by sanx72** [comment] 2019-09-16 15:00
OK, FYI as a test I removed the "paging: true" from the Datagrid settings object of one of our tables and the highighting started working again. Maybe the behaviour or default for that setting has changed?

**Comment by tmcconechy** [comment] 2019-09-16 15:02
OK, yes will sort it out. Not sure why it shouldnt work with paging except perhaps if its just serverside paging as you dont have the data all there and your doing that filter serverside so initially my guess is this should be ok for client side paging but not serverside paging. (so change this logic and add a regression test)

**Comment by sanx72** [comment] 2019-09-16 15:06
Thanks. It is also client side paging that is the problem (the examples I linked above are client side). Not tried server side as we only have one table in our product that uses it.

**Comment by tmcconechy** [comment] 2019-09-19 20:16
This is resolved in the linked PR will move to test once approved and merged.

**Comment by brianjuan** [comment] 2019-09-23 11:02
http://master-enterprise.demo.design.infor.com/components/datagrid/example-paging-client-side
@tmcconechy is it expected that the highlighting removes when changing data grid page or sorting?

**Comment by tmcconechy** [comment] 2019-09-23 12:46
Ideally it could kept that information. So lets make a new issue for that as that never worked.

**Comment by brianjuan** [comment] 2019-09-23 12:51
Alright @tmcconechy , will create separate issue for that. This one passed QA in all browsers, moving to Done.

**Comment by sanx72** [comment] 2019-09-23 12:53
Surely, for client side paging at least, if I've filtered the table data, then the table should contain only the matching results of the filter text, whether on a single page, or over multiple pages, sorting or paging through the filtered result rows should not reset the filter or change the highlighting. Only if I clear the filter or reload the table data some how should the highlighting be removed.

**Comment by tmcconechy** [comment] 2019-09-23 12:56
OK lets fail this then. I do agree since the search field is showing the search term, that filtering should probably work once paging or sorting.

**Comment by tmcconechy** [comment] 2019-09-23 12:58
@brianjuan changed my mind and failed this to add sorting and filtering support for client side paging  + keyword filtering

**Comment by brianjuan** [comment] 2019-09-23 12:58
Search filtering remains when changing page or sorting, it's just the highlighting that gets removed. But yeah I think highlighting should still remain as well.

**Comment by tmcconechy** [comment] 2019-09-23 12:59
Ok then definitely failed issue as that was the whole point of the fix 😞 
I'll takeanotherr look 👍

**Closed** 2019-09-26 13:36 UTC
Labels: [2], focus: datagrid, priority: high, type: regression bug  :leftwards_arrow_with_hook:

**Comment by brianjuan** [comment] 2019-09-27 08:56
http://master-enterprise.demo.design.infor.com/components/datagrid/example-paging-client-side
Passed QA in all browsers, highlighting works as expected and now remains when sorting and changing page.
