### ISSUE TITLE
Trackdirty: Dirty indicator does not work on forms within a tab

### ISSUE THREAD

**Issue by ktfields** [infor-design/enterprise#4840] opened 2021-02-15 03:29 UTC
**Describe the bug**
Trackdirty: Dirty indicator does not work on forms within a tab

**To Reproduce**
When trackdirty utility is incorporated with forms within a tab, we encounter an error like this:
![image](https://user-images.githubusercontent.com/39935379/107901724-5dca4980-6f7f-11eb-90fb-a726867bcd22.png)

I was able to replicate the issue using IDS sample codes. 
Example:
[trackDirtyIssue.zip](https://github.com/infor-design/enterprise/files/5979334/trackDirtyIssue.zip)

1. Run the sample codes above.
2. Check developer console. "Uncaught TypeError" appears
3. Edit "Text box"

**Expected behavior**
Dirty indicator should be displayed after editing the textbox.

**Version**
ids-enterprise: v4.36.0

**Platform**
Browser Name: Chrome, Edge
Browser Version: Chrome 88.0.4324.150, Edge 88.0.705.68

**Comment by andriivarhanov** [comment] 2021-08-04 13:44
@tmcconechy @jmacaluso711 
it looks like it's been fixed here https://github.com/infor-design/enterprise/commit/259344e038be77dc04ae346f1f163e585e46554c#diff-73ed5c424307b294b0b2ac30e88a510a1f0a781584e5d55319f257e42c9e477bR11

I can reproduce on v4.36.0, I can't reproduce on newest versions

**Comment by tmcconechy** [comment] 2021-08-04 13:48
Thanks @andriivarhanov 
@ktfields looks like the issue is fixed on the latest version 4.54 (beta now)

**Closed by tmcconechy** 2021-08-04 13:48 UTC
Labels: [2], type: bug :bug:
