### ISSUE TITLE
Datagrid: Column style doesn't clear show that columns are resizable

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#4374] opened 2020-09-15 07:27 UTC
Please see below. Descriptions are truncated. I didn't notice that columns were actually resizable (no border). I think it's not very obvious for end users

![image](https://user-images.githubusercontent.com/66057969/93178854-212ac580-f735-11ea-9a5c-a78c9c6bf863.png)

**Comment by tmcconechy** [comment] 2020-09-15 13:38
Yes this is a known issue that has no solution at the moment. We have two different datagrid styles and this one doesnt have borders so something needs to be changed with the two different styles. We have talked about this a bit but dont have any agreement yet.

See also #3688

**Comment by kevinwhitedesign** [comment] 2021-04-13 17:27
Yeah this looks like an intense usecase for this simple list (datagrid style). 

If any filtering indicators are needed I would prefer use of the fully featured datagrid for users.

**Comment by tmcconechy** [comment] 2021-04-13 17:49
Ok, I think we agree. For the resize suggest turning off isList in the grid. Then you get the indicators.
So closing this for now.

**Closed by tmcconechy** 2021-04-13 17:49 UTC
Labels: [3], focus: datagrid, focus: micro-interactions, for: design, type: bug :bug:

**Comment by JangleShubham** [comment] 2021-05-19 09:51
Hello @tmcconechy,

We tried using isList = false and now we can see resize indicators but actually in some cases columns are not getting resized.
We have reproduced this issue with latest(4.51.1) version.
Please refer below example: https://ids-quick-start-model-popup-issue.stackblitz.io/model-popup-example 
To refer code follow link: https://stackblitz.com/edit/ids-quick-start-model-popup-issue

Thanks,
Shubham Jangle
