### ISSUE TITLE
Modals are to small on mobile screens

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#2453] opened 2019-06-28 06:37 UTC
**Describe the bug**
Not quite sure if this should be a bug or feature. But we have a problem with modals when used in Homepages in Infor Go, when the keyboard is up they become  so small that it's not possible to see much of it, but there are still alot of margins that could be removed to make the dialog usable.

**To Reproduce**
1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/contextualactionpanel/example-index' on a mobile device (For example Samsung Galaxy S7)
2. Click on 'Contextual action panel'
3. Scroll down to 'Notes'
4. Click the notes field (So that the phone keyboard appears)
5. See error

**Expected behavior**
No margins (or very small ones like the ones on the sides in the below image) should be used for modals and Contextual action panels when viewed on a small screen/browser

**Version**
Found in 4.17, but reproducible in v4.19.3

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/60322086-e1848c00-997e-11e9-8eec-7a7ed7bc4b4e.png)

**Platform**
 - Device: Samsung Galaxy S7
 - OS Version:Android 8.0.0
 - Browser Name Infor Go / Samsung Internet
 - Browser Version: 12.0.36 / version 9.2.10.15

**Additional context**
-

**Comment by tmcconechy** [comment] 2019-06-28 13:21
Duplicate of #2433

**Comment by tmcconechy** [comment] 2019-06-28 13:21
Hi @SofiK 
We had the same thought and raised this as an enhancement. Please watch #2433

**Closed by tmcconechy** 2019-06-28 13:21 UTC
