### ISSUE TITLE
Autocomplete drop down list appears broken when in responsive view 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3132] opened 2019-11-18 11:38 UTC
**Describe the bug**
Autocomplete drop down list appears broken when in responsive view 

**To Reproduce**
1. Go to http://4230-rc0-enterprise.demo.design.infor.com/?theme=uplift&variant=dark&colors=0053B1 
2. Minimize the screen as with the screenshot 
3. Type "k" then delete
4. Type "new"

**Expected behavior**
Dropdown filter should appear fine and not broken in Autocomplete's responsive view

**Version**
ids-enterprise v4.23-rc0 smoke testing

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/69049475-e683ce00-0a3a-11ea-90e8-cc2effb96dda.png)

**Platform**
All Browser, and OS

**Additional context**
N/a

**Comment by tmcconechy** [comment] 2019-11-18 14:30
![Screen Shot 2019-11-18 at 9 30 03 AM](https://user-images.githubusercontent.com/814283/69060833-0ccb4e80-09e6-11ea-9e2a-cb727e86a9b4.png)

I cant seem to reproduce this issue. I think we need more info on the size of the screen and position. As such this is probably minor.

**Comment by tmcconechy** [comment] 2020-01-07 14:45
Was not able to reproduce this issue so closing.

**Closed by tmcconechy** 2020-01-07 14:45 UTC
Labels: [2], priority: minor, status: cant reproduce, type: bug :bug:
