### ISSUE TITLE
Data grid: drop down list frame is cut off or sizing is not responsive

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1420] opened 2018-12-18 09:00 UTC
**Describe the bug**
Data grid: drop down list frame is cut off or sizing is not responsive

**To Reproduce**
1. Go to : https://4140-beta0-enterprise.demo.design.infor.com/components/datagrid/example-editable
2. Click on 'Action' Column the dropdown list
3. Notice that the list frame is cut off / not responsive

**Expected behavior**
dropdown list frame should be responsive

**Version**

- ids-enterprise: [v4.14.0]

**Screenshots**
<img width="1527" alt="screen shot 2018-12-18 at 4 35 53 pm" src="https://user-images.githubusercontent.com/45757016/50142982-59923b00-02e6-11e9-9d8d-06cafb261c7d.png">

**Platform**
All browser, devices and OS

**Additional context**
No additional context

**Comment by tmcconechy** [comment] 2018-12-18 14:54
This is a duplicate of a fix added for the Release Candidate. https://github.com/infor-design/enterprise/pull/1403

Moving it to RC to retest.

**Closed** 2018-12-18 17:06 UTC
Labels: status: duplicate, type: bug :bug:
