### ISSUE TITLE
Dropdown: pressing the function keys while the dropdown has focus causes letters to be typed.

### ISSUE THREAD

**Issue by JBismonte** [infor-design/enterprise#4976] opened 2021-03-22 11:06 UTC
**Describe the bug**
When the dropdown field is in focus, clicking some function keys causes some letters to be typed

**To Reproduce**

1. Go to https://master-enterprise.demo.design.infor.com/components/dropdown/test-2000-items.html
2. Navigate to the dropdown via keyboard
3. click any of the function keys (F7, F8, F9 etc.)
4. letters getting typed in the drop down

**Expected behavior**
Nothing should happen, when clicking any of the function keys

**Version**

- ids-enterprise: 4.39.0

**Screenshots**
https://user-images.githubusercontent.com/29673378/111980853-d6ee2b00-8b41-11eb-8336-0e83c20e31d7.mp4

**Platform**
 - Infor Application/Team Name: Landmark Team
 - Device: (if applicable): NA
 - OS Version: Windows 10
 - Browser Name: Firefox
 - Browser Version: 85.0

**Additional context**
found this bug while creating a fix for a VPAT Ticket: https://jira.lawson.com/browse/LMCLIENT-34615

**Comment by janahintal** [comment] 2021-09-16 09:13
QA Passed. Working as expected in https://main-enterprise.demo.design.infor.com/components/dropdown/test-disabling-function-keys. Thank you!

**Comment by s-werking** [comment] 2022-01-25 22:14
Hi @tmcconechy @ericangeles ,
Any way that the issue on the ticket could be resolved without disabling the function keys? Our team gives the ability to set custom hotkeys and this would be a loss of functionality if anyone has a function key set as a hotkey. Thanks

**Comment by tmcconechy** [comment] 2022-01-26 14:54
yeah good point. one easy thing i think we could do is make sure onKeyDown still fires for function keys https://github.com/infor-design/enterprise/blob/main/src/components/dropdown/dropdown.js#L55

That should do it right @s-werking ? Or did you test that still fires and can use that?

**Comment by s-werking** [comment] 2022-01-26 15:27
Right, that should work.

**Closed** 2022-02-07 08:04 UTC
Labels: type: regression bug  :leftwards_arrow_with_hook:, [2], team: landmark

**Comment by janahintal** [comment] 2022-02-07 09:48
QA Failed in https://main-enterprise.demo.design.infor.com/components/dropdown/test-2000-items.html.

Steps:
1. Press f1 to f12
2. Press arrow down in the keyboard
3. Wait for the unwanted characters to show

Device: Windows 10 Chrome
![image](https://user-images.githubusercontent.com/45757016/152763734-5a7c53af-68f7-4402-aaae-10ed2f149938.png)

**Comment by ericangeles** [comment] 2022-02-07 09:58
@janahintal did you also use fn key + pressing the f1-f9?

**Comment by janahintal** [comment] 2022-02-07 10:02
> @janahintal did you also use fn key + pressing the f1-f9?

Yes I did test on both with and without FN key. It's working whenever I press Fn+F(x) but unwanted characters appears when I press it without the Fn key.

**Comment by ericangeles** [comment] 2022-02-07 10:07
I think pressing F(x) keys without fn key is using other functionalities on your machine. (e.g., volume up, volume down, mute, etc.) So technically it's not F(x) functions. 

@tmcconechy what do you think about this?

**Comment by tmcconechy** [comment] 2022-02-07 14:14
I cant reproduce it if I properly hit the F1 key (mac / windows). Im guessing its probably due to the simulator / browser stack.
So i guess i would say that we leave this for now.
